use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HtmlConfig {
    pub title: String,
    pub theme: String,
    pub include_charts: bool,
}

impl Default for HtmlConfig {
    fn default() -> Self {
        Self {
            title: "Security Scan Report".to_string(),
            theme: "dark".to_string(),
            include_charts: true,
        }
    }
}

#[allow(deprecated)]
pub struct HtmlReport {
    findings: Vec<super::markdown::Finding>,
    summary: super::markdown::ScanSummary,
    config: HtmlConfig,
}

#[allow(deprecated)]
impl HtmlReport {
    pub fn new(
        summary: super::markdown::ScanSummary,
        findings: Vec<super::markdown::Finding>,
    ) -> Self {
        Self {
            summary,
            findings,
            config: HtmlConfig::default(),
        }
    }

    pub fn with_config(mut self, config: HtmlConfig) -> Self {
        self.config = config;
        self
    }

    pub fn generate(&self) -> String {
        let theme = if self.config.theme == "dark" {
            self.dark_theme()
        } else {
            self.light_theme()
        };

        let findings_html = self
            .findings
            .iter()
            .map(|f| self.render_finding(f))
            .collect::<Vec<_>>()
            .join("\n");

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{}</title>
    <style>
        {}
    </style>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <div class="container">
        <header>
            <h1>🛡️ Security Scan Report</h1>
            <p class="subtitle">{}</p>
        </header>

        <section class="summary">
            <h2>Summary</h2>
            <div class="summary-grid">
                <div class="summary-card">
                    <div class="label">Target</div>
                    <div class="value">{}</div>
                </div>
                <div class="summary-card">
                    <div class="label">Scan Type</div>
                    <div class="value">{}</div>
                </div>
                <div class="summary-card">
                    <div class="label">Duration</div>
                    <div class="value">{}s</div>
                </div>
                <div class="summary-card">
                    <div class="label">Requests</div>
                    <div class="value">{}</div>
                </div>
            </div>

            <div class="severity-summary">
                <div class="severity-card critical">🔴 <span>{}</span></div>
                <div class="severity-card high">🟠 <span>{}</span></div>
                <div class="severity-card medium">🟡 <span>{}</span></div>
                <div class="severity-card low">🔵 <span>{}</span></div>
                <div class="severity-card info">⚪ <span>{}</span></div>
            </div>
        </section>

        <section class="findings">
            <h2>Findings ({})</h2>
            {}
        </section>

        <footer>
            <p>Generated by Slapper | {}</p>
        </footer>
    </div>

    <script>
        const ctx = document.getElementById('severityChart');
        if (ctx) {{
            new Chart(ctx, {{
                type: 'doughnut',
                data: {{
                    labels: ['Critical', 'High', 'Medium', 'Low', 'Info'],
                    datasets: [{{
                        data: [{}, {}, {}, {}, {}],
                        backgroundColor: ['#ff4444', '#ff8800', '#ffcc00', '#4488ff', '#888888']
                    }}]
                }},
                options: {{
                    responsive: true,
                    plugins: {{
                        legend: {{ position: 'bottom' }}
                    }}
                }}
            }});
        }}
    </script>
</body>
</html>"#,
            self.config.title,
            theme,
            self.summary.timestamp,
            self.summary.target,
            self.summary.scan_type,
            self.summary.duration_seconds,
            self.summary.total_requests,
            self.summary.critical_count,
            self.summary.high_count,
            self.summary.medium_count,
            self.summary.low_count,
            self.summary.info_count,
            self.findings.len(),
            findings_html,
            chrono::Utc::now().format("%Y-%m-%d %H:%M UTC"),
            self.summary.critical_count,
            self.summary.high_count,
            self.summary.medium_count,
            self.summary.low_count,
            self.summary.info_count,
        )
    }

    fn render_finding(&self, finding: &super::markdown::Finding) -> String {
        let severity_class = match finding.severity.to_lowercase().as_str() {
            "critical" => "critical",
            "high" => "high",
            "medium" => "medium",
            "low" => "low",
            _ => "info",
        };

        let evidence_block = finding
            .evidence
            .as_ref()
            .map(|e| {
                format!(
                    r#"<div class="evidence"><pre>{}</pre></div>"#,
                    super::escape::escape_html(e)
                )
            })
            .unwrap_or_default();

        let cve_block = if !finding.cve_ids.is_empty() {
            format!(
                r#"<div class="cve-ids">CVE: {}</div>"#,
                finding.cve_ids.join(", ")
            )
        } else {
            String::new()
        };

        format!(
            r#"<div class="finding {}">
                <div class="finding-header">
                    <h3>{}</h3>
                    <span class="badge {}">{}</span>
                </div>
                <div class="finding-meta">
                    <span class="category">{}</span>
                    <span class="location">{}</span>
                </div>
                <div class="finding-description">
                    {}
                </div>
                {}
                {}
            </div>"#,
            severity_class,
            super::escape::escape_html(&finding.title),
            severity_class,
            finding.severity,
            super::escape::escape_html(&finding.category),
            super::escape::escape_html(&finding.location),
            super::escape::escape_html(&finding.description),
            evidence_block,
            cve_block,
        )
    }

    fn dark_theme(&self) -> String {
        r#"
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; }
            .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
            header { text-align: center; margin-bottom: 2rem; padding-bottom: 2rem; border-bottom: 1px solid #30363d; }
            h1 { color: #58a6ff; margin-bottom: 0.5rem; }
            h2 { color: #8b949e; margin: 1.5rem 0 1rem; }
            .subtitle { color: #8b949e; }
            .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }
            .summary-card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1rem; }
            .summary-card .label { color: #8b949e; font-size: 0.875rem; }
            .summary-card .value { font-size: 1.5rem; font-weight: 600; color: #58a6ff; }
            .severity-summary { display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap; }
            .severity-card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1rem 2rem; text-align: center; }
            .severity-card.critical { border-color: #ff4444; }
            .severity-card.high { border-color: #ff8800; }
            .severity-card.medium { border-color: #ffcc00; }
            .severity-card.low { border-color: #4488ff; }
            .severity-card span { font-size: 1.5rem; font-weight: 600; margin-left: 0.5rem; }
            .finding { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; margin-bottom: 1rem; }
            .finding.critical { border-left: 4px solid #ff4444; }
            .finding.high { border-left: 4px solid #ff8800; }
            .finding.medium { border-left: 4px solid #ffcc00; }
            .finding.low { border-left: 4px solid #4488ff; }
            .finding-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem; }
            .finding-header h3 { color: #c9d1d9; }
            .badge { padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; }
            .badge.critical { background: #ff444433; color: #ff4444; }
            .badge.high { background: #ff880033; color: #ff8800; }
            .badge.medium { background: #ffcc0033; color: #ffcc00; }
            .badge.low { background: #4488ff33; color: #4488ff; }
            .badge.info { background: #88888833; color: #888888; }
            .finding-meta { color: #8b949e; font-size: 0.875rem; margin-bottom: 1rem; }
            .finding-meta .location { margin-left: 1rem; }
            .evidence { background: #0d1117; border-radius: 4px; padding: 1rem; margin: 1rem 0; overflow-x: auto; }
            .evidence pre { color: #7ee787; font-family: monospace; font-size: 0.875rem; }
            .cve-ids { color: #f0883e; font-weight: 600; margin-top: 1rem; }
            footer { text-align: center; margin-top: 3rem; padding-top: 2rem; border-top: 1px solid #30363d; color: #8b949e; }
            @media (max-width: 768px) {
                .container { padding: 1rem; }
                .severity-summary { flex-direction: column; }
            }
        "#.to_string()
    }

    fn light_theme(&self) -> String {
        r#"
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #ffffff; color: #24292f; line-height: 1.6; }
            .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
            header { text-align: center; margin-bottom: 2rem; padding-bottom: 2rem; border-bottom: 1px solid #d0d7de; }
            h1 { color: #0969da; margin-bottom: 0.5rem; }
            h2 { color: #57606a; margin: 1.5rem 0 1rem; }
            .subtitle { color: #57606a; }
            .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }
            .summary-card { background: #f6f8fa; border: 1px solid #d0d7de; border-radius: 8px; padding: 1rem; }
            .summary-card .label { color: #57606a; font-size: 0.875rem; }
            .summary-card .value { font-size: 1.5rem; font-weight: 600; color: #0969da; }
            .severity-summary { display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap; }
            .severity-card { background: #f6f8fa; border: 1px solid #d0d7de; border-radius: 8px; padding: 1rem 2rem; text-align: center; }
            .severity-card.critical { border-color: #cf222e; }
            .severity-card.high { border-color: #bf8700; }
            .severity-card.medium { border-color: #9a6700; }
            .severity-card.low { border-color: #0969da; }
            .severity-card span { font-size: 1.5rem; font-weight: 600; margin-left: 0.5rem; }
            .finding { background: #f6f8fa; border: 1px solid #d0d7de; border-radius: 8px; padding: 1.5rem; margin-bottom: 1rem; }
            .finding.critical { border-left: 4px solid #cf222e; }
            .finding.high { border-left: 4px solid #bf8700; }
            .finding.medium { border-left: 4px solid #9a6700; }
            .finding.low { border-left: 4px solid #0969da; }
            .finding-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem; }
            .finding-header h3 { color: #24292f; }
            .badge { padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; }
            .badge.critical { background: #cf222e1a; color: #cf222e; }
            .badge.high { background: #bf87001a; color: #bf8700; }
            .badge.medium { background: #9a67001a; color: #9a6700; }
            .badge.low { background: #0969da1a; color: #0969da; }
            .badge.info { background: #57606a1a; color: #57606a; }
            .finding-meta { color: #57606a; font-size: 0.875rem; margin-bottom: 1rem; }
            .finding-meta .location { margin-left: 1rem; }
            .evidence { background: #ffffff; border-radius: 4px; padding: 1rem; margin: 1rem 0; overflow-x: auto; }
            .evidence pre { color: #1a7f37; font-family: monospace; font-size: 0.875rem; }
            .cve-ids { color: #bf8700; font-weight: 600; margin-top: 1rem; }
            footer { text-align: center; margin-top: 3rem; padding-top: 2rem; border-top: 1px solid #d0d7de; color: #57606a; }
            @media (max-width: 768px) {
                .container { padding: 1rem; }
                .severity-summary { flex-direction: column; }
            }
        }
        "#.to_string()
    }
}

#[allow(deprecated)]
pub fn generate_html_report(
    summary: super::markdown::ScanSummary,
    findings: Vec<super::markdown::Finding>,
) -> String {
    let report = HtmlReport::new(summary, findings);
    report.generate()
}
