use crate::error::Result;
use crate::output::agent::AgentFinding;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PdfConfig {
    pub title: String,
    pub author: String,
    pub subject: String,
}

impl Default for PdfConfig {
    fn default() -> Self {
        Self {
            title: "Security Scan Report".to_string(),
            author: "Slapper".to_string(),
            subject: "Vulnerability Assessment".to_string(),
        }
    }
}

pub struct PdfGenerator;

impl PdfGenerator {
    pub fn generate_report(findings: &[AgentFinding], config: &PdfConfig) -> Result<Vec<u8>> {
        let html = Self::generate_html(findings, config);
        Ok(html.into_bytes())
    }

    fn generate_html(findings: &[AgentFinding], config: &PdfConfig) -> String {
        let findings_html: String = findings
            .iter()
            .map(|f| {
                format!(
                    r#"<div class="finding">
                        <h3>{}</h3>
                        <p class="severity">Severity: {}</p>
                        <p>{}</p>
                        <h4>Remediation</h4>
                        <p>{}</p>
                    </div>"#,
                    f.title, f.severity, f.description, f.remediation.summary
                )
            })
            .collect();

        format!(
            r#"<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{}</title>
    <style>
        body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; line-height: 1.6; }}
        h1 {{ color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }}
        h2 {{ color: #555; margin-top: 30px; }}
        h3 {{ color: #666; }}
        .finding {{ background: #f9f9f9; padding: 15px; margin: 15px 0; border-left: 4px solid #ccc; }}
        .severity {{ font-weight: bold; }}
        .critical {{ border-color: #d32f2f; }}
        .high {{ border-color: #f57c00; }}
        .medium {{ border-color: #ff9800; }}
        .low {{ border-color: #4caf50; }}
        .info {{ border-color: #2196f3; }}
        .footer {{ margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc; color: #666; font-size: 12px; }}
    </style>
</head>
<body>
    <h1>{}</h1>
    <p><strong>Subject:</strong> {}</p>
    <p><strong>Generated:</strong> {}</p>
    <p><strong>Author:</strong> {}</p>

    <h2>Executive Summary</h2>
    <p>This report presents the findings of {} security vulnerabilities identified during the assessment.</p>

    <h2>Findings</h2>
    {}

    <div class="footer">
        <p>Generated by Slapper Security Scanner</p>
    </div>
</body>
</html>"#,
            config.title,
            config.title,
            config.subject,
            chrono::Utc::now().format("%Y-%m-%d %H:%M UTC"),
            config.author,
            findings.len(),
            findings_html
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pdf_config_default() {
        let config = PdfConfig::default();
        assert_eq!(config.title, "Security Scan Report");
    }

    #[test]
    fn test_html_generation() {
        let findings = vec![];
        let html = PdfGenerator::generate_html(&findings, &PdfConfig::default());
        assert!(html.contains("Security Scan Report"));
    }
}
