use crate::error::Result;
use crate::output::agent::AgentFinding;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PdfConfig {
    pub title: String,
    pub author: String,
    pub subject: String,
}

impl Default for PdfConfig {
    fn default() -> Self {
        Self {
            title: "Security Scan Report".to_string(),
            author: "Slapper".to_string(),
            subject: "Vulnerability Assessment".to_string(),
        }
    }
}

pub struct PdfGenerator;

impl PdfGenerator {
    #[cfg(feature = "pdf")]
    pub fn generate_report(findings: &[AgentFinding], config: &PdfConfig) -> Result<Vec<u8>> {
        use printpdf::*;

        let (doc, page1, layer1) = PdfDocument::new(&config.title, Mm(210.0), Mm(297.0), "Layer 1");

        let font = doc.add_builtin_font(BuiltinFont::Helvetica).map_err(|e| {
            crate::error::SlapperError::Config(format!("Failed to add font: {}", e))
        })?;

        let current_layer = doc.get_page(page1).get_layer(layer1);

        current_layer.use_text(&config.title, 24.0, Mm(20.0), Mm(277.0), &font);
        current_layer.use_text(
            &format!("Subject: {}", config.subject),
            12.0,
            Mm(20.0),
            Mm(265.0),
            &font,
        );
        current_layer.use_text(
            &format!("Author: {}", config.author),
            12.0,
            Mm(20.0),
            Mm(258.0),
            &font,
        );
        current_layer.use_text(
            &format!(
                "Generated: {}",
                chrono::Utc::now().format("%Y-%m-%d %H:%M UTC")
            ),
            12.0,
            Mm(20.0),
            Mm(251.0),
            &font,
        );

        current_layer.use_text(
            &format!("Total Findings: {}", findings.len()),
            14.0,
            Mm(20.0),
            Mm(235.0),
            &font,
        );

        let mut y_position = 220.0;
        let severity_colors: &[(&str, Color)] = &[
            ("Critical", Color::new(0.83, 0.18, 0.18)),
            ("High", Color::new(0.97, 0.49, 0.0)),
            ("Medium", Color::new(1.0, 0.6, 0.0)),
            ("Low", Color::new(0.3, 0.69, 0.31)),
            ("Info", Color::new(0.13, 0.59, 0.95)),
        ];

        for finding in findings.iter().take(30) {
            if y_position < 30.0 {
                break;
            }

            current_layer.use_text(&finding.title, 12.0, Mm(20.0), Mm(y_position), &font);
            y_position -= 6.0;

            let severity_str = format!("Severity: {}", finding.severity);
            current_layer.use_text(&severity_str, 10.0, Mm(25.0), Mm(y_position), &font);
            y_position -= 5.0;

            let description = if finding.description.len() > 100 {
                format!("{}...", &finding.description[..100])
            } else {
                finding.description.clone()
            };
            current_layer.use_text(&description, 9.0, Mm(25.0), Mm(y_position), &font);
            y_position -= 10.0;
        }

        current_layer.use_text(
            "Generated by Slapper Security Scanner",
            8.0,
            Mm(20.0),
            Mm(10.0),
            &font,
        );

        let bytes = doc.save_to_bytes().map_err(|e| {
            crate::error::SlapperError::Config(format!("Failed to save PDF: {}", e))
        })?;

        Ok(bytes)
    }

    #[cfg(not(feature = "pdf"))]
    pub fn generate_report(findings: &[AgentFinding], config: &PdfConfig) -> Result<Vec<u8>> {
        let html = Self::generate_html(findings, config);
        Ok(html.into_bytes())
    }

    fn generate_html(findings: &[AgentFinding], config: &PdfConfig) -> String {
        let findings_html: String = findings
            .iter()
            .map(|f| {
                format!(
                    r#"<div class="finding">
                        <h3>{}</h3>
                        <p class="severity">Severity: {}</p>
                        <p>{}</p>
                        <h4>Remediation</h4>
                        <p>{}</p>
                    </div>"#,
                    f.title, f.severity, f.description, f.remediation.summary
                )
            })
            .collect();

        format!(
            r#"<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{}</title>
    <style>
        body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; line-height: 1.6; }}
        h1 {{ color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }}
        h2 {{ color: #555; margin-top: 30px; }}
        h3 {{ color: #666; }}
        .finding {{ background: #f9f9f9; padding: 15px; margin: 15px 0; border-left: 4px solid #ccc; }}
        .severity {{ font-weight: bold; }}
        .critical {{ border-color: #d32f2f; }}
        .high {{ border-color: #f57c00; }}
        .medium {{ border-color: #ff9800; }}
        .low {{ border-color: #4caf50; }}
        .info {{ border-color: #2196f3; }}
        .footer {{ margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc; color: #666; font-size: 12px; }}
    </style>
</head>
<body>
    <h1>{}</h1>
    <p><strong>Subject:</strong> {}</p>
    <p><strong>Generated:</strong> {}</p>
    <p><strong>Author:</strong> {}</p>

    <h2>Executive Summary</h2>
    <p>This report presents the findings of {} security vulnerabilities identified during the assessment.</p>

    <h2>Findings</h2>
    {}

    <div class="footer">
        <p>Generated by Slapper Security Scanner</p>
    </div>
</body>
</html>"#,
            config.title,
            config.title,
            config.subject,
            chrono::Utc::now().format("%Y-%m-%d %H:%M UTC"),
            config.author,
            findings.len(),
            findings_html
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pdf_config_default() {
        let config = PdfConfig::default();
        assert_eq!(config.title, "Security Scan Report");
    }

    #[test]
    fn test_html_generation() {
        let findings = vec![];
        let html = PdfGenerator::generate_html(&findings, &PdfConfig::default());
        assert!(html.contains("Security Scan Report"));
    }
}
