// This file provides the gRPC service implementation
// The proto-generated code is in slapper.tool.v1 module

use serde::{Deserialize, Serialize};
use subtle::ConstantTimeEq;
use tonic::{Request, Response, Status};

use crate::tool::traits::{ParameterType, ToolCategory};
use crate::tool::{ToolDispatcher, ToolRegistry, ToolRequest};

// Include the proto-generated code
tonic::include_proto!("slapper.tool.v1");

// Helper structs for internal use (not generated by proto)
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcToolInfo {
    pub id: String,
    pub name: String,
    pub category: String,
    pub description: String,
    pub protocols: Vec<String>,
    pub capabilities: Vec<GrpcToolCapability>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcToolCapability {
    pub name: String,
    pub description: String,
    pub parameters: Vec<GrpcParameterDef>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcParameterDef {
    pub name: String,
    pub param_type: String,
    pub required: bool,
    pub default: Option<serde_json::Value>,
    pub description: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcResponseMetadata {
    pub started_at: String,
    pub completed_at: String,
    pub duration_ms: u64,
    pub targets_scanned: u32,
    pub findings_count: u32,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcToolError {
    pub code: String,
    pub message: String,
    pub details: Option<serde_json::Value>,
    pub target: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcFinding {
    pub id: String,
    pub finding_type: String,
    pub severity: String,
    pub title: String,
    pub description: String,
    pub location: String,
    pub evidence: Option<String>,
    pub cve_ids: Vec<String>,
    pub remediation: Option<String>,
    pub references: Vec<String>,
}

// ---------------------------------------------------------------------------
// API key interceptor
// ---------------------------------------------------------------------------

fn extract_api_key<T>(request: &Request<T>) -> Option<String> {
    request
        .metadata()
        .get("authorization")
        .and_then(|v| v.to_str().ok())
        .and_then(|v| {
            v.strip_prefix("Bearer ")
                .or_else(|| v.strip_prefix("bearer "))
        })
        .map(|v| v.to_string())
}

pub struct ApiKeyInterceptor {
    expected_key: Option<String>,
}

impl Clone for ApiKeyInterceptor {
    fn clone(&self) -> Self {
        Self {
            expected_key: self.expected_key.clone(),
        }
    }
}

impl ApiKeyInterceptor {
    pub fn new(expected_key: Option<String>) -> Self {
        Self { expected_key }
    }
}

impl tonic::service::Interceptor for ApiKeyInterceptor {
    fn call(&mut self, request: Request<()>) -> Result<Request<()>, Status> {
        if let Some(ref expected) = self.expected_key {
            let provided = extract_api_key(&request).unwrap_or_default();
            if !bool::from(expected.as_bytes().ct_eq(provided.as_bytes())) {
                return Err(Status::unauthenticated("Invalid or missing API key"));
            }
        }
        Ok(request)
    }
}

// Service implementation
pub struct GrpcService {
    registry: ToolRegistry,
    dispatcher: ToolDispatcher,
    api_key: Option<String>,
}

impl GrpcService {
    pub fn new(registry: ToolRegistry, api_key: Option<String>) -> Self {
        let dispatcher = ToolDispatcher::new(registry.clone());
        Self {
            registry,
            dispatcher,
            api_key,
        }
    }

    pub fn validate_api_key(&self, key: &str) -> Result<(), String> {
        if let Some(ref expected) = self.api_key {
            if !bool::from(expected.as_bytes().ct_eq(key.as_bytes())) {
                return Err("Invalid or missing API key".to_string());
            }
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Conversion functions: internal types -> protobuf types
// ---------------------------------------------------------------------------

fn tool_category_to_string(cat: ToolCategory) -> &'static str {
    match cat {
        ToolCategory::Recon => "Reconnaissance",
        ToolCategory::Scanning => "Scanning",
        ToolCategory::Fuzzing => "Fuzzing",
        ToolCategory::Waf => "WAF",
        ToolCategory::LoadTest => "Load Testing",
        ToolCategory::Stress => "Stress Testing",
        ToolCategory::Pipeline => "Pipeline",
    }
}

fn parameter_type_to_string(pt: ParameterType) -> &'static str {
    match pt {
        ParameterType::String => "string",
        ParameterType::Integer => "integer",
        ParameterType::Boolean => "boolean",
        ParameterType::Float => "float",
        ParameterType::Array => "array",
        ParameterType::Object => "object",
        ParameterType::Url => "url",
        ParameterType::Ip => "ip",
        ParameterType::Domain => "domain",
    }
}

fn convert_internal_tool_info(info: &crate::tool::registry::ToolInfo) -> ToolInfo {
    ToolInfo {
        id: info.id.clone(),
        name: info.name.clone(),
        category: tool_category_to_string(info.category).to_string(),
        description: info.description.clone(),
        protocols: info.protocols.clone(),
        capabilities: info
            .capabilities
            .iter()
            .map(convert_internal_capability)
            .collect(),
    }
}

fn convert_internal_capability(cap: &crate::tool::traits::ToolCapability) -> ToolCapability {
    ToolCapability {
        name: cap.name.clone(),
        description: cap.description.clone(),
        parameters: cap.parameters.iter().map(convert_internal_param).collect(),
    }
}

fn convert_internal_param(param: &crate::tool::traits::ParameterDef) -> ParameterDef {
    ParameterDef {
        name: param.name.clone(),
        param_type: parameter_type_to_string(param.param_type.clone()).to_string(),
        required: param.required,
        default: param.default.as_ref().map(serde_json_to_proto_value),
        description: param.description.clone(),
    }
}

fn serde_json_to_proto_value(value: &serde_json::Value) -> prost_types::Value {
    match value {
        serde_json::Value::Null => prost_types::Value {
            kind: Some(prost_types::value::Kind::NullValue(0)),
        },
        serde_json::Value::Bool(b) => prost_types::Value {
            kind: Some(prost_types::value::Kind::BoolValue(*b)),
        },
        serde_json::Value::Number(n) => prost_types::Value {
            kind: Some(prost_types::value::Kind::NumberValue(
                n.as_f64().unwrap_or(0.0),
            )),
        },
        serde_json::Value::String(s) => prost_types::Value {
            kind: Some(prost_types::value::Kind::StringValue(s.clone())),
        },
        serde_json::Value::Array(arr) => prost_types::Value {
            kind: Some(prost_types::value::Kind::ListValue(
                prost_types::ListValue {
                    values: arr.iter().map(serde_json_to_proto_value).collect(),
                },
            )),
        },
        serde_json::Value::Object(obj) => prost_types::Value {
            kind: Some(prost_types::value::Kind::StructValue(prost_types::Struct {
                fields: obj
                    .iter()
                    .map(|(k, v)| (k.clone(), serde_json_to_proto_value(v)))
                    .collect(),
            })),
        },
    }
}

fn proto_to_serde_json_value(value: &prost_types::Value) -> serde_json::Value {
    use prost_types::value::Kind;
    match &value.kind {
        Some(Kind::NullValue(_)) => serde_json::Value::Null,
        Some(Kind::BoolValue(b)) => serde_json::Value::Bool(*b),
        Some(Kind::NumberValue(n)) => serde_json::Number::from_f64(*n)
            .map(serde_json::Value::Number)
            .unwrap_or(serde_json::Value::Null),
        Some(Kind::StringValue(s)) => serde_json::Value::String(s.clone()),
        Some(Kind::ListValue(list)) => {
            serde_json::Value::Array(list.values.iter().map(proto_to_serde_json_value).collect())
        }
        Some(Kind::StructValue(st)) => {
            let map: serde_json::Map<String, serde_json::Value> = st
                .fields
                .iter()
                .map(|(k, v)| (k.clone(), proto_to_serde_json_value(v)))
                .collect();
            serde_json::Value::Object(map)
        }
        None => serde_json::Value::Null,
    }
}

fn convert_response_status(status: crate::tool::response::ResponseStatus) -> i32 {
    use response_status::Status;
    (match status {
        crate::tool::response::ResponseStatus::Success => Status::Success,
        crate::tool::response::ResponseStatus::PartialSuccess => Status::PartialSuccess,
        crate::tool::response::ResponseStatus::Failed => Status::Failed,
        crate::tool::response::ResponseStatus::Timeout => Status::Timeout,
        crate::tool::response::ResponseStatus::ScopeViolation => Status::ScopeViolation,
        crate::tool::response::ResponseStatus::Cancelled => Status::Cancelled,
    }) as i32
}

fn convert_internal_response(resp: &crate::tool::response::ToolResponse) -> ExecuteToolResponse {
    ExecuteToolResponse {
        request_id: resp.request_id.clone(),
        tool_id: resp.tool_id.clone(),
        status: Some(ResponseStatus {
            status: convert_response_status(resp.status),
        }),
        results: Some(serde_json_to_proto_value(&resp.results)),
        metadata: Some(ResponseMetadata {
            started_at: resp.metadata.started_at.to_rfc3339(),
            completed_at: resp.metadata.completed_at.to_rfc3339(),
            duration_ms: resp.metadata.duration_ms,
            targets_scanned: resp.metadata.targets_scanned as u32,
            findings_count: resp.metadata.findings_count as u32,
        }),
        errors: resp.errors.iter().map(convert_internal_error).collect(),
        findings: resp.findings.iter().map(convert_internal_finding).collect(),
    }
}

fn convert_internal_error(err: &crate::tool::tool_error::ToolError) -> ToolError {
    ToolError {
        code: err.code.clone(),
        message: err.message.clone(),
        details: err.details.as_ref().map(serde_json_to_proto_value),
        target: err.target.clone().unwrap_or_default(),
    }
}

fn convert_internal_finding(finding: &crate::tool::finding::Finding) -> Finding {
    Finding {
        id: finding.id.clone(),
        finding_type: format!("{:?}", finding.finding_type),
        severity: finding.severity.as_str().to_string(),
        title: finding.title.clone(),
        description: finding.description.clone(),
        location: finding.location.clone(),
        evidence: finding.evidence.clone().unwrap_or_default(),
        cve_ids: finding.cve_ids.clone(),
        remediation: finding.remediation.clone().unwrap_or_default(),
        references: finding.references.clone(),
    }
}

// ---------------------------------------------------------------------------
// Conversion functions: protobuf types -> internal types
// ---------------------------------------------------------------------------

fn proto_target_type_to_internal(t: i32) -> crate::tool::request::TargetType {
    match t {
        1 => crate::tool::request::TargetType::Url,
        2 => crate::tool::request::TargetType::Domain,
        3 => crate::tool::request::TargetType::Ip,
        4 => crate::tool::request::TargetType::Cidr,
        5 => crate::tool::request::TargetType::File,
        _ => crate::tool::request::TargetType::Url,
    }
}

fn convert_proto_target(target: &Target) -> crate::tool::request::Target {
    let scope = target.scope.as_ref().map(|s| crate::tool::request::Scope {
        allowed_patterns: s.allowed_patterns.clone(),
        excluded_patterns: s.excluded_patterns.clone(),
        allowed_ips: s.allowed_ips.clone(),
        allow_subdomains: s.allow_subdomains,
    });

    crate::tool::request::Target {
        target_type: proto_target_type_to_internal(target.r#type),
        value: target.value.clone(),
        scope,
    }
}

fn convert_proto_options(opts: &RequestOptions) -> crate::tool::request::RequestOptions {
    use crate::tool::request::{AuthConfig as ReqAuthConfig, AuthType as ReqAuthType};

    let auth = opts.auth.as_ref().map(|a| {
        let auth_type = match a.auth_type {
            0 => ReqAuthType::None,
            1 => ReqAuthType::None,
            2 => ReqAuthType::Basic,
            3 => ReqAuthType::Bearer,
            4 => ReqAuthType::ApiKey,
            5 => ReqAuthType::OAuth2,
            _ => ReqAuthType::None,
        };
        let credentials = a
            .credentials
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();
        ReqAuthConfig {
            auth_type,
            credentials,
        }
    });

    let headers = if opts.headers.is_empty() {
        None
    } else {
        Some(
            opts.headers
                .iter()
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect(),
        )
    };

    crate::tool::request::RequestOptions {
        timeout_ms: Some(opts.timeout_ms),
        concurrency: Some(opts.concurrency as usize),
        rate_limit: Some(opts.rate_limit),
        proxy: if opts.proxy.is_empty() {
            None
        } else {
            Some(opts.proxy.clone())
        },
        headers,
        auth,
        stealth: opts.stealth,
        follow_redirects: opts.follow_redirects,
        verify_ssl: opts.verify_ssl,
    }
}

// ---------------------------------------------------------------------------
// Server implementation
// ---------------------------------------------------------------------------

pub async fn start_grpc_server(host: &str, port: u16, service: GrpcService) -> Result<(), String> {
    use tonic::transport::Server;

    let addr_str = format!("{}:{}", host, port);
    let addr: std::net::SocketAddr = match addr_str.parse() {
        Ok(a) => a,
        Err(e) => return Err(e.to_string()),
    };

    // Register the file descriptor set for reflection
    let reflection_service = tonic_reflection::server::Builder::configure()
        .register_encoded_file_descriptor_set(include_bytes!(concat!(
            env!("OUT_DIR"),
            "/tool_descriptor.bin"
        )))
        .build_v1()
        .map_err(|e| e.to_string())?;

    let api_key = service.api_key.clone();
    let tool_service = ToolServiceImpl {
        service: std::sync::Arc::new(service),
    };

    tracing::info!("Starting gRPC server on {}", addr);

    let interceptor_service = tool_service_server::ToolServiceServer::with_interceptor(
        tool_service,
        ApiKeyInterceptor::new(api_key),
    );

    Server::builder()
        .add_service(reflection_service)
        .add_service(interceptor_service)
        .serve(addr)
        .await
        .map_err(|e| e.to_string())?;

    Ok(())
}

pub struct ToolServiceImpl {
    service: std::sync::Arc<GrpcService>,
}

impl Clone for ToolServiceImpl {
    fn clone(&self) -> Self {
        Self {
            service: self.service.clone(),
        }
    }
}

#[tonic::async_trait]
impl tool_service_server::ToolService for ToolServiceImpl {
    type StreamExecuteToolStream =
        std::pin::Pin<Box<dyn tokio_stream::Stream<Item = Result<ToolStreamEvent, Status>> + Send>>;

    async fn list_tools(
        &self,
        request: Request<ListToolsRequest>,
    ) -> Result<Response<ListToolsResponse>, Status> {
        let req = request.into_inner();

        let tool_infos = if req.category.is_empty() {
            self.service.registry.list()
        } else {
            let category = ToolCategory::from_str(&req.category).ok_or_else(|| {
                Status::invalid_argument(format!("Unknown category: {}", req.category))
            })?;
            self.service.registry.list_by_category(category)
        };

        let categories: Vec<String> = self
            .service
            .registry
            .categories()
            .into_iter()
            .map(tool_category_to_string)
            .map(String::from)
            .collect();

        let tools = tool_infos.iter().map(convert_internal_tool_info).collect();

        Ok(Response::new(ListToolsResponse { tools, categories }))
    }

    async fn get_tool(
        &self,
        request: Request<GetToolRequest>,
    ) -> Result<Response<GetToolResponse>, Status> {
        let req = request.into_inner();

        let tool_arc = self
            .service
            .registry
            .get(&req.tool_id)
            .ok_or_else(|| Status::not_found(format!("Tool not found: {}", req.tool_id)))?;

        let info = crate::tool::registry::ToolInfo {
            id: tool_arc.id().to_string(),
            name: tool_arc.name().to_string(),
            category: tool_arc.category(),
            description: tool_arc.description().to_string(),
            capabilities: tool_arc.capabilities(),
            protocols: tool_arc
                .supported_protocols()
                .into_iter()
                .map(String::from)
                .collect(),
        };

        Ok(Response::new(GetToolResponse {
            tool: Some(convert_internal_tool_info(&info)),
        }))
    }

    async fn execute_tool(
        &self,
        request: Request<ExecuteToolRequest>,
    ) -> Result<Response<ExecuteToolResponse>, Status> {
        let req = request.into_inner();

        let target = req
            .target
            .as_ref()
            .ok_or_else(|| Status::invalid_argument("Target is required"))?;

        let internal_target = convert_proto_target(target);

        let params = req
            .params
            .as_ref()
            .map(proto_to_serde_json_value)
            .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));

        let options = req
            .options
            .as_ref()
            .map(convert_proto_options)
            .unwrap_or_default();

        let tool_request = ToolRequest::new(&req.tool_id, internal_target)
            .with_params(params)
            .with_options(options);

        let response = self
            .service
            .dispatcher
            .dispatch(tool_request)
            .await
            .map_err(|e| Status::internal(format!("Tool execution failed: {}", e)))?;

        Ok(Response::new(convert_internal_response(&response)))
    }

    async fn stream_execute_tool(
        &self,
        request: Request<ExecuteToolRequest>,
    ) -> Result<Response<Self::StreamExecuteToolStream>, Status> {
        let req = request.into_inner();

        let target = req
            .target
            .as_ref()
            .ok_or_else(|| Status::invalid_argument("Target is required"))?;

        let internal_target = convert_proto_target(target);

        let params = req
            .params
            .as_ref()
            .map(proto_to_serde_json_value)
            .unwrap_or(serde_json::Value::Object(serde_json::Map::new()));

        let options = req
            .options
            .as_ref()
            .map(convert_proto_options)
            .unwrap_or_default();

        let tool_request = ToolRequest::new(&req.tool_id, internal_target)
            .with_params(params)
            .with_options(options);

        let request_id = tool_request.id.clone();
        let dispatcher = self.service.dispatcher.clone();

        // TODO: Progress percentages are hardcoded. To provide real progress updates,
        // the SecurityTool trait would need a progress callback or channel mechanism.
        let stream = async_stream::stream! {
            // Send initial progress event
            yield Ok(ToolStreamEvent {
                request_id: request_id.clone(),
                event: Some(tool_stream_event::Event::Progress(ProgressEvent {
                    message: format!("Starting tool: {}", req.tool_id),
                    percent: 0,
                })),
            });

            // Execute the tool
            match dispatcher.dispatch(tool_request).await {
                Ok(response) => {
                    // Send progress update: execution complete, streaming findings
                    yield Ok(ToolStreamEvent {
                        request_id: request_id.clone(),
                        event: Some(tool_stream_event::Event::Progress(ProgressEvent {
                            message: "Tool execution complete, streaming findings".into(),
                            percent: 80,
                        })),
                    });

                    // Send findings as they come (batched)
                    for finding in &response.findings {
                        yield Ok(ToolStreamEvent {
                            request_id: request_id.clone(),
                            event: Some(tool_stream_event::Event::Finding(FindingEvent {
                                finding: Some(convert_internal_finding(finding)),
                            })),
                        });
                    }

                    // Send progress update: finalizing
                    yield Ok(ToolStreamEvent {
                        request_id: request_id.clone(),
                        event: Some(tool_stream_event::Event::Progress(ProgressEvent {
                            message: "Finalizing response".into(),
                            percent: 95,
                        })),
                    });

                    // Send completion event
                    yield Ok(ToolStreamEvent {
                        request_id: request_id.clone(),
                        event: Some(tool_stream_event::Event::Complete(CompleteEvent {
                            response: Some(convert_internal_response(&response)),
                        })),
                    });
                }
                Err(e) => {
                    yield Ok(ToolStreamEvent {
                        request_id: request_id.clone(),
                        event: Some(tool_stream_event::Event::Error(ErrorEvent {
                            message: format!("Tool execution failed: {}", e),
                            code: "EXECUTION_ERROR".to_string(),
                        })),
                    });
                }
            }
        };

        Ok(Response::new(Box::pin(stream)))
    }

    async fn get_capabilities(
        &self,
        request: Request<CapabilitiesRequest>,
    ) -> Result<Response<CapabilitiesResponse>, Status> {
        let req = request.into_inner();

        let tool_arc = self
            .service
            .registry
            .get(&req.tool_id)
            .ok_or_else(|| Status::not_found(format!("Tool not found: {}", req.tool_id)))?;

        let capabilities = tool_arc
            .capabilities()
            .into_iter()
            .map(|c| convert_internal_capability(&c))
            .collect();

        Ok(Response::new(CapabilitiesResponse { capabilities }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tool::finding::{Finding as InternalFinding, FindingType, ResponseSeverity};
    use crate::tool::response::ToolResponse;
    use crate::tool::tool_error::ToolError as InternalToolError;
    use crate::tool::traits::{
        ParameterDef as InternalParameterDef, ParameterType, ToolCapability,
    };

    #[test]
    fn test_serde_json_to_proto_value_null() {
        let proto = serde_json_to_proto_value(&serde_json::Value::Null);
        assert!(matches!(
            proto.kind,
            Some(prost_types::value::Kind::NullValue(0))
        ));
    }

    #[test]
    fn test_serde_json_to_proto_value_bool() {
        let proto = serde_json_to_proto_value(&serde_json::Value::Bool(true));
        assert!(matches!(
            proto.kind,
            Some(prost_types::value::Kind::BoolValue(true))
        ));
    }

    #[test]
    fn test_serde_json_to_proto_value_string() {
        let proto = serde_json_to_proto_value(&serde_json::Value::String("hello".into()));
        match proto.kind {
            Some(prost_types::value::Kind::StringValue(s)) => assert_eq!(s, "hello"),
            _ => panic!("Expected StringValue"),
        }
    }

    #[test]
    fn test_proto_to_serde_json_value_roundtrip() {
        let original = serde_json::json!({
            "key": "value",
            "number": 42.0,
            "nested": {"a": true}
        });
        let proto = serde_json_to_proto_value(&original);
        let back = proto_to_serde_json_value(&proto);
        assert_eq!(original, back);
    }

    #[test]
    fn test_convert_internal_finding() {
        let finding = InternalFinding {
            id: "f1".into(),
            finding_type: FindingType::Vulnerability,
            severity: ResponseSeverity::High,
            title: "Test".into(),
            description: "Desc".into(),
            location: "http://example.com".into(),
            evidence: Some("evidence".into()),
            cve_ids: vec!["CVE-2024-0001".into()],
            remediation: Some("Fix it".into()),
            references: vec!["https://ref.example.com".into()],
            metadata: Default::default(),
        };

        let proto = convert_internal_finding(&finding);
        assert_eq!(proto.id, "f1");
        assert_eq!(proto.title, "Test");
        assert_eq!(proto.severity, "high");
        assert_eq!(proto.evidence, "evidence");
        assert_eq!(proto.cve_ids, vec!["CVE-2024-0001"]);
        assert_eq!(proto.remediation, "Fix it");
    }

    #[test]
    fn test_convert_internal_error() {
        let err = InternalToolError::new("E001", "something broke")
            .with_details(serde_json::json!({"detail": "info"}))
            .at_target("http://example.com");

        let proto = convert_internal_error(&err);
        assert_eq!(proto.code, "E001");
        assert_eq!(proto.message, "something broke");
        assert!(proto.details.is_some());
        assert_eq!(proto.target, "http://example.com");
    }

    #[test]
    fn test_convert_internal_response() {
        let resp = ToolResponse::success("req-1", "scanner", serde_json::json!({}));
        let proto = convert_internal_response(&resp);
        assert_eq!(proto.request_id, "req-1");
        assert_eq!(proto.tool_id, "scanner");
        assert!(proto.status.is_some());
        assert!(proto.metadata.is_some());
        assert!(proto.errors.is_empty());
        assert!(proto.findings.is_empty());
    }

    #[test]
    fn test_tool_category_to_string() {
        assert_eq!(
            tool_category_to_string(ToolCategory::Recon),
            "Reconnaissance"
        );
        assert_eq!(tool_category_to_string(ToolCategory::Scanning), "Scanning");
        assert_eq!(tool_category_to_string(ToolCategory::Waf), "WAF");
    }

    #[test]
    fn test_parameter_type_to_string() {
        assert_eq!(parameter_type_to_string(ParameterType::String), "string");
        assert_eq!(parameter_type_to_string(ParameterType::Integer), "integer");
        assert_eq!(parameter_type_to_string(ParameterType::Url), "url");
    }

    #[test]
    fn test_proto_target_type_to_internal() {
        assert_eq!(
            proto_target_type_to_internal(1),
            crate::tool::request::TargetType::Url
        );
        assert_eq!(
            proto_target_type_to_internal(3),
            crate::tool::request::TargetType::Ip
        );
        assert_eq!(
            proto_target_type_to_internal(0),
            crate::tool::request::TargetType::Url
        );
    }

    #[test]
    fn test_convert_proto_target_with_scope() {
        let target = Target {
            r#type: 2,
            value: "example.com".into(),
            scope: Some(Scope {
                allowed_patterns: vec!["*.example.com".into()],
                excluded_patterns: vec![],
                allowed_ips: vec![],
                allow_subdomains: true,
            }),
        };

        let internal = convert_proto_target(&target);
        assert_eq!(
            internal.target_type,
            crate::tool::request::TargetType::Domain
        );
        assert_eq!(internal.value, "example.com");
        assert!(internal.scope.is_some());
        let scope = internal.scope.unwrap();
        assert_eq!(scope.allowed_patterns, vec!["*.example.com"]);
        assert!(scope.allow_subdomains);
    }

    #[test]
    fn test_convert_proto_options_defaults() {
        let opts = RequestOptions {
            timeout_ms: 5000,
            concurrency: 20,
            rate_limit: 100.0,
            proxy: String::new(),
            headers: Default::default(),
            auth: None,
            stealth: true,
            follow_redirects: false,
            verify_ssl: false,
        };

        let internal = convert_proto_options(&opts);
        assert_eq!(internal.timeout_ms, Some(5000));
        assert_eq!(internal.concurrency, Some(20));
        assert_eq!(internal.rate_limit, Some(100.0));
        assert!(internal.proxy.is_none());
        assert!(internal.stealth);
        assert!(!internal.follow_redirects);
        assert!(!internal.verify_ssl);
    }

    #[test]
    fn test_convert_internal_tool_info() {
        let info = crate::tool::registry::ToolInfo {
            id: "scanner-1".into(),
            name: "Port Scanner".into(),
            category: ToolCategory::Scanning,
            description: "Scans ports".into(),
            capabilities: vec![ToolCapability {
                name: "port-scan".into(),
                description: "Scan TCP ports".into(),
                parameters: vec![InternalParameterDef {
                    name: "ports".into(),
                    param_type: ParameterType::String,
                    required: true,
                    default: None,
                    description: "Port range".into(),
                }],
                ..Default::default()
            }],
            protocols: vec!["http".into()],
        };

        let proto = convert_internal_tool_info(&info);
        assert_eq!(proto.id, "scanner-1");
        assert_eq!(proto.name, "Port Scanner");
        assert_eq!(proto.category, "Scanning");
        assert_eq!(proto.capabilities.len(), 1);
        assert_eq!(proto.capabilities[0].name, "port-scan");
        assert_eq!(proto.capabilities[0].parameters.len(), 1);
        assert_eq!(proto.capabilities[0].parameters[0].name, "ports");
        assert!(proto.capabilities[0].parameters[0].required);
    }
}
