// This file provides the gRPC service implementation
// The proto-generated code is in slapper.tool.v1 module

use serde::{Deserialize, Serialize};
use subtle::ConstantTimeEq;
use tonic::{Request, Response, Status};

use crate::tool::{
    ToolDispatcher, ToolRegistry, ToolRequest,
};

// Include the proto-generated code
tonic::include_proto!("slapper.tool.v1");

// Helper structs for internal use (not generated by proto)
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcToolInfo {
    pub id: String,
    pub name: String,
    pub category: String,
    pub description: String,
    pub protocols: Vec<String>,
    pub capabilities: Vec<GrpcToolCapability>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcToolCapability {
    pub name: String,
    pub description: String,
    pub parameters: Vec<GrpcParameterDef>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcParameterDef {
    pub name: String,
    pub param_type: String,
    pub required: bool,
    pub default: Option<serde_json::Value>,
    pub description: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcResponseMetadata {
    pub started_at: String,
    pub completed_at: String,
    pub duration_ms: u64,
    pub targets_scanned: u32,
    pub findings_count: u32,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcToolError {
    pub code: String,
    pub message: String,
    pub details: Option<serde_json::Value>,
    pub target: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GrpcFinding {
    pub id: String,
    pub finding_type: String,
    pub severity: String,
    pub title: String,
    pub description: String,
    pub location: String,
    pub evidence: Option<String>,
    pub cve_ids: Vec<String>,
    pub remediation: Option<String>,
    pub references: Vec<String>,
}

// Service implementation
pub struct GrpcService {
    registry: ToolRegistry,
    dispatcher: ToolDispatcher,
    api_key: Option<String>,
}

impl GrpcService {
    pub fn new(registry: ToolRegistry, api_key: Option<String>) -> Self {
        let dispatcher = ToolDispatcher::new(registry.clone());
        Self {
            registry,
            dispatcher,
            api_key,
        }
    }

    pub fn validate_api_key(&self, key: &str) -> Result<(), String> {
        if let Some(ref expected) = self.api_key {
            if !bool::from(expected.as_bytes().ct_eq(key.as_bytes())) {
                return Err("Invalid or missing API key".to_string());
            }
        }
        Ok(())
    }
}

// Conversion functions
fn convert_tool_info_to_proto(info: GrpcToolInfo) -> ToolInfo {
    ToolInfo {
        id: info.id,
        name: info.name,
        category: info.category,
        description: info.description,
        protocols: info.protocols,
        capabilities: info.capabilities.into_iter().map(convert_capability_to_proto).collect(),
    }
}

fn convert_capability_to_proto(cap: GrpcToolCapability) -> ToolCapability {
    ToolCapability {
        name: cap.name,
        description: cap.description,
        parameters: cap.parameters.into_iter().map(convert_param_to_proto).collect(),
    }
}

fn convert_param_to_proto(param: GrpcParameterDef) -> ParameterDef {
    ParameterDef {
        name: param.name,
        param_type: param.param_type,
        required: param.required,
        default: Some(serde_json_value_to_proto(param.default)),
        description: param.description,
    }
}

fn serde_json_value_to_proto(value: Option<serde_json::Value>) -> prost_types::Value {
    match value {
        Some(serde_json::Value::Null) => prost_types::Value {
            kind: Some(prost_types::value::Kind::NullValue(0)),
        },
        Some(serde_json::Value::Bool(b)) => prost_types::Value {
            kind: Some(prost_types::value::Kind::BoolValue(b)),
        },
        Some(serde_json::Value::Number(n)) => {
            prost_types::Value {
                kind: Some(prost_types::value::Kind::NumberValue(n.as_f64().unwrap_or(0.0))),
            }
        }
        Some(serde_json::Value::String(s)) => prost_types::Value {
            kind: Some(prost_types::value::Kind::StringValue(s)),
        },
        Some(serde_json::Value::Array(arr)) => prost_types::Value {
            kind: Some(prost_types::value::Kind::ListValue(prost_types::ListValue {
                values: arr.into_iter().map(|v| {
                    let opt: Option<serde_json::Value> = Some(v);
                    serde_json_value_to_proto(opt)
                }).collect(),
            })),
        },
        Some(serde_json::Value::Object(obj)) => prost_types::Value {
            kind: Some(prost_types::value::Kind::StructValue(prost_types::Struct {
                fields: obj
                    .into_iter()
                    .map(|(k, v)| (k, serde_json_value_to_proto(Some(v))))
                    .collect(),
            })),
        },
        None => prost_types::Value {
            kind: Some(prost_types::value::Kind::NullValue(0)),
        },
    }
}

// Server implementation
pub async fn start_grpc_server(
    host: &str,
    port: u16,
    service: GrpcService,
) -> Result<(), String> {
    use tonic::{transport::Server, Request, Response, Status};

    let addr_str = format!("{}:{}", host, port);
    let addr: std::net::SocketAddr = match addr_str.parse() {
        Ok(a) => a,
        Err(e) => return Err(e.to_string()),
    };

    // Register the file descriptor set for reflection
    let reflection_service = tonic_reflection::server::Builder::configure()
        .register_encoded_file_descriptor_set(include_bytes!(concat!(env!("OUT_DIR"), "/tool_descriptor.bin")))
        .build_v1()
        .map_err(|e| e.to_string())?;

    let tool_service = ToolServiceImpl { service };

    tracing::info!("Starting gRPC server on {}", addr);

    Server::builder()
        .add_service(reflection_service)
        .add_service(
            tool_service_server::ToolServiceServer::new(tool_service),
        )
        .serve(addr)
        .await
        .map_err(|e| e.to_string())?;

    Ok(())
}

pub struct ToolServiceImpl {
    service: GrpcService,
}

#[tonic::async_trait]
impl tool_service_server::ToolService for ToolServiceImpl {
    type StreamExecuteToolStream = tonic::Streaming<ToolStreamEvent>;

    async fn list_tools(
        &self,
        request: Request<ListToolsRequest>,
    ) -> Result<Response<ListToolsResponse>, Status> {
        let req = request.into_inner();
        // Implementation here
        Err(Status::unimplemented("Not yet implemented"))
    }

    async fn get_tool(
        &self,
        request: Request<GetToolRequest>,
    ) -> Result<Response<GetToolResponse>, Status> {
        Err(Status::unimplemented("Not yet implemented"))
    }

    async fn execute_tool(
        &self,
        request: Request<ExecuteToolRequest>,
    ) -> Result<Response<ExecuteToolResponse>, Status> {
        Err(Status::unimplemented("Not yet implemented"))
    }

    async fn stream_execute_tool(
        &self,
        request: Request<ExecuteToolRequest>,
    ) -> Result<Response<Self::StreamExecuteToolStream>, Status> {
        Err(Status::unimplemented("Not yet implemented"))
    }

    async fn get_capabilities(
        &self,
        request: Request<CapabilitiesRequest>,
    ) -> Result<Response<CapabilitiesResponse>, Status> {
        Err(Status::unimplemented("Not yet implemented"))
    }
}
