//! Configuration management module
//!
//! This module handles loading, parsing, and managing Eggsec configuration.
//! Configuration can be loaded from TOML/YAML files or created programmatically.
//!
//! ## Key Components
//!
//! - [`EggsecConfig`] - Main configuration struct containing all settings
//! - [`Scope`] - Target scope rules for authorized scanning
//! - [`ScanConfig`] - Port scanning, endpoint discovery, and fuzzing settings
//! - [`HttpConfig`] - HTTP client configuration (timeouts, proxies, auth)
//!
//! ## Usage
//!
//! ### Loading Configuration
//!
//! ```rust,no_run
//! use eggsec::config::{load_config, EggsecConfig};
//!
//! // Load from default location (~/.config/eggsec/eggsec.toml)
//! let config = load_config(None)?;
//! println!("Default concurrency: {}", config.scan.default_concurrency);
//!
//! // Load from specific path
//! let config = load_config(Some("/path/to/config.toml"))?;
//! # Ok::<(), anyhow::Error>(())
//! ```
//!
//! ## Configuration File
//!
//! The default configuration file is located at:
//! - Linux/macOS: `~/.config/eggsec/eggsec.toml`
//! - Windows: `%APPDATA%\eggsec\eggsec.toml`

mod api;
mod budget;
mod discovery;
mod feature_registry;
mod http;
mod loader;
mod policy;
mod policy_approval;
mod policy_catalog;
mod policy_decision;
mod policy_target;
mod presets;
mod scan;
mod scope;
mod scope_address;
mod scope_resolver;
mod scope_spec;
mod scope_transport;
mod settings;

pub use feature_registry::{
    classify_feature, feature_missing_hint, feature_state, full_exclusion_reason,
    is_feature_enabled as is_feature_enabled_registry, is_full_member,
    is_known_feature as is_known_feature_registry, FeatureCategory, FeatureEntry, FeatureState,
    ALL_FEATURES, FULL_EXCLUDED_WITH_REASON, FULL_MEMBERS,
};

pub use api::{ApiConfig, ApiKeyConfig, IpApiConfig, MaxMindConfig, NvdConfig, WaybackConfig};
pub use budget::{BudgetError, ExecutionBudget};
pub use discovery::DiscoveredTargetStatus;
pub use http::{HttpConfig, Verbosity};
pub use loader::{config_dir, load_config, load_scope, load_scope_with_source};
pub use policy::{
    baseline_allowed_capability, normalize_target, Capability, DenialClass, DescriptorError,
    ExecutionPolicy, ExecutionProfile, ExecutionSurface, IntendedUse, OperationDescriptor,
    OperationMode, OperationRisk, OperationTarget, TargetHint,
};
pub use policy_decision::{
    classify_denial_reasons, confirmation_class_strings, confirmation_classes_for,
    evaluate_enforcement, evaluate_operation_policy, is_feature_enabled, is_known_feature,
    may_downgrade_to_warning, preflight_operation, ApprovedExecution, ApprovedOperation,
    ConfirmationClass, EnforcementContext, EnforcementError, EnforcementOutcome, ManualOverride,
    PolicyDecision, PreflightOutcomeKind, PreflightResult,
};
pub use presets::DefenseLabPreset;

/// Explicit feature-availability input (canonical owner: `eggsec-policy`).
pub use eggsec_policy::EnabledFeatures;
pub use policy::{
    all_operation_metadata, metadata_for_tool_id, operation_matches_tool_id, operation_metadata,
    OperationMetadata, TargetPolicyKind, ALL_OPERATION_METADATA, ALL_OPERATION_METADATA_ALIASES,
};
pub use policy_catalog::derive_operation_integration;
pub use scan::{
    FuzzProfile, NotificationConfig, OutputConfig, ScanConfig, ScanProfile, WebhookConfig,
    WebhookEvent,
};
pub use scope::{
    classify_address, default_resolver, is_private_ip, resolve_hostname_facts,
    resolve_hostname_facts_with, resolve_target_facts, resolve_target_facts_with,
    session_scope_from_loaded, AddressClass, HostResolver, LoadedScope, ResolutionResult, Scope,
    ScopeError, ScopeResolution, ScopeRule, ScopeSource, SystemResolver, TargetScope,
};
pub use scope_spec::{
    is_parsed_target_allowed_by_scope_and_spec, is_target_allowed_by_scope_and_spec,
    is_target_allowed_by_scope_and_spec_with_resolver, scope_from_spec, ScopeSpecError,
};
pub use scope_transport::ScopeAuthority;
pub use settings::{
    AiConfig, AlertChannelConfigEntry, AlertChannelsConfig, AllowedWorker, CacheConfig,
    ConfigError, EggsecConfig, EmailConfigEntry, PagerDutyConfigEntry, PathsConfig,
    ProxyConfigEntry, ReconConfig, RemoteConfig, ScheduledScan, SearchConfig, SlackConfigEntry,
    WebhookConfigEntry,
};

pub const ENV_PREFIX: &str = "EGGSEC_";

pub fn get_default_config() -> String {
    r#"# Eggsec Configuration File
# Generated by eggsec

[http]
timeout_secs = 30
max_retries = 3
retry_delay_ms = 1000
verify_tls = true
follow_redirects = true
max_redirects = 10
# default_user_agent = "Eggsec/0.1.0"
# proxy = "http://127.0.0.1:8080"
# proxy_auth = "username:password"

[scan]
default_concurrency = 10
port_timeout_secs = 2
stealth_mode = false
# rate_limit_per_second = 100
# jitter_ms = [5, 25]

[recon]
dns_concurrency = 10

[output]
format = "pretty"
verbosity = "Normal"
# Uncomment to save reports
# save_results = true
# results_dir = "./reports"

# Execution policy: which risk tiers the operator has enabled. Everything
# below defaults to false, so only passive and safe-active operations run
# until you opt in. Each flag still requires the matching --allow-* CLI flag
# (or the matching --yes, for low-risk scope prompts) before it executes:
# this section enables the tier, it does not authorize a specific run.
[execution_policy]
# Intrusive fuzzing (SQLi/RCE payloads, authenticated request replay).
allow_intrusive_fuzzing = false
# Load testing against an authorized target.
allow_load_testing = false
# Volumetric stress / flood testing.
allow_stress_testing = false
# Raw packet send/capture (requires elevated capabilities).
allow_raw_packets = false
# Credential / authentication testing.
allow_credential_testing = false
# Direct database pentesting (authorized lab instances only).
allow_db_pentesting = false
# Traffic interception (MITM proxy).
allow_traffic_interception = false
# Remote command execution against managed agents.
allow_remote_execution = false
# Evasive/detection-bypass testing.
allow_evasion_testing = false
# Post-exploitation actions.
allow_post_exploitation = false
# Exploit-adjacent (non-destructive) validation.
allow_exploit_adjacent = false
# Command-and-control infrastructure operations.
allow_c2_operations = false
# Autonomous agent operation without per-step confirmation.
allow_agent_autonomous = false
"#
    .to_string()
}

#[cfg(test)]
mod default_config_template_tests {
    use super::get_default_config;
    use crate::config::EggsecConfig;

    /// The template emitted by `eggsec --generate-config` is the only file the
    /// operator is told to write, so it must actually deserialize. It also has
    /// to name every `ExecutionPolicy` key: the entire enforcement surface was
    /// previously absent from the template, leaving the only supported way to
    /// enable a risk tier undiscoverable.
    #[test]
    fn generated_template_deserializes_into_config() {
        let template = get_default_config();
        let parsed: EggsecConfig = toml::from_str(&template).unwrap_or_else(|e| {
            panic!("generated config template must parse: {e}\n---\n{template}")
        });
        // Every advertised tier must default to disabled, so shipping the
        // template cannot silently widen the policy.
        assert!(!parsed.execution_policy.allow_intrusive_fuzzing);
        assert!(!parsed.execution_policy.allow_load_testing);
        assert!(!parsed.execution_policy.allow_stress_testing);
        assert!(!parsed.execution_policy.allow_raw_packets);
        assert!(!parsed.execution_policy.allow_credential_testing);
        assert!(!parsed.execution_policy.allow_db_pentesting);
        assert!(!parsed.execution_policy.allow_traffic_interception);
        assert!(!parsed.execution_policy.allow_remote_execution);
        assert!(!parsed.execution_policy.allow_evasion_testing);
        assert!(!parsed.execution_policy.allow_post_exploitation);
        assert!(!parsed.execution_policy.allow_exploit_adjacent);
        assert!(!parsed.execution_policy.allow_c2_operations);
        assert!(!parsed.execution_policy.allow_agent_autonomous);
    }

    /// Guards against a key being added to `ExecutionPolicy` but forgotten in
    /// the generated template, which would leave it undiscoverable again.
    #[test]
    fn generated_template_covers_every_execution_policy_key() {
        let template = get_default_config();
        for key in POLICY_TEMPLATE_KEYS {
            assert!(
                template.contains(&format!("{key} =")),
                "[execution_policy] key `{key}` is missing from the generated config template"
            );
        }
    }

    const POLICY_TEMPLATE_KEYS: &[&str] = &[
        "allow_intrusive_fuzzing",
        "allow_load_testing",
        "allow_stress_testing",
        "allow_raw_packets",
        "allow_credential_testing",
        "allow_db_pentesting",
        "allow_traffic_interception",
        "allow_remote_execution",
        "allow_evasion_testing",
        "allow_post_exploitation",
        "allow_exploit_adjacent",
        "allow_c2_operations",
        "allow_agent_autonomous",
    ];
}
