//! Configuration management module
//!
//! This module handles loading, parsing, and managing Eggsec configuration.
//! Configuration can be loaded from TOML/YAML files or created programmatically.
//!
//! ## Key Components
//!
//! - [`EggsecConfig`] - Main configuration struct containing all settings
//! - [`Scope`] - Target scope rules for authorized scanning
//! - [`ScanConfig`] - Port scanning, endpoint discovery, and fuzzing settings
//! - [`HttpConfig`] - HTTP client configuration (timeouts, proxies, auth)
//!
//! ## Usage
//!
//! ### Loading Configuration
//!
//! ```rust,no_run
//! use eggsec::config::{load_config, EggsecConfig};
//!
//! // Load from default location (~/.config/eggsec/eggsec.toml)
//! let config = load_config(None)?;
//! println!("Default concurrency: {}", config.scan.default_concurrency);
//!
//! // Load from specific path
//! let config = load_config(Some("/path/to/config.toml"))?;
//! # Ok::<(), anyhow::Error>(())
//! ```
//!
//! ## Configuration File
//!
//! The default configuration file is located at:
//! - Linux/macOS: `~/.config/eggsec/eggsec.toml`
//! - Windows: `%APPDATA%\eggsec\eggsec.toml`

mod api;
mod budget;
mod discovery;
mod http;
mod loader;
mod policy;
mod policy_decision;
mod presets;
mod scan;
mod scope;
mod settings;

pub use api::{ApiConfig, ApiKeyConfig, IpApiConfig, MaxMindConfig, NvdConfig, WaybackConfig};
pub use budget::{BudgetError, ExecutionBudget};
pub use discovery::DiscoveredTargetStatus;
pub use http::{HttpConfig, Verbosity};
pub use loader::{config_dir, load_config, load_scope, load_scope_with_source};
pub use policy::{
    baseline_allowed_capability, Capability, DenialClass, ExecutionPolicy, ExecutionProfile,
    IntendedUse, OperationDescriptor, OperationMode, OperationRisk,
};
pub use policy_decision::{
    classify_denial_reasons, evaluate_enforcement, evaluate_operation_policy,
    may_downgrade_to_warning, EnforcementContext, EnforcementOutcome, PolicyDecision,
};
pub use presets::DefenseLabPreset;
pub use scan::{
    FuzzProfile, NotificationConfig, OutputConfig, ScanConfig, ScanProfile, WebhookConfig,
    WebhookEvent,
};
pub use scope::{
    is_private_ip, LoadedScope, Scope, ScopeError, ScopeRule, ScopeSource, TargetScope,
};
pub use settings::{
    AiConfig, AlertChannelConfigEntry, AlertChannelsConfig, AllowedWorker, CacheConfig,
    ConfigError, EggsecConfig, EmailConfigEntry, PagerDutyConfigEntry, PathsConfig,
    ProxyConfigEntry, ReconConfig, RemoteConfig, ScheduledScan, SlackConfigEntry,
    WebhookConfigEntry,
};

pub const ENV_PREFIX: &str = "EGGSEC_";

pub fn get_default_config() -> String {
    r#"# Eggsec Configuration File
# Generated by eggsec

[http]
timeout_secs = 30
max_retries = 3
retry_delay_ms = 1000
verify_tls = true
follow_redirects = true
max_redirects = 10
# default_user_agent = "Eggsec/0.1.0"
# proxy = "http://127.0.0.1:8080"
# proxy_auth = "username:password"

[scan]
default_concurrency = 10
port_timeout_secs = 2
stealth_mode = false
# rate_limit_per_second = 100
# jitter_ms = [5, 25]

[recon]
dns_concurrency = 10

[output]
format = "pretty"
verbosity = "Normal"
# Uncomment to save reports
# save_results = true
# results_dir = "./reports"
"#
    .to_string()
}
