use crate::fuzzer::payloads::{Payload, PayloadType, Severity};

pub fn get_payloads() -> Vec<Payload> {
    vec![
        Payload {
            payload_type: PayloadType::Host,
            payload: "evil.com".to_string(),
            description: "Host header injection - basic domain".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "header-injection".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "127.0.0.1".to_string(),
            description: "Host header injection - localhost".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "localhost".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "localhost".to_string(),
            description: "Host header injection - localhost string".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "localhost".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "0.0.0.0".to_string(),
            description: "Host header injection - 0.0.0.0".to_string(),
            severity: Severity::Medium,
            tags: vec!["host".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "127.1".to_string(),
            description: "Host header injection - shortened localhost".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "localhost".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "127.0.1".to_string(),
            description: "Host header injection - alternative localhost".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "localhost".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "[::1]".to_string(),
            description: "Host header injection - IPv6 localhost".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "ipv6".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "example.com:443".to_string(),
            description: "Host header injection - with port".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "port".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "example.com#".to_string(),
            description: "Host header injection - fragment bypass".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "bypass".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "example.com?foo=bar".to_string(),
            description: "Host header injection - query string bypass".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "bypass".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "example.com%00".to_string(),
            description: "Host header injection - null byte bypass".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "bypass".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "example.com\r\nX-Forwarded-Host: evil.com".to_string(),
            description: "Host header injection - CRLF injection".to_string(),
            severity: Severity::Critical,
            tags: vec!["host".to_string(), "crlf".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "example.com%0d%0aX-Forwarded-Host: evil.com".to_string(),
            description: "Host header injection - URL encoded CRLF".to_string(),
            severity: Severity::Critical,
            tags: vec!["host".to_string(), "crlf".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "host: example.com".to_string(),
            description: "Host header injection - lowercase host".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "HOST: example.com".to_string(),
            description: "Host header injection - uppercase HOST".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "eXaMpLe.CoM".to_string(),
            description: "Host header injection - case variation".to_string(),
            severity: Severity::Medium,
            tags: vec!["host".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "example.com.evil.com".to_string(),
            description: "Host header injection - domain hijacking attempt".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "domain-hijack".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "example.com.127.0.0.1".to_string(),
            description: "Host header injection - domain + IP confusion".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "a".to_string(),
            description: "Host header injection - single character".to_string(),
            severity: Severity::Low,
            tags: vec!["host".to_string(), "test".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "".to_string(),
            description: "Host header injection - empty host".to_string(),
            severity: Severity::Low,
            tags: vec!["host".to_string(), "test".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "127.0.0.1:8080".to_string(),
            description: "Host header injection - internal port scan".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "port-scan".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "192.168.1.1".to_string(),
            description: "Host header injection - private IP".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "private-ip".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "10.0.0.1".to_string(),
            description: "Host header injection - 10.x private IP".to_string(),
            severity: Severity::High,
            tags: vec!["host".to_string(), "private-ip".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "169.254.169.254".to_string(),
            description: "Host header injection - AWS metadata".to_string(),
            severity: Severity::Critical,
            tags: vec!["host".to_string(), "cloud".to_string(), "aws".to_string()],
        },
        Payload {
            payload_type: PayloadType::Host,
            payload: "metadata.google.internal".to_string(),
            description: "Host header injection - GCP metadata".to_string(),
            severity: Severity::Critical,
            tags: vec!["host".to_string(), "cloud".to_string(), "gcp".to_string()],
        },
    ]
}
