//! Attack payload corpora (extracted from `eggsec::fuzzer::payloads` in Phase G).
//!
//! Injection, traversal, deserialization, and protocol-abuse payload sets, plus
//! the [`PayloadType`] enum and [`Payload`] DTO they share.
//!
//! # What this crate is
//!
//! Payload **data**: it builds strings and returns them. It opens no socket and
//! performs no probing. Its only workspace dependency is `eggsec-core`, for
//! [`Severity`]; guard 148 forbids any I/O, transport, frontend, or engine
//! dependency.
//!
//! # This crate owns all 40 payload types
//!
//! Every [`PayloadType`] variant resolves here, and [`get_payloads`] returns
//! real payloads for all of them. Nothing panics, nothing returns a silent
//! empty vector, and [`get_payloads_cached`] / [`get_all_payloads_cached`] span
//! the whole set. That is what makes the crate usable as a library.
//!
//! # The split is execution, not payload data
//!
//! Six types — [`PayloadType::GraphQL`], [`PayloadType::OAuth`],
//! [`PayloadType::Jwt`], [`PayloadType::Idor`], [`PayloadType::Ssti`], and
//! [`PayloadType::Grpc`] — are marked [`PayloadType::is_advanced`], and the
//! *probers* for them live in the `eggsec` engine, in
//! `eggsec::fuzzer::payloads::*` (`GraphQLFuzzer`, `OAuthFuzzer`, `JwtFuzzer`,
//! `IdorFuzzer`, `SstiFuzzer`, `GrpcFuzzer`).
//!
//! Those probers hold a `reqwest::Client` and make live requests, so they stay
//! in the engine. But the payload *strings* they send are static data, and
//! those live here, in the modules of the same names. An earlier cut of this
//! crate assumed the two were inseparable and left these 6 engine-owned,
//! which made [`get_payloads`] panic for 6 of 40 variants. That was wrong: the
//! payloads were always static.
//!
//! So read [`PayloadType::is_advanced`] as **"this type is executed by the
//! live-probe strategy"**, not "this type's payloads are generated by probing".
//! The engine's fuzzer branches on it to choose an execution strategy
//! (`eggsec::fuzzer::engine`); both branches feed off payloads defined here.
//!
//! # Laziness is load-bearing
//!
//! The caches below are `LazyLock`, so a process that never asks for a payload
//! never pays to build one. Materializing all 40 variants eagerly at startup
//! would regress every binary that links this crate, including the TUI.

pub mod cache;
pub mod compression;
pub mod csv;
pub mod deser;
pub mod expression;
pub mod graphql;
pub mod grpc;
pub mod headers;
pub mod host;
pub mod idor;
pub mod jwt;
pub mod ldap;
#[macro_use]
pub mod macros;
pub mod cmd;
pub mod css_inject;
pub mod dep_confusion;
pub mod dom_clobber;
pub mod html_inject;
pub mod latex;
pub mod mass_assign;
pub mod nosql;
pub mod oast;
pub mod oauth;
pub mod prototype;
pub mod race;
pub mod redirect;
pub mod redos;
pub mod saml;
pub mod soap;
pub mod sqli;
pub mod ssi;
pub mod ssrf;
pub mod ssti;
pub mod traversal;
pub mod viewstate;
pub mod websocket;
pub mod xpath;
pub mod xs_leak;
pub mod xslt;
pub mod xss;
pub mod xxe;

use serde::{Deserialize, Serialize};
use std::sync::LazyLock;
use strum::{EnumIter, IntoEnumIterator};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, EnumIter)]
pub enum PayloadType {
    Sqli,
    Xss,
    Traversal,
    Ssrf,
    Redirect,
    Redos,
    Headers,
    Compression,
    GraphQL,
    OAuth,
    Jwt,
    Idor,
    Ssti,
    Grpc,
    Xxe,
    Ldap,
    Cmd,
    Deser,
    Host,
    Cache,
    Csv,
    Soap,
    Websocket,
    Nosql,
    Xpath,
    Expression,
    Prototype,
    Race,
    MassAssign,
    Oast,
    Saml,
    HtmlInject,
    CssInject,
    Ssi,
    DomClobber,
    Xslt,
    Viewstate,
    DepConfusion,
    XsLeak,
    Latex,
}

impl std::fmt::Display for PayloadType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PayloadType::Sqli => write!(f, "SQL Injection"),
            PayloadType::Xss => write!(f, "XSS"),
            PayloadType::Traversal => write!(f, "Path Traversal"),
            PayloadType::Ssrf => write!(f, "SSRF"),
            PayloadType::Redirect => write!(f, "Open Redirect"),
            PayloadType::Redos => write!(f, "ReDoS"),
            PayloadType::Headers => write!(f, "Header Expansion"),
            PayloadType::Compression => write!(f, "Compression Bomb"),
            PayloadType::GraphQL => write!(f, "GraphQL"),
            PayloadType::OAuth => write!(f, "OAuth/OIDC"),
            PayloadType::Jwt => write!(f, "JWT"),
            PayloadType::Idor => write!(f, "IDOR"),
            PayloadType::Ssti => write!(f, "SSTI"),
            PayloadType::Grpc => write!(f, "gRPC"),
            PayloadType::Xxe => write!(f, "XXE"),
            PayloadType::Ldap => write!(f, "LDAP Injection"),
            PayloadType::Cmd => write!(f, "Command Injection"),
            PayloadType::Deser => write!(f, "Deserialization"),
            PayloadType::Host => write!(f, "Host Header Injection"),
            PayloadType::Cache => write!(f, "Cache Poisoning"),
            PayloadType::Csv => write!(f, "CSV Injection"),
            PayloadType::Soap => write!(f, "SOAP/XML"),
            PayloadType::Websocket => write!(f, "WebSocket"),
            PayloadType::Nosql => write!(f, "NoSQL Injection"),
            PayloadType::Xpath => write!(f, "XPath Injection"),
            PayloadType::Expression => write!(f, "Expression Injection"),
            PayloadType::Prototype => write!(f, "Prototype Pollution"),
            PayloadType::Race => write!(f, "Race Condition"),
            PayloadType::MassAssign => write!(f, "Mass Assignment"),
            PayloadType::Oast => write!(f, "OAST"),
            PayloadType::Saml => write!(f, "SAML"),
            PayloadType::HtmlInject => write!(f, "HTML Injection"),
            PayloadType::CssInject => write!(f, "CSS Injection"),
            PayloadType::Ssi => write!(f, "SSI Injection"),
            PayloadType::DomClobber => write!(f, "DOM Clobbering"),
            PayloadType::Xslt => write!(f, "XSLT Injection"),
            PayloadType::Viewstate => write!(f, "ViewState Deserialization"),
            PayloadType::DepConfusion => write!(f, "Dependency Confusion"),
            PayloadType::XsLeak => write!(f, "XS-Leak"),
            PayloadType::Latex => write!(f, "LaTeX Injection"),
        }
    }
}

impl PayloadType {
    /// Whether the **engine** executes this type with a live-probe strategy.
    ///
    /// This says nothing about where the payload *data* lives — all 40 types,
    /// including these six, resolve through [`get_payloads`] in this crate.
    /// It selects an execution strategy in `eggsec::fuzzer::engine`, where the
    /// six are driven by their probers (`GraphQLFuzzer`, `JwtFuzzer`, …) rather
    /// than by the generic payload-batch runner.
    pub fn is_advanced(&self) -> bool {
        matches!(
            self,
            PayloadType::GraphQL
                | PayloadType::OAuth
                | PayloadType::Jwt
                | PayloadType::Idor
                | PayloadType::Ssti
                | PayloadType::Grpc
        )
    }

    pub fn all_variants() -> &'static [PayloadType] {
        static VARIANTS: LazyLock<Vec<PayloadType>> =
            LazyLock::new(|| PayloadType::iter().collect());
        &VARIANTS
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Payload {
    pub payload_type: PayloadType,
    pub payload: String,
    pub description: String,
    pub severity: Severity,
    pub tags: Vec<String>,
}

pub use eggsec_core::types::Severity;

/// Build the payloads for one [`PayloadType`].
///
/// Resolves **all 40 variants**. Every variant returns real payloads; none
/// panics and none returns an empty vector. The match is exhaustive over
/// [`PayloadType`], so adding a variant is a compile error here rather than a
/// silent gap.
pub fn get_payloads(payload_type: PayloadType) -> Vec<Payload> {
    match payload_type {
        PayloadType::Sqli => sqli::get_payloads(),
        PayloadType::Xss => xss::get_payloads(),
        PayloadType::Traversal => traversal::get_payloads(),
        PayloadType::Ssrf => ssrf::get_payloads(),
        PayloadType::Redirect => redirect::get_payloads(),
        PayloadType::Redos => redos::get_payloads(),
        PayloadType::Headers => headers::get_payloads(),
        PayloadType::Compression => compression::get_payloads(),
        PayloadType::GraphQL => graphql::get_payloads(),
        PayloadType::OAuth => oauth::get_payloads(),
        PayloadType::Jwt => jwt::get_payloads(),
        PayloadType::Idor => idor::get_payloads(),
        PayloadType::Ssti => ssti::get_payloads(),
        PayloadType::Grpc => grpc::get_payloads(),
        PayloadType::Xxe => xxe::get_payloads(),
        PayloadType::Ldap => ldap::get_payloads(),
        PayloadType::Cmd => cmd::get_payloads(),
        PayloadType::Deser => deser::get_payloads(),
        PayloadType::Host => host::get_payloads(),
        PayloadType::Cache => cache::get_payloads(),
        PayloadType::Csv => csv::get_payloads(),
        PayloadType::Soap => soap::get_payloads(),
        PayloadType::Websocket => websocket::get_payloads(),
        PayloadType::Nosql => nosql::get_payloads(),
        PayloadType::Xpath => xpath::get_payloads(),
        PayloadType::Expression => expression::get_payloads(),
        PayloadType::Prototype => prototype::get_payloads(),
        PayloadType::Race => race::get_payloads(),
        PayloadType::MassAssign => mass_assign::get_payloads(),
        PayloadType::Oast => oast::get_oast_payloads(),
        PayloadType::Saml => saml::get_payloads(),
        PayloadType::HtmlInject => html_inject::get_payloads(),
        PayloadType::CssInject => css_inject::get_payloads(),
        PayloadType::DomClobber => dom_clobber::get_payloads(),
        PayloadType::Ssi => ssi::get_payloads(),
        PayloadType::Xslt => xslt::get_payloads(),
        PayloadType::Viewstate => viewstate::get_payloads(),
        PayloadType::Latex => latex::get_payloads(),
        PayloadType::DepConfusion => dep_confusion::get_payloads(),
        PayloadType::XsLeak => xs_leak::get_payloads(),
    }
}

/// Cross-variant caches.
///
/// **Laziness is load-bearing.** These stay `LazyLock`: a process that never asks
/// for a payload never pays to build one. Materializing all 40 variants eagerly
/// at startup would regress every binary that links this crate, including the
/// TUI.
static PAYLOAD_CACHE: LazyLock<rustc_hash::FxHashMap<PayloadType, Vec<Payload>>> =
    LazyLock::new(|| {
        let mut map = rustc_hash::FxHashMap::default();
        for pt in PayloadType::all_variants() {
            map.insert(*pt, get_payloads(*pt));
        }
        map
    });

static ALL_PAYLOADS_CACHE: LazyLock<Vec<Payload>> =
    LazyLock::new(|| PAYLOAD_CACHE.values().flatten().cloned().collect());

/// Payloads for one type, built once and cached across the process.
///
/// A miss is impossible rather than merely unlikely: the cache is populated
/// from [`PayloadType::all_variants`], which is exhaustive over the enum, so
/// every key this function can be asked for is present. The `expect` documents
/// that invariant instead of degrading to the silent-empty `Vec` that a miss
/// used to return — an empty result would read as "this type has no payloads",
/// which is false.
pub fn get_payloads_cached(payload_type: PayloadType) -> &'static Vec<Payload> {
    PAYLOAD_CACHE
        .get(&payload_type)
        .expect("every PayloadType variant is inserted by all_variants()")
}

/// Every payload for every type, built once and cached across the process.
pub fn get_all_payloads_cached() -> &'static Vec<Payload> {
    &ALL_PAYLOADS_CACHE
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every variant must resolve to real, correctly-labelled payloads.
    ///
    /// This is the crate's shippability contract. An earlier cut of this crate
    /// left 6 variants (GraphQL, OAuth, Jwt, Idor, Ssti, Grpc) engine-owned, and
    /// `get_payloads` **panicked** for them. A panic is the worst possible
    /// failure for a library: it does not return an error the caller can
    /// handle, it unwinds through the caller's frame. This test turns that into
    /// a build-time failure instead.
    ///
    /// It also pins the two adjacent failure shapes: a silent empty `Vec`
    /// ("this type has no payloads", which is false) and a mislabelled payload
    /// (right strings under the wrong `payload_type`).
    #[test]
    fn every_variant_resolves_to_non_empty_correctly_labelled_payloads() {
        for pt in PayloadType::all_variants() {
            let payloads = get_payloads(*pt);
            assert!(
                !payloads.is_empty(),
                "{pt:?} resolved to no payloads; an empty set must never stand in for \
                 a type whose payloads simply live elsewhere"
            );
            for p in &payloads {
                assert_eq!(
                    p.payload_type, *pt,
                    "{pt:?} returned a payload labelled {:?}",
                    p.payload_type
                );
                assert!(
                    !p.payload.is_empty(),
                    "{pt:?} returned an empty payload string"
                );
                assert!(
                    !p.description.is_empty(),
                    "{pt:?} returned a payload with no description"
                );
                assert!(!p.tags.is_empty(), "{pt:?} returned a payload with no tags");
            }
        }
    }

    /// The cache must cover every variant and agree with a fresh build.
    ///
    /// `get_payloads_cached` used to degrade to a shared empty `Vec` on a miss.
    /// With all 40 variants owned here that path is unreachable, and an empty
    /// return would be indistinguishable from "no payloads" — so assert the
    /// total instead of trusting it.
    #[test]
    fn cached_lookup_covers_every_variant_and_matches_a_fresh_build() {
        let mut expected_total = 0usize;
        for pt in PayloadType::all_variants() {
            let cached = get_payloads_cached(*pt);
            let fresh = get_payloads(*pt);
            assert!(!cached.is_empty(), "cache for {pt:?} is empty");
            assert_eq!(
                cached.len(),
                fresh.len(),
                "cache for {pt:?} has a different length than a fresh build"
            );
            let cached_text: Vec<&str> = cached.iter().map(|p| p.payload.as_str()).collect();
            let fresh_text: Vec<&str> = fresh.iter().map(|p| p.payload.as_str()).collect();
            assert_eq!(
                cached_text, fresh_text,
                "cache for {pt:?} holds different payloads than a fresh build"
            );
            expected_total += cached.len();
        }
        assert_eq!(
            get_all_payloads_cached().len(),
            expected_total,
            "get_all_payloads_cached must be the union of all per-type caches"
        );
    }

    /// The six `is_advanced` types resolve here too.
    ///
    /// This is the regression test for the original defect, stated narrowly so a
    /// future refactor cannot reintroduce it behind a still-passing general
    /// test.
    #[test]
    fn advanced_types_resolve_too() {
        let advanced: Vec<&PayloadType> = PayloadType::all_variants()
            .iter()
            .filter(|p| p.is_advanced())
            .collect();
        assert_eq!(
            advanced.len(),
            6,
            "is_advanced must still cover exactly GraphQL, OAuth, Jwt, Idor, Ssti, Grpc"
        );
        for pt in advanced {
            assert!(
                !get_payloads(*pt).is_empty(),
                "{pt:?} is executed by a live prober, but its payload strings must still be \
                 owned and returned by this crate"
            );
        }
    }

    /// `all_variants` stays exhaustive over the enum.
    ///
    /// `strum`'s `EnumIter` is what makes the caches total. If a variant were
    /// ever added without the derive, this catches it instead of letting the
    /// cache quietly miss.
    #[test]
    fn all_variants_is_exhaustive() {
        assert_eq!(PayloadType::all_variants().len(), 40);
    }
}
