//! NSE output formatting module
//!
//! Provides various output format handlers compatible with nmap conventions.

use serde::{Deserialize, Serialize};
use std::fmt::Write as FmtWrite;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NseOutput {
    pub target: String,
    pub scripts: String,
    pub output: String,
    pub ports: Option<String>,
    pub timing: u8,
    pub debug: u8,
}

#[derive(Debug, Clone)]
pub enum OutputFormat {
    Stdout,
    Xml(String),
    Grepable(String),
    Normal(String),
    All,
}

/// Generate XML output in nmap format
pub fn generate_xml(results: &[NseOutput]) -> String {
    let mut xml = String::new();

    writeln!(xml, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>").unwrap();
    writeln!(
        xml,
        "<nmaprun scanner=\"slapper\" args=\"slapper nse\" start=\"{}\" version=\"1.0\">",
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs()
    )
    .unwrap();

    // Generate verbose output
    writeln!(xml, "  <verbose level=\"0\"/>").unwrap();
    writeln!(xml, "  <debugging level=\"0\"/>").unwrap();

    for result in results {
        writeln!(
            xml,
            "  <host starttime=\"{}\" endtime=\"{}\">",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs()
                + 1
        )
        .unwrap();

        writeln!(xml, "    <status state=\"up\" reason=\"echo-reply\"/>").unwrap();
        writeln!(
            xml,
            "    <address addr=\"{}\" addrtype=\"ipv4\"/>",
            result.target
        )
        .unwrap();

        writeln!(xml, "    <hostnames>").unwrap();
        writeln!(
            xml,
            "      <hostname name=\"{}\" type=\"user\"/>",
            result.target
        )
        .unwrap();
        writeln!(xml, "    </hostnames>").unwrap();

        writeln!(xml, "    <ports>").unwrap();
        writeln!(xml, "      <port protocol=\"tcp\" portid=\"80\">").unwrap();
        writeln!(xml, "        <state state=\"open\" reason=\"syn-ack\"/>").unwrap();
        writeln!(
            xml,
            "        <service name=\"http\" method=\"probed\" conf=\"10\"/>"
        )
        .unwrap();
        writeln!(
            xml,
            "        <script id=\"{}\" output=\"{}\">",
            escape_xml(&result.scripts),
            escape_xml(&result.output)
        )
        .unwrap();
        writeln!(xml, "        </script>").unwrap();
        writeln!(xml, "      </port>").unwrap();
        writeln!(xml, "    </ports>").unwrap();

        writeln!(xml, "    <times srtt=\"0\" rttvar=\"0\" to=\"100000\"/>").unwrap();
        writeln!(xml, "  </host>").unwrap();
    }

    writeln!(xml, "  <runstats>").unwrap();
    writeln!(xml, "    <finished elapsed=\"1\" exit=\"success\"/>").unwrap();
    writeln!(
        xml,
        "    <hosts up=\"{}\" down=\"0\" total=\"{}\"/>",
        results.len(),
        results.len()
    )
    .unwrap();
    writeln!(xml, "  </runstats>").unwrap();
    writeln!(xml, "</nmaprun>").unwrap();

    xml
}

/// Generate grepable output in nmap -oG format
pub fn generate_grepable(results: &[NseOutput]) -> String {
    let mut output = String::new();

    // Nmap grepable header
    writeln!(output, "# Nmap scan report generated by Slapper").unwrap();

    for result in results {
        // Host status line
        writeln!(output, "Host: {} () Status: Up", result.target).unwrap();
        writeln!(
            output,
            "Host: {} ()     Ports: 80/open/tcp//http///",
            result.target
        )
        .unwrap();

        // Script results
        let script_output = result.output.replace('\n', "\\n");
        writeln!(output, "| {}: {}", result.scripts, script_output).unwrap();
    }

    // Summary
    writeln!(
        output,
        "# Scan done: {} IP address (1 host up) scanned in 0.01 seconds",
        results.len()
    )
    .unwrap();

    output
}

/// Generate normal output in nmap format
pub fn generate_normal(results: &[NseOutput]) -> String {
    let mut output = String::new();

    writeln!(
        output,
        "Starting Slapper NSE scan at {}",
        chrono_lite_timestamp()
    )
    .unwrap();
    writeln!(
        output,
        "NSE Timing: About {}% done",
        (results.len() as f32 * 33.0).min(100.0)
    )
    .unwrap();
    writeln!(output).unwrap();

    for result in results {
        writeln!(output, "Nmap scan report for {}", result.target).unwrap();
        writeln!(output, "Host is up (0.0010s latency).").unwrap();
        writeln!(output, "PORT     STATE SERVICE").unwrap();
        write_ports(&mut output, result.ports.as_deref()).unwrap();

        writeln!(output, "| {}:", result.scripts).unwrap();
        for line in result.output.lines() {
            writeln!(output, "|   {}", line).unwrap();
        }

        writeln!(output).unwrap();
    }

    writeln!(
        output,
        "Nmap done: {} IP address ({} host up) scanned",
        results.len(),
        results.len()
    )
    .unwrap();

    output
}

fn write_ports(output: &mut String, ports: Option<&str>) -> std::fmt::Result {
    match ports {
        Some(ports) => {
            for raw in ports.lines().map(str::trim).filter(|line| !line.is_empty()) {
                if raw.contains('/') {
                    writeln!(output, "{}", raw)?;
                } else {
                    writeln!(output, "{}/tcp   open  unknown", raw)?;
                }
            }
        }
        None => {
            writeln!(output, "80/tcp   open  http")?;
        }
    }
    Ok(())
}

fn escape_xml(s: &str) -> String {
    let mut escaped = String::new();
    for c in s.chars() {
        match c {
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '&' => escaped.push_str("&amp;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&apos;"),
            _ => escaped.push(c),
        }
    }
    escaped
}

fn chrono_lite_timestamp() -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap();
    format!("{}", now.as_secs())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_xml_output() {
        let results = vec![NseOutput {
            target: "example.com".to_string(),
            scripts: "http-title".to_string(),
            output: "Example Domain".to_string(),
            ports: Some("80".to_string()),
            timing: 3,
            debug: 0,
        }];

        let xml = generate_xml(&results);
        assert!(xml.contains("<?xml"));
        assert!(xml.contains("example.com"));
    }

    #[test]
    fn test_grepable_output() {
        let results = vec![NseOutput {
            target: "example.com".to_string(),
            scripts: "http-title".to_string(),
            output: "Example Domain".to_string(),
            ports: Some("80".to_string()),
            timing: 3,
            debug: 0,
        }];

        let grepable = generate_grepable(&results);
        assert!(grepable.contains("example.com"));
    }

    #[test]
    fn test_normal_output() {
        let results = vec![NseOutput {
            target: "example.com".to_string(),
            scripts: "http-title".to_string(),
            output: "Example Domain".to_string(),
            ports: Some("80".to_string()),
            timing: 3,
            debug: 0,
        }];

        let normal = generate_normal(&results);
        assert!(normal.contains("example.com"));
    }

    #[test]
    fn test_normal_output_uses_ports_field() {
        let results = vec![NseOutput {
            target: "example.com".to_string(),
            scripts: "http-title".to_string(),
            output: "Example Domain".to_string(),
            ports: Some("443/tcp   open  https".to_string()),
            timing: 3,
            debug: 0,
        }];

        let normal = generate_normal(&results);
        assert!(normal.contains("443/tcp   open  https"));
        assert!(!normal.contains("80/tcp   open  http"));
    }
}
