# Feature-gated: AI post-processing
from typing import Any

class AiProviderPy:
    OpenAI: "AiProviderPy"
    Azure: "AiProviderPy"
    Anthropic: "AiProviderPy"
    OpenAICompatible: "AiProviderPy"
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class PluginLanguagePy:
    Python: "PluginLanguagePy"
    Ruby: "PluginLanguagePy"
    Rust: "PluginLanguagePy"
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class ScriptTargetPy:
    Nmap: "ScriptTargetPy"
    Burp: "ScriptTargetPy"
    Custom: "ScriptTargetPy"
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class AiAnalysisResultPy:
    @property
    def summary(self) -> str: ...

class AiPayloadSuggestionPy:
    @property
    def payload(self) -> str: ...

class AiWafBypassSuggestionPy:
    @property
    def technique(self) -> str: ...

class AiCacheStatsPy:
    @property
    def hits(self) -> int: ...
    @property
    def misses(self) -> int: ...

class ScriptMetadataPy:
    @property
    def name(self) -> str: ...

class GeneratedScriptPy:
    @property
    def source(self) -> str: ...

class AiCachePy:
    pass

def ai_analyze_finding(finding: Any, provider: AiProviderPy = ...) -> AiAnalysisResultPy: ...
async def async_ai_analyze_finding(finding: Any, provider: AiProviderPy = ...) -> AiAnalysisResultPy: ...
def ai_generate_payloads(context: Any, provider: AiProviderPy = ...) -> list[AiPayloadSuggestionPy]: ...
def ai_suggest_waf_bypass(waf_info: Any, provider: AiProviderPy = ...) -> list[AiWafBypassSuggestionPy]: ...
def ai_generate_script(metadata: ScriptMetadataPy, language: PluginLanguagePy = ..., target: ScriptTargetPy = ...) -> GeneratedScriptPy: ...
