from typing import Any, Dict, List, Optional

class Artifact:
    def __init__(self, id: str, name: str, mime_type: str, size_bytes: int, content_hash: str, *, provenance: Optional[str] = None, redacted: bool = False, retention_policy: Optional[str] = None, external_uri: Optional[str] = None) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def mime_type(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def content_hash(self) -> str: ...
    @property
    def provenance(self) -> str: ...
    @property
    def redacted(self) -> bool: ...
    @property
    def retention_policy(self) -> str: ...
    @property
    def external_uri(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ArtifactReference:
    def __init__(self, artifact_id: str, finding_id: str, role: str) -> None: ...
    @property
    def artifact_id(self) -> str: ...
    @property
    def finding_id(self) -> str: ...
    @property
    def role(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ArtifactStore:
    def __init__(self) -> None: ...
    def store(self, artifact: Artifact) -> str: ...
    def get(self, artifact_id: str) -> Optional[Artifact]: ...
    def contains(self, artifact_id: str) -> bool: ...
    def remove(self, artifact_id: str) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def list_ids(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
