from typing import Any, Optional
from .scope import Scope
from .runtime import PyFuture
from .planning import ScanPlan
from .requests import (
    OperationRequest,
    PortScanRequest,
    EndpointScanRequest,
    FingerprintRequest,
    ReconDnsRequest,
    TlsInspectRequest,
    TechDetectRequest,
    WafDetectRequest,
    LoadTestRequest,
    WafValidateRequest,
    FuzzRequest,
)

class AsyncEngine:
    def __init__(
        self,
        scope: Scope,
        *,
        mode: str = "manual",
        concurrency: int = 100,
        timeout_ms: int = 5000,
    ) -> None: ...
    def run(self, request: OperationRequest) -> PyFuture: ...
    def list_operations(self) -> list[str]: ...
    def has_operation(self, operation_id: str) -> bool: ...
    def audit_events(self) -> list[Any]: ...
    def run_port_scan(self, request: PortScanRequest) -> PyFuture: ...
    def run_endpoint_scan(self, request: EndpointScanRequest) -> PyFuture: ...
    def run_fingerprint(self, request: FingerprintRequest) -> PyFuture: ...
    def run_recon_dns(self, request: ReconDnsRequest) -> PyFuture: ...
    def run_tls_inspect(self, request: TlsInspectRequest) -> PyFuture: ...
    def run_tech_detect(self, request: TechDetectRequest) -> PyFuture: ...
    def run_waf_detect(self, request: WafDetectRequest) -> PyFuture: ...
    def run_load_test(self, request: LoadTestRequest) -> PyFuture: ...
    def run_waf_validate(self, request: WafValidateRequest) -> PyFuture: ...
    def run_fuzz(self, request: FuzzRequest) -> PyFuture: ...
    def plan(self, target: str) -> PyFuture: ...
    @property
    def scope(self) -> Scope: ...
    @property
    def mode(self) -> str: ...
    @property
    def concurrency(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    def close(self) -> None: ...
    async def __aenter__(self) -> AsyncEngine: ...
    async def __aexit__(self, *args: object) -> None: ...
    def __repr__(self) -> str: ...
