from typing import Optional
from .scope import Scope
from . import dto, endpoint, fingerprint, recon, waf
from .runtime import PyFuture

class AsyncClient:
    def __init__(self, scope: Scope, *, mode: str = "manual", concurrency: int = 100, timeout_ms: int = 5000) -> None: ...
    @property
    def scope(self) -> Scope: ...
    @property
    def mode(self) -> str: ...
    def scan_ports(self, target: str, ports: list[int], *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> PyFuture: ...
    def scan_endpoints(self, base_url: str, endpoints: list[str], *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None, include_404: bool = False, verify_tls: bool = True) -> PyFuture: ...
    def fingerprint_services(self, target: str, ports: list[int], *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> PyFuture: ...
    def recon_dns(self, domain: str) -> PyFuture: ...
    def inspect_tls(self, host: str, *, port: int = 443) -> PyFuture: ...
    def detect_technology(self, url: str) -> PyFuture: ...
    def detect_waf(self, url: str) -> PyFuture: ...
    async def __aenter__(self) -> AsyncClient: ...
    async def __aexit__(self, *args: object) -> None: ...
