from types import TracebackType
from typing import Any, Callable, Optional, Self

class AsyncCallback:
    def __init__(self, callback: Callable[..., Any]) -> None: ...
    def invoke(self, event: Any) -> Any: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Optional[type[BaseException]] = None, exc_value: Optional[BaseException] = None, traceback: Optional[TracebackType] = None) -> bool: ...

class CallbackScheduler:
    def __init__(self, capacity: int = 1000) -> None: ...
    def enqueue(self, event: Any) -> bool: ...
    def drain(self) -> list[Any]: ...
    def pending(self) -> int: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def capacity(self) -> int: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Optional[type[BaseException]] = None, exc_value: Optional[BaseException] = None, traceback: Optional[TracebackType] = None) -> bool: ...
