from __future__ import annotations
from typing import AsyncIterator, Any

class EventStreamAsyncIterator:
    def __init__(self, events: list[dict]) -> None: ...
    def __aiter__(self) -> EventStreamAsyncIterator: ...
    async def __anext__(self) -> dict[str, Any] | None: ...

class FindingStreamAsyncIterator:
    def __init__(self, findings: list[Any]) -> None: ...
    def __aiter__(self) -> FindingStreamAsyncIterator: ...
    async def __anext__(self) -> Any | None: ...
