class AuditOutcomePy:
    allow: AuditOutcomePy
    warn: AuditOutcomePy
    confirmed: AuditOutcomePy
    deny: AuditOutcomePy
    confirmation_required: AuditOutcomePy
    @property
    def name(self) -> str: ...
    def to_dict(self) -> dict[str, str]: ...

class ManualOverrideAuditPy:
    @property
    def reason(self) -> str | None: ...
    @property
    def classes(self) -> list[str]: ...
    def to_dict(self) -> dict[str, object]: ...

class ScopeAuditPy:
    @property
    def source(self) -> str: ...
    @property
    def path(self) -> str | None: ...
    @property
    def allow_rule_count(self) -> int: ...
    @property
    def exclusion_rule_count(self) -> int: ...
    @property
    def explicit_manifest(self) -> bool: ...
    def to_dict(self) -> dict[str, object]: ...

class EnforcementAuditEventPy:
    @property
    def event_id(self) -> str: ...
    @property
    def timestamp(self) -> str: ...
    @property
    def surface(self) -> str: ...
    @property
    def profile(self) -> str: ...
    @property
    def operation_id(self) -> str: ...
    @property
    def target(self) -> str | None: ...
    @property
    def outcome(self) -> AuditOutcomePy: ...
    @property
    def decision_summary(self) -> str: ...
    @property
    def confirmation_classes(self) -> list[str]: ...
    @property
    def manual_override(self) -> ManualOverrideAuditPy | None: ...
    @property
    def scope(self) -> ScopeAuditPy: ...
    @property
    def policy_hash(self) -> str: ...
    @property
    def correlation_id(self) -> str | None: ...
    @property
    def manual_override_ignored(self) -> bool: ...
    @property
    def decision_id(self) -> str: ...
    @property
    def metadata_id(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

def audit_event_from_enforcement(surface: str, operation_id: str, target: str | None, allowed: bool, denied: bool, confirmed: bool, override_ignored: bool, decision_summary: str, confirmation_classes: list[str], manual_override_reason: str | None, scope_source: str, scope_path: str | None, allow_rule_count: int, exclusion_rule_count: int, explicit_manifest: bool, policy_hash: str, correlation_id: str | None = None) -> EnforcementAuditEventPy: ...
def audit_event_from_preflight(surface: str, operation_id: str, target: str | None, allowed: bool, denied: bool, decision_summary: str, confirmation_classes: list[str], scope_source: str, scope_path: str | None, allow_rule_count: int, exclusion_rule_count: int, explicit_manifest: bool, policy_hash: str, correlation_id: str | None = None) -> EnforcementAuditEventPy: ...
def emit_audit_event(event: EnforcementAuditEventPy) -> None: ...
