class ExecutionPolicyPy:
    @staticmethod
    def default() -> ExecutionPolicyPy: ...
    @staticmethod
    def from_config(config: object) -> ExecutionPolicyPy: ...
    @property
    def allow_passive(self) -> bool: ...
    @property
    def allow_read_only(self) -> bool: ...
    @property
    def allow_low_risk(self) -> bool: ...
    @property
    def allow_medium_risk(self) -> bool: ...
    @property
    def allow_elevated_risk(self) -> bool: ...
    @property
    def allow_high_risk(self) -> bool: ...
    @property
    def allow_destructive(self) -> bool: ...
    @property
    def allow_intrusive(self) -> bool: ...
    @property
    def allow_credential_access(self) -> bool: ...
    @property
    def allow_network_intrusion(self) -> bool: ...
    @property
    def allow_denial_of_service(self) -> bool: ...
    @property
    def allow_data_exfiltration(self) -> bool: ...
    @property
    def allow_privilege_escalation(self) -> bool: ...
    @property
    def allow_persistence(self) -> bool: ...
    @property
    def allow_agent_autonomous(self) -> bool: ...
    @property
    def require_confirmation_above_medium(self) -> bool: ...
    @property
    def require_confirmation_above_high(self) -> bool: ...
    @property
    def max_risk_without_confirm(self) -> str | None: ...
    @property
    def allowed_capabilities(self) -> list[str]: ...
    @property
    def denied_capabilities(self) -> list[str]: ...
    def validate(self) -> list[str]: ...

class ManualOverridePy:
    def __init__(self, *, reason: str = "", assume_yes: bool = False, allow_out_of_scope: bool = False, allow_explicit_exclusion: bool = False, allow_high_risk: bool = False, allow_intrusive: bool = False, allow_credential_access: bool = False, allow_network_intrusion: bool = False, allow_denial_of_service: bool = False, allow_data_exfiltration: bool = False) -> None: ...
    @property
    def reason(self) -> str: ...
    @property
    def assume_yes(self) -> bool: ...
    @property
    def allow_out_of_scope(self) -> bool: ...
    @property
    def allow_explicit_exclusion(self) -> bool: ...
    @property
    def allow_high_risk(self) -> bool: ...
    @property
    def allow_intrusive(self) -> bool: ...
    @property
    def allow_credential_access(self) -> bool: ...
    @property
    def allow_network_intrusion(self) -> bool: ...
    @property
    def allow_denial_of_service(self) -> bool: ...
    @property
    def allow_data_exfiltration(self) -> bool: ...
    def permits(self, class_name: str) -> bool: ...
