from typing import Any, Dict, Optional

class EventDeliveryStats:
    emitted_count: int
    delivered_count: int
    dropped_count: int
    dropped_by_kind: Dict[str, int]
    max_queue_depth: int
    consumer_lag: int
    terminal_event_delivery_failures: int
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class BackpressureChannel:
    def __init__(self, capacity: int = 256) -> None: ...
    def send(self, event: Any) -> None: ...
    def try_recv(self) -> Optional[Any]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def total_dropped(self) -> int: ...
    def stats(self) -> EventDeliveryStats: ...
    @property
    def capacity(self) -> int: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
