from typing import Any, Optional

class BackpressureChannel:
    def __init__(self, capacity: int = 256) -> None: ...
    def send(self, event: Any) -> None: ...
    def try_recv(self) -> Optional[Any]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def total_dropped(self) -> int: ...
    @property
    def capacity(self) -> int: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
