from typing import Any, Dict, List, Optional
from .finding_schema import VersionedFinding

class FindingCorrelation:
    def __init__(self, baseline_finding_id: str, current_finding_id: str, correlation_method: str, confidence: float, changed_fields: List[str]) -> None: ...
    @property
    def baseline_finding_id(self) -> str: ...
    @property
    def current_finding_id(self) -> str: ...
    @property
    def correlation_method(self) -> str: ...
    @property
    def confidence(self) -> float: ...
    @property
    def changed_fields(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class FindingDiff:
    New: FindingDiff
    Resolved: FindingDiff
    Changed: FindingDiff
    Unchanged: FindingDiff
    Suppressed: FindingDiff
    Indeterminate: FindingDiff
    def as_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class AssessmentDiff:
    @property
    def baseline_id(self) -> str: ...
    @property
    def current_id(self) -> str: ...
    @property
    def compared_at(self) -> str: ...
    @property
    def new_findings(self) -> int: ...
    @property
    def resolved_findings(self) -> int: ...
    @property
    def changed_findings(self) -> int: ...
    @property
    def unchanged_findings(self) -> int: ...
    @property
    def suppressed_findings(self) -> int: ...
    @property
    def is_regression(self) -> bool: ...
    @property
    def is_improvement(self) -> bool: ...
    @property
    def summary(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class BaselineComparator:
    def __init__(self) -> None: ...
    def compare(self, baseline: List[VersionedFinding], current: List[VersionedFinding]) -> AssessmentDiff: ...
    def correlate(self, baseline: List[VersionedFinding], current: List[VersionedFinding]) -> List[FindingCorrelation]: ...
    def add_correlation_rule(self, rule: str) -> None: ...
    def correlation_rules(self) -> List[str]: ...
