from typing import Any, Dict, List, Optional, Tuple

from .artifact import ArtifactReference

class BrowserCapabilities:
    def __init__(
        self,
        *,
        engine: str = "",
        version: Optional[str] = None,
        supports_javascript: bool = False,
        supports_dom: bool = False,
        supports_network_intercept: bool = False,
        supports_console_capture: bool = False,
        supports_screenshot: bool = False,
        supports_pdf_export: bool = False,
        supports_cookie_access: bool = False,
        supports_storage_access: bool = False,
        supports_route_discovery: bool = False,
        supports_proxy: bool = False,
    ) -> None: ...
    @property
    def engine(self) -> str: ...
    @property
    def version(self) -> Optional[str]: ...
    @property
    def supports_javascript(self) -> bool: ...
    @property
    def supports_dom(self) -> bool: ...
    @property
    def supports_network_intercept(self) -> bool: ...
    @property
    def supports_console_capture(self) -> bool: ...
    @property
    def supports_screenshot(self) -> bool: ...
    @property
    def supports_pdf_export(self) -> bool: ...
    @property
    def supports_cookie_access(self) -> bool: ...
    @property
    def supports_storage_access(self) -> bool: ...
    @property
    def supports_route_discovery(self) -> bool: ...
    @property
    def supports_proxy(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class BrowserSessionState:
    Created: "BrowserSessionState"
    Discovering: "BrowserSessionState"
    Launching: "BrowserSessionState"
    Ready: "BrowserSessionState"
    Navigating: "BrowserSessionState"
    Loading: "BrowserSessionState"
    Inspecting: "BrowserSessionState"
    Stopping: "BrowserSessionState"
    Cleaning: "BrowserSessionState"
    Stopped: "BrowserSessionState"
    Failed: "BrowserSessionState"
    Cancelled: "BrowserSessionState"
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserSessionConfig:
    def __init__(
        self,
        *,
        target_url: Optional[str] = None,
        headless: bool = True,
        proxy: Optional[str] = None,
        user_agent: Optional[str] = None,
        viewport_width: int = 1280,
        viewport_height: int = 720,
        timeout_ms: int = 30000,
        navigation_timeout_ms: int = 60000,
        collect_console: bool = True,
        collect_network: bool = True,
        collect_cookies: bool = True,
        collect_storage: bool = True,
        screenshot_on_complete: bool = False,
        extra_headers: Optional[List[str]] = None,
        ignore_cert_errors: bool = False,
    ) -> None: ...
    @property
    def target_url(self) -> Optional[str]: ...
    @property
    def headless(self) -> bool: ...
    @property
    def proxy(self) -> Optional[str]: ...
    @property
    def user_agent(self) -> Optional[str]: ...
    @property
    def viewport_width(self) -> int: ...
    @property
    def viewport_height(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def navigation_timeout_ms(self) -> int: ...
    @property
    def collect_console(self) -> bool: ...
    @property
    def collect_network(self) -> bool: ...
    @property
    def collect_cookies(self) -> bool: ...
    @property
    def collect_storage(self) -> bool: ...
    @property
    def screenshot_on_complete(self) -> bool: ...
    @property
    def extra_headers(self) -> List[str]: ...
    @property
    def ignore_cert_errors(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class BrowserSessionStats:
    def __init__(
        self,
        *,
        pages_navigated: int = 0,
        dom_snapshots: int = 0,
        console_events: int = 0,
        network_requests: int = 0,
        cookies_collected: int = 0,
        screenshots_taken: int = 0,
        artifacts_collected: int = 0,
        duration_ms: int = 0,
    ) -> None: ...
    @property
    def pages_navigated(self) -> int: ...
    @property
    def dom_snapshots(self) -> int: ...
    @property
    def console_events(self) -> int: ...
    @property
    def network_requests(self) -> int: ...
    @property
    def cookies_collected(self) -> int: ...
    @property
    def screenshots_taken(self) -> int: ...
    @property
    def artifacts_collected(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class BrowserNavigationEvent:
    def __init__(
        self,
        url: str,
        final_url: str,
        status_code: int,
        *,
        redirect_chain: Optional[List[str]] = None,
        load_time_ms: int = 0,
        timestamp_ms: int = 0,
    ) -> None: ...
    @property
    def url(self) -> str: ...
    @property
    def final_url(self) -> str: ...
    @property
    def status_code(self) -> int: ...
    @property
    def redirect_chain(self) -> List[str]: ...
    @property
    def load_time_ms(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class BrowserConsoleEvent:
    def __init__(
        self,
        level: str,
        message: str,
        *,
        source: Optional[str] = None,
        line_number: Optional[int] = None,
        timestamp_ms: int = 0,
    ) -> None: ...
    @property
    def level(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def source(self) -> Optional[str]: ...
    @property
    def line_number(self) -> Optional[int]: ...
    @property
    def timestamp_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class BrowserNetworkEvent:
    def __init__(
        self,
        method: str,
        url: str,
        *,
        status_code: Optional[int] = None,
        request_headers: Optional[List[Tuple[str, str]]] = None,
        response_headers: Optional[List[Tuple[str, str]]] = None,
        content_type: Optional[str] = None,
        size_bytes: Optional[int] = None,
        duration_ms: int = 0,
        timestamp_ms: int = 0,
    ) -> None: ...
    @property
    def method(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def status_code(self) -> Optional[int]: ...
    @property
    def request_headers(self) -> List[Tuple[str, str]]: ...
    @property
    def response_headers(self) -> List[Tuple[str, str]]: ...
    @property
    def content_type(self) -> Optional[str]: ...
    @property
    def size_bytes(self) -> Optional[int]: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class BrowserFormField:
    def __init__(
        self,
        name: str,
        field_type: str,
        *,
        value: Optional[str] = None,
        required: bool = False,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def field_type(self) -> str: ...
    @property
    def value(self) -> Optional[str]: ...
    @property
    def required(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class BrowserFormInfo:
    def __init__(
        self,
        action: str,
        method: str,
        *,
        fields: Optional[List[BrowserFormField]] = None,
    ) -> None: ...
    @property
    def action(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def fields(self) -> List[BrowserFormField]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class BrowserLinkInfo:
    def __init__(
        self,
        href: str,
        text: str,
        *,
        rel: Optional[str] = None,
    ) -> None: ...
    @property
    def href(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def rel(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class BrowserDomSnapshot:
    def __init__(
        self,
        url: str,
        *,
        title: Optional[str] = None,
        forms: Optional[List[BrowserFormInfo]] = None,
        links: Optional[List[BrowserLinkInfo]] = None,
        scripts: Optional[List[str]] = None,
        frames: Optional[List[str]] = None,
        timestamp_ms: int = 0,
    ) -> None: ...
    @property
    def url(self) -> str: ...
    @property
    def title(self) -> Optional[str]: ...
    @property
    def forms(self) -> List[BrowserFormInfo]: ...
    @property
    def links(self) -> List[BrowserLinkInfo]: ...
    @property
    def scripts(self) -> List[str]: ...
    @property
    def frames(self) -> List[str]: ...
    @property
    def timestamp_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class BrowserCookieInfo:
    def __init__(
        self,
        name: str,
        value: str,
        domain: str,
        path: str,
        *,
        expires: Optional[int] = None,
        http_only: bool = False,
        secure: bool = False,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def domain(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def expires(self) -> Optional[int]: ...
    @property
    def http_only(self) -> bool: ...
    @property
    def secure(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class BrowserStorageInfo:
    def __init__(
        self,
        *,
        local_storage: Optional[List[Tuple[str, str]]] = None,
        session_storage: Optional[List[Tuple[str, str]]] = None,
        cookies: Optional[List[BrowserCookieInfo]] = None,
    ) -> None: ...
    @property
    def local_storage(self) -> List[Tuple[str, str]]: ...
    @property
    def session_storage(self) -> List[Tuple[str, str]]: ...
    @property
    def cookies(self) -> List[BrowserCookieInfo]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class BrowserSession:
    def __init__(self, config: BrowserSessionConfig) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def config(self) -> BrowserSessionConfig: ...
    @property
    def state(self) -> BrowserSessionState: ...
    @property
    def stats(self) -> BrowserSessionStats: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def navigate(self, url: str) -> BrowserNavigationEvent: ...
    def wait_for_selector(self, selector: str, timeout_ms: Optional[int] = None) -> bool: ...
    def get_dom_snapshot(self) -> BrowserDomSnapshot: ...
    def get_console_events(self) -> List[BrowserConsoleEvent]: ...
    def get_network_events(self) -> List[BrowserNetworkEvent]: ...
    def get_cookies(self) -> BrowserStorageInfo: ...
    def take_screenshot(self) -> ArtifactReference: ...
    def execute_script(self, script: str, timeout_ms: Optional[int] = None) -> str: ...
    def __enter__(self) -> BrowserSession: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class AsyncBrowserSession:
    def __init__(self, config: BrowserSessionConfig) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def config(self) -> BrowserSessionConfig: ...
    @property
    def state(self) -> BrowserSessionState: ...
    @property
    def stats(self) -> BrowserSessionStats: ...
    def async_start(self) -> Any: ...
    def async_stop(self) -> Any: ...
    def async_navigate(self, url: str) -> Any: ...
    def async_wait_for_selector(self, selector: str, timeout_ms: Optional[int] = None) -> Any: ...
    def async_get_dom_snapshot(self) -> Any: ...
    def async_get_console_events(self) -> Any: ...
    def async_get_network_events(self) -> Any: ...
    def async_get_cookies(self) -> Any: ...
    def async_take_screenshot(self) -> Any: ...
    def async_execute_script(self, script: str, timeout_ms: Optional[int] = None) -> Any: ...
    def __aenter__(self) -> AsyncBrowserSession: ...
    def __aexit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
