from typing import Any, Dict, List, Optional

class BrowserDomEvent:
    def __init__(
        self,
        event_id: str,
        session_id: str,
        event_type: str,
        sequence: int,
        timestamp_ms: int,
        url: str,
        *,
        selector: Optional[str] = None,
        attribute_name: Optional[str] = None,
        old_value: Optional[str] = None,
        new_value: Optional[str] = None,
        element_tag: Optional[str] = None,
    ) -> None: ...
    @property
    def event_id(self) -> str: ...
    @property
    def session_id(self) -> str: ...
    @property
    def event_type(self) -> str: ...
    @property
    def sequence(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def url(self) -> str: ...
    @property
    def selector(self) -> Optional[str]: ...
    @property
    def attribute_name(self) -> Optional[str]: ...
    @property
    def old_value(self) -> Optional[str]: ...
    @property
    def new_value(self) -> Optional[str]: ...
    @property
    def element_tag(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class BrowserDownloadEvent:
    def __init__(
        self,
        event_id: str,
        session_id: str,
        sequence: int,
        timestamp_ms: int,
        url: str,
        *,
        suggested_filename: Optional[str] = None,
        content_type: Optional[str] = None,
        size_bytes: Optional[int] = None,
        download_path: Optional[str] = None,
        status: Optional[str] = None,
    ) -> None: ...
    @property
    def event_id(self) -> str: ...
    @property
    def session_id(self) -> str: ...
    @property
    def sequence(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def url(self) -> str: ...
    @property
    def suggested_filename(self) -> Optional[str]: ...
    @property
    def content_type(self) -> Optional[str]: ...
    @property
    def size_bytes(self) -> Optional[int]: ...
    @property
    def download_path(self) -> Optional[str]: ...
    @property
    def status(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class BrowserSecurityObservation:
    def __init__(
        self,
        observation_id: str,
        session_id: str,
        sequence: int,
        timestamp_ms: int,
        observation_type: str,
        url: str,
        severity: str,
        description: str,
        *,
        header_name: Optional[str] = None,
        header_value: Optional[str] = None,
        tls_version: Optional[str] = None,
        certificate_info: Optional[str] = None,
    ) -> None: ...
    @property
    def observation_id(self) -> str: ...
    @property
    def session_id(self) -> str: ...
    @property
    def sequence(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def observation_type(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def header_name(self) -> Optional[str]: ...
    @property
    def header_value(self) -> Optional[str]: ...
    @property
    def severity(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def tls_version(self) -> Optional[str]: ...
    @property
    def certificate_info(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
