from typing import Any, Dict, List, Optional, Tuple

class BrowserCapabilities:
    def __init__(
        self,
        *,
        headless: bool = True,
        screenshot: bool = True,
        pdf_export: bool = True,
        network_intercept: bool = False,
        console_capture: bool = True,
        cookie_access: bool = True,
        local_storage_access: bool = True,
        dom_snapshot: bool = True,
        form_interaction: bool = True,
        javascript_execution: bool = True,
    ) -> None: ...
    @property
    def headless(self) -> bool: ...
    @property
    def screenshot(self) -> bool: ...
    @property
    def pdf_export(self) -> bool: ...
    @property
    def network_intercept(self) -> bool: ...
    @property
    def console_capture(self) -> bool: ...
    @property
    def cookie_access(self) -> bool: ...
    @property
    def local_storage_access(self) -> bool: ...
    @property
    def dom_snapshot(self) -> bool: ...
    @property
    def form_interaction(self) -> bool: ...
    @property
    def javascript_execution(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserSessionState:
    Idle: "BrowserSessionState"
    Navigating: "BrowserSessionState"
    Loading: "BrowserSessionState"
    Ready: "BrowserSessionState"
    Evaluating: "BrowserSessionState"
    Closed: "BrowserSessionState"
    Error: "BrowserSessionState"
    @property
    def value(self) -> str: ...
    def from_str(s: str) -> BrowserSessionState: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserSessionConfig:
    def __init__(
        self,
        *,
        target_url: Optional[str] = None,
        headless: bool = True,
        viewport_width: int = 1280,
        viewport_height: int = 720,
        user_agent: Optional[str] = None,
        timeout_ms: int = 30000,
        ignore_https_errors: bool = False,
        extra_headers: Optional[Dict[str, str]] = None,
        proxy: Optional[str] = None,
        java_script_enabled: bool = True,
    ) -> None: ...
    @property
    def target_url(self) -> Optional[str]: ...
    @property
    def headless(self) -> bool: ...
    @property
    def viewport_width(self) -> int: ...
    @property
    def viewport_height(self) -> int: ...
    @property
    def user_agent(self) -> Optional[str]: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def ignore_https_errors(self) -> bool: ...
    @property
    def extra_headers(self) -> Dict[str, str]: ...
    @property
    def proxy(self) -> Optional[str]: ...
    @property
    def java_script_enabled(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserSessionStats:
    def __init__(
        self,
        *,
        pages_navigated: int = 0,
        js_evaluations: int = 0,
        screenshots_taken: int = 0,
        console_messages_captured: int = 0,
        network_requests_observed: int = 0,
        forms_discovered: int = 0,
        cookies_accessed: int = 0,
        duration_ms: int = 0,
    ) -> None: ...
    @property
    def pages_navigated(self) -> int: ...
    @property
    def js_evaluations(self) -> int: ...
    @property
    def screenshots_taken(self) -> int: ...
    @property
    def console_messages_captured(self) -> int: ...
    @property
    def network_requests_observed(self) -> int: ...
    @property
    def forms_discovered(self) -> int: ...
    @property
    def cookies_accessed(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserNavigationEvent:
    def __init__(
        self,
        url: str,
        status: str,
        *,
        navigation_type: str = "navigate",
        duration_ms: Optional[float] = None,
        referrer: Optional[str] = None,
    ) -> None: ...
    @property
    def url(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def navigation_type(self) -> str: ...
    @property
    def duration_ms(self) -> Optional[float]: ...
    @property
    def referrer(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserConsoleEvent:
    def __init__(
        self,
        level: str,
        message: str,
        *,
        source_url: Optional[str] = None,
        line_number: Optional[int] = None,
        timestamp_ms: Optional[int] = None,
    ) -> None: ...
    @property
    def level(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def source_url(self) -> Optional[str]: ...
    @property
    def line_number(self) -> Optional[int]: ...
    @property
    def timestamp_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserNetworkEvent:
    def __init__(
        self,
        request_url: str,
        method: str,
        *,
        status_code: Optional[int] = None,
        resource_type: Optional[str] = None,
        duration_ms: Optional[float] = None,
        request_headers: Optional[Dict[str, str]] = None,
        response_headers: Optional[Dict[str, str]] = None,
    ) -> None: ...
    @property
    def request_url(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def status_code(self) -> Optional[int]: ...
    @property
    def resource_type(self) -> Optional[str]: ...
    @property
    def duration_ms(self) -> Optional[float]: ...
    @property
    def request_headers(self) -> Dict[str, str]: ...
    @property
    def response_headers(self) -> Dict[str, str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserDomSnapshot:
    def __init__(
        self,
        url: str,
        title: str,
        *,
        html: Optional[str] = None,
        text_content: Optional[str] = None,
        element_count: int = 0,
        link_count: int = 0,
        form_count: int = 0,
        script_count: int = 0,
    ) -> None: ...
    @property
    def url(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def html(self) -> Optional[str]: ...
    @property
    def text_content(self) -> Optional[str]: ...
    @property
    def element_count(self) -> int: ...
    @property
    def link_count(self) -> int: ...
    @property
    def form_count(self) -> int: ...
    @property
    def script_count(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserFormInfo:
    def __init__(
        self,
        action: str,
        method: str,
        *,
        form_id: Optional[str] = None,
        form_name: Optional[str] = None,
        fields: Optional[List["BrowserFormField"]] = None,
        enctype: Optional[str] = None,
    ) -> None: ...
    @property
    def action(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def form_id(self) -> Optional[str]: ...
    @property
    def form_name(self) -> Optional[str]: ...
    @property
    def fields(self) -> List["BrowserFormField"]: ...
    @property
    def enctype(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserFormField:
    def __init__(
        self,
        name: str,
        field_type: str,
        *,
        value: Optional[str] = None,
        required: bool = False,
        placeholder: Optional[str] = None,
        maxlength: Optional[int] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def field_type(self) -> str: ...
    @property
    def value(self) -> Optional[str]: ...
    @property
    def required(self) -> bool: ...
    @property
    def placeholder(self) -> Optional[str]: ...
    @property
    def maxlength(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserLinkInfo:
    def __init__(
        self,
        href: str,
        text: str,
        *,
        rel: Optional[str] = None,
        target: Optional[str] = None,
        is_external: bool = False,
    ) -> None: ...
    @property
    def href(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def rel(self) -> Optional[str]: ...
    @property
    def target(self) -> Optional[str]: ...
    @property
    def is_external(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserStorageInfo:
    def __init__(
        self,
        *,
        local_storage: Optional[Dict[str, str]] = None,
        session_storage: Optional[Dict[str, str]] = None,
        cookies: Optional[List["BrowserCookieInfo"]] = None,
        indexed_db_keys: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def local_storage(self) -> Dict[str, str]: ...
    @property
    def session_storage(self) -> Dict[str, str]: ...
    @property
    def cookies(self) -> List["BrowserCookieInfo"]: ...
    @property
    def indexed_db_keys(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserCookieInfo:
    def __init__(
        self,
        name: str,
        value: str,
        *,
        domain: Optional[str] = None,
        path: Optional[str] = None,
        expires: Optional[str] = None,
        http_only: bool = False,
        secure: bool = False,
        same_site: Optional[str] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def domain(self) -> Optional[str]: ...
    @property
    def path(self) -> Optional[str]: ...
    @property
    def expires(self) -> Optional[str]: ...
    @property
    def http_only(self) -> bool: ...
    @property
    def secure(self) -> bool: ...
    @property
    def same_site(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BrowserSession:
    def __init__(self, config: BrowserSessionConfig) -> None: ...
    @property
    def config(self) -> BrowserSessionConfig: ...
    @property
    def state(self) -> BrowserSessionState: ...
    @property
    def session_id(self) -> str: ...
    @property
    def stats(self) -> BrowserSessionStats: ...
    def start(self) -> BrowserCapabilities: ...
    def navigate(self, url: str) -> BrowserNavigationEvent: ...
    def current_url(self) -> str: ...
    def screenshot(self, *, full_page: bool = False) -> bytes: ...
    def pdf(self) -> bytes: ...
    def evaluate(self, script: str) -> Any: ...
    def snapshot(self) -> BrowserDomSnapshot: ...
    def forms(self) -> List[BrowserFormInfo]: ...
    def links(self) -> List[BrowserLinkInfo]: ...
    def storage(self) -> BrowserStorageInfo: ...
    def set_cookie(self, cookie: BrowserCookieInfo) -> None: ...
    def clear_cookies(self) -> None: ...
    def console_events(self) -> List[BrowserConsoleEvent]: ...
    def network_events(self) -> List[BrowserNetworkEvent]: ...
    def close(self) -> None: ...
    def __enter__(self) -> BrowserSession: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class AsyncBrowserSession:
    def __init__(self, config: BrowserSessionConfig) -> None: ...
    @property
    def config(self) -> BrowserSessionConfig: ...
    @property
    def state(self) -> BrowserSessionState: ...
    @property
    def session_id(self) -> str: ...
    def async_start(self) -> Any: ...
    def async_navigate(self, url: str) -> Any: ...
    def async_current_url(self) -> Any: ...
    def async_screenshot(self, *, full_page: bool = False) -> Any: ...
    def async_pdf(self) -> Any: ...
    def async_evaluate(self, script: str) -> Any: ...
    def async_snapshot(self) -> Any: ...
    def async_forms(self) -> Any: ...
    def async_links(self) -> Any: ...
    def async_storage(self) -> Any: ...
    def async_set_cookie(self, cookie: BrowserCookieInfo) -> Any: ...
    def async_clear_cookies(self) -> Any: ...
    def async_console_events(self) -> Any: ...
    def async_network_events(self) -> Any: ...
    def async_close(self) -> Any: ...
    def __aenter__(self) -> AsyncBrowserSession: ...
    def __aexit__(self, *args: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
