from typing import Any, Callable

class AuditSink:
    def __init__(self, callback: Callable[..., Any]) -> None: ...
    def send(self, event: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __repr__(self) -> str: ...

class FindingSink:
    def __init__(self, callback: Callable[..., Any]) -> None: ...
    def send(self, finding: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __repr__(self) -> str: ...

class ArtifactSink:
    def __init__(self, callback: Callable[..., Any]) -> None: ...
    def send(self, artifact: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __repr__(self) -> str: ...

class ProgressSink:
    def __init__(self, callback: Callable[..., Any]) -> None: ...
    def send(self, percentage: float, message: str) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __repr__(self) -> str: ...

class EventConsumer:
    def __init__(self, callback: Callable[..., Any]) -> None: ...
    def send(self, event: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __repr__(self) -> str: ...
