from types import TracebackType
from typing import Any, Callable, Optional, Self

class AuditSink:
    def __init__(self, callback: Callable[..., Any]) -> None: ...
    def send(self, event: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Optional[type[BaseException]] = None, exc_value: Optional[BaseException] = None, traceback: Optional[TracebackType] = None) -> bool: ...

class FindingSink:
    def __init__(self, callback: Callable[..., Any]) -> None: ...
    def send(self, finding: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Optional[type[BaseException]] = None, exc_value: Optional[BaseException] = None, traceback: Optional[TracebackType] = None) -> bool: ...

class ArtifactSink:
    def __init__(self, callback: Callable[..., Any]) -> None: ...
    def send(self, artifact: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Optional[type[BaseException]] = None, exc_value: Optional[BaseException] = None, traceback: Optional[TracebackType] = None) -> bool: ...

class ProgressSink:
    def __init__(self, callback: Callable[..., Any]) -> None: ...
    def send(self, percentage: float, message: str) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Optional[type[BaseException]] = None, exc_value: Optional[BaseException] = None, traceback: Optional[TracebackType] = None) -> bool: ...

class EventConsumer:
    def __init__(self, callback: Callable[..., Any]) -> None: ...
    def send(self, event: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Optional[type[BaseException]] = None, exc_value: Optional[BaseException] = None, traceback: Optional[TracebackType] = None) -> bool: ...
