from typing import Any, Optional

class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self, reason: Optional[str] = None) -> None: ...
    def is_cancelled(self) -> bool: ...
    def cancel_token(self) -> dict[str, Any]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
