from typing import Optional, List
from .pipeline import StepResult

class Checkpoint:
    def __init__(
        self,
        id: str,
        pipeline_name: str,
        *,
        completed_steps: Optional[List[str]] = None,
        results: Optional[List[StepResult]] = None,
        created_at_ms: int = 0,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def pipeline_name(self) -> str: ...
    @property
    def completed_steps(self) -> List[str]: ...
    @property
    def results(self) -> List[StepResult]: ...
    @property
    def created_at_ms(self) -> int: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class CheckpointStore:
    def __init__(self) -> None: ...
    def save(
        self,
        pipeline_name: str,
        completed_steps: List[str],
        results: List[StepResult],
    ) -> Checkpoint: ...
    def load(self, checkpoint_id: str) -> Optional[Checkpoint]: ...
    def list_checkpoints(self) -> List[Checkpoint]: ...
    def delete(self, checkpoint_id: str) -> bool: ...
    def len(self) -> int: ...
    def __repr__(self) -> str: ...
