from typing import Any, Optional
from .scope import Scope
from . import dto, endpoint, fingerprint, recon, waf
from .loadtest import LoadTestResult
from .waf_validation import WafScanResult, FuzzSession

class Client:
    def __init__(self, scope: Scope, *, mode: str = "manual", concurrency: int = 100, timeout_ms: int = 5000) -> None: ...
    @property
    def scope(self) -> Scope: ...
    @property
    def mode(self) -> str: ...
    def scan_ports(self, target: str, ports: list[int], *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> dto.PortScanResult: ...
    def scan_endpoints(self, base_url: str, endpoints: list[str], *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None, include_404: bool = False, verify_tls: bool = True) -> endpoint.EndpointScanResult: ...
    def fingerprint_services(self, target: str, ports: list[int], *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> fingerprint.FingerprintScanResult: ...
    def recon_dns(self, domain: str) -> recon.DnsRecordSet: ...
    def inspect_tls(self, host: str, *, port: int = 443) -> recon.TlsInspectionResult: ...
    def detect_technology(self, url: str) -> recon.TechDetectionResult: ...
    def detect_waf(self, url: str) -> waf.WafDetectionResult: ...
    def load_test_http(self, url: str, total_requests: int, concurrency: int, timeout_secs: int, *, method: str = "GET") -> Any: ...
    def validate_waf(self, url: str, *, bypass: bool = False, test_type: Optional[str] = None) -> Any: ...
    def fuzz_http(self, url: str, payload_type: str = "all", *, method: str = "GET", param: Optional[str] = None, concurrency: int = 10, timeout: int = 30) -> Any: ...
    def __enter__(self) -> Client: ...
    def __exit__(self, *args: object) -> None: ...
