from typing import Any, Dict, List, Optional
from .finding_schema import VersionedFinding

class ComplianceFramework:
    OwaspTop10: ComplianceFramework
    NistCsf: ComplianceFramework
    PciDss: ComplianceFramework
    Hipaa: ComplianceFramework
    Soca2: ComplianceFramework
    Iso27001: ComplianceFramework
    CisBenchmarks: ComplianceFramework
    Custom: ComplianceFramework
    @staticmethod
    def from_str(s: str) -> ComplianceFramework: ...
    def as_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class ComplianceControl:
    def __init__(self, framework: ComplianceFramework, control_id: str, title: str, description: str, version: str, *, parent_control: Optional[str] = None) -> None: ...
    @property
    def framework(self) -> ComplianceFramework: ...
    @property
    def control_id(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def parent_control(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ComplianceMapping:
    def __init__(self, finding_id: str, control: ComplianceControl, mapping_confidence: float, rationale: str, mapped_by: str, mapped_at: str) -> None: ...
    @property
    def finding_id(self) -> str: ...
    @property
    def control(self) -> ComplianceControl: ...
    @property
    def mapping_confidence(self) -> float: ...
    @property
    def rationale(self) -> str: ...
    @property
    def mapped_by(self) -> str: ...
    @property
    def mapped_at(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ComplianceResult:
    Pass: ComplianceResult
    Fail: ComplianceResult
    Partial: ComplianceResult
    NotApplicable: ComplianceResult
    NotAssessed: ComplianceResult
    def as_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class ControlAssessment:
    def __init__(self, control: ComplianceControl, result: ComplianceResult, finding_ids: List[str], *, notes: Optional[str] = None, assessed_at: str = "") -> None: ...
    @property
    def control(self) -> ComplianceControl: ...
    @property
    def result(self) -> ComplianceResult: ...
    @property
    def finding_ids(self) -> List[str]: ...
    @property
    def notes(self) -> Optional[str]: ...
    @property
    def assessed_at(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ComplianceReport:
    @property
    def framework(self) -> ComplianceFramework: ...
    @property
    def generated_at(self) -> str: ...
    @property
    def total_controls(self) -> int: ...
    @property
    def passed(self) -> int: ...
    @property
    def failed(self) -> int: ...
    @property
    def partial(self) -> int: ...
    @property
    def not_applicable(self) -> int: ...
    @property
    def compliance_percentage(self) -> float: ...
    @property
    def assessments(self) -> List[ControlAssessment]: ...
    @property
    def disclaimer(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ComplianceMapper:
    def __init__(self) -> None: ...
    def register_control(self, control: ComplianceControl) -> None: ...
    def register_controls(self, controls: List[ComplianceControl]) -> None: ...
    def map_finding(self, finding_id: str, control_id: str, framework: ComplianceFramework, confidence: float, rationale: str) -> ComplianceMapping: ...
    def auto_map_findings(self, findings: List[VersionedFinding]) -> List[ComplianceMapping]: ...
    def get_mappings_for_finding(self, finding_id: str) -> List[ComplianceMapping]: ...
    def get_mappings_for_control(self, control_id: str) -> List[ComplianceMapping]: ...
    def assess_control(self, control_id: str, findings: List[VersionedFinding]) -> ControlAssessment: ...
    def generate_report(self, framework: ComplianceFramework, findings: List[VersionedFinding]) -> ComplianceReport: ...
    def controls(self) -> List[ComplianceControl]: ...
    def mappings(self) -> List[ComplianceMapping]: ...
