class SensitiveString:
    """Zeroized secret wrapper."""
    @staticmethod
    def new(value: str) -> SensitiveString: ...
    def expose_secret(self) -> str: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HttpConfig:
    @staticmethod
    def default() -> HttpConfig: ...
    @property
    def timeout_secs(self) -> int: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def retry_delay_ms(self) -> int: ...
    @property
    def verify_tls(self) -> bool: ...
    @property
    def follow_redirects(self) -> bool: ...
    @property
    def max_redirects(self) -> int: ...
    @property
    def default_headers(self) -> dict[str, str]: ...
    @property
    def default_user_agent(self) -> str | None: ...
    @property
    def proxy(self) -> str | None: ...
    @property
    def proxy_auth(self) -> tuple[str, str] | None: ...
    @property
    def has_proxy_auth(self) -> bool: ...

class ScanConfig:
    @staticmethod
    def default() -> ScanConfig: ...
    @property
    def default_concurrency(self) -> int: ...
    @property
    def rate_limit_per_second(self) -> int: ...
    @property
    def jitter_ms(self) -> int: ...
    @property
    def stealth_mode(self) -> bool: ...
    @property
    def exclude_ports(self) -> list[int]: ...
    @property
    def exclude_hosts(self) -> list[str]: ...
    @property
    def port_timeout_secs(self) -> int: ...
    @property
    def save_session(self) -> bool: ...

class OutputConfig:
    @staticmethod
    def default() -> OutputConfig: ...
    @property
    def format(self) -> str: ...
    @property
    def verbosity(self) -> int: ...
    @property
    def color(self) -> bool: ...
    @property
    def progress_bars(self) -> bool: ...
    @property
    def save_results(self) -> bool: ...
    @property
    def results_dir(self) -> str | None: ...
    @property
    def include_timestamp(self) -> bool: ...

class ReconApiConfig:
    @property
    def virustotal_enabled(self) -> bool: ...
    @property
    def has_virustotal_api_key(self) -> bool: ...
    @property
    def alienvault_enabled(self) -> bool: ...
    @property
    def has_alienvault_api_key(self) -> bool: ...
    @property
    def shodan_enabled(self) -> bool: ...
    @property
    def has_shodan_api_key(self) -> bool: ...
    @property
    def ipapi_enabled(self) -> bool: ...
    @property
    def has_ipapi_api_key(self) -> bool: ...
    @property
    def maxmind_enabled(self) -> bool: ...
    @property
    def has_maxmind_api_key(self) -> bool: ...
    @property
    def wayback_enabled(self) -> bool: ...
    @property
    def has_wayback_api_key(self) -> bool: ...
    @property
    def nvd_enabled(self) -> bool: ...
    @property
    def has_nvd_api_key(self) -> bool: ...

class ReconConfig:
    @staticmethod
    def default() -> ReconConfig: ...
    @property
    def dns_concurrency(self) -> int: ...
    @property
    def apis(self) -> ReconApiConfig: ...

class ProxyConfigEntry:
    @property
    def proxy_type(self) -> str: ...
    @property
    def address(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def username(self) -> str | None: ...
    @property
    def has_password(self) -> bool: ...
    @property
    def local_addr(self) -> str | None: ...
    @property
    def weight(self) -> int: ...
    @property
    def priority(self) -> int: ...
    @property
    def enabled(self) -> bool: ...

class AllowedWorker:
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...

class RemoteConfig:
    @staticmethod
    def default() -> RemoteConfig: ...
    @property
    def has_psk(self) -> bool: ...
    @property
    def default_port(self) -> int: ...
    @property
    def allowed_workers(self) -> list[AllowedWorker]: ...

class AiConfig:
    @property
    def provider(self) -> str: ...
    @property
    def model(self) -> str: ...
    @property
    def has_api_key(self) -> bool: ...
    @property
    def base_url(self) -> str | None: ...
    @property
    def max_tokens(self) -> int: ...
    @property
    def temperature(self) -> float: ...
    @property
    def max_payloads(self) -> int: ...
    @property
    def max_bypasses(self) -> int: ...

class SearchConfig:
    @property
    def enabled(self) -> bool: ...
    @property
    def url(self) -> str: ...
    @property
    def engines(self) -> list[str]: ...
    @property
    def cache_ttl_seconds(self) -> int: ...

class PathsConfig:
    @property
    def custom_payloads_dir(self) -> str | None: ...
    @property
    def wordlists_dir(self) -> str | None: ...
    @property
    def export_dir(self) -> str | None: ...

class CacheConfig:
    @property
    def ttl_secs(self) -> int: ...

class AlertChannelConfig:
    @staticmethod
    def webhook(url: str, name: str | None = None) -> AlertChannelConfig: ...
    @staticmethod
    def email(smtp_host: str, smtp_port: int, from_addr: str, to_addrs: list[str], name: str | None = None) -> AlertChannelConfig: ...
    @staticmethod
    def slack(webhook_url: str, name: str | None = None) -> AlertChannelConfig: ...
    @staticmethod
    def pagerduty(routing_key: str, name: str | None = None) -> AlertChannelConfig: ...
    @property
    def channel_type(self) -> str: ...

class EggsecConfig:
    @staticmethod
    def load(path: str | None = None) -> EggsecConfig: ...
    @staticmethod
    def default_path() -> str: ...
    def save(self, path: str | None = None) -> None: ...
    def validate(self) -> list[str]: ...
    @property
    def http(self) -> HttpConfig: ...
    @property
    def scan(self) -> ScanConfig: ...
    @property
    def output(self) -> OutputConfig: ...
    @property
    def recon(self) -> ReconConfig: ...
    @property
    def profiles(self) -> dict[str, str]: ...
    @property
    def proxies(self) -> list[ProxyConfigEntry]: ...
    @property
    def remote(self) -> RemoteConfig: ...
    @property
    def ai(self) -> AiConfig | None: ...
    @property
    def search(self) -> SearchConfig | None: ...
    @property
    def paths(self) -> PathsConfig: ...
    @property
    def alert_channels(self) -> dict[str, AlertChannelConfig]: ...
    @property
    def auto_save_interval_secs(self) -> int: ...
