from typing import Any, Dict, List, Optional

class ContentAddressedArtifactStore:
    def __init__(self, base_path: str) -> None: ...
    @property
    def base_path(self) -> str: ...
    def store(self, data: bytes, *, name: Optional[str] = None, mime_type: Optional[str] = None, metadata: Optional[Dict[str, Any]] = None) -> "ArtifactInfo": ...
    def get(self, content_hash: str) -> Optional["ArtifactData"]: ...
    def has(self, content_hash: str) -> bool: ...
    def remove(self, content_hash: str) -> bool: ...
    def count(self) -> int: ...
    def list_hashes(self) -> List[str]: ...
    def list_artifacts(self) -> List["ArtifactInfo"]: ...
    def query(self, *, name: Optional[str] = None, mime_type: Optional[str] = None) -> List["ArtifactInfo"]: ...
    def verify_integrity(self, content_hash: str) -> "IntegrityResult": ...
    def verify_all(self) -> List["IntegrityResult"]: ...
    def gc(self, referenced_hashes: Optional[List[str]] = None) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DirectoryArtifactStore:
    def __init__(self, directory: str) -> None: ...
    @property
    def directory(self) -> str: ...
    def store_file(self, file_path: str, *, name: Optional[str] = None, mime_type: Optional[str] = None, metadata: Optional[Dict[str, Any]] = None) -> "ArtifactInfo": ...
    def retrieve(self, content_hash: str, dest_path: str) -> bool: ...
    def has(self, content_hash: str) -> bool: ...
    def remove(self, content_hash: str) -> bool: ...
    def count(self) -> int: ...
    def list_artifacts(self) -> List["ArtifactInfo"]: ...
    def total_size_bytes(self) -> int: ...
    def verify_integrity(self, content_hash: str) -> "IntegrityResult": ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ArtifactInfo:
    def __init__(
        self,
        content_hash: str,
        *,
        name: Optional[str] = None,
        mime_type: Optional[str] = None,
        size_bytes: int = 0,
        created_at: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None: ...
    @property
    def content_hash(self) -> str: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def mime_type(self) -> Optional[str]: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def created_at(self) -> Optional[str]: ...
    @property
    def metadata(self) -> Dict[str, Any]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ArtifactData:
    def __init__(
        self,
        content_hash: str,
        data: bytes,
        *,
        info: Optional[ArtifactInfo] = None,
    ) -> None: ...
    @property
    def content_hash(self) -> str: ...
    @property
    def data(self) -> bytes: ...
    @property
    def info(self) -> Optional[ArtifactInfo]: ...
    @property
    def size(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class IntegrityResult:
    def __init__(
        self,
        content_hash: str,
        *,
        valid: bool = False,
        expected_size: Optional[int] = None,
        actual_size: Optional[int] = None,
        error: Optional[str] = None,
    ) -> None: ...
    @property
    def content_hash(self) -> str: ...
    @property
    def valid(self) -> bool: ...
    @property
    def expected_size(self) -> Optional[int]: ...
    @property
    def actual_size(self) -> Optional[int]: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ArtifactQuery:
    def __init__(
        self,
        *,
        name: Optional[str] = None,
        name_pattern: Optional[str] = None,
        mime_type: Optional[str] = None,
        min_size: Optional[int] = None,
        max_size: Optional[int] = None,
        created_after: Optional[str] = None,
        created_before: Optional[str] = None,
        metadata_key: Optional[str] = None,
        metadata_value: Optional[str] = None,
    ) -> None: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def name_pattern(self) -> Optional[str]: ...
    @property
    def mime_type(self) -> Optional[str]: ...
    @property
    def min_size(self) -> Optional[int]: ...
    @property
    def max_size(self) -> Optional[int]: ...
    @property
    def created_after(self) -> Optional[str]: ...
    @property
    def created_before(self) -> Optional[str]: ...
    @property
    def metadata_key(self) -> Optional[str]: ...
    @property
    def metadata_value(self) -> Optional[str]: ...
    def matches(self, info: ArtifactInfo) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
