from typing import Any, Dict, List, Optional

class ArtifactInfo:
    def __init__(
        self,
        artifact_id: str,
        content_hash: str,
        content_type: str,
        size_bytes: int,
        *,
        created_at_ms: int = 0,
        metadata: Optional[str] = None,
        redacted: bool = False,
    ) -> None: ...
    @property
    def artifact_id(self) -> str: ...
    @property
    def content_hash(self) -> str: ...
    @property
    def content_type(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def created_at_ms(self) -> int: ...
    @property
    def metadata(self) -> Optional[str]: ...
    @property
    def redacted(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ArtifactData:
    def __init__(self, info: ArtifactInfo, data: bytes) -> None: ...
    @property
    def info(self) -> ArtifactInfo: ...
    @property
    def data(self) -> bytes: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class IntegrityResult:
    def __init__(
        self,
        valid: bool,
        expected_hash: str,
        actual_hash: str,
        size_bytes: int,
        *,
        verified_at_ms: int = 0,
    ) -> None: ...
    @property
    def valid(self) -> bool: ...
    @property
    def expected_hash(self) -> str: ...
    @property
    def actual_hash(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def verified_at_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ArtifactQuery:
    def __init__(
        self,
        *,
        content_type: Optional[str] = None,
        min_size: Optional[int] = None,
        max_size: Optional[int] = None,
        created_after_ms: Optional[int] = None,
        created_before_ms: Optional[int] = None,
        limit: int = 100,
        offset: int = 0,
    ) -> None: ...
    @property
    def content_type(self) -> Optional[str]: ...
    @property
    def min_size(self) -> Optional[int]: ...
    @property
    def max_size(self) -> Optional[int]: ...
    @property
    def created_after_ms(self) -> Optional[int]: ...
    @property
    def created_before_ms(self) -> Optional[int]: ...
    @property
    def limit(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ContentAddressedArtifactStore:
    def __init__(self, base_dir: str) -> None: ...
    @property
    def base_dir(self) -> str: ...
    def initialize(self) -> None: ...
    def put(
        self,
        data: bytes,
        content_type: str,
        metadata_json: Optional[str] = None,
    ) -> ArtifactInfo: ...
    def get(self, content_hash: str) -> Optional[ArtifactData]: ...
    def has(self, content_hash: str) -> bool: ...
    def delete(self, content_hash: str) -> bool: ...
    def verify(self, content_hash: str) -> IntegrityResult: ...
    def list_artifacts(self, limit: int = 100, offset: int = 0) -> List[ArtifactInfo]: ...
    def size_bytes(self, content_hash: str) -> Optional[int]: ...
    def total_size_bytes(self) -> int: ...
    def prune(
        self,
        *,
        max_age_secs: Optional[int] = None,
        max_size_bytes: Optional[int] = None,
    ) -> int: ...
    def __enter__(self) -> ContentAddressedArtifactStore: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DirectoryArtifactStore:
    def __init__(self, base_dir: str, *, flat: bool = True) -> None: ...
    @property
    def base_dir(self) -> str: ...
    def initialize(self) -> None: ...
    def put(
        self,
        name: str,
        data: bytes,
        content_type: str,
    ) -> ArtifactInfo: ...
    def get(self, name: str) -> Optional[ArtifactData]: ...
    def has(self, name: str) -> bool: ...
    def delete(self, name: str) -> bool: ...
    def list_artifacts(self, limit: int = 100, offset: int = 0) -> List[ArtifactInfo]: ...
    def resolve_path(self, name: str) -> Optional[str]: ...
    def __enter__(self) -> DirectoryArtifactStore: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
