from typing import Any, Dict, List, Optional

from .finding import Severity

class ContainerScanTypePy:
    DOCKER: "ContainerScanTypePy"
    KUBERNETES: "ContainerScanTypePy"
    ESCAPE_DETECTION: "ContainerScanTypePy"
    CIS_BENCHMARK: "ContainerScanTypePy"
    FULL: "ContainerScanTypePy"
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class EscapeRiskLevelPy:
    NONE: "EscapeRiskLevelPy"
    LOW: "EscapeRiskLevelPy"
    MEDIUM: "EscapeRiskLevelPy"
    HIGH: "EscapeRiskLevelPy"
    CRITICAL: "EscapeRiskLevelPy"
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class CisCheckStatusPy:
    PASS: "CisCheckStatusPy"
    FAIL: "CisCheckStatusPy"
    WARN: "CisCheckStatusPy"
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class ImageLayerPy:
    @property
    def layer_id(self) -> str: ...
    @property
    def instruction(self) -> str: ...
    @property
    def size_bytes(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class DockerMisconfigPy:
    @property
    def check(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def description(self) -> str: ...
    @property
    def recommendation(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class DockerScanResultPy:
    @property
    def image_name(self) -> str: ...
    @property
    def base_image(self) -> Optional[str]: ...
    @property
    def layers(self) -> List[ImageLayerPy]: ...
    @property
    def misconfigurations(self) -> List[DockerMisconfigPy]: ...
    @property
    def exposed_ports(self) -> List[int]: ...
    @property
    def running_as_root(self) -> bool: ...
    @property
    def has_healthcheck(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ClusterInfoPy:
    @property
    def server_version(self) -> Optional[str]: ...
    @property
    def node_count(self) -> Optional[int]: ...
    @property
    def namespace_count(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class K8sFindingPy:
    @property
    def resource_type(self) -> str: ...
    @property
    def resource_name(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def description(self) -> str: ...
    @property
    def recommendation(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class KubernetesScanResultPy:
    @property
    def cluster_info(self) -> Optional[ClusterInfoPy]: ...
    @property
    def rbac_issues(self) -> List[K8sFindingPy]: ...
    @property
    def network_policy_issues(self) -> List[K8sFindingPy]: ...
    @property
    def pod_security_issues(self) -> List[K8sFindingPy]: ...
    @property
    def secret_exposure(self) -> List[K8sFindingPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class EscapeRiskPy:
    @property
    def risk_type(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def description(self) -> str: ...
    @property
    def recommendation(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class EscapeDetectionResultPy:
    @property
    def target(self) -> str: ...
    @property
    def escape_risks(self) -> List[EscapeRiskPy]: ...
    @property
    def risk_level(self) -> EscapeRiskLevelPy: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CisCheckPy:
    @property
    def id(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def status(self) -> CisCheckStatusPy: ...
    @property
    def recommendation(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class CisBenchmarkResultPy:
    @property
    def benchmark_version(self) -> str: ...
    @property
    def total_checks(self) -> int: ...
    @property
    def passed(self) -> int: ...
    @property
    def failed(self) -> int: ...
    @property
    def warnings(self) -> int: ...
    @property
    def checks(self) -> List[CisCheckPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ContainerFindingPy:
    @property
    def category(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def recommendation(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ContainerReportPy:
    @property
    def target(self) -> str: ...
    @property
    def scan_type(self) -> ContainerScanTypePy: ...
    @property
    def docker(self) -> Optional[DockerScanResultPy]: ...
    @property
    def kubernetes(self) -> Optional[KubernetesScanResultPy]: ...
    @property
    def escape_risks(self) -> Optional[EscapeDetectionResultPy]: ...
    @property
    def cis_benchmarks(self) -> Optional[CisBenchmarkResultPy]: ...
    @property
    def findings(self) -> List[ContainerFindingPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def scan_docker_image(image_name: str) -> DockerScanResultPy: ...
def async_scan_docker_image(image_name: str) -> Any: ...
def scan_kubernetes(api_server: str, token: Optional[str] = None, timeout_secs: int = 30) -> KubernetesScanResultPy: ...
def async_scan_kubernetes(api_server: str, token: Optional[str] = None, timeout_secs: int = 30) -> Any: ...
def detect_escape_risks(config: str) -> EscapeDetectionResultPy: ...
def check_cis_docker_benchmark(docker_info: str) -> CisBenchmarkResultPy: ...
