from typing import Any, Dict, List, Optional

class CvssScore:
    def __init__(self, version: str, vector: str, base_score: float, *, severity: Optional[str] = None, exploitability: Optional[float] = None, impact: Optional[float] = None) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def vector(self) -> str: ...
    @property
    def base_score(self) -> float: ...
    @property
    def severity(self) -> str: ...
    @property
    def exploitability(self) -> Optional[float]: ...
    @property
    def impact(self) -> Optional[float]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def parse(vector: str) -> CvssScore: ...

class VulnerabilityRecord:
    def __init__(self, title: str, description: str, severity: str, *, cve_id: Optional[str] = None, cwe_id: Optional[str] = None, cvss: Optional[CvssScore] = None, confidence: Optional[str] = None, affected_assets: Optional[List[str]] = None, references: Optional[List[str]] = None, published_at: Optional[str] = None, exploit_available: bool = False, risk_accepted: bool = False) -> None: ...
    @property
    def cve_id(self) -> Optional[str]: ...
    @property
    def cwe_id(self) -> Optional[str]: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def cvss(self) -> Optional[CvssScore]: ...
    @property
    def severity(self) -> str: ...
    @property
    def confidence(self) -> str: ...
    @property
    def affected_assets(self) -> List[str]: ...
    @property
    def references(self) -> List[str]: ...
    @property
    def published_at(self) -> Optional[str]: ...
    @property
    def exploit_available(self) -> bool: ...
    @property
    def risk_accepted(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class RemediationRecord:
    def __init__(self, finding_id: str, *, status: Optional[str] = None, assigned_to: Optional[str] = None, notes: Optional[List[str]] = None, created_at: Optional[str] = None, updated_at: Optional[str] = None, estimated_effort: Optional[str] = None) -> None: ...
    @property
    def finding_id(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def assigned_to(self) -> Optional[str]: ...
    @property
    def notes(self) -> List[str]: ...
    @property
    def created_at(self) -> str: ...
    @property
    def updated_at(self) -> str: ...
    @property
    def estimated_effort(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
