from typing import Any, Dict, Optional

class DaemonResponsePy:
    @property
    def ok(self) -> bool: ...
    @property
    def request_id(self) -> str: ...
    @property
    def message(self) -> Optional[str]: ...
    @property
    def error_code(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DaemonClientPy:
    @property
    def socket_path(self) -> Optional[str]: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> DaemonClientPy: ...
    def __exit__(self, exc_type: Any = None, exc_value: Any = None, traceback: Any = None) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...

def daemon_connect(socket_path: str) -> DaemonClientPy: ...
def async_daemon_health(client: DaemonClientPy) -> Any: ...
def async_daemon_declare_client(
    client: DaemonClientPy, kind: str = "cli", label: Optional[str] = None
) -> Any: ...
def async_daemon_create_session(
    client: DaemonClientPy,
    surface: str = "cli_manual",
    labels: Optional[list] = None,
) -> Any: ...
def async_daemon_list_sessions(client: DaemonClientPy) -> Any: ...
def async_daemon_get_snapshot(client: DaemonClientPy, session_id: str) -> Any: ...
def async_daemon_close_session(client: DaemonClientPy, session_id: str) -> Any: ...

class DaemonCapabilitiesPy:
    @property
    def runtime_version(self) -> str: ...
    @property
    def protocol_version(self) -> int: ...
    @property
    def transport_count(self) -> int: ...
    @property
    def transports(self) -> List[TransportMetadataPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TaskHandlePy:
    @property
    def task_id(self) -> str: ...
    @property
    def session_id(self) -> str: ...
    @property
    def status(self) -> TaskStatusPy: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TaskStatusPy:
    @property
    def state(self) -> str: ...
    @property
    def progress(self) -> Optional[float]: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DaemonEventPy:
    @property
    def session_id(self) -> str: ...
    @property
    def event_type(self) -> str: ...
    @property
    def timestamp(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionSummaryPy:
    @property
    def session_id(self) -> str: ...
    @property
    def surface(self) -> str: ...
    @property
    def labels(self) -> List[str]: ...
    @property
    def created_at(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TransportMetadataPy:
    @property
    def kind(self) -> str: ...
    @property
    def bind_address(self) -> str: ...
    @property
    def enabled(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
