from typing import Any, Dict, List, Optional

class DaemonEvent:
    def __init__(
        self,
        session_id: str,
        event_type: str,
        sequence: int,
        timestamp_ms: int,
        *,
        data: Optional[str] = None,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def event_type(self) -> str: ...
    @property
    def sequence(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def data(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class DaemonProtocolVersion:
    def __init__(
        self,
        api_schema_version: int,
        operation_registry_id: str,
        feature_profile: str,
    ) -> None: ...
    @property
    def protocol_version(self) -> int: ...
    @property
    def api_schema_version(self) -> int: ...
    @property
    def operation_registry_id(self) -> str: ...
    @property
    def feature_profile(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class IdempotencyKey:
    @classmethod
    def from_request(cls, operation_name: str, request_json: str) -> "IdempotencyKey": ...
    @property
    def key(self) -> str: ...
    @property
    def created_at_ms(self) -> int: ...
    @property
    def operation_name(self) -> str: ...
    @property
    def request_hash(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class DaemonSubmissionResult:
    def __init__(
        self,
        task_id: str,
        session_id: str,
        idempotency_key: str,
        is_duplicate: bool,
        submitted_at_ms: int,
        *,
        estimated_duration_ms: Optional[int] = None,
    ) -> None: ...
    @property
    def task_id(self) -> str: ...
    @property
    def session_id(self) -> str: ...
    @property
    def idempotency_key(self) -> str: ...
    @property
    def is_duplicate(self) -> bool: ...
    @property
    def submitted_at_ms(self) -> int: ...
    @property
    def estimated_duration_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ReconnectOptions:
    def __init__(
        self,
        *,
        max_retries: int = 5,
        retry_delay_ms: int = 500,
        backoff_multiplier: float = 2.0,
        max_backoff_ms: int = 30000,
        replay_from_sequence: Optional[int] = None,
    ) -> None: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def retry_delay_ms(self) -> int: ...
    @property
    def backoff_multiplier(self) -> float: ...
    @property
    def max_backoff_ms(self) -> int: ...
    @property
    def replay_from_sequence(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ReplayCursor:
    def __init__(
        self,
        session_id: str,
        last_sequence: int,
        total_events: int,
        gap_count: int,
        duplicate_count: int,
        timestamp_ms: int,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def last_sequence(self) -> int: ...
    @property
    def total_events(self) -> int: ...
    @property
    def gap_count(self) -> int: ...
    @property
    def duplicate_count(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ReplayResult:
    def __init__(self, cursor: ReplayCursor, has_more: bool) -> None: ...
    @property
    def cursor(self) -> ReplayCursor: ...
    @property
    def has_more(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class CancellationRequest:
    def __init__(
        self,
        session_id: str,
        task_id: str,
        *,
        reason: Optional[str] = None,
        force: bool = False,
        requested_at_ms: int = 0,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def task_id(self) -> str: ...
    @property
    def reason(self) -> Optional[str]: ...
    @property
    def force(self) -> bool: ...
    @property
    def requested_at_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class CancellationResult:
    def __init__(
        self,
        acknowledged: bool,
        task_was_running: bool,
        task_was_completed: bool,
        cleanup_started: bool,
        *,
        message: Optional[str] = None,
    ) -> None: ...
    @property
    def acknowledged(self) -> bool: ...
    @property
    def task_was_running(self) -> bool: ...
    @property
    def task_was_completed(self) -> bool: ...
    @property
    def cleanup_started(self) -> bool: ...
    @property
    def message(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class TaskArtifactDescriptor:
    def __init__(
        self,
        artifact_id: str,
        task_id: str,
        session_id: str,
        kind: str,
        content_type: str,
        size_bytes: int,
        content_hash: str,
        created_at_ms: int,
        *,
        redacted: bool = False,
        download_url: Optional[str] = None,
    ) -> None: ...
    @property
    def artifact_id(self) -> str: ...
    @property
    def task_id(self) -> str: ...
    @property
    def session_id(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def content_type(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def content_hash(self) -> str: ...
    @property
    def created_at_ms(self) -> int: ...
    @property
    def redacted(self) -> bool: ...
    @property
    def download_url(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class EventReplayInfo:
    def __init__(
        self,
        session_id: str,
        from_sequence: int,
        to_sequence: int,
        event_count: int,
        ordered: bool,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def from_sequence(self) -> int: ...
    @property
    def to_sequence(self) -> int: ...
    @property
    def event_count(self) -> int: ...
    @property
    def ordered(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class DaemonHealthDetail:
    def __init__(
        self,
        status: str = "ok",
        *,
        uptime_secs: int = 0,
        protocol_version: int = 2,
        active_sessions: int = 0,
        active_clients: int = 0,
        total_tasks_completed: int = 0,
        persistence_backend: str = "none",
        transport: str = "unix",
    ) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def uptime_secs(self) -> int: ...
    @property
    def protocol_version(self) -> int: ...
    @property
    def active_sessions(self) -> int: ...
    @property
    def active_clients(self) -> int: ...
    @property
    def total_tasks_completed(self) -> int: ...
    @property
    def persistence_backend(self) -> str: ...
    @property
    def transport(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
