from typing import Any, Dict, Optional

class DaemonResponsePy:
    @property
    def ok(self) -> bool: ...
    @property
    def request_id(self) -> str: ...
    @property
    def message(self) -> Optional[str]: ...
    @property
    def error_code(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DaemonClientPy:
    @property
    def socket_path(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...

def daemon_connect(socket_path: str) -> DaemonClientPy: ...
def async_daemon_health(client: DaemonClientPy) -> Any: ...
def async_daemon_declare_client(
    client: DaemonClientPy, kind: str = "cli", label: Optional[str] = None
) -> Any: ...
def async_daemon_create_session(
    client: DaemonClientPy,
    surface: str = "cli_manual",
    labels: Optional[list] = None,
) -> Any: ...
def async_daemon_list_sessions(client: DaemonClientPy) -> Any: ...
def async_daemon_get_snapshot(client: DaemonClientPy, session_id: str) -> Any: ...
def async_daemon_close_session(client: DaemonClientPy, session_id: str) -> Any: ...
