from typing import Any, Dict, List, Optional

class DaemonProtocolVersion:
    def __init__(self, major: int, minor: int, patch: int) -> None: ...
    @property
    def major(self) -> int: ...
    @property
    def minor(self) -> int: ...
    @property
    def patch(self) -> int: ...
    @property
    def as_string(self) -> str: ...
    def is_compatible(self, other: "DaemonProtocolVersion") -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class IdempotencyKey:
    def __init__(self, key: str) -> None: ...
    @property
    def key(self) -> str: ...
    @staticmethod
    def generate() -> "IdempotencyKey": ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DaemonSubmissionResult:
    def __init__(
        self,
        *,
        accepted: bool = False,
        task_id: Optional[str] = None,
        session_id: Optional[str] = None,
        error: Optional[str] = None,
        duplicate: bool = False,
    ) -> None: ...
    @property
    def accepted(self) -> bool: ...
    @property
    def task_id(self) -> Optional[str]: ...
    @property
    def session_id(self) -> Optional[str]: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def duplicate(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ReconnectOptions:
    def __init__(
        self,
        *,
        max_retries: int = 3,
        retry_delay_ms: int = 1000,
        backoff_multiplier: float = 2.0,
        max_retry_delay_ms: int = 30000,
        resume_session: bool = True,
    ) -> None: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def retry_delay_ms(self) -> int: ...
    @property
    def backoff_multiplier(self) -> float: ...
    @property
    def max_retry_delay_ms(self) -> int: ...
    @property
    def resume_session(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ReplayCursor:
    def __init__(
        self,
        *,
        last_event_id: Optional[str] = None,
        last_sequence: Optional[int] = None,
        session_id: Optional[str] = None,
    ) -> None: ...
    @property
    def last_event_id(self) -> Optional[str]: ...
    @property
    def last_sequence(self) -> Optional[int]: ...
    @property
    def session_id(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ReplayResult:
    def __init__(
        self,
        *,
        events_replayed: int = 0,
        events_skipped: int = 0,
        cursor: Optional[ReplayCursor] = None,
        has_more: bool = False,
    ) -> None: ...
    @property
    def events_replayed(self) -> int: ...
    @property
    def events_skipped(self) -> int: ...
    @property
    def cursor(self) -> Optional[ReplayCursor]: ...
    @property
    def has_more(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DaemonParityEvent:
    def __init__(
        self,
        event_type: str,
        payload: Any,
        *,
        session_id: Optional[str] = None,
        task_id: Optional[str] = None,
        timestamp_ms: Optional[int] = None,
        event_id: Optional[str] = None,
        sequence: Optional[int] = None,
    ) -> None: ...
    @property
    def event_type(self) -> str: ...
    @property
    def payload(self) -> Any: ...
    @property
    def session_id(self) -> Optional[str]: ...
    @property
    def task_id(self) -> Optional[str]: ...
    @property
    def timestamp_ms(self) -> Optional[int]: ...
    @property
    def event_id(self) -> Optional[str]: ...
    @property
    def sequence(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CancellationRequest:
    def __init__(
        self,
        session_id: str,
        task_id: str,
        *,
        reason: Optional[str] = None,
        requested_by: Optional[str] = None,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def task_id(self) -> str: ...
    @property
    def reason(self) -> Optional[str]: ...
    @property
    def requested_by(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CancellationResult:
    def __init__(
        self,
        *,
        cancelled: bool = False,
        task_id: Optional[str] = None,
        error: Optional[str] = None,
        already_completed: bool = False,
    ) -> None: ...
    @property
    def cancelled(self) -> bool: ...
    @property
    def task_id(self) -> Optional[str]: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def already_completed(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TaskArtifactDescriptor:
    def __init__(
        self,
        artifact_id: str,
        artifact_type: str,
        *,
        mime_type: Optional[str] = None,
        size_bytes: Optional[int] = None,
        content_hash: Optional[str] = None,
        task_id: Optional[str] = None,
        session_id: Optional[str] = None,
    ) -> None: ...
    @property
    def artifact_id(self) -> str: ...
    @property
    def artifact_type(self) -> str: ...
    @property
    def mime_type(self) -> Optional[str]: ...
    @property
    def size_bytes(self) -> Optional[int]: ...
    @property
    def content_hash(self) -> Optional[str]: ...
    @property
    def task_id(self) -> Optional[str]: ...
    @property
    def session_id(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class EventReplayInfo:
    def __init__(
        self,
        *,
        total_events: int = 0,
        replayable_events: int = 0,
        oldest_event_ms: Optional[int] = None,
        newest_event_ms: Optional[int] = None,
        cursor: Optional[ReplayCursor] = None,
    ) -> None: ...
    @property
    def total_events(self) -> int: ...
    @property
    def replayable_events(self) -> int: ...
    @property
    def oldest_event_ms(self) -> Optional[int]: ...
    @property
    def newest_event_ms(self) -> Optional[int]: ...
    @property
    def cursor(self) -> Optional[ReplayCursor]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DaemonHealthDetail:
    def __init__(
        self,
        *,
        status: str = "ok",
        uptime_ms: int = 0,
        active_sessions: int = 0,
        active_tasks: int = 0,
        transport_count: int = 0,
        protocol_version: Optional[DaemonProtocolVersion] = None,
        memory_usage_bytes: Optional[int] = None,
    ) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def uptime_ms(self) -> int: ...
    @property
    def active_sessions(self) -> int: ...
    @property
    def active_tasks(self) -> int: ...
    @property
    def transport_count(self) -> int: ...
    @property
    def protocol_version(self) -> Optional[DaemonProtocolVersion]: ...
    @property
    def memory_usage_bytes(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
