# Feature-gated: distributed computing
from typing import Any

class DistributedTaskTypePy:
    PortScan: "DistributedTaskTypePy"
    ServiceFingerprint: "DistributedTaskTypePy"
    EndpointDiscovery: "DistributedTaskTypePy"
    Fuzz: "DistributedTaskTypePy"
    WafTest: "DistributedTaskTypePy"
    LoadTest: "DistributedTaskTypePy"
    Recon: "DistributedTaskTypePy"
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class WorkerStatusPy:
    Idle: "WorkerStatusPy"
    Busy: "WorkerStatusPy"
    Disconnected: "WorkerStatusPy"
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class WorkerRegistrationPy:
    @property
    def worker_id(self) -> str: ...

class HeartbeatPy:
    @property
    def worker_id(self) -> str: ...

class DistributedTaskPy:
    @property
    def task_id(self) -> str: ...

class DistributedTaskResultPy:
    @property
    def task_id(self) -> str: ...
    @property
    def success(self) -> bool: ...

def distributed_task_types() -> list[DistributedTaskTypePy]: ...
def distributed_generate_psk() -> str: ...
