class DomainDescriptorPy:
    @property
    def id(self) -> str: ...
    @property
    def display_name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def required_feature(self) -> str | None: ...
    @property
    def operations(self) -> list[str]: ...
    @property
    def is_available(self) -> bool: ...
    def to_dict(self) -> dict: ...

class DomainRegistry:
    @staticmethod
    def all_domains() -> list[DomainDescriptorPy]: ...
    @staticmethod
    def available_domains() -> list[DomainDescriptorPy]: ...
    @staticmethod
    def find(domain_id: str) -> DomainDescriptorPy | None: ...
