from typing import Any, Dict, List, Optional

class PortRange:
    @staticmethod
    def list(ports: list[int]) -> PortRange: ...
    @staticmethod
    def range(start: int, end: int) -> PortRange: ...
    @staticmethod
    def top_100() -> PortRange: ...
    @staticmethod
    def top_1000() -> PortRange: ...
    @property
    def ports(self) -> list[int]: ...

class TimingPreset:
    @staticmethod
    def paranoid() -> TimingPreset: ...
    @staticmethod
    def sneaky() -> TimingPreset: ...
    @staticmethod
    def polite() -> TimingPreset: ...
    @staticmethod
    def normal() -> TimingPreset: ...
    @staticmethod
    def aggressive() -> TimingPreset: ...
    @staticmethod
    def insane() -> TimingPreset: ...

class OpenPort:
    @property
    def port(self) -> int: ...
    @property
    def protocol(self) -> str: ...
    @property
    def service(self) -> str: ...
    @property
    def banner(self) -> Optional[str]: ...
    @property
    def confidence(self) -> float: ...

class ScanStats:
    @property
    def ports_scanned(self) -> int: ...
    @property
    def total_open(self) -> int: ...
    @property
    def elapsed_ms(self) -> int: ...

class PortScanResult:
    @property
    def target(self) -> str: ...
    @property
    def open_ports(self) -> list[OpenPort]: ...
    @property
    def scanned_ports(self) -> int: ...
    @property
    def elapsed_ms(self) -> int: ...
    @property
    def stats(self) -> ScanStats: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def to_rows(self) -> List[Dict[str, Any]]: ...
