from typing import Any, Dict, List, Optional

class EndpointScanConfig:
    def __init__(self, base_url: str, endpoints: list[str], *, concurrency: int = 20, timeout_ms: int = 30000, include_404: bool = False, verify_tls: bool = True) -> None: ...

class EndpointFinding:
    @property
    def url(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def status_code(self) -> int: ...
    @property
    def content_length(self) -> Optional[int]: ...
    @property
    def content_type(self) -> Optional[str]: ...
    @property
    def redirect_location(self) -> Optional[str]: ...
    @property
    def interesting(self) -> bool: ...
    @property
    def response_time_ms(self) -> int: ...

class EndpointScanStats:
    @property
    def endpoints_scanned(self) -> int: ...
    @property
    def endpoints_found(self) -> int: ...
    @property
    def interesting_findings(self) -> int: ...
    @property
    def elapsed_ms(self) -> int: ...

class EndpointScanResult:
    @property
    def findings(self) -> list[EndpointFinding]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def to_rows(self) -> List[Dict[str, Any]]: ...
