from typing import Any, Literal, Optional, Union
from .scope import Scope
from .status import ExecutionStats, ExecutionStatus, OperationResult
from .requests import (
    OperationRequest,
    PortScanRequest,
    EndpointScanRequest,
    FingerprintRequest,
    ReconDnsRequest,
    TlsInspectRequest,
    TechDetectRequest,
    WafDetectRequest,
    LoadTestRequest,
    WafValidateRequest,
    FuzzRequest,
    GitSecretsScanRequest,
    SbomRequest,
    ConsolidatedReconRequest,
    GraphqlTestRequest,
    OauthTestRequest,
    AuthTestRequest,
    DbProbeRequest,
    NseRunRequest,
    DockerImageScanRequest,
    KubernetesScanRequest,
    ApkAnalysisRequest,
    IpaAnalysisRequest,
)
from .cancellation import CancellationToken
from .planning import ScanPlan

OperationId = Literal[
    "scan_ports", "scan_endpoints", "fingerprint_services", "recon_dns",
    "inspect_tls", "detect_technology", "detect_waf", "validate_waf",
    "fuzz_http", "load_test", "scan_git_secrets", "generate_sbom",
    "run_consolidated_recon", "graphql_test", "oauth_test", "auth_test",
    "db_probe", "nse_run", "scan_docker_image", "scan_kubernetes",
    "analyze_apk", "analyze_ipa",
]

class Engine:
    def __init__(
        self,
        scope: Scope,
        *,
        mode: str = "manual",
        concurrency: int = 100,
        timeout_ms: int = 5000,
    ) -> None: ...
    @staticmethod
    def local(
        scope: Scope,
        *,
        mode: str = "manual",
        concurrency: int = 100,
        timeout_ms: int = 5000,
    ) -> Engine: ...
    @staticmethod
    def daemon(
        socket_path: str,
        *,
        session_id: Optional[str] = None,
        mode: str = "manual",
        concurrency: int = 100,
        timeout_ms: int = 5000,
    ) -> Engine: ...
    def run(
        self,
        request: OperationRequest,
        *,
        cancel_token: Optional[CancellationToken] = None,
    ) -> OperationResult: ...
    def list_operations(self) -> list[str]: ...
    def has_operation(self, operation_id: str) -> bool: ...
    def audit_events(self) -> list[Any]: ...
    def run_port_scan(self, request: PortScanRequest) -> OperationResult: ...
    def run_endpoint_scan(self, request: EndpointScanRequest) -> OperationResult: ...
    def run_fingerprint(self, request: FingerprintRequest) -> OperationResult: ...
    def run_recon_dns(self, request: ReconDnsRequest) -> OperationResult: ...
    def run_tls_inspect(self, request: TlsInspectRequest) -> OperationResult: ...
    def run_tech_detect(self, request: TechDetectRequest) -> OperationResult: ...
    def run_waf_detect(self, request: WafDetectRequest) -> OperationResult: ...
    def run_load_test(self, request: LoadTestRequest) -> OperationResult: ...
    def run_waf_validate(self, request: WafValidateRequest) -> OperationResult: ...
    def run_fuzz(self, request: FuzzRequest) -> OperationResult: ...
    def run_git_secrets(self, request: GitSecretsScanRequest) -> OperationResult: ...
    def run_sbom(self, request: SbomRequest) -> OperationResult: ...
    def run_consolidated_recon(self, request: ConsolidatedReconRequest) -> OperationResult: ...
    def run_graphql_test(self, request: GraphqlTestRequest) -> OperationResult: ...
    def run_oauth_test(self, request: OauthTestRequest) -> OperationResult: ...
    def run_auth_test(self, request: AuthTestRequest) -> OperationResult: ...
    def run_db_probe(self, request: DbProbeRequest) -> OperationResult: ...
    def run_nse(self, request: NseRunRequest) -> OperationResult: ...
    def run_docker_scan(self, request: DockerImageScanRequest) -> OperationResult: ...
    def run_kubernetes_scan(self, request: KubernetesScanRequest) -> OperationResult: ...
    def run_apk_analysis(self, request: ApkAnalysisRequest) -> OperationResult: ...
    def run_ipa_analysis(self, request: IpaAnalysisRequest) -> OperationResult: ...
    def plan(self, target: str) -> ScanPlan: ...
    @property
    def scope(self) -> Scope: ...
    @property
    def mode(self) -> str: ...
    @property
    def concurrency(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> Engine: ...
    def __exit__(self, *args: object) -> None: ...
    def __repr__(self) -> str: ...
