from typing import Optional
from .scope import Scope
from .status import ExecutionStats, ExecutionStatus, OperationResult
from .requests import (
    OperationRequest,
    PortScanRequest,
    EndpointScanRequest,
    FingerprintRequest,
    ReconDnsRequest,
    TlsInspectRequest,
    TechDetectRequest,
    WafDetectRequest,
    LoadTestRequest,
    WafValidateRequest,
    FuzzRequest,
)
from .planning import ScanPlan

class Engine:
    def __init__(
        self,
        scope: Scope,
        *,
        mode: str = "manual",
        concurrency: int = 100,
        timeout_ms: int = 5000,
    ) -> None: ...
    def run(self, request: OperationRequest) -> OperationResult: ...
    def run_port_scan(self, request: PortScanRequest) -> OperationResult: ...
    def run_endpoint_scan(self, request: EndpointScanRequest) -> OperationResult: ...
    def run_fingerprint(self, request: FingerprintRequest) -> OperationResult: ...
    def run_recon_dns(self, request: ReconDnsRequest) -> OperationResult: ...
    def run_tls_inspect(self, request: TlsInspectRequest) -> OperationResult: ...
    def run_tech_detect(self, request: TechDetectRequest) -> OperationResult: ...
    def run_waf_detect(self, request: WafDetectRequest) -> OperationResult: ...
    def run_load_test(self, request: LoadTestRequest) -> OperationResult: ...
    def run_waf_validate(self, request: WafValidateRequest) -> OperationResult: ...
    def run_fuzz(self, request: FuzzRequest) -> OperationResult: ...
    def plan(self, target: str) -> ScanPlan: ...
    @property
    def scope(self) -> Scope: ...
    @property
    def mode(self) -> str: ...
    @property
    def concurrency(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> Engine: ...
    def __exit__(self, *args: object) -> None: ...
    def __repr__(self) -> str: ...
