from typing import Any, Optional

EVENT_SCHEMA_VERSION: str

class EventEnvelope:
    def __init__(
        self,
        event_type: str,
        payload: Any,
        *,
        event_id: Optional[str] = None,
        timestamp_ms: Optional[int] = None,
        correlation_id: Optional[str] = None,
        schema_version: Optional[str] = None,
    ) -> None: ...
    @property
    def schema_version(self) -> str: ...
    @property
    def event_id(self) -> str: ...
    @property
    def sequence(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def correlation_id(self) -> Optional[str]: ...
    @property
    def event_type(self) -> str: ...
    @property
    def payload(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    @staticmethod
    def from_legacy(event: Any) -> EventEnvelope: ...

class PlanningEvent:
    def __init__(self, operation_id: str, target: str, scope_summary: str) -> None: ...
    @property
    def operation_id(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def scope_summary(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class PreflightEvent:
    def __init__(
        self,
        outcome: str,
        confirmations_required: list[str],
        suggested_flags: list[str],
    ) -> None: ...
    @property
    def outcome(self) -> str: ...
    @property
    def confirmations_required(self) -> list[str]: ...
    @property
    def suggested_flags(self) -> list[str]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class StageLifecycleEvent:
    def __init__(self, stage: str, status: str) -> None: ...
    @property
    def stage(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ProgressEvent:
    def __init__(
        self, percentage: float, message: str, items_processed: int, items_total: int
    ) -> None: ...
    @property
    def percentage(self) -> float: ...
    @property
    def message(self) -> str: ...
    @property
    def items_processed(self) -> int: ...
    @property
    def items_total(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class FindingEvent:
    def __init__(
        self, finding_id: str, severity: str, title: str, auto_added: bool
    ) -> None: ...
    @property
    def finding_id(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def auto_added(self) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ArtifactEvent:
    def __init__(
        self, artifact_name: str, kind: str, mime_type: str, size_bytes: int
    ) -> None: ...
    @property
    def artifact_name(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def mime_type(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class CancellationEvent:
    def __init__(self, reason: str, cancelled_by: str) -> None: ...
    @property
    def reason(self) -> str: ...
    @property
    def cancelled_by(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class FailureEvent:
    def __init__(self, error_type: str, error_message: str, is_retryable: bool) -> None: ...
    @property
    def error_type(self) -> str: ...
    @property
    def error_message(self) -> str: ...
    @property
    def is_retryable(self) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class CompletionEvent:
    def __init__(
        self, status: str, stats: Any, duration_ms: int
    ) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def stats(self) -> Any: ...
    @property
    def duration_ms(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

def wrap_event(
    event_type: str,
    payload: Any,
    *,
    correlation_id: Optional[str] = None,
    event_id: Optional[str] = None,
) -> EventEnvelope: ...
