from typing import Any, Dict, Optional

EVENT_SCHEMA_VERSION: str

class EventEnvelope:
    def __init__(
        self,
        event_type: str,
        payload: Any,
        *,
        event_id: Optional[str] = None,
        timestamp_ms: Optional[int] = None,
        correlation_id: Optional[str] = None,
        schema_version: Optional[str] = None,
    ) -> None: ...
    @property
    def schema_version(self) -> str: ...
    @property
    def event_id(self) -> str: ...
    @property
    def sequence(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def correlation_id(self) -> Optional[str]: ...
    @property
    def event_type(self) -> str: ...
    @property
    def payload(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    @staticmethod
    def from_legacy(event: Any) -> EventEnvelope: ...

class PlanningEvent:
    def __init__(self, operation_id: str, target: str, scope_summary: str) -> None: ...
    @property
    def operation_id(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def scope_summary(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class PreflightEvent:
    def __init__(
        self,
        outcome: str,
        confirmations_required: list[str],
        suggested_flags: list[str],
    ) -> None: ...
    @property
    def outcome(self) -> str: ...
    @property
    def confirmations_required(self) -> list[str]: ...
    @property
    def suggested_flags(self) -> list[str]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class StageLifecycleEvent:
    def __init__(self, stage: str, status: str) -> None: ...
    @property
    def stage(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ProgressEvent:
    def __init__(
        self, percentage: float, message: str, items_processed: int, items_total: int
    ) -> None: ...
    @property
    def percentage(self) -> float: ...
    @property
    def message(self) -> str: ...
    @property
    def items_processed(self) -> int: ...
    @property
    def items_total(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class FindingEvent:
    def __init__(
        self, finding_id: str, severity: str, title: str, auto_added: bool
    ) -> None: ...
    @property
    def finding_id(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def auto_added(self) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ArtifactEvent:
    def __init__(
        self, artifact_name: str, kind: str, mime_type: str, size_bytes: int
    ) -> None: ...
    @property
    def artifact_name(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def mime_type(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class CancellationEvent:
    def __init__(self, reason: str, cancelled_by: str) -> None: ...
    @property
    def reason(self) -> str: ...
    @property
    def cancelled_by(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class FailureEvent:
    def __init__(self, error_type: str, error_message: str, is_retryable: bool) -> None: ...
    @property
    def error_type(self) -> str: ...
    @property
    def error_message(self) -> str: ...
    @property
    def is_retryable(self) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class CompletionEvent:
    def __init__(
        self, status: str, stats: Any, duration_ms: int
    ) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def stats(self) -> Any: ...
    @property
    def duration_ms(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

def wrap_event(
    event_type: str,
    payload: Any,
    *,
    correlation_id: Optional[str] = None,
    event_id: Optional[str] = None,
) -> EventEnvelope: ...

# WS11: Network-specific events
class ResolutionEvent:
    def __init__(self, target: str, status: str, resolved_address: Optional[str] = None, resolution_time_ms: Optional[float] = None) -> None: ...
    @property
    def target(self) -> str: ...
    @property
    def resolved_address(self) -> Optional[str]: ...
    @property
    def status(self) -> str: ...
    @property
    def resolution_time_ms(self) -> Optional[float]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ConnectionEvent:
    def __init__(self, target: str, port: int, status: str, rtt_ms: Optional[float] = None) -> None: ...
    @property
    def target(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def status(self) -> str: ...
    @property
    def rtt_ms(self) -> Optional[float]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ProbeEvent:
    def __init__(self, probe_type: str, target: str, success: bool, rtt_ms: Optional[float] = None) -> None: ...
    @property
    def probe_type(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def rtt_ms(self) -> Optional[float]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class WebSocketMessageEvent:
    def __init__(self, url: str, direction: str, message_type: str, size: int) -> None: ...
    @property
    def url(self) -> str: ...
    @property
    def direction(self) -> str: ...
    @property
    def message_type(self) -> str: ...
    @property
    def size(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class CaptureStatsEvent:
    def __init__(self, interface: str, packets_captured: int, packets_dropped: int, bytes_captured: int, runtime_ms: int) -> None: ...
    @property
    def interface(self) -> str: ...
    @property
    def packets_captured(self) -> int: ...
    @property
    def packets_dropped(self) -> int: ...
    @property
    def bytes_captured(self) -> int: ...
    @property
    def runtime_ms(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class HandshakeCompletedEvent:
    @property
    def protocol(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def duration_ms(self) -> float: ...
    @property
    def negotiated_version(self) -> Optional[str]: ...
    @property
    def cipher_suite(self) -> Optional[str]: ...
    def __init__(self, protocol: str, host: str, port: int, duration_ms: float, negotiated_version: Optional[str] = None, cipher_suite: Optional[str] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RequestSentEvent:
    @property
    def method(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def headers_count(self) -> int: ...
    @property
    def body_size(self) -> Optional[int]: ...
    @property
    def request_index(self) -> int: ...
    def __init__(self, method: str, url: str, headers_count: int, request_index: int, body_size: Optional[int] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ResponseHeadersReceivedEvent:
    @property
    def status_code(self) -> int: ...
    @property
    def reason(self) -> str: ...
    @property
    def headers_count(self) -> int: ...
    @property
    def content_length(self) -> Optional[int]: ...
    @property
    def content_type(self) -> Optional[str]: ...
    @property
    def redirect_url(self) -> Optional[str]: ...
    @property
    def request_index(self) -> int: ...
    def __init__(self, status_code: int, reason: str, headers_count: int, request_index: int, content_length: Optional[int] = None, content_type: Optional[str] = None, redirect_url: Optional[str] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BodyProgressEvent:
    @property
    def bytes_received(self) -> int: ...
    @property
    def bytes_expected(self) -> Optional[int]: ...
    @property
    def percentage(self) -> Optional[float]: ...
    @property
    def is_complete(self) -> bool: ...
    def __init__(self, bytes_received: int, is_complete: bool, bytes_expected: Optional[int] = None, percentage: Optional[float] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CaptureStartedEvent:
    @property
    def interface(self) -> str: ...
    @property
    def filter(self) -> Optional[str]: ...
    @property
    def promiscuous(self) -> bool: ...
    @property
    def snapshot_len(self) -> int: ...
    def __init__(self, interface: str, promiscuous: bool, snapshot_len: int, filter: Optional[str] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PacketSampledEvent:
    @property
    def interface(self) -> str: ...
    @property
    def packet_index(self) -> int: ...
    @property
    def captured_len(self) -> int: ...
    @property
    def original_len(self) -> int: ...
    @property
    def protocol_hint(self) -> Optional[str]: ...
    def __init__(self, interface: str, packet_index: int, captured_len: int, original_len: int, protocol_hint: Optional[str] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FlowObservedEvent:
    @property
    def src_address(self) -> str: ...
    @property
    def src_port(self) -> int: ...
    @property
    def dst_address(self) -> str: ...
    @property
    def dst_port(self) -> int: ...
    @property
    def protocol(self) -> str: ...
    @property
    def packet_count(self) -> int: ...
    @property
    def byte_count(self) -> int: ...
    def __init__(self, src_address: str, src_port: int, dst_address: str, dst_port: int, protocol: str, packet_count: int, byte_count: int) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ArtifactCreatedEvent:
    @property
    def artifact_type(self) -> str: ...
    @property
    def path(self) -> Optional[str]: ...
    @property
    def size(self) -> int: ...
    @property
    def mime_type(self) -> Optional[str]: ...
    @property
    def description(self) -> str: ...
    def __init__(self, artifact_type: str, size: int, description: str, path: Optional[str] = None, mime_type: Optional[str] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
