from typing import Any, Optional

class EventStream:
    def __init__(self, event_log: Any = None) -> None: ...
    @staticmethod
    def empty() -> EventStream: ...
    def push(self, event: EventEnvelope) -> None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get(self, i: int) -> dict[str, Any]: ...
    def filter_by_type(self, event_type: str) -> EventStream: ...
    def filter_by_correlation(self, correlation_id: str) -> EventStream: ...
    def to_list(self) -> list[dict[str, Any]]: ...
    def to_dict_list(self) -> list[dict[str, Any]]: ...
    def latest(self) -> Optional[dict[str, Any]]: ...
    def count(self) -> int: ...
    def snapshot(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...

from .event_protocol import EventEnvelope

def event_stream_from_legacy(events: list[Any]) -> EventStream: ...
