from .operation_metadata import OperationDescriptorPy, OperationRiskPy

class ExecutionSurfacePy:
    CLI_MANUAL: ExecutionSurfacePy
    TUI_MANUAL: ExecutionSurfacePy
    CLI_MANUAL_STRICT: ExecutionSurfacePy
    TUI_MANUAL_STRICT: ExecutionSurfacePy
    MCP_SERVER: ExecutionSurfacePy
    SECURITY_AGENT: ExecutionSurfacePy
    CI: ExecutionSurfacePy
    REST_API: ExecutionSurfacePy
    GRPC_API: ExecutionSurfacePy
    @property
    def name(self) -> str: ...
    @property
    def label(self) -> str: ...
    @property
    def is_manual(self) -> bool: ...
    @property
    def is_agent_controlled(self) -> bool: ...

class ExecutionProfilePy:
    manual_permissive: ExecutionProfilePy
    manual_guarded: ExecutionProfilePy
    ci_strict: ExecutionProfilePy
    mcp_strict: ExecutionProfilePy
    agent_strict: ExecutionProfilePy
    @property
    def name(self) -> str: ...
    @property
    def is_strict(self) -> bool: ...
    @property
    def is_automated(self) -> bool: ...

class PolicyDecisionPy:
    @property
    def operation_id(self) -> str: ...
    @property
    def allowed(self) -> bool: ...
    @property
    def denied(self) -> bool: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def requires_confirmation(self) -> bool: ...
    @property
    def confirmation_classes(self) -> list[str]: ...
    @property
    def scope_match(self) -> str | None: ...
    @property
    def risk_assessment(self) -> str | None: ...

class EnforcementOutcomePy:
    @property
    def outcome_type(self) -> str: ...
    @property
    def decision(self) -> PolicyDecisionPy: ...
    @property
    def confirmation_classes(self) -> list[str]: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def is_allowed(self) -> bool: ...
    @property
    def is_denied(self) -> bool: ...
    @property
    def requires_confirmation(self) -> bool: ...

class ApprovedOperationPy:
    @property
    def operation_id(self) -> str: ...
    @property
    def target(self) -> str | None: ...
    @property
    def risk(self) -> str: ...
    @property
    def mode(self) -> str: ...
    @property
    def surface(self) -> str: ...
    @property
    def policy_hash(self) -> str: ...
    @property
    def audit_event_id(self) -> str: ...

class EnforcementContextPy:
    @staticmethod
    def manual_permissive(policy: object, scope: object) -> EnforcementContextPy: ...
    @staticmethod
    def manual_guarded(policy: object, scope: object) -> EnforcementContextPy: ...
    @staticmethod
    def ci_strict(policy: object, scope: object) -> EnforcementContextPy: ...
    @staticmethod
    def mcp_strict(policy: object, scope: object) -> EnforcementContextPy: ...
    @staticmethod
    def agent_strict(policy: object, scope: object) -> EnforcementContextPy: ...
    @staticmethod
    def for_surface(surface: ExecutionSurfacePy, policy: object, scope: object) -> EnforcementContextPy: ...
    def evaluate(self, descriptor: OperationDescriptorPy) -> EnforcementOutcomePy: ...
    def approve(self, surface: ExecutionSurfacePy, descriptor: OperationDescriptorPy) -> ApprovedOperationPy: ...
    def approve_manual(self, surface: ExecutionSurfacePy, descriptor: OperationDescriptorPy, override: object | None = None) -> ApprovedOperationPy: ...
    def policy_hash(self) -> str: ...
