from typing import Any, Dict, List, Optional, Union

class Severity:
    Critical: Severity
    High: Severity
    Medium: Severity
    Low: Severity
    Info: Severity
    @staticmethod
    def from_str(s: str) -> Severity: ...

class Evidence:
    def __init__(self, kind: str, value: str, source: str, *, confidence: float = 1.0, metadata: Optional[Dict[str, Any]] = None) -> None: ...
    @property
    def kind(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def confidence(self) -> float: ...
    @property
    def metadata(self) -> Optional[Dict[str, Any]]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class Finding:
    def __init__(self, id: str, title: str, severity: Severity, target: str, category: str, description: str, *, recommendation: Optional[str] = None, evidence: Optional[Evidence] = None, metadata: Optional[Dict[str, Any]] = None) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def target(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def recommendation(self) -> Optional[str]: ...
    @property
    def evidence(self) -> Optional[Evidence]: ...
    @property
    def metadata(self) -> Optional[Dict[str, Any]]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def to_row(self) -> Dict[str, Any]: ...

class FindingSet:
    def add_finding(self, finding: Finding) -> None: ...
    def by_severity(self, severity: Severity) -> list[Finding]: ...
    @property
    def findings(self) -> list[Finding]: ...
    def to_dicts(self) -> List[Dict[str, Any]]: ...
    def to_rows(self) -> List[Dict[str, Any]]: ...

class Report:
    def __init__(self, *, metadata: Optional[Dict[str, Any]] = None) -> None: ...
    def add_finding(self, finding: Finding) -> None: ...
    def add_finding_set(self, finding_set: FindingSet) -> None: ...
    def add_result(self, result: Union[Any, Any, Any, Any]) -> None: ...
    @property
    def findings(self) -> list[Finding]: ...
    @property
    def metadata(self) -> Optional[Dict[str, Any]]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def to_rows(self) -> List[Dict[str, Any]]: ...
    def write_json(self, path: str) -> None: ...
    def write_markdown(self, path: str) -> None: ...
