from typing import Any, Dict, List, Optional

class FindingState:
    New: FindingState
    Triaged: FindingState
    Confirmed: FindingState
    InProgress: FindingState
    AcceptedRisk: FindingState
    FalsePositive: FindingState
    Remediated: FindingState
    Reopened: FindingState
    @staticmethod
    def from_str(s: str) -> FindingState: ...
    def as_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class WorkflowTransition:
    def __init__(self, from_state: FindingState, to_state: FindingState, changed_at: str, *, changed_by: Optional[str] = None, note: Optional[str] = None) -> None: ...
    @property
    def from_state(self) -> FindingState: ...
    @property
    def to_state(self) -> FindingState: ...
    @property
    def changed_at(self) -> str: ...
    @property
    def changed_by(self) -> Optional[str]: ...
    @property
    def note(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class Suppression:
    def __init__(self, finding_id: str, reason: str, suppressed_at: str, *, suppressed_by: Optional[str] = None, expires_at: Optional[str] = None) -> None: ...
    @property
    def finding_id(self) -> str: ...
    @property
    def reason(self) -> str: ...
    @property
    def suppressed_by(self) -> Optional[str]: ...
    @property
    def suppressed_at(self) -> str: ...
    @property
    def expires_at(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class FindingWorkflow:
    def __init__(self) -> None: ...
    def register_finding(self, finding_id: str) -> None: ...
    def get_state(self, finding_id: str) -> FindingState: ...
    def transition(self, finding_id: str, to_state: FindingState, *, changed_by: Optional[str] = None, note: Optional[str] = None) -> WorkflowTransition: ...
    def can_transition(self, finding_id: str, to_state: FindingState) -> bool: ...
    def valid_transitions(self, finding_id: str) -> List[FindingState]: ...
    def suppress(self, finding_id: str, reason: str, *, suppressed_by: Optional[str] = None, expires_at: Optional[str] = None) -> Suppression: ...
    def is_suppressed(self, finding_id: str) -> bool: ...
    def unsuppress(self, finding_id: str) -> None: ...
    def get_history(self, finding_id: str) -> List[WorkflowTransition]: ...
