from typing import Any, Dict, List, Optional

FINDING_SCHEMA_VERSION: str

class Confidence:
    Confirmed: Confidence
    High: Confidence
    Medium: Confidence
    Low: Confidence
    Informational: Confidence
    @staticmethod
    def from_str(s: str) -> Confidence: ...
    def score(self) -> float: ...
    def as_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FindingType:
    Vulnerability: FindingType
    Misconfiguration: FindingType
    InformationLeak: FindingType
    PolicyViolation: FindingType
    AssetDiscovery: FindingType
    ServiceDetection: FindingType
    WafDetection: FindingType
    FuzzResult: FindingType
    ScanResult: FindingType
    @staticmethod
    def from_str(s: str) -> FindingType: ...
    def as_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class EvidenceKind:
    HttpRequest: EvidenceKind
    HttpResponse: EvidenceKind
    Header: EvidenceKind
    BodySnippet: EvidenceKind
    Timing: EvidenceKind
    Diff: EvidenceKind
    Banner: EvidenceKind
    DnsRecord: EvidenceKind
    Certificate: EvidenceKind
    PortState: EvidenceKind
    Screenshot: EvidenceKind
    FilePath: EvidenceKind
    LogLine: EvidenceKind
    @staticmethod
    def from_str(s: str) -> EvidenceKind: ...
    def as_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class AffectedAsset:
    def __init__(self, asset_type: str, identifier: str, *, host: Optional[str] = None, port: Optional[int] = None, protocol: Optional[str] = None) -> None: ...
    @property
    def asset_type(self) -> str: ...
    @property
    def identifier(self) -> str: ...
    @property
    def host(self) -> Optional[str]: ...
    @property
    def port(self) -> Optional[int]: ...
    @property
    def protocol(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class FindingLocation:
    def __init__(self, *, url: Optional[str] = None, path: Optional[str] = None, parameter: Optional[str] = None, header: Optional[str] = None, method: Optional[str] = None, line: Optional[int] = None, file: Optional[str] = None) -> None: ...
    @property
    def url(self) -> Optional[str]: ...
    @property
    def path(self) -> Optional[str]: ...
    @property
    def parameter(self) -> Optional[str]: ...
    @property
    def header(self) -> Optional[str]: ...
    @property
    def method(self) -> Optional[str]: ...
    @property
    def line(self) -> Optional[int]: ...
    @property
    def file(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class VersionedEvidence:
    def __init__(self, kind: EvidenceKind, summary: str, *, data: Optional[str] = None, redacted: bool = False) -> None: ...
    @property
    def kind(self) -> EvidenceKind: ...
    @property
    def redacted(self) -> bool: ...
    @property
    def summary(self) -> str: ...
    @property
    def data(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class VersionedFinding:
    def __init__(self, id: str, title: str, description: str, severity: str, finding_type: FindingType, affected_asset: AffectedAsset, source_tool: str, source_module: str, *, fingerprint: Optional[str] = None, confidence: Optional[Confidence] = None, cwe: Optional[str] = None, owasp: Optional[str] = None, cve: Optional[str] = None, location: Optional[FindingLocation] = None, evidence: Optional[List[VersionedEvidence]] = None, remediation: Optional[str] = None, tags: Optional[List[str]] = None, discovered_at: Optional[str] = None, metadata: Optional[str] = None) -> None: ...
    @property
    def schema_version(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def confidence(self) -> Confidence: ...
    @property
    def finding_type(self) -> FindingType: ...
    @property
    def cwe(self) -> Optional[str]: ...
    @property
    def owasp(self) -> Optional[str]: ...
    @property
    def cve(self) -> Optional[str]: ...
    @property
    def affected_asset(self) -> AffectedAsset: ...
    @property
    def location(self) -> FindingLocation: ...
    @property
    def evidence(self) -> List[VersionedEvidence]: ...
    @property
    def remediation(self) -> Optional[str]: ...
    @property
    def tags(self) -> List[str]: ...
    @property
    def discovered_at(self) -> str: ...
    @property
    def source_tool(self) -> str: ...
    @property
    def source_module(self) -> str: ...
    @property
    def metadata(self) -> str: ...
    def compute_fingerprint(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def schema_version() -> str: ...
