from typing import Any, Dict, List, Optional

class FingerprintEvidence:
    @property
    def probe(self) -> str: ...
    @property
    def pattern(self) -> str: ...
    @property
    def matched(self) -> bool: ...

class FingerprintConfidence:
    @property
    def score(self) -> int: ...
    @property
    def level(self) -> str: ...

class ServiceFingerprintResult:
    @property
    def port(self) -> int: ...
    @property
    def service(self) -> str: ...
    @property
    def banner(self) -> Optional[str]: ...
    @property
    def version(self) -> Optional[str]: ...
    @property
    def product(self) -> Optional[str]: ...
    @property
    def extra(self) -> Optional[str]: ...
    @property
    def confidence(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class FingerprintScanResult:
    @property
    def services(self) -> list[ServiceFingerprintResult]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def to_rows(self) -> List[Dict[str, Any]]: ...
