from typing import Any, Dict, List, Optional, Union
from .scope import Scope
from . import dto, endpoint, fingerprint, recon, waf

def features() -> Dict[str, bool]: ...
def has_feature(name: str) -> bool: ...
def feature_matrix() -> Dict[str, Dict[str, Any]]: ...
def build_info() -> Dict[str, Any]: ...
def api_surface_version() -> Dict[str, Any]: ...
def domain_maturity() -> Dict[str, Dict[str, str]]: ...
def scan_ports(target: str, ports: list[int], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> dto.PortScanResult: ...
def async_scan_ports(target: str, ports: list[int], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> Any: ...
def scan_endpoints(base_url: str, endpoints: list[str], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None, include_404: bool = False, verify_tls: bool = True) -> endpoint.EndpointScanResult: ...
def async_scan_endpoints(base_url: str, endpoints: list[str], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None, include_404: bool = False, verify_tls: bool = True) -> Any: ...
def fingerprint_services(target: str, ports: list[int], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> fingerprint.FingerprintScanResult: ...
def async_fingerprint_services(target: str, ports: list[int], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> Any: ...
def recon_dns(domain: str) -> recon.DnsRecordSet: ...
def async_recon_dns(domain: str) -> Any: ...
def inspect_tls(host: str, *, port: int = 443) -> recon.TlsInspectionResult: ...
def async_inspect_tls(host: str, *, port: int = 443) -> Any: ...
def detect_technology(url: str) -> recon.TechDetectionResult: ...
def async_detect_technology(url: str) -> Any: ...
def detect_waf(url: str) -> waf.WafDetectionResult: ...
def async_detect_waf(url: str) -> Any: ...
def validate_waf(url: str, scope: Scope, *, bypass: bool = False, test_type: Optional[str] = None) -> Any: ...
def async_validate_waf(url: str, scope: Scope, *, bypass: bool = False, test_type: Optional[str] = None) -> Any: ...
def fuzz_http(url: str, scope: Scope, payload_type: str = "all", *, method: str = "GET", param: Optional[str] = None, concurrency: int = 10, timeout: int = 30) -> Any: ...
def async_fuzz_http(url: str, scope: Scope, payload_type: str = "all", *, method: str = "GET", param: Optional[str] = None, concurrency: int = 10, timeout: int = 30) -> Any: ...
def generate_fuzz_payloads(payload_types: Optional[list[str]] = None) -> list[Any]: ...
def load_test_http(url: str, total_requests: int, concurrency: int, timeout_secs: int, scope: Scope, *, method: str = "GET") -> Any: ...
def async_load_test_http(url: str, total_requests: int, concurrency: int, timeout_secs: int, scope: Scope, *, method: str = "GET") -> Any: ...
