from typing import Any, Dict, List, Optional, Union
from .scope import Scope
from . import dto, endpoint, fingerprint, recon, waf

def features() -> Dict[str, bool]: ...
def has_feature(name: str) -> bool: ...
def build_info() -> Dict[str, Any]: ...
def scan_ports(target: str, ports: list[int], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> dto.PortScanResult: ...
def async_scan_ports(target: str, ports: list[int], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> Any: ...
def scan_endpoints(base_url: str, endpoints: list[str], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None, include_404: bool = False, verify_tls: bool = True) -> endpoint.EndpointScanResult: ...
def async_scan_endpoints(base_url: str, endpoints: list[str], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None, include_404: bool = False, verify_tls: bool = True) -> Any: ...
def fingerprint_services(target: str, ports: list[int], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> fingerprint.FingerprintScanResult: ...
def async_fingerprint_services(target: str, ports: list[int], scope: Scope, *, concurrency: Optional[int] = None, timeout_ms: Optional[int] = None) -> Any: ...
def recon_dns(domain: str) -> recon.DnsRecordSet: ...
def async_recon_dns(domain: str) -> Any: ...
def inspect_tls(host: str, *, port: int = 443) -> recon.TlsInspectionResult: ...
def async_inspect_tls(host: str, *, port: int = 443) -> Any: ...
def detect_technology(url: str) -> recon.TechDetectionResult: ...
def async_detect_technology(url: str) -> Any: ...
def detect_waf(url: str) -> waf.WafDetectionResult: ...
def async_detect_waf(url: str) -> Any: ...
