from typing import Any, Dict, List, Optional

class Confidence:
    HIGH: "Confidence"
    MEDIUM: "Confidence"
    LOW: "Confidence"
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class SecretType:
    AWS_ACCESS_KEY: "SecretType"
    AWS_SECRET_KEY: "SecretType"
    AWS_SESSION_TOKEN: "SecretType"
    AZURE_KEY: "SecretType"
    GCP_API_KEY: "SecretType"
    GCP_SERVICE_ACCOUNT: "SecretType"
    GITHUB_TOKEN: "SecretType"
    GITLAB_TOKEN: "SecretType"
    BITBUCKET_TOKEN: "SecretType"
    SLACK_TOKEN: "SecretType"
    DISCORD_TOKEN: "SecretType"
    SLACK_WEBHOOK: "SecretType"
    GENERIC_API_KEY: "SecretType"
    PRIVATE_KEY: "SecretType"
    JWT_TOKEN: "SecretType"
    BASIC_AUTH: "SecretType"
    BEARER_TOKEN: "SecretType"
    OPENAI_KEY: "SecretType"
    STRIPE_KEY: "SecretType"
    TWILIO_KEY: "SecretType"
    SENDGRID_KEY: "SecretType"
    MAILCHIMP_KEY: "SecretType"
    PASSWORD_IN_URL: "SecretType"
    DATABASE_CONNECTION_STRING: "SecretType"
    NPM_TOKEN: "SecretType"
    PYPI_TOKEN: "SecretType"
    HEROKU_KEY: "SecretType"
    NETLIFY_TOKEN: "SecretType"
    DOCKERHUB_TOKEN: "SecretType"
    KUBERNETES_SECRET: "SecretType"
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class SecretFindingPy:
    @property
    def secret_type(self) -> SecretType: ...
    @property
    def value_preview(self) -> str: ...
    @property
    def location(self) -> str: ...
    @property
    def confidence(self) -> Confidence: ...
    @property
    def severity(self) -> str: ...
    @property
    def description(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class GitSecretFindingPy:
    @property
    def commit_hash(self) -> str: ...
    @property
    def commit_message(self) -> str: ...
    @property
    def author(self) -> str: ...
    @property
    def date(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    @property
    def secret_type(self) -> SecretType: ...
    @property
    def secret_preview(self) -> str: ...
    @property
    def confidence(self) -> Confidence: ...
    @property
    def severity(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def introduced_in(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class GitSecretsSummaryPy:
    @property
    def critical(self) -> int: ...
    @property
    def high(self) -> int: ...
    @property
    def medium(self) -> int: ...
    @property
    def low(self) -> int: ...
    @property
    def info(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class GitSecretsReportPy:
    @property
    def repo_path(self) -> str: ...
    @property
    def commits_scanned(self) -> int: ...
    @property
    def files_scanned(self) -> int: ...
    @property
    def findings(self) -> List[GitSecretFindingPy]: ...
    @property
    def summary(self) -> GitSecretsSummaryPy: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def scan_git_secrets(repo_path: str, max_commits: int = 100) -> GitSecretsReportPy: ...
def async_scan_git_secrets(repo_path: str, max_commits: int = 100) -> Any: ...
