from typing import Any, Optional
from .status import ExecutionStatus, OperationResult

class ExecutionHandle:
    def __init__(
        self,
        handle_id: str,
        status: Optional[ExecutionStatus] = None,
        result: Optional[OperationResult] = None,
    ) -> None: ...
    @property
    def handle_id(self) -> str: ...
    @property
    def status(self) -> ExecutionStatus: ...
    def is_complete(self) -> bool: ...
    def is_running(self) -> bool: ...
    @property
    def result(self) -> Optional[OperationResult]: ...
    def await_result(self) -> OperationResult: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ExecutionEvent:
    def __init__(
        self,
        handle_id: str,
        event_type: str,
        timestamp_ms: int,
        *,
        detail: Optional[str] = None,
    ) -> None: ...
    @property
    def handle_id(self) -> str: ...
    @property
    def event_type(self) -> str: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def detail(self) -> Optional[str]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class EventLog:
    def __init__(self) -> None: ...
    def push(self, event: ExecutionEvent) -> None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get(self, i: int) -> ExecutionEvent: ...
    def to_list(self) -> list[dict[str, Any]]: ...
    def filter_by_type(self, event_type: str) -> list[ExecutionEvent]: ...
    def to_versioned_list(self) -> list[dict[str, Any]]: ...
    def schema_version(self) -> str: ...
    def drain(self) -> list[dict[str, Any]]: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
