from typing import Any, Dict, List, Optional, Tuple

class RedactConfigPy:
    @property
    def redact_headers(self) -> List[str]: ...
    @property
    def redact_query_params(self) -> List[str]: ...
    @property
    def redact_body_fields(self) -> List[str]: ...
    def __init__(self, redact_headers: Optional[List[str]] = None, redact_query_params: Optional[List[str]] = None, redact_body_fields: Optional[List[str]] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HttpRequestPy:
    @property
    def method(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def headers(self) -> List[Tuple[str, str]]: ...
    @property
    def query_params(self) -> List[Tuple[str, str]]: ...
    @property
    def body_bytes(self) -> Optional[bytes]: ...
    @property
    def body_text(self) -> Optional[str]: ...
    @property
    def body_json(self) -> Optional[str]: ...
    @property
    def body_form(self) -> Optional[List[Tuple[str, str]]]: ...
    @property
    def cookies(self) -> List[Tuple[str, str]]: ...
    @property
    def follow_redirects(self) -> bool: ...
    @property
    def max_redirects(self) -> int: ...
    @property
    def verify_tls(self) -> bool: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def connect_timeout_ms(self) -> int: ...
    @property
    def user_agent(self) -> Optional[str]: ...
    @property
    def proxy_url(self) -> Optional[str]: ...
    @property
    def response_size_limit(self) -> Optional[int]: ...
    def __init__(self, method: str, url: str, *, headers: Optional[List[Tuple[str, str]]] = None, query_params: Optional[List[Tuple[str, str]]] = None, body_bytes: Optional[bytes] = None, body_text: Optional[str] = None, body_json: Optional[str] = None, body_form: Optional[List[Tuple[str, str]]] = None, cookies: Optional[List[Tuple[str, str]]] = None, follow_redirects: bool = True, max_redirects: int = 10, verify_tls: bool = True, timeout_ms: int = 30000, connect_timeout_ms: int = 5000, user_agent: Optional[str] = None, proxy_url: Optional[str] = None, response_size_limit: Optional[int] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HttpHeadersPy:
    @property
    def entries(self) -> List[Tuple[str, str]]: ...
    def __init__(self, entries: Optional[List[Tuple[str, str]]] = None) -> None: ...
    def get(self, name: str) -> Optional[str]: ...
    def get_all(self, name: str) -> List[str]: ...
    def contains(self, name: str) -> bool: ...
    def names(self) -> List[str]: ...
    def len(self) -> int: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HttpCookiePy:
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def domain(self) -> Optional[str]: ...
    @property
    def path(self) -> Optional[str]: ...
    @property
    def expires(self) -> Optional[str]: ...
    @property
    def secure(self) -> bool: ...
    @property
    def http_only(self) -> bool: ...
    def __init__(self, name: str, value: str, *, domain: Optional[str] = None, path: Optional[str] = None, expires: Optional[str] = None, secure: bool = False, http_only: bool = False) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RedirectEntryPy:
    @property
    def url(self) -> str: ...
    @property
    def status_code(self) -> int: ...
    @property
    def headers(self) -> List[Tuple[str, str]]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TlsMetadataPy:
    @property
    def version(self) -> Optional[str]: ...
    @property
    def cipher(self) -> Optional[str]: ...
    @property
    def certificate_chain(self) -> List[str]: ...
    def __init__(self, version: Optional[str] = None, cipher: Optional[str] = None, certificate_chain: Optional[List[str]] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HttpTimingPy:
    @property
    def dns_ms(self) -> Optional[float]: ...
    @property
    def connect_ms(self) -> Optional[float]: ...
    @property
    def tls_handshake_ms(self) -> Optional[float]: ...
    @property
    def first_byte_ms(self) -> Optional[float]: ...
    @property
    def total_ms(self) -> float: ...
    @property
    def size_download(self) -> int: ...
    @property
    def speed_download(self) -> float: ...
    def __init__(self, dns_ms: Optional[float] = None, connect_ms: Optional[float] = None, tls_handshake_ms: Optional[float] = None, first_byte_ms: Optional[float] = None, total_ms: float = 0.0, size_download: int = 0, speed_download: float = 0.0) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HttpResponsePy:
    @property
    def status_code(self) -> int: ...
    @property
    def reason(self) -> Optional[str]: ...
    @property
    def body_text(self) -> Optional[str]: ...
    @property
    def content_length(self) -> Optional[int]: ...
    @property
    def final_url(self) -> str: ...
    @property
    def protocol_version(self) -> Optional[str]: ...
    @property
    def timing(self) -> HttpTimingPy: ...
    @property
    def bytes_received(self) -> int: ...
    @property
    def headers(self) -> HttpHeadersPy: ...
    @property
    def cookies(self) -> List[HttpCookiePy]: ...
    @property
    def body_bytes(self) -> bytes: ...
    @property
    def redirect_history(self) -> List[RedirectEntryPy]: ...
    @property
    def tls_metadata(self) -> Optional[TlsMetadataPy]: ...
    def redacted_headers(self) -> List[Tuple[str, str]]: ...
    def iter_body_chunks(self, chunk_size: Optional[int] = None) -> List[bytes]: ...
    def body_bytes_limited(self, max_bytes: int) -> Tuple[bytes, bool]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HttpClientConfigPy:
    @property
    def base_url(self) -> Optional[str]: ...
    @property
    def default_headers(self) -> List[Tuple[str, str]]: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def connect_timeout_ms(self) -> int: ...
    @property
    def max_redirects(self) -> int: ...
    @property
    def verify_tls(self) -> bool: ...
    @property
    def proxy_url(self) -> Optional[str]: ...
    @property
    def user_agent(self) -> Optional[str]: ...
    @property
    def cookie_store(self) -> bool: ...
    @property
    def pool_idle_timeout_ms(self) -> int: ...
    @property
    def pool_max_idle_per_host(self) -> int: ...
    def __init__(self, *, base_url: Optional[str] = None, default_headers: Optional[List[Tuple[str, str]]] = None, timeout_ms: int = 30000, connect_timeout_ms: int = 5000, max_redirects: int = 10, verify_tls: bool = True, proxy_url: Optional[str] = None, user_agent: Optional[str] = None, cookie_store: bool = True, pool_idle_timeout_ms: int = 90000, pool_max_idle_per_host: int = 10) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HttpClientPy:
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, config: HttpClientConfigPy) -> None: ...
    def request(self, req: HttpRequestPy) -> HttpResponsePy: ...
    def get(self, url: str, *, headers: Optional[List[Tuple[str, str]]] = None) -> HttpResponsePy: ...
    def post(self, url: str, body: Optional[str] = None, *, headers: Optional[List[Tuple[str, str]]] = None, content_type: Optional[str] = None) -> HttpResponsePy: ...
    def put(self, url: str, body: Optional[str] = None, *, headers: Optional[List[Tuple[str, str]]] = None, content_type: Optional[str] = None) -> HttpResponsePy: ...
    def delete(self, url: str, *, headers: Optional[List[Tuple[str, str]]] = None) -> HttpResponsePy: ...
    def close(self) -> None: ...
    def __enter__(self) -> HttpClientPy: ...
    def __exit__(self, *args: Any) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class AsyncHttpClientPy:
    @property
    def is_closed(self) -> bool: ...
    def __init__(self, config: HttpClientConfigPy) -> None: ...
    def async_request(self, req: HttpRequestPy) -> Any: ...
    def async_get(self, url: str, *, headers: Optional[List[Tuple[str, str]]] = None) -> Any: ...
    def async_post(self, url: str, body: Optional[str] = None, *, headers: Optional[List[Tuple[str, str]]] = None, content_type: Optional[str] = None) -> Any: ...
    def async_put(self, url: str, body: Optional[str] = None, *, headers: Optional[List[Tuple[str, str]]] = None, content_type: Optional[str] = None) -> Any: ...
    def async_delete(self, url: str, *, headers: Optional[List[Tuple[str, str]]] = None) -> Any: ...
    def close(self) -> None: ...
    def __aenter__(self) -> AsyncHttpClientPy: ...
    def __aexit__(self, *args: Any) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def create_http_client(config: HttpClientConfigPy) -> HttpClientPy: ...
def async_create_http_client(config: HttpClientConfigPy) -> AsyncHttpClientPy: ...
