from typing import Any, Dict, List, Optional
from .finding_schema import VersionedFinding

class IntegrationType:
    GitHub: IntegrationType
    GitLab: IntegrationType
    Jira: IntegrationType
    Webhook: IntegrationType
    Custom: IntegrationType
    @staticmethod
    def from_str(s: str) -> IntegrationType: ...
    def as_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PublicationRecord:
    @property
    def id(self) -> str: ...
    @property
    def integration_type(self) -> IntegrationType: ...
    @property
    def finding_id(self) -> str: ...
    @property
    def external_id(self) -> Optional[str]: ...
    @property
    def action(self) -> str: ...
    @property
    def published_at(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def dry_run(self) -> bool: ...
    @property
    def dedup_key(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class RetryPolicy:
    def __init__(self, *, max_retries: int = 3, base_delay_ms: int = 1000, max_delay_ms: int = 30000, backoff_multiplier: float = 2.0) -> None: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def base_delay_ms(self) -> int: ...
    @property
    def max_delay_ms(self) -> int: ...
    @property
    def backoff_multiplier(self) -> float: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class PublicationPolicy:
    def __init__(self, *, dry_run: bool = True, include_evidence: bool = False, include_artifacts: bool = False, redact_sensitive: bool = True, min_severity: str = "Medium", allowed_finding_types: Optional[List[str]] = None, blocked_tags: Optional[List[str]] = None) -> None: ...
    @property
    def dry_run(self) -> bool: ...
    @property
    def include_evidence(self) -> bool: ...
    @property
    def include_artifacts(self) -> bool: ...
    @property
    def redact_sensitive(self) -> bool: ...
    @property
    def min_severity(self) -> str: ...
    @property
    def allowed_finding_types(self) -> List[str]: ...
    @property
    def blocked_tags(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ExternalIntegration:
    def __init__(self, integration_type: IntegrationType, name: str, config: Dict[str, str], *, policy: Optional[PublicationPolicy] = None, retry_policy: Optional[RetryPolicy] = None) -> None: ...
    @property
    def integration_type(self) -> IntegrationType: ...
    @property
    def name(self) -> str: ...
    def is_dry_run(self) -> bool: ...
    def publish_finding(self, finding: VersionedFinding) -> PublicationRecord: ...
    def publish_findings(self, findings: List[VersionedFinding]) -> List[PublicationRecord]: ...
    def publication_records(self) -> List[PublicationRecord]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
