from typing import Any, Dict, List, Optional

class JsonlFindingRepository:
    def __init__(self, path: str) -> None: ...
    @property
    def path(self) -> str: ...
    def initialize(self) -> None: ...
    def insert_finding(self, finding_json: str) -> str: ...
    def get_finding(self, finding_id: str) -> Optional[str]: ...
    def update_finding(self, finding_id: str, finding_json: str) -> bool: ...
    def delete_finding(self, finding_id: str) -> bool: ...
    def query_findings(
        self,
        *,
        assessment_id: Optional[str] = None,
        severity: Optional[str] = None,
        state: Optional[str] = None,
        finding_type: Optional[str] = None,
        limit: int = 100,
        offset: int = 0,
    ) -> List[str]: ...
    def count_findings(
        self,
        *,
        assessment_id: Optional[str] = None,
        severity: Optional[str] = None,
    ) -> int: ...
    def deduplicate(self, dedup_key: str) -> Optional[str]: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> JsonlFindingRepository: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class JsonlAssessmentRepository:
    def __init__(self, path: str) -> None: ...
    @property
    def path(self) -> str: ...
    def initialize(self) -> None: ...
    def create_assessment(self, name: str, target: str, assessment_type: str) -> str: ...
    def get_assessment(self, assessment_id: str) -> Optional[str]: ...
    def update_assessment_state(self, assessment_id: str, state: str) -> bool: ...
    def attach_finding(self, assessment_id: str, finding_id: str) -> bool: ...
    def attach_artifact(self, assessment_id: str, artifact_json: str) -> bool: ...
    def list_assessments(self, limit: int = 100, offset: int = 0) -> List[str]: ...
    def delete_assessment(self, assessment_id: str) -> bool: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> JsonlAssessmentRepository: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
