"""HTTP load testing type stubs."""

from typing import Any, Dict, List, Optional, Tuple

class LoadTestResultPy:
    @property
    def target_url(self) -> str: ...
    @property
    def total_requests(self) -> int: ...
    @property
    def successful_requests(self) -> int: ...
    @property
    def failed_requests(self) -> int: ...
    @property
    def total_duration_ms(self) -> int: ...
    @property
    def requests_per_second(self) -> float: ...
    @property
    def latency_min_ms(self) -> float: ...
    @property
    def latency_max_ms(self) -> float: ...
    @property
    def latency_mean_ms(self) -> float: ...
    @property
    def latency_p50_ms(self) -> float: ...
    @property
    def latency_p90_ms(self) -> float: ...
    @property
    def latency_p95_ms(self) -> float: ...
    @property
    def latency_p99_ms(self) -> float: ...
    @property
    def status_codes(self) -> Dict[int, int]: ...
    @property
    def errors(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

LoadTestResult = LoadTestResultPy

class LoadTestConfig:
    def __init__(
        self,
        url: str,
        total_requests: int = 100,
        concurrency: int = 10,
        timeout_secs: int = 30,
        method: str = "GET",
        body: Optional[str] = None,
        headers: Optional[List[Tuple[str, str]]] = None,
    ) -> None: ...
    @property
    def url(self) -> str: ...
    @property
    def total_requests(self) -> int: ...
    @property
    def concurrency(self) -> int: ...
    @property
    def timeout_secs(self) -> int: ...
    @property
    def method(self) -> str: ...
    @property
    def body(self) -> Optional[str]: ...
    @property
    def headers(self) -> List[Tuple[str, str]]: ...
