from typing import Any, Dict, List, Optional
from .finding_schema import VersionedFinding

class SchemaVersion:
    def __init__(self, version: str, description: str, compatible_with: List[str]) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def created_at(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def compatible_with(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class MigrationResult:
    @property
    def success(self) -> bool: ...
    @property
    def source_version(self) -> str: ...
    @property
    def target_version(self) -> str: ...
    @property
    def items_migrated(self) -> int: ...
    @property
    def warnings(self) -> List[str]: ...
    @property
    def errors(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class FindingMigration:
    def __init__(self) -> None: ...
    def migrate_legacy_finding(self, id: str, title: str, severity: str, target: str, category: str, description: str, *, recommendation: Optional[str] = None, evidence: Optional[str] = None, metadata: Optional[Dict[str, str]] = None) -> VersionedFinding: ...
    def migrate_engine_finding(self, finding_json: str) -> VersionedFinding: ...
    def migrate_batch(self, legacy_findings: List[Dict[str, Any]]) -> MigrationResult: ...
    def needs_migration(self, finding_json: str) -> bool: ...
    def supported_versions(self) -> List[str]: ...
    def target_version(self) -> str: ...
