from typing import Any, Dict, List, Optional

from .finding import Severity

class MobilePlatformPy:
    ANDROID: "MobilePlatformPy"
    IOS: "MobilePlatformPy"
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MobileFindingPy:
    @property
    def category(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def recommendation(self) -> str: ...
    @property
    def evidence(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MobileScanReportPy:
    @property
    def target(self) -> str: ...
    @property
    def scan_type(self) -> str: ...
    @property
    def platform(self) -> MobilePlatformPy: ...
    @property
    def app_id(self) -> Optional[str]: ...
    @property
    def version(self) -> Optional[str]: ...
    @property
    def timestamp(self) -> str: ...
    @property
    def findings(self) -> List[MobileFindingPy]: ...
    @property
    def recommendations(self) -> List[str]: ...
    @property
    def duration_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def analyze_apk(path: str) -> MobileScanReportPy: ...
def async_analyze_apk(path: str) -> Any: ...
def analyze_ipa(path: str) -> MobileScanReportPy: ...
def async_analyze_ipa(path: str) -> Any: ...
