from typing import Any, Dict, List, Optional

from .finding import Severity

class MobilePlatformPy:
    ANDROID: "MobilePlatformPy"
    IOS: "MobilePlatformPy"
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class MobileFindingPy:
    @property
    def category(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def recommendation(self) -> str: ...
    @property
    def evidence(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MobileScanReportPy:
    @property
    def target(self) -> str: ...
    @property
    def scan_type(self) -> str: ...
    @property
    def platform(self) -> MobilePlatformPy: ...
    @property
    def app_id(self) -> Optional[str]: ...
    @property
    def version(self) -> Optional[str]: ...
    @property
    def timestamp(self) -> str: ...
    @property
    def findings(self) -> List[MobileFindingPy]: ...
    @property
    def recommendations(self) -> List[str]: ...
    @property
    def duration_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def analyze_apk(path: str) -> MobileScanReportPy: ...
def async_analyze_apk(path: str) -> Any: ...
def analyze_ipa(path: str) -> MobileScanReportPy: ...
def async_analyze_ipa(path: str) -> Any: ...

class MobileDevicePy:
    @property
    def serial(self) -> str: ...
    @property
    def model(self) -> Optional[str]: ...
    @property
    def android_version(self) -> Optional[str]: ...
    @property
    def is_emulator(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DynamicMobileConfigPy:
    @property
    def install(self) -> bool: ...
    @property
    def launch(self) -> Optional[str]: ...
    @property
    def capture_logs(self) -> bool: ...
    @property
    def duration(self) -> Optional[int]: ...
    @property
    def uninstall_after(self) -> bool: ...
    @property
    def dry_run(self) -> bool: ...
    @property
    def frida_script(self) -> Optional[str]: ...
    @property
    def allow_frida(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DynamicMobileReportPy:
    @property
    def target(self) -> str: ...
    @property
    def scan_type(self) -> str: ...
    @property
    def platform(self) -> MobilePlatformPy: ...
    @property
    def device_serial(self) -> Optional[str]: ...
    @property
    def app_id(self) -> Optional[str]: ...
    @property
    def findings(self) -> List[MobileFindingPy]: ...
    @property
    def recommendations(self) -> List[str]: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def actions_performed(self) -> List[str]: ...
    @property
    def dry_run(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def list_mobile_devices() -> List[MobileDevicePy]: ...
def dynamic_mobile_analysis(
    package: str,
    config: DynamicMobileConfigPy,
    device_serial: Optional[str] = None,
) -> DynamicMobileReportPy: ...
