from typing import Any, Dict, List, Optional

class MobileDeviceDescriptor:
    def __init__(
        self,
        serial: str,
        *,
        model: Optional[str] = None,
        android_version: Optional[str] = None,
        ios_version: Optional[str] = None,
        is_emulator: bool = False,
        is_rooted: bool = False,
        usb_debugging: bool = False,
    ) -> None: ...
    @property
    def serial(self) -> str: ...
    @property
    def model(self) -> Optional[str]: ...
    @property
    def android_version(self) -> Optional[str]: ...
    @property
    def ios_version(self) -> Optional[str]: ...
    @property
    def is_emulator(self) -> bool: ...
    @property
    def is_rooted(self) -> bool: ...
    @property
    def usb_debugging(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MobileDeviceCapabilities:
    def __init__(
        self,
        *,
        supports_install: bool = False,
        supports_uninstall: bool = False,
        supports_logcat: bool = False,
        supports_frida: bool = False,
        supports_screenshot: bool = False,
        supports_screen_record: bool = False,
        supports_dumpsys: bool = False,
        supports_aapt: bool = False,
        supports_ui_automator: bool = False,
        features: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def supports_install(self) -> bool: ...
    @property
    def supports_uninstall(self) -> bool: ...
    @property
    def supports_logcat(self) -> bool: ...
    @property
    def supports_frida(self) -> bool: ...
    @property
    def supports_screenshot(self) -> bool: ...
    @property
    def supports_screen_record(self) -> bool: ...
    @property
    def supports_dumpsys(self) -> bool: ...
    @property
    def supports_aapt(self) -> bool: ...
    @property
    def supports_ui_automator(self) -> bool: ...
    @property
    def features(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MobileSessionConfig:
    def __init__(
        self,
        *,
        package: Optional[str] = None,
        install: bool = False,
        uninstall_after: bool = False,
        capture_logs: bool = True,
        duration_secs: Optional[int] = None,
        frida_script: Optional[str] = None,
        allow_frida: bool = False,
        dry_run: bool = False,
        launch_activity: Optional[str] = None,
        permissions: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def package(self) -> Optional[str]: ...
    @property
    def install(self) -> bool: ...
    @property
    def uninstall_after(self) -> bool: ...
    @property
    def capture_logs(self) -> bool: ...
    @property
    def duration_secs(self) -> Optional[int]: ...
    @property
    def frida_script(self) -> Optional[str]: ...
    @property
    def allow_frida(self) -> bool: ...
    @property
    def dry_run(self) -> bool: ...
    @property
    def launch_activity(self) -> Optional[str]: ...
    @property
    def permissions(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MobileSessionState:
    Disconnected: "MobileSessionState"
    Connecting: "MobileSessionState"
    Connected: "MobileSessionState"
    AppInstalled: "MobileSessionState"
    AppRunning: "MobileSessionState"
    Analyzing: "MobileSessionState"
    Disconnecting: "MobileSessionState"
    Error: "MobileSessionState"
    @property
    def value(self) -> str: ...
    def from_str(s: str) -> MobileSessionState: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MobileSessionStats:
    def __init__(
        self,
        *,
        adb_commands_executed: int = 0,
        log_lines_captured: int = 0,
        screenshots_taken: int = 0,
        frida_scripts_loaded: int = 0,
        permissions_granted: int = 0,
        duration_ms: int = 0,
    ) -> None: ...
    @property
    def adb_commands_executed(self) -> int: ...
    @property
    def log_lines_captured(self) -> int: ...
    @property
    def screenshots_taken(self) -> int: ...
    @property
    def frida_scripts_loaded(self) -> int: ...
    @property
    def permissions_granted(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MobileSession:
    def __init__(
        self,
        device: MobileDeviceDescriptor,
        config: MobileSessionConfig,
    ) -> None: ...
    @property
    def device(self) -> MobileDeviceDescriptor: ...
    @property
    def config(self) -> MobileSessionConfig: ...
    @property
    def state(self) -> MobileSessionState: ...
    @property
    def session_id(self) -> str: ...
    @property
    def stats(self) -> MobileSessionStats: ...
    def connect(self) -> MobileDeviceCapabilities: ...
    def install_apk(self, path: str) -> bool: ...
    def uninstall_package(self, package: str) -> bool: ...
    def launch_app(self, activity: Optional[str] = None) -> bool: ...
    def capture_logcat(self, *, filter_tag: Optional[str] = None) -> List[str]: ...
    def screenshot(self) -> bytes: ...
    def run_adb(self, args: List[str]) -> str: ...
    def close(self) -> None: ...
    def __enter__(self) -> MobileSession: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class AsyncMobileSession:
    def __init__(
        self,
        device: MobileDeviceDescriptor,
        config: MobileSessionConfig,
    ) -> None: ...
    @property
    def device(self) -> MobileDeviceDescriptor: ...
    @property
    def config(self) -> MobileSessionConfig: ...
    @property
    def state(self) -> MobileSessionState: ...
    @property
    def session_id(self) -> str: ...
    def async_connect(self) -> Any: ...
    def async_install_apk(self, path: str) -> Any: ...
    def async_uninstall_package(self, package: str) -> Any: ...
    def async_launch_app(self, activity: Optional[str] = None) -> Any: ...
    def async_capture_logcat(self, *, filter_tag: Optional[str] = None) -> Any: ...
    def async_screenshot(self) -> Any: ...
    def async_run_adb(self, args: List[str]) -> Any: ...
    def async_close(self) -> Any: ...
    def __aenter__(self) -> AsyncMobileSession: ...
    def __aexit__(self, *args: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MobileDeviceRegistry:
    def __init__(self) -> None: ...
    def list_devices(self) -> List[MobileDeviceDescriptor]: ...
    def get_device(self, serial: str) -> Optional[MobileDeviceDescriptor]: ...
    def get_capabilities(self, serial: str) -> Optional[MobileDeviceCapabilities]: ...
    def refresh(self) -> List[MobileDeviceDescriptor]: ...
    @property
    def device_count(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
