from typing import Any, Dict, List, Optional

from .artifact import ArtifactReference

class MobileDeviceDescriptor:
    def __init__(
        self,
        serial: str,
        *,
        model: Optional[str] = None,
        platform: str = "android",
        android_version: Optional[str] = None,
        sdk_version: Optional[int] = None,
        abi: Optional[str] = None,
        is_emulator: bool = False,
        is_rooted: bool = False,
        transport: str = "usb",
        authorization_status: str = "unknown",
        supported_operations: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def serial(self) -> str: ...
    @property
    def model(self) -> Optional[str]: ...
    @property
    def platform(self) -> str: ...
    @property
    def android_version(self) -> Optional[str]: ...
    @property
    def sdk_version(self) -> Optional[int]: ...
    @property
    def abi(self) -> Optional[str]: ...
    @property
    def is_emulator(self) -> bool: ...
    @property
    def is_rooted(self) -> bool: ...
    @property
    def transport(self) -> str: ...
    @property
    def authorization_status(self) -> str: ...
    @property
    def supported_operations(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MobileDeviceCapabilities:
    def __init__(
        self,
        *,
        supports_install: bool = False,
        supports_uninstall: bool = False,
        supports_launch: bool = False,
        supports_frida: bool = False,
        supports_log_capture: bool = False,
        supports_screenshot: bool = False,
        supports_network_capture: bool = False,
        supports_filesystem_extract: bool = False,
        supports_permission_management: bool = False,
    ) -> None: ...
    @property
    def supports_install(self) -> bool: ...
    @property
    def supports_uninstall(self) -> bool: ...
    @property
    def supports_launch(self) -> bool: ...
    @property
    def supports_frida(self) -> bool: ...
    @property
    def supports_log_capture(self) -> bool: ...
    @property
    def supports_screenshot(self) -> bool: ...
    @property
    def supports_network_capture(self) -> bool: ...
    @property
    def supports_filesystem_extract(self) -> bool: ...
    @property
    def supports_permission_management(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class MobileSessionConfig:
    def __init__(
        self,
        device_serial: str,
        *,
        package_id: Optional[str] = None,
        install_app: bool = False,
        uninstall_after: bool = False,
        capture_logs: bool = False,
        capture_screenshots: bool = False,
        capture_network: bool = False,
        traffic_output: Optional[str] = None,
        frida_scripts: Optional[List[str]] = None,
        allow_frida: bool = False,
        timeout_secs: Optional[int] = None,
        proxy: Optional[str] = None,
        grant_permissions: Optional[List[str]] = None,
        revoke_permissions: Optional[List[str]] = None,
        dry_run: bool = False,
    ) -> None: ...
    @property
    def device_serial(self) -> str: ...
    @property
    def package_id(self) -> Optional[str]: ...
    @property
    def install_app(self) -> bool: ...
    @property
    def uninstall_after(self) -> bool: ...
    @property
    def capture_logs(self) -> bool: ...
    @property
    def capture_screenshots(self) -> bool: ...
    @property
    def capture_network(self) -> bool: ...
    @property
    def traffic_output(self) -> Optional[str]: ...
    @property
    def frida_scripts(self) -> List[str]: ...
    @property
    def allow_frida(self) -> bool: ...
    @property
    def timeout_secs(self) -> Optional[int]: ...
    @property
    def proxy(self) -> Optional[str]: ...
    @property
    def grant_permissions(self) -> List[str]: ...
    @property
    def revoke_permissions(self) -> List[str]: ...
    @property
    def dry_run(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class MobileSessionState:
    Created: "MobileSessionState"
    Connecting: "MobileSessionState"
    Installing: "MobileSessionState"
    Launching: "MobileSessionState"
    Running: "MobileSessionState"
    Capturing: "MobileSessionState"
    Stopping: "MobileSessionState"
    Uninstalling: "MobileSessionState"
    Cleaning: "MobileSessionState"
    Stopped: "MobileSessionState"
    Failed: "MobileSessionState"
    Cancelled: "MobileSessionState"
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class MobileSessionStats:
    def __init__(
        self,
        *,
        screenshots_captured: int = 0,
        log_entries: int = 0,
        network_exchanges: int = 0,
        artifacts_collected: int = 0,
        frida_events: int = 0,
        duration_ms: int = 0,
    ) -> None: ...
    @property
    def screenshots_captured(self) -> int: ...
    @property
    def log_entries(self) -> int: ...
    @property
    def network_exchanges(self) -> int: ...
    @property
    def artifacts_collected(self) -> int: ...
    @property
    def frida_events(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class MobileSession:
    def __init__(
        self,
        session_id: str,
        device_serial: str,
        config: MobileSessionConfig,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def device_serial(self) -> str: ...
    @property
    def config(self) -> MobileSessionConfig: ...
    @property
    def state(self) -> MobileSessionState: ...
    @property
    def stats(self) -> MobileSessionStats: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def install_app(self, package_path: str) -> str: ...
    def uninstall_app(self) -> None: ...
    def launch_app(self) -> None: ...
    def stop_app(self) -> None: ...
    def capture_screenshot(self) -> ArtifactReference: ...
    def get_logs(self) -> List[str]: ...
    def __enter__(self) -> MobileSession: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class AsyncMobileSession:
    def __init__(
        self,
        session_id: str,
        device_serial: str,
        config: MobileSessionConfig,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def device_serial(self) -> str: ...
    @property
    def config(self) -> MobileSessionConfig: ...
    @property
    def state(self) -> MobileSessionState: ...
    @property
    def stats(self) -> MobileSessionStats: ...
    def async_start(self) -> Any: ...
    def async_stop(self) -> Any: ...
    def async_install_app(self, package_path: str) -> Any: ...
    def async_uninstall_app(self) -> Any: ...
    def async_launch_app(self) -> Any: ...
    def async_stop_app(self) -> Any: ...
    def async_capture_screenshot(self) -> Any: ...
    def async_get_logs(self) -> Any: ...
    def __aenter__(self) -> AsyncMobileSession: ...
    def __aexit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class MobileDeviceRegistry:
    def __init__(self) -> None: ...
    @property
    def devices(self) -> List[MobileDeviceDescriptor]: ...
    def refresh(self) -> List[MobileDeviceDescriptor]: ...
    def get_device(self, serial: str) -> Optional[MobileDeviceDescriptor]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
