from typing import Any, Dict, List, Optional

class StaticAnalysisSummary:
    def __init__(
        self,
        package_id: str,
        *,
        package_name: Optional[str] = None,
        version: Optional[str] = None,
        min_sdk: Optional[int] = None,
        target_sdk: Optional[int] = None,
        permissions: Optional[List[str]] = None,
        urls: Optional[List[str]] = None,
        certificates: Optional[List[str]] = None,
        exported_components: Optional[List[str]] = None,
        activities: Optional[List[str]] = None,
        services: Optional[List[str]] = None,
        receivers: Optional[List[str]] = None,
        providers: Optional[List[str]] = None,
        deep_links: Optional[List[str]] = None,
        intent_filters: Optional[List[str]] = None,
        native_libraries: Optional[List[str]] = None,
        hardcoded_secrets: Optional[List[str]] = None,
        source_type: Optional[str] = None,
    ) -> None: ...
    @property
    def package_id(self) -> str: ...
    @property
    def package_name(self) -> Optional[str]: ...
    @property
    def version(self) -> Optional[str]: ...
    @property
    def min_sdk(self) -> Optional[int]: ...
    @property
    def target_sdk(self) -> Optional[int]: ...
    @property
    def permissions(self) -> List[str]: ...
    @property
    def urls(self) -> List[str]: ...
    @property
    def certificates(self) -> List[str]: ...
    @property
    def exported_components(self) -> List[str]: ...
    @property
    def activities(self) -> List[str]: ...
    @property
    def services(self) -> List[str]: ...
    @property
    def receivers(self) -> List[str]: ...
    @property
    def providers(self) -> List[str]: ...
    @property
    def deep_links(self) -> List[str]: ...
    @property
    def intent_filters(self) -> List[str]: ...
    @property
    def native_libraries(self) -> List[str]: ...
    @property
    def hardcoded_secrets(self) -> List[str]: ...
    @property
    def source_type(self) -> str: ...
    def to_dynamic_plan(self) -> "DynamicAnalysisPlan": ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class AnalysisTarget:
    def __init__(
        self,
        identifier: str,
        target_type: str,
        category: str,
        priority: int = 5,
    ) -> None: ...
    @property
    def identifier(self) -> str: ...
    @property
    def target_type(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def priority(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class DynamicAnalysisPlan:
    def __init__(
        self,
        package_id: str,
        *,
        targets: Optional[List[AnalysisTarget]] = None,
        permissions_to_test: Optional[List[str]] = None,
        components_to_inspect: Optional[List[str]] = None,
        urls_to_probe: Optional[List[str]] = None,
        use_frida: bool = False,
        instrumentation_focus: str = "java",
    ) -> None: ...
    @property
    def package_id(self) -> str: ...
    @property
    def targets(self) -> List[AnalysisTarget]: ...
    @property
    def permissions_to_test(self) -> List[str]: ...
    @property
    def components_to_inspect(self) -> List[str]: ...
    @property
    def urls_to_probe(self) -> List[str]: ...
    @property
    def use_frida(self) -> bool: ...
    @property
    def instrumentation_focus(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class InstrumentationConfig:
    def __init__(
        self,
        session_id: str,
        device_serial: str,
        package_id: str,
        *,
        timeout_secs: int = 300,
        max_output_bytes: int = 10485760,
        allow_system_hooks: bool = False,
        enable_logging: bool = True,
        scripts: Optional[List[InstrumentationScript]] = None,
        hooks: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def device_serial(self) -> str: ...
    @property
    def package_id(self) -> str: ...
    @property
    def timeout_secs(self) -> int: ...
    @property
    def max_output_bytes(self) -> int: ...
    @property
    def allow_system_hooks(self) -> bool: ...
    @property
    def enable_logging(self) -> bool: ...
    @property
    def scripts(self) -> List[InstrumentationScript]: ...
    @property
    def hooks(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class InstrumentationScript:
    def __init__(
        self,
        name: str,
        source_hash: str,
        script_type: str,
        *,
        built_in: bool = False,
        description: Optional[str] = None,
        target_classes: Optional[List[str]] = None,
        target_methods: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def source_hash(self) -> str: ...
    @property
    def script_type(self) -> str: ...
    @property
    def built_in(self) -> bool: ...
    @property
    def description(self) -> Optional[str]: ...
    @property
    def target_classes(self) -> List[str]: ...
    @property
    def target_methods(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class InstrumentationEvent:
    def __init__(
        self,
        event_id: str,
        session_id: str,
        event_type: str,
        timestamp_ms: int,
        *,
        script_name: Optional[str] = None,
        target_class: Optional[str] = None,
        target_method: Optional[str] = None,
        data: Optional[str] = None,
        sequence: int = 0,
    ) -> None: ...
    @property
    def event_id(self) -> str: ...
    @property
    def session_id(self) -> str: ...
    @property
    def event_type(self) -> str: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def script_name(self) -> Optional[str]: ...
    @property
    def target_class(self) -> Optional[str]: ...
    @property
    def target_method(self) -> Optional[str]: ...
    @property
    def data(self) -> Optional[str]: ...
    @property
    def sequence(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class InstrumentationResult:
    def __init__(
        self,
        session_id: str,
        success: bool,
        scripts_loaded: int,
        hooks_installed: int,
        events_captured: int,
        output_bytes: int,
        duration_ms: int,
        *,
        timed_out: bool = False,
        error: Optional[str] = None,
        output_truncated: bool = False,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def scripts_loaded(self) -> int: ...
    @property
    def hooks_installed(self) -> int: ...
    @property
    def events_captured(self) -> int: ...
    @property
    def output_bytes(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def timed_out(self) -> bool: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def output_truncated(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class MobileEvidenceKind:
    Screenshot: "MobileEvidenceKind"
    Log: "MobileEvidenceKind"
    NetworkTrace: "MobileEvidenceKind"
    ApplicationFile: "MobileEvidenceKind"
    ProcessMetadata: "MobileEvidenceKind"
    RuntimePermission: "MobileEvidenceKind"
    DynamicApiObservation: "MobileEvidenceKind"
    CrashTrace: "MobileEvidenceKind"
    InstrumentationOutput: "MobileEvidenceKind"
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MobileEvidence:
    def __init__(
        self,
        evidence_id: str,
        session_id: str,
        kind: MobileEvidenceKind,
        device_serial: str,
        package_id: str,
        timestamp_ms: int,
        content_type: str,
        *,
        content_hash: Optional[str] = None,
        size_bytes: int = 0,
        redacted: bool = False,
        description: Optional[str] = None,
        linked_static_evidence: Optional[str] = None,
    ) -> None: ...
    @property
    def evidence_id(self) -> str: ...
    @property
    def session_id(self) -> str: ...
    @property
    def kind(self) -> MobileEvidenceKind: ...
    @property
    def device_serial(self) -> str: ...
    @property
    def package_id(self) -> str: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def content_type(self) -> str: ...
    @property
    def content_hash(self) -> Optional[str]: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def redacted(self) -> bool: ...
    @property
    def description(self) -> Optional[str]: ...
    @property
    def linked_static_evidence(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class MobileEvidenceCollection:
    def __init__(self, session_id: str) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def evidence(self) -> List[MobileEvidence]: ...
    @property
    def total_size_bytes(self) -> int: ...
    @property
    def redacted_count(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
