from typing import Any, Dict, List, Optional, Tuple

class TargetPy:
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> Optional[int]: ...
    @property
    def scheme(self) -> Optional[str]: ...
    @property
    def url_path(self) -> Optional[str]: ...
    def __init__(self, host: str, port: Optional[int] = None, scheme: Optional[str] = None, url_path: Optional[str] = None) -> None: ...
    def normalized(self) -> str: ...
    def is_ip(self) -> bool: ...
    def is_hostname(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ResolvedTargetPy:
    @property
    def target(self) -> str: ...
    @property
    def resolved_ips(self) -> List[str]: ...
    @property
    def address_family(self) -> str: ...
    @property
    def resolver_source(self) -> str: ...
    @property
    def canonical_name(self) -> Optional[str]: ...
    @property
    def resolution_time_ms(self) -> Optional[float]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ConnectionConfigPy:
    @property
    def connect_timeout_ms(self) -> int: ...
    @property
    def read_timeout_ms(self) -> int: ...
    @property
    def write_timeout_ms(self) -> int: ...
    @property
    def handshake_timeout_ms(self) -> int: ...
    @property
    def idle_timeout_ms(self) -> int: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def retry_delay_ms(self) -> int: ...
    def __init__(self, connect_timeout_ms: int = 5000, read_timeout_ms: int = 30000, write_timeout_ms: int = 30000, handshake_timeout_ms: int = 10000, idle_timeout_ms: int = 60000, max_retries: int = 0, retry_delay_ms: int = 1000) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TimeoutConfigPy:
    @property
    def connect_ms(self) -> int: ...
    @property
    def read_ms(self) -> int: ...
    @property
    def write_ms(self) -> int: ...
    @property
    def handshake_ms(self) -> int: ...
    @property
    def operation_ms(self) -> int: ...
    @property
    def idle_ms(self) -> int: ...
    def __init__(self, connect_ms: int = 5000, read_ms: int = 30000, write_ms: int = 30000, handshake_ms: int = 10000, operation_ms: int = 60000, idle_ms: int = 60000) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RetryPolicyPy:
    @property
    def max_retries(self) -> int: ...
    @property
    def delay_ms(self) -> int: ...
    @property
    def backoff_multiplier(self) -> float: ...
    @property
    def max_delay_ms(self) -> int: ...
    @property
    def retryable_errors(self) -> List[str]: ...
    def __init__(self, max_retries: int = 0, delay_ms: int = 1000, backoff_multiplier: float = 1.0, max_delay_ms: int = 30000, retryable_errors: Optional[List[str]] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SocketEndpointPy:
    @property
    def address(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def address_family(self) -> str: ...
    @property
    def is_loopback(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ConnectionTimingPy:
    @property
    def dns_resolution_ms(self) -> Optional[float]: ...
    @property
    def tcp_connect_ms(self) -> Optional[float]: ...
    @property
    def tls_handshake_ms(self) -> Optional[float]: ...
    @property
    def first_byte_ms(self) -> Optional[float]: ...
    @property
    def total_ms(self) -> float: ...
    @property
    def connection_reused(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ConnectionMetadataPy:
    @property
    def local_endpoint(self) -> Optional[SocketEndpointPy]: ...
    @property
    def remote_endpoint(self) -> Optional[SocketEndpointPy]: ...
    @property
    def resolved_address(self) -> Optional[str]: ...
    @property
    def transport_protocol(self) -> str: ...
    @property
    def negotiated_protocol(self) -> Optional[str]: ...
    @property
    def connection_reused(self) -> bool: ...
    @property
    def timing(self) -> Optional[ConnectionTimingPy]: ...
    @property
    def tls_version(self) -> Optional[str]: ...
    @property
    def tls_cipher(self) -> Optional[str]: ...
    @property
    def bytes_sent(self) -> int: ...
    @property
    def bytes_received(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NetworkEvidencePy:
    @property
    def operation(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def metadata(self) -> Optional[ConnectionMetadataPy]: ...
    @property
    def transcript(self) -> Optional[NetworkTranscriptPy]: ...
    @property
    def artifact_refs(self) -> List[str]: ...
    @property
    def timing(self) -> Optional[ConnectionTimingPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TranscriptEntryPy:
    @property
    def sequence(self) -> int: ...
    @property
    def direction(self) -> str: ...
    @property
    def timestamp_ms(self) -> float: ...
    @property
    def data_type(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def summary(self) -> Optional[str]: ...
    @property
    def redacted(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NetworkTranscriptPy:
    @property
    def entries(self) -> List[TranscriptEntryPy]: ...
    @property
    def total_bytes(self) -> int: ...
    @property
    def truncated(self) -> bool: ...
    def add_entry(self, entry: TranscriptEntryPy) -> NetworkTranscriptPy: ...
    def summary(self) -> str: ...
    def __getitem__(self, index: int) -> TranscriptEntryPy: ...
    def __len__(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ProxyRoutePy:
    @property
    def proxy_type(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def username(self) -> Optional[str]: ...
    @property
    def password(self) -> Optional[str]: ...
    @property
    def no_proxy(self) -> List[str]: ...
    def __init__(self, host: str, port: int, proxy_type: str = "http", username: Optional[str] = None, password: Optional[str] = None, no_proxy: Optional[List[str]] = None) -> None: ...
    def url(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def resolve_target_sync(target: TargetPy, timeout_ms: int = 5000, max_results: int = 100) -> ResolvedTargetPy: ...
def async_resolve_target(target: TargetPy, timeout_ms: int = 5000, max_results: int = 100) -> Any: ...
