from typing import Any, Dict, List, Optional

class NseConfigPy:
    @property
    def target(self) -> str: ...
    @property
    def script(self) -> str: ...
    @property
    def script_args(self) -> Optional[str]: ...
    @property
    def script_file(self) -> Optional[str]: ...
    @property
    def json(self) -> bool: ...
    @property
    def verbose(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseLibraryUsePy:
    @property
    def name(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def loaded(self) -> bool: ...
    @property
    def side_effects(self) -> List[str]: ...
    @property
    def fallback_behavior(self) -> str: ...
    @property
    def notes(self) -> str: ...
    @property
    def warnings(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseRuleEvaluationPy:
    @property
    def kind(self) -> str: ...
    @property
    def evaluated(self) -> bool: ...
    @property
    def matched(self) -> bool: ...
    @property
    def exactness(self) -> str: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def summary(self) -> str: ...
    @property
    def unsupported(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseReportPy:
    @property
    def target(self) -> str: ...
    @property
    def script_name(self) -> str: ...
    @property
    def output(self) -> str: ...
    @property
    def output_lines(self) -> int: ...
    @property
    def has_output(self) -> bool: ...
    @property
    def warnings(self) -> List[str]: ...
    @property
    def errors(self) -> List[str]: ...
    @property
    def library_count(self) -> int: ...
    @property
    def compatibility_status(self) -> str: ...
    @property
    def fidelity(self) -> str: ...
    @property
    def elapsed_secs(self) -> float: ...
    @property
    def libraries(self) -> List[NseLibraryUsePy]: ...
    @property
    def rules(self) -> List[NseRuleEvaluationPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def nse_run(target: str, script: str, *, script_args: Optional[str] = None, verbose: bool = False) -> NseReportPy: ...
def async_nse_run(target: str, script: str, *, script_args: Optional[str] = None, verbose: bool = False) -> Any: ...
def nse_list_libraries() -> List[str]: ...
