from typing import Any, Dict, List, Optional

class NseConfigPy:
    @property
    def target(self) -> str: ...
    @property
    def script(self) -> str: ...
    @property
    def script_args(self) -> Optional[str]: ...
    @property
    def script_file(self) -> Optional[str]: ...
    @property
    def json(self) -> bool: ...
    @property
    def verbose(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseLibraryUsePy:
    @property
    def name(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def loaded(self) -> bool: ...
    @property
    def side_effects(self) -> List[str]: ...
    @property
    def fallback_behavior(self) -> str: ...
    @property
    def notes(self) -> str: ...
    @property
    def warnings(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseRuleEvaluationPy:
    @property
    def kind(self) -> str: ...
    @property
    def evaluated(self) -> bool: ...
    @property
    def matched(self) -> bool: ...
    @property
    def exactness(self) -> str: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def summary(self) -> str: ...
    @property
    def unsupported(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseEvidenceItemPy:
    @property
    def id(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def summary(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def port(self) -> Optional[int]: ...
    @property
    def service(self) -> Optional[str]: ...
    @property
    def confidence(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def raw_excerpt(self) -> Optional[str]: ...
    @property
    def references(self) -> List[str]: ...
    @property
    def tags(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseReportPy:
    @property
    def target(self) -> str: ...
    @property
    def script_name(self) -> str: ...
    @property
    def output(self) -> str: ...
    @property
    def output_lines(self) -> int: ...
    @property
    def has_output(self) -> bool: ...
    @property
    def warnings(self) -> List[str]: ...
    @property
    def errors(self) -> List[str]: ...
    @property
    def library_count(self) -> int: ...
    @property
    def compatibility_status(self) -> str: ...
    @property
    def fidelity(self) -> str: ...
    @property
    def elapsed_secs(self) -> float: ...
    @property
    def libraries(self) -> List[NseLibraryUsePy]: ...
    @property
    def rules(self) -> List[NseRuleEvaluationPy]: ...
    @property
    def evidence(self) -> List[NseEvidenceItemPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseScriptMetadataPy:
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def author(self) -> Optional[str]: ...
    @property
    def license(self) -> Optional[str]: ...
    @property
    def dependencies(self) -> List[str]: ...
    @property
    def targets(self) -> Optional[str]: ...
    @property
    def categories(self) -> List[str]: ...
    @property
    def is_builtin(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseSandboxPolicyPy:
    @property
    def allow_filesystem(self) -> bool: ...
    @property
    def allowed_dirs(self) -> List[str]: ...
    @property
    def allow_network(self) -> bool: ...
    @property
    def allowed_cidrs(self) -> List[str]: ...
    @property
    def max_lua_instructions(self) -> int: ...
    @property
    def max_output_bytes(self) -> int: ...
    @property
    def max_network_ops(self) -> int: ...
    @property
    def max_memory_bytes(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseTargetContextPy:
    @property
    def host_ip(self) -> str: ...
    @property
    def hostname(self) -> Optional[str]: ...
    @property
    def port(self) -> Optional[int]: ...
    @property
    def protocol(self) -> Optional[str]: ...
    @property
    def service_name(self) -> Optional[str]: ...
    @property
    def service_product(self) -> Optional[str]: ...
    @property
    def service_version(self) -> Optional[str]: ...
    @property
    def os_detection(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseLibraryDescriptorPy:
    @property
    def name(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def sandbox_side_effects(self) -> List[str]: ...
    @property
    def fallback_behavior(self) -> str: ...
    @property
    def notes(self) -> str: ...
    @property
    def optional_deps(self) -> List[str]: ...
    @property
    def enforcement_status(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseArgumentPy:
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def arg_type(self) -> str: ...
    @property
    def arg_value(self) -> Any: ...
    @property
    def is_secret(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseLibraryRegistryPy:
    def __init__(self) -> None: ...
    def list(self) -> List[NseLibraryDescriptorPy]: ...
    def get(self, name: str) -> Optional[NseLibraryDescriptorPy]: ...
    def by_category(self, category: str) -> List[NseLibraryDescriptorPy]: ...
    def count(self) -> int: ...

# Release 3 WS2: Runtime lifecycle
class NseExecutionLimitsPy:
    @property
    def wall_clock_timeout_secs(self) -> Optional[int]: ...
    @property
    def lua_instruction_budget(self) -> Optional[int]: ...
    @property
    def max_output_bytes(self) -> Optional[int]: ...
    @property
    def max_script_bytes(self) -> Optional[int]: ...
    @property
    def max_required_module_bytes(self) -> Optional[int]: ...
    @property
    def max_network_operations(self) -> Optional[int]: ...
    @property
    def max_network_bytes_read(self) -> Optional[int]: ...
    @property
    def max_network_bytes_written(self) -> Optional[int]: ...
    @property
    def max_filesystem_operations(self) -> Optional[int]: ...
    @property
    def max_filesystem_bytes_read(self) -> Optional[int]: ...
    @property
    def max_lua_memory_bytes(self) -> Optional[int]: ...
    @staticmethod
    def manual_defaults() -> NseExecutionLimitsPy: ...
    @staticmethod
    def automated_defaults() -> NseExecutionLimitsPy: ...
    @staticmethod
    def unlimited() -> NseExecutionLimitsPy: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class NseCancellationTokenPy:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    def is_cancelled(self) -> bool: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class NseRuntimeStatsPy:
    @property
    def elapsed_ms(self) -> int: ...
    @property
    def output_bytes(self) -> int: ...
    @property
    def lua_instruction_count(self) -> int: ...
    @property
    def network_operations(self) -> int: ...
    @property
    def network_bytes_read(self) -> int: ...
    @property
    def network_bytes_written(self) -> int: ...
    @property
    def filesystem_operations(self) -> int: ...
    @property
    def filesystem_bytes_read(self) -> int: ...
    @property
    def limit_violation(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class NseRuntimeConfigPy:
    @property
    def target(self) -> str: ...
    @property
    def profile_kind(self) -> str: ...
    @property
    def verbose(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class NseRuntimePy:
    def __init__(self, config: NseRuntimeConfigPy, *, limits: Optional[NseExecutionLimitsPy] = None) -> None: ...
    def cancellation_token(self) -> NseCancellationTokenPy: ...
    def run_script(self, script: str) -> NseReportPy: ...
    def run_script_with_args(self, script: str, script_args: str) -> NseReportPy: ...
    def run_script_async(self, script: str) -> Any: ...
    def __repr__(self) -> str: ...

# Release 3 WS3: Script inspection
class NseScriptSourcePy:
    @property
    def kind(self) -> str: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def path(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def __repr__(self) -> str: ...

class NseDiagnosticPy:
    @property
    def kind(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def path(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def __repr__(self) -> str: ...

# Release 3 WS4: Rule evaluation
class NseHostContextPy:
    @property
    def ip(self) -> str: ...
    @property
    def hostname(self) -> Optional[str]: ...
    @property
    def target_label(self) -> str: ...
    @property
    def source(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def __repr__(self) -> str: ...

class NsePortContextPy:
    @property
    def port(self) -> int: ...
    @property
    def protocol(self) -> str: ...
    @property
    def state(self) -> str: ...
    @property
    def service_name(self) -> Optional[str]: ...
    @property
    def service_product(self) -> Optional[str]: ...
    @property
    def service_version(self) -> Optional[str]: ...
    @property
    def source(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def __repr__(self) -> str: ...

class NseRuleResultPy:
    @property
    def kind(self) -> str: ...
    @property
    def evaluated(self) -> bool: ...
    @property
    def matched(self) -> bool: ...
    @property
    def exactness(self) -> Optional[str]: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def summary(self) -> Optional[str]: ...
    @property
    def unsupported(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

def nse_run(target: str, script: str, *, script_args: Optional[str] = None, verbose: bool = False) -> NseReportPy: ...
def async_nse_run(target: str, script: str, *, script_args: Optional[str] = None, verbose: bool = False) -> Any: ...
def nse_list_libraries() -> List[str]: ...
def nse_list_libraries_detailed() -> List[NseLibraryDescriptorPy]: ...
def nse_get_library_descriptor(name: str) -> Optional[NseLibraryDescriptorPy]: ...
def nse_list_scripts(category: Optional[str] = None) -> List[NseScriptMetadataPy]: ...
def nse_get_script_metadata(name: str) -> Optional[NseScriptMetadataPy]: ...
def nse_run_with_config(config: NseConfigPy) -> NseReportPy: ...
def nse_validate_script(script: str) -> Dict[str, Any]: ...

# Release 3 WS2: Capability context

class NseCapabilityContextPy:
    @property
    def profile_kind(self) -> str: ...
    @property
    def limits(self) -> NseExecutionLimitsPy: ...
    @property
    def is_cancelled(self) -> bool: ...
    @property
    def network_policy_kind(self) -> str: ...
    @property
    def script_policy_allows_builtins(self) -> bool: ...
    @property
    def script_policy_allows_files(self) -> bool: ...
    @property
    def module_policy_allows_builtins(self) -> bool: ...
    @property
    def module_policy_allows_filesystem(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# Release 3 WS6: Library version and conflicts

class NseLibraryVersionPy:
    @property
    def library_name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def min_nse_compat(self) -> str: ...
    @property
    def deprecated(self) -> bool: ...
    @property
    def replacement(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseLibraryConflictPy:
    @property
    def library_a(self) -> str: ...
    @property
    def library_b(self) -> str: ...
    @property
    def conflict_type(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def resolution(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# Release 3 WS7: Execution request/result types

class NseExecutionRequestPy:
    @property
    def target(self) -> str: ...
    @property
    def port(self) -> Optional[int]: ...
    @property
    def scripts(self) -> List[str]: ...
    @property
    def script_args(self) -> Optional[str]: ...
    @property
    def script_file(self) -> Optional[str]: ...
    @property
    def arguments(self) -> List[NseArgumentPy]: ...
    @property
    def profile_kind(self) -> str: ...
    @property
    def verbose(self) -> bool: ...
    @property
    def json_output(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class NseOutputValuePy:
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def value_type(self) -> str: ...
    @property
    def truncated(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class NseScriptResultPy:
    @property
    def script_name(self) -> str: ...
    @property
    def output(self) -> str: ...
    @property
    def output_lines(self) -> List[str]: ...
    @property
    def structured_output(self) -> List[NseOutputValuePy]: ...
    @property
    def execution_time_ms(self) -> int: ...
    @property
    def libraries_used(self) -> List[str]: ...
    @property
    def warnings(self) -> List[str]: ...
    @property
    def errors(self) -> List[str]: ...
    def has_output(self) -> bool: ...
    def has_errors(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class NseExecutionResultPy:
    @property
    def target(self) -> str: ...
    @property
    def script_results(self) -> List[NseScriptResultPy]: ...
    @property
    def total_scripts(self) -> int: ...
    @property
    def scripts_succeeded(self) -> int: ...
    @property
    def scripts_failed(self) -> int: ...
    @property
    def total_execution_time_ms(self) -> int: ...
    @property
    def warnings(self) -> List[str]: ...
    @property
    def errors(self) -> List[str]: ...
    @property
    def capability_context(self) -> Optional[NseCapabilityContextPy]: ...
    def succeeded(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
