from typing import Any, Dict, List, Optional

class NseConfigPy:
    @property
    def target(self) -> str: ...
    @property
    def script(self) -> str: ...
    @property
    def script_args(self) -> Optional[str]: ...
    @property
    def script_file(self) -> Optional[str]: ...
    @property
    def json(self) -> bool: ...
    @property
    def verbose(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseLibraryUsePy:
    @property
    def name(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def loaded(self) -> bool: ...
    @property
    def side_effects(self) -> List[str]: ...
    @property
    def fallback_behavior(self) -> str: ...
    @property
    def notes(self) -> str: ...
    @property
    def warnings(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseRuleEvaluationPy:
    @property
    def kind(self) -> str: ...
    @property
    def evaluated(self) -> bool: ...
    @property
    def matched(self) -> bool: ...
    @property
    def exactness(self) -> str: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def summary(self) -> str: ...
    @property
    def unsupported(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseEvidenceItemPy:
    @property
    def id(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def summary(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def port(self) -> Optional[int]: ...
    @property
    def service(self) -> Optional[str]: ...
    @property
    def confidence(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def raw_excerpt(self) -> Optional[str]: ...
    @property
    def references(self) -> List[str]: ...
    @property
    def tags(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseReportPy:
    @property
    def target(self) -> str: ...
    @property
    def script_name(self) -> str: ...
    @property
    def output(self) -> str: ...
    @property
    def output_lines(self) -> int: ...
    @property
    def has_output(self) -> bool: ...
    @property
    def warnings(self) -> List[str]: ...
    @property
    def errors(self) -> List[str]: ...
    @property
    def library_count(self) -> int: ...
    @property
    def compatibility_status(self) -> str: ...
    @property
    def fidelity(self) -> str: ...
    @property
    def elapsed_secs(self) -> float: ...
    @property
    def libraries(self) -> List[NseLibraryUsePy]: ...
    @property
    def rules(self) -> List[NseRuleEvaluationPy]: ...
    @property
    def evidence(self) -> List[NseEvidenceItemPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseScriptMetadataPy:
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def author(self) -> Optional[str]: ...
    @property
    def license(self) -> Optional[str]: ...
    @property
    def dependencies(self) -> List[str]: ...
    @property
    def targets(self) -> Optional[str]: ...
    @property
    def categories(self) -> List[str]: ...
    @property
    def is_builtin(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseSandboxPolicyPy:
    @property
    def allow_filesystem(self) -> bool: ...
    @property
    def allowed_dirs(self) -> List[str]: ...
    @property
    def allow_network(self) -> bool: ...
    @property
    def allowed_cidrs(self) -> List[str]: ...
    @property
    def max_lua_instructions(self) -> int: ...
    @property
    def max_output_bytes(self) -> int: ...
    @property
    def max_network_ops(self) -> int: ...
    @property
    def max_memory_bytes(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseTargetContextPy:
    @property
    def host_ip(self) -> str: ...
    @property
    def hostname(self) -> Optional[str]: ...
    @property
    def port(self) -> Optional[int]: ...
    @property
    def protocol(self) -> Optional[str]: ...
    @property
    def service_name(self) -> Optional[str]: ...
    @property
    def service_product(self) -> Optional[str]: ...
    @property
    def service_version(self) -> Optional[str]: ...
    @property
    def os_detection(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseLibraryDescriptorPy:
    @property
    def name(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def sandbox_side_effects(self) -> List[str]: ...
    @property
    def fallback_behavior(self) -> str: ...
    @property
    def notes(self) -> str: ...
    @property
    def optional_deps(self) -> List[str]: ...
    @property
    def enforcement_status(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseArgumentPy:
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def arg_type(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NseLibraryRegistryPy:
    def __init__(self) -> None: ...
    def list(self) -> List[NseLibraryDescriptorPy]: ...
    def get(self, name: str) -> Optional[NseLibraryDescriptorPy]: ...
    def by_category(self, category: str) -> List[NseLibraryDescriptorPy]: ...
    def count(self) -> int: ...

def nse_run(target: str, script: str, *, script_args: Optional[str] = None, verbose: bool = False) -> NseReportPy: ...
def async_nse_run(target: str, script: str, *, script_args: Optional[str] = None, verbose: bool = False) -> Any: ...
def nse_list_libraries() -> List[str]: ...
def nse_list_libraries_detailed() -> List[NseLibraryDescriptorPy]: ...
def nse_get_library_descriptor(name: str) -> Optional[NseLibraryDescriptorPy]: ...
def nse_list_scripts(category: Optional[str] = None) -> List[NseScriptMetadataPy]: ...
def nse_get_script_metadata(name: str) -> Optional[NseScriptMetadataPy]: ...
def nse_run_with_config(config: NseConfigPy) -> NseReportPy: ...
def nse_validate_script(script: str) -> Dict[str, Any]: ...
