class OperationRiskPy:
    @staticmethod
    def passive() -> OperationRiskPy: ...
    @staticmethod
    def safe_active() -> OperationRiskPy: ...
    @staticmethod
    def intrusive() -> OperationRiskPy: ...
    @staticmethod
    def load_test() -> OperationRiskPy: ...
    @staticmethod
    def stress_test() -> OperationRiskPy: ...
    @staticmethod
    def raw_packet() -> OperationRiskPy: ...
    @staticmethod
    def credential_testing() -> OperationRiskPy: ...
    @staticmethod
    def db_pentest() -> OperationRiskPy: ...
    @staticmethod
    def traffic_interception() -> OperationRiskPy: ...
    @staticmethod
    def exploit_adjacent() -> OperationRiskPy: ...
    @staticmethod
    def evasion_testing() -> OperationRiskPy: ...
    @staticmethod
    def post_exploitation() -> OperationRiskPy: ...
    @staticmethod
    def c2_operation() -> OperationRiskPy: ...
    @staticmethod
    def remote_execution() -> OperationRiskPy: ...
    @staticmethod
    def agent_autonomous() -> OperationRiskPy: ...
    @property
    def name(self) -> str: ...
    @property
    def level(self) -> int: ...

class OperationModePy:
    @staticmethod
    def standard_assessment() -> OperationModePy: ...
    @staticmethod
    def defense_lab() -> OperationModePy: ...
    @staticmethod
    def hazardous_lab() -> OperationModePy: ...
    @property
    def name(self) -> str: ...

class IntendedUsePy:
    @staticmethod
    def web_assessment() -> IntendedUsePy: ...
    @staticmethod
    def api_assessment() -> IntendedUsePy: ...
    @staticmethod
    def waf_regression() -> IntendedUsePy: ...
    @staticmethod
    def synvoid_regression() -> IntendedUsePy: ...
    @staticmethod
    def distributed_system_stress() -> IntendedUsePy: ...
    @staticmethod
    def protocol_edge_validation() -> IntendedUsePy: ...
    @staticmethod
    def ci_regression() -> IntendedUsePy: ...
    @staticmethod
    def coding_agent_verification() -> IntendedUsePy: ...
    @property
    def name(self) -> str: ...

class CapabilityPy:
    @staticmethod
    def passive_fingerprint() -> CapabilityPy: ...
    @staticmethod
    def active_probe() -> CapabilityPy: ...
    @staticmethod
    def crawl() -> CapabilityPy: ...
    @staticmethod
    def http_fuzz_low_impact() -> CapabilityPy: ...
    @staticmethod
    def intrusive_fuzz() -> CapabilityPy: ...
    @staticmethod
    def waf_detect() -> CapabilityPy: ...
    @staticmethod
    def waf_bypass_simulation() -> CapabilityPy: ...
    @staticmethod
    def waf_stress_test() -> CapabilityPy: ...
    @staticmethod
    def load_test() -> CapabilityPy: ...
    @staticmethod
    def raw_packet_probe() -> CapabilityPy: ...
    @staticmethod
    def credential_testing() -> CapabilityPy: ...
    @staticmethod
    def remote_execution() -> CapabilityPy: ...
    @staticmethod
    def nse_safe() -> CapabilityPy: ...
    @staticmethod
    def nse_intrusive() -> CapabilityPy: ...
    @staticmethod
    def traffic_interception() -> CapabilityPy: ...
    @staticmethod
    def evasion_testing() -> CapabilityPy: ...
    @staticmethod
    def database_assessment() -> CapabilityPy: ...
    @staticmethod
    def c2_simulation() -> CapabilityPy: ...
    @staticmethod
    def mobile_dynamic_analysis() -> CapabilityPy: ...
    @property
    def name(self) -> str: ...

class DenialClassPy:
    @staticmethod
    def scope_missing() -> DenialClassPy: ...
    @staticmethod
    def target_out_of_scope() -> DenialClassPy: ...
    @staticmethod
    def explicit_exclusion() -> DenialClassPy: ...
    @staticmethod
    def feature_missing() -> DenialClassPy: ...
    @staticmethod
    def risk_policy_denied() -> DenialClassPy: ...
    @staticmethod
    def capability_denied() -> DenialClassPy: ...
    @staticmethod
    def invalid_target() -> DenialClassPy: ...
    @staticmethod
    def unknown() -> DenialClassPy: ...
    @property
    def name(self) -> str: ...

class TargetPolicyKindPy:
    @staticmethod
    def no_target() -> TargetPolicyKindPy: ...
    @staticmethod
    def optional_target() -> TargetPolicyKindPy: ...
    @staticmethod
    def target_required() -> TargetPolicyKindPy: ...
    @staticmethod
    def explicit_scope_required() -> TargetPolicyKindPy: ...
    @staticmethod
    def private_or_local_required() -> TargetPolicyKindPy: ...
    @property
    def name(self) -> str: ...

class OperationDescriptorPy:
    @property
    def operation_id(self) -> str: ...
    @property
    def operation_name(self) -> str: ...
    @property
    def mode(self) -> OperationModePy: ...
    @property
    def risk(self) -> OperationRiskPy: ...
    @property
    def intended_uses(self) -> list[IntendedUsePy]: ...
    @property
    def target(self) -> str | None: ...
    @property
    def required_features(self) -> list[str]: ...
    @property
    def required_capabilities(self) -> list[CapabilityPy]: ...
    @property
    def denied_capabilities(self) -> list[CapabilityPy]: ...
    @property
    def target_policy(self) -> TargetPolicyKindPy: ...

class OperationMetadataViewPy:
    @property
    def operation_id(self) -> str: ...
    @property
    def operation_name(self) -> str: ...
    @property
    def default_risk(self) -> OperationRiskPy: ...
    @property
    def default_mode(self) -> OperationModePy: ...
    @property
    def target_policy(self) -> TargetPolicyKindPy: ...
    @property
    def request_schema(self) -> str | None: ...
    @property
    def result_schema(self) -> str | None: ...
    @property
    def feature_required(self) -> str | None: ...
    @property
    def python_async_available(self) -> bool: ...
    @property
    def supported_surfaces(self) -> list[str]: ...
    @property
    def default_timeout_ms(self) -> int | None: ...
    def descriptor_for_target(self, target: str | None = None) -> OperationDescriptorPy: ...
    def to_dict(self) -> dict: ...

class OperationRegistry:
    @staticmethod
    def all_operations() -> list[OperationMetadataViewPy]: ...
    @staticmethod
    def find(operation_id: str) -> OperationMetadataViewPy | None: ...
    @staticmethod
    def find_by_tool_id(tool_id: str) -> OperationMetadataViewPy | None: ...
    @staticmethod
    def operation_count() -> int: ...
    @staticmethod
    def operations_for_feature(feature: str) -> list[OperationMetadataViewPy]: ...
    @staticmethod
    def operations_for_surface(surface: str) -> list[OperationMetadataViewPy]: ...
    @staticmethod
    def operation_ids() -> list[str]: ...
    @staticmethod
    def operation_names() -> list[str]: ...
