class OperationRiskPy:
    @staticmethod
    def passive() -> OperationRiskPy: ...
    @staticmethod
    def read_only() -> OperationRiskPy: ...
    @staticmethod
    def low() -> OperationRiskPy: ...
    @staticmethod
    def medium() -> OperationRiskPy: ...
    @staticmethod
    def elevated() -> OperationRiskPy: ...
    @staticmethod
    def high() -> OperationRiskPy: ...
    @staticmethod
    def destructive() -> OperationRiskPy: ...
    @staticmethod
    def intrusive() -> OperationRiskPy: ...
    @staticmethod
    def credential_access() -> OperationRiskPy: ...
    @staticmethod
    def network_intrusion() -> OperationRiskPy: ...
    @staticmethod
    def denial_of_service() -> OperationRiskPy: ...
    @staticmethod
    def data_exfiltration() -> OperationRiskPy: ...
    @staticmethod
    def privilege_escalation() -> OperationRiskPy: ...
    @staticmethod
    def persistence() -> OperationRiskPy: ...
    @staticmethod
    def agent_autonomous() -> OperationRiskPy: ...
    @property
    def name(self) -> str: ...
    @property
    def level(self) -> int: ...

class OperationModePy:
    @staticmethod
    def standard_assessment() -> OperationModePy: ...
    @staticmethod
    def defense_lab() -> OperationModePy: ...
    @staticmethod
    def hazardous_lab() -> OperationModePy: ...
    @property
    def name(self) -> str: ...

class IntendedUsePy:
    @staticmethod
    def web_assessment() -> IntendedUsePy: ...
    @staticmethod
    def api_assessment() -> IntendedUsePy: ...
    @staticmethod
    def network_assessment() -> IntendedUsePy: ...
    @staticmethod
    def wireless_assessment() -> IntendedUsePy: ...
    @staticmethod
    def database_assessment() -> IntendedUsePy: ...
    @staticmethod
    def mobile_assessment() -> IntendedUsePy: ...
    @staticmethod
    def cloud_assessment() -> IntendedUsePy: ...
    @staticmethod
    def general_assessment() -> IntendedUsePy: ...
    @property
    def name(self) -> str: ...

class CapabilityPy:
    @staticmethod
    def passive_fingerprint() -> CapabilityPy: ...
    @staticmethod
    def active_fingerprint() -> CapabilityPy: ...
    @staticmethod
    def port_scan() -> CapabilityPy: ...
    @staticmethod
    def service_detection() -> CapabilityPy: ...
    @staticmethod
    def vulnerability_scan() -> CapabilityPy: ...
    @staticmethod
    def exploit_simulation() -> CapabilityPy: ...
    @staticmethod
    def credential_test() -> CapabilityPy: ...
    @staticmethod
    def web_crawl() -> CapabilityPy: ...
    @staticmethod
    def web_fuzz() -> CapabilityPy: ...
    @staticmethod
    def web_inject() -> CapabilityPy: ...
    @staticmethod
    def proxy_required() -> CapabilityPy: ...
    @staticmethod
    def packet_capture() -> CapabilityPy: ...
    @staticmethod
    def packet_injection() -> CapabilityPy: ...
    @staticmethod
    def stress_test() -> CapabilityPy: ...
    @staticmethod
    def denial_of_service() -> CapabilityPy: ...
    @staticmethod
    def nse_script() -> CapabilityPy: ...
    @staticmethod
    def database_query() -> CapabilityPy: ...
    @staticmethod
    def mobile_static() -> CapabilityPy: ...
    @staticmethod
    def mobile_dynamic_analysis() -> CapabilityPy: ...
    @property
    def name(self) -> str: ...

class DenialClassPy:
    @staticmethod
    def scope_missing() -> DenialClassPy: ...
    @staticmethod
    def target_out_of_scope() -> DenialClassPy: ...
    @staticmethod
    def explicit_exclusion() -> DenialClassPy: ...
    @staticmethod
    def risk_too_high() -> DenialClassPy: ...
    @staticmethod
    def capability_denied() -> DenialClassPy: ...
    @staticmethod
    def feature_unavailable() -> DenialClassPy: ...
    @staticmethod
    def policy_violation() -> DenialClassPy: ...
    @staticmethod
    def surface_mismatch() -> DenialClassPy: ...
    @property
    def name(self) -> str: ...

class TargetPolicyKindPy:
    @staticmethod
    def no_target() -> TargetPolicyKindPy: ...
    @staticmethod
    def optional_target() -> TargetPolicyKindPy: ...
    @staticmethod
    def target_required() -> TargetPolicyKindPy: ...
    @staticmethod
    def explicit_scope_required() -> TargetPolicyKindPy: ...
    @staticmethod
    def private_or_local_required() -> TargetPolicyKindPy: ...
    @property
    def name(self) -> str: ...

class OperationDescriptorPy:
    @property
    def operation_id(self) -> str: ...
    @property
    def operation_label(self) -> str: ...
    @property
    def risk(self) -> OperationRiskPy: ...
    @property
    def mode(self) -> OperationModePy: ...
    @property
    def intended_uses(self) -> list[IntendedUsePy]: ...
    @property
    def required_capabilities(self) -> list[CapabilityPy]: ...
    @property
    def requires_explicit_scope(self) -> bool: ...
    @property
    def requires_target(self) -> bool: ...
    @property
    def requires_network(self) -> bool: ...
    @property
    def required_features(self) -> list[str]: ...
    @property
    def target_policy(self) -> TargetPolicyKindPy: ...

class OperationMetadataViewPy:
    @property
    def operation_id(self) -> str: ...
    @property
    def label(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def risk(self) -> OperationRiskPy: ...
    @property
    def required_features(self) -> list[str]: ...
    @property
    def required_capabilities(self) -> list[CapabilityPy]: ...
    @property
    def target_required(self) -> bool: ...
    @property
    def target_policy(self) -> TargetPolicyKindPy: ...
    def descriptor_for_target(self, target: str | None = None) -> OperationDescriptorPy: ...

class OperationRegistry:
    @staticmethod
    def all_operations() -> list[OperationMetadataViewPy]: ...
    @staticmethod
    def find(operation_id: str) -> OperationMetadataViewPy | None: ...
    @staticmethod
    def find_by_tool_id(tool_id: str) -> OperationMetadataViewPy | None: ...
