from typing import Any, Dict, List, Optional

class CaptureConfigPy:
    @property
    def interface(self) -> str: ...
    @property
    def filter(self) -> Optional[str]: ...
    @property
    def promiscuous(self) -> bool: ...
    @property
    def snapshot_len(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def max_packets(self) -> Optional[int]: ...
    @property
    def save_to_file(self) -> Optional[str]: ...
    @property
    def validate_checksums(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CaptureStatsPy:
    @property
    def packets_captured(self) -> int: ...
    @property
    def bytes_captured(self) -> int: ...
    @property
    def packets_dropped(self) -> int: ...
    @property
    def runtime_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PacketInfoPy:
    @property
    def timestamp(self) -> str: ...
    @property
    def src_ip(self) -> Optional[str]: ...
    @property
    def dst_ip(self) -> Optional[str]: ...
    @property
    def protocol(self) -> str: ...
    @property
    def src_port(self) -> Optional[int]: ...
    @property
    def dst_port(self) -> Optional[int]: ...
    @property
    def size(self) -> int: ...
    @property
    def summary(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NetworkInterfaceInfoPy:
    @property
    def name(self) -> str: ...
    @property
    def ips(self) -> List[str]: ...
    @property
    def mac(self) -> Optional[str]: ...
    @property
    def is_up(self) -> bool: ...
    @property
    def is_loopback(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PcapWriterPy:
    def __init__(self, path: str, snapshot_len: int = 65535) -> None: ...
    def write_packet(self, data: bytes) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __enter__(self) -> PcapWriterPy: ...
    def __exit__(self, exc_type: Any = None, exc_value: Any = None, traceback: Any = None) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def list_network_interfaces() -> List[NetworkInterfaceInfoPy]: ...
def parse_pcap(file_path: str, max_packets: int = 10000) -> List[PacketInfoPy]: ...

class PacketFilterPy:
    @property
    def src_ip(self) -> Optional[str]: ...
    @property
    def dst_ip(self) -> Optional[str]: ...
    @property
    def protocol(self) -> Optional[str]: ...
    @property
    def src_port(self) -> Optional[int]: ...
    @property
    def dst_port(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FlowRecordPy:
    @property
    def src_ip(self) -> str: ...
    @property
    def dst_ip(self) -> str: ...
    @property
    def src_port(self) -> int: ...
    @property
    def dst_port(self) -> int: ...
    @property
    def protocol(self) -> str: ...
    @property
    def packet_count(self) -> int: ...
    @property
    def byte_count(self) -> int: ...
    @property
    def first_seen_ms(self) -> int: ...
    @property
    def last_seen_ms(self) -> int: ...
    @property
    def tcp_flags_seen(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class LiveCaptureResultPy:
    @property
    def interface(self) -> str: ...
    @property
    def packets_captured(self) -> int: ...
    @property
    def packets_dropped(self) -> int: ...
    @property
    def bytes_captured(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def flows(self) -> List[FlowRecordPy]: ...
    @property
    def packets(self) -> List[PacketInfoPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# WS7: Managed capture lifecycle
class BackpressurePolicyPy:
    Block: "BackpressurePolicyPy"
    DropOldest: "BackpressurePolicyPy"
    DropNewest: "BackpressurePolicyPy"
    ArtifactOnly: "BackpressurePolicyPy"
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CaptureDropStatsPy:
    @property
    def dropped_by_policy(self) -> int: ...
    @property
    def dropped_by_full_queue(self) -> int: ...
    @property
    def dropped_by_error(self) -> int: ...
    @property
    def total_dropped(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CapturedPacketPy:
    @property
    def sequence(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def captured_len(self) -> int: ...
    @property
    def original_len(self) -> int: ...
    @property
    def info(self) -> PacketInfoPy: ...
    def raw_bytes(self) -> bytes: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class AsyncCaptureSessionPy:
    def __init__(self, config: CaptureConfigPy, *, backpressure: Optional[BackpressurePolicyPy] = None, queue_size: int = 1000) -> None: ...
    @property
    def is_running(self) -> bool: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def interface(self) -> str: ...
    @property
    def queue_size(self) -> int: ...
    def start(self) -> None: ...
    def stop(self) -> CaptureStatsPy: ...
    def drop_stats(self) -> CaptureDropStatsPy: ...
    def stats(self) -> CaptureStatsPy: ...
    def __enter__(self) -> AsyncCaptureSessionPy: ...
    def __exit__(self, *args: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# WS8: Packet layer DTOs
class EthernetFramePy:
    @property
    def src_mac(self) -> str: ...
    @property
    def dst_mac(self) -> str: ...
    @property
    def ether_type(self) -> int: ...
    @property
    def ether_type_name(self) -> str: ...
    @property
    def vlan_id(self) -> Optional[int]: ...
    @property
    def payload_len(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Ipv4PacketPy:
    @property
    def src_ip(self) -> str: ...
    @property
    def dst_ip(self) -> str: ...
    @property
    def protocol(self) -> int: ...
    @property
    def protocol_name(self) -> str: ...
    @property
    def ttl(self) -> int: ...
    @property
    def tos(self) -> int: ...
    @property
    def total_length(self) -> int: ...
    @property
    def fragment_offset(self) -> int: ...
    @property
    def flags(self) -> List[str]: ...
    @property
    def header_checksum(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Ipv6PacketPy:
    @property
    def src_ip(self) -> str: ...
    @property
    def dst_ip(self) -> str: ...
    @property
    def next_header(self) -> int: ...
    @property
    def next_header_name(self) -> str: ...
    @property
    def hop_limit(self) -> int: ...
    @property
    def payload_length(self) -> int: ...
    @property
    def flow_label(self) -> int: ...
    @property
    def traffic_class(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TcpSegmentPy:
    @property
    def src_port(self) -> int: ...
    @property
    def dst_port(self) -> int: ...
    @property
    def seq_num(self) -> int: ...
    @property
    def ack_num(self) -> int: ...
    @property
    def data_offset(self) -> int: ...
    @property
    def flags(self) -> List[str]: ...
    @property
    def window_size(self) -> int: ...
    @property
    def urgent_pointer(self) -> int: ...
    @property
    def options(self) -> List[str]: ...
    @property
    def payload_len(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class UdpDatagramPy:
    @property
    def src_port(self) -> int: ...
    @property
    def dst_port(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def checksum(self) -> Optional[int]: ...
    @property
    def payload_len(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class IcmpPacketPy:
    @property
    def icmp_type(self) -> int: ...
    @property
    def icmp_type_name(self) -> str: ...
    @property
    def icmp_code(self) -> int: ...
    @property
    def checksum(self) -> Optional[int]: ...
    @property
    def id(self) -> Optional[int]: ...
    @property
    def sequence(self) -> Optional[int]: ...
    @property
    def payload_len(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FlowKeyPy:
    @property
    def src_ip(self) -> str: ...
    @property
    def dst_ip(self) -> str: ...
    @property
    def src_port(self) -> int: ...
    @property
    def dst_port(self) -> int: ...
    @property
    def protocol(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FlowAggregatorPy:
    def __init__(self, max_flows: int = 10000) -> None: ...
    def record_packet(self, src_ip: str, dst_ip: str, src_port: int, dst_port: int, protocol: str, packet_size: int, timestamp_ms: int, tcp_flags: Optional[List[str]] = None) -> None: ...
    def get_flows(self) -> List[FlowRecordPy]: ...
    def flow_count(self) -> int: ...
    def eviction_count(self) -> int: ...
    def total_packets(self) -> int: ...
    def total_bytes(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# WS9: Active probe types
class IcmpProbeConfigPy:
    @property
    def target(self) -> str: ...
    @property
    def count(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def packet_size(self) -> int: ...
    @property
    def ttl(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class IcmpProbeReplyPy:
    @property
    def seq(self) -> int: ...
    @property
    def rtt_ms(self) -> float: ...
    @property
    def ttl(self) -> int: ...
    @property
    def bytes(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class IcmpProbeResultPy:
    @property
    def target(self) -> str: ...
    @property
    def resolved_address(self) -> Optional[str]: ...
    @property
    def reachable(self) -> bool: ...
    @property
    def replies(self) -> List[IcmpProbeReplyPy]: ...
    @property
    def packets_sent(self) -> int: ...
    @property
    def packets_received(self) -> int: ...
    @property
    def min_rtt_ms(self) -> Optional[float]: ...
    @property
    def max_rtt_ms(self) -> Optional[float]: ...
    @property
    def avg_rtt_ms(self) -> Optional[float]: ...
    @property
    def packet_loss_pct(self) -> float: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TcpProbeConfigPy:
    @property
    def target(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def ttl(self) -> int: ...
    @property
    def source_port(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class TcpProbeResultPy:
    @property
    def target(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def state(self) -> str: ...
    @property
    def rtt_ms(self) -> Optional[float]: ...
    @property
    def ttl(self) -> Optional[int]: ...
    @property
    def window_size(self) -> Optional[int]: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def icmp_probe(config: IcmpProbeConfigPy) -> IcmpProbeResultPy: ...
def async_icmp_probe(config: IcmpProbeConfigPy) -> Any: ...
def tcp_syn_probe(config: TcpProbeConfigPy) -> TcpProbeResultPy: ...
def async_tcp_syn_probe(config: TcpProbeConfigPy) -> Any: ...

# Traceroute
class TracerouteConfigPy:
    @property
    def target(self) -> str: ...
    @property
    def max_hops(self) -> int: ...
    @property
    def timeout_secs(self) -> int: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def first_ttl(self) -> int: ...
    @property
    def port(self) -> int: ...
    @property
    def use_icmp(self) -> bool: ...
    @property
    def resolve_names(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def __repr__(self) -> str: ...

class TracerouteHopPy:
    @property
    def hop(self) -> int: ...
    @property
    def address(self) -> Optional[str]: ...
    @property
    def rtt_ms(self) -> Optional[float]: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def is_final(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TracerouteResultPy:
    @property
    def target(self) -> str: ...
    @property
    def resolved_address(self) -> str: ...
    @property
    def hops(self) -> List[TracerouteHopPy]: ...
    @property
    def total_hops(self) -> int: ...
    @property
    def success(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def run_traceroute(config: TracerouteConfigPy) -> TracerouteResultPy: ...
def async_run_traceroute(config: TracerouteConfigPy) -> Any: ...
def traceroute(target: str, max_hops: int = 30, timeout_secs: int = 3) -> TracerouteResultPy: ...
