from typing import Any, Dict, List, Optional

class CaptureConfigPy:
    @property
    def interface(self) -> str: ...
    @property
    def filter(self) -> Optional[str]: ...
    @property
    def promiscuous(self) -> bool: ...
    @property
    def snapshot_len(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def max_packets(self) -> Optional[int]: ...
    @property
    def save_to_file(self) -> Optional[str]: ...
    @property
    def validate_checksums(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CaptureStatsPy:
    @property
    def packets_captured(self) -> int: ...
    @property
    def bytes_captured(self) -> int: ...
    @property
    def packets_dropped(self) -> int: ...
    @property
    def runtime_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PacketInfoPy:
    @property
    def timestamp(self) -> str: ...
    @property
    def src_ip(self) -> Optional[str]: ...
    @property
    def dst_ip(self) -> Optional[str]: ...
    @property
    def protocol(self) -> str: ...
    @property
    def src_port(self) -> Optional[int]: ...
    @property
    def dst_port(self) -> Optional[int]: ...
    @property
    def size(self) -> int: ...
    @property
    def summary(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NetworkInterfaceInfoPy:
    @property
    def name(self) -> str: ...
    @property
    def ips(self) -> List[str]: ...
    @property
    def mac(self) -> Optional[str]: ...
    @property
    def is_up(self) -> bool: ...
    @property
    def is_loopback(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PcapWriterPy:
    def __init__(self, path: str, snapshot_len: int = 65535) -> None: ...
    def write_packet(self, data: bytes) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def __enter__(self) -> PcapWriterPy: ...
    def __exit__(self, exc_type: Any = None, exc_value: Any = None, traceback: Any = None) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def list_network_interfaces() -> List[NetworkInterfaceInfoPy]: ...
def parse_pcap(file_path: str, max_packets: int = 10000) -> List[PacketInfoPy]: ...

class PacketFilterPy:
    @property
    def src_ip(self) -> Optional[str]: ...
    @property
    def dst_ip(self) -> Optional[str]: ...
    @property
    def protocol(self) -> Optional[str]: ...
    @property
    def src_port(self) -> Optional[int]: ...
    @property
    def dst_port(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FlowRecordPy:
    @property
    def src_ip(self) -> str: ...
    @property
    def dst_ip(self) -> str: ...
    @property
    def src_port(self) -> int: ...
    @property
    def dst_port(self) -> int: ...
    @property
    def protocol(self) -> str: ...
    @property
    def packet_count(self) -> int: ...
    @property
    def byte_count(self) -> int: ...
    @property
    def first_seen(self) -> str: ...
    @property
    def last_seen(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class LiveCaptureResultPy:
    @property
    def interface(self) -> str: ...
    @property
    def packets_captured(self) -> int: ...
    @property
    def packets_dropped(self) -> int: ...
    @property
    def bytes_captured(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def flows(self) -> List[FlowRecordPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TracerouteConfigPy:
    @property
    def target(self) -> str: ...
    @property
    def max_hops(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def first_ttl(self) -> int: ...
    @property
    def port(self) -> int: ...
    @property
    def use_icmp(self) -> bool: ...
    @property
    def resolve_names(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TracerouteHopPy:
    @property
    def hop(self) -> int: ...
    @property
    def address(self) -> Optional[str]: ...
    @property
    def rtt_ms(self) -> Optional[float]: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def is_final(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TracerouteResultPy:
    @property
    def target(self) -> str: ...
    @property
    def resolved_address(self) -> str: ...
    @property
    def hops(self) -> List[TracerouteHopPy]: ...
    @property
    def total_hops(self) -> int: ...
    @property
    def success(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def run_traceroute(target: str, *, max_hops: int = 30, timeout_ms: int = 5000, resolve_names: bool = True) -> TracerouteResultPy: ...
def async_run_traceroute(target: str, *, max_hops: int = 30, timeout_ms: int = 5000, resolve_names: bool = True) -> Any: ...
def traceroute(target: str, *, max_hops: int = 30, timeout_ms: int = 5000) -> TracerouteResultPy: ...
