from typing import Any, Dict, List, Optional

class CaptureConfigPy:
    @property
    def interface(self) -> str: ...
    @property
    def filter(self) -> Optional[str]: ...
    @property
    def promiscuous(self) -> bool: ...
    @property
    def snapshot_len(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def max_packets(self) -> Optional[int]: ...
    @property
    def save_to_file(self) -> Optional[str]: ...
    @property
    def validate_checksums(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CaptureStatsPy:
    @property
    def packets_captured(self) -> int: ...
    @property
    def bytes_captured(self) -> int: ...
    @property
    def packets_dropped(self) -> int: ...
    @property
    def runtime_ms(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PacketInfoPy:
    @property
    def timestamp(self) -> str: ...
    @property
    def src_ip(self) -> Optional[str]: ...
    @property
    def dst_ip(self) -> Optional[str]: ...
    @property
    def protocol(self) -> str: ...
    @property
    def src_port(self) -> Optional[int]: ...
    @property
    def dst_port(self) -> Optional[int]: ...
    @property
    def size(self) -> int: ...
    @property
    def summary(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NetworkInterfaceInfoPy:
    @property
    def name(self) -> str: ...
    @property
    def ips(self) -> List[str]: ...
    @property
    def mac(self) -> Optional[str]: ...
    @property
    def is_up(self) -> bool: ...
    @property
    def is_loopback(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PcapWriterPy:
    def __init__(self, path: str, snapshot_len: int = 65535) -> None: ...
    def write_packet(self, data: bytes) -> None: ...
    def flush(self) -> None: ...

def list_network_interfaces() -> List[NetworkInterfaceInfoPy]: ...
def parse_pcap(file_path: str, max_packets: int = 10000) -> List[PacketInfoPy]: ...
