from typing import Optional, List
from .status import ExecutionStatus, OperationResult
from .requests import OperationRequest
from .checkpoint import Checkpoint

class PipelineStep:
    def __init__(
        self,
        name: str,
        request: OperationRequest,
        *,
        condition: Optional[str] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def request(self) -> OperationRequest: ...
    @property
    def condition(self) -> Optional[str]: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class StepResult:
    def __init__(
        self,
        step_name: str,
        status: ExecutionStatus,
        *,
        result: Optional[OperationResult] = None,
        duration_ms: int = 0,
    ) -> None: ...
    @property
    def step_name(self) -> str: ...
    @property
    def status(self) -> ExecutionStatus: ...
    @property
    def result(self) -> Optional[OperationResult]: ...
    @property
    def duration_ms(self) -> int: ...
    def is_success(self) -> bool: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PipelineResult:
    def __init__(
        self,
        name: str,
        status: ExecutionStatus,
        *,
        step_results: Optional[List[StepResult]] = None,
        total_duration_ms: int = 0,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def status(self) -> ExecutionStatus: ...
    @property
    def step_results(self) -> List[StepResult]: ...
    @property
    def total_duration_ms(self) -> int: ...
    def is_success(self) -> bool: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Pipeline:
    def __init__(self, name: str) -> None: ...
    def add_step(
        self,
        name: str,
        request: OperationRequest,
        *,
        condition: Optional[str] = None,
    ) -> Pipeline: ...
    def set_stop_on_failure(self, stop: bool) -> None: ...
    def set_checkpoint_store(self, store: "CheckpointStore") -> None: ...
    def run(self, engine: "Engine") -> PipelineResult: ...
    def resume_from(
        self,
        engine: "Engine",
        checkpoint: Checkpoint,
    ) -> PipelineResult: ...
    def steps_count(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def steps(self) -> List[PipelineStep]: ...
    @property
    def stop_on_failure(self) -> bool: ...
    def __repr__(self) -> str: ...

class AsyncPipeline:
    def __init__(self, name: str) -> None: ...
    def add_step(
        self,
        name: str,
        request: OperationRequest,
        *,
        condition: Optional[str] = None,
    ) -> AsyncPipeline: ...
    def set_stop_on_failure(self, stop: bool) -> None: ...
    def set_checkpoint_store(self, store: "CheckpointStore") -> None: ...
    def run(self, engine: "AsyncEngine") -> "PyFuture": ...
    def steps_count(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def steps(self) -> List[PipelineStep]: ...
    @property
    def stop_on_failure(self) -> bool: ...
    def __repr__(self) -> str: ...
