from typing import Optional, List
from .status import ExecutionStatus, OperationResult
from .requests import OperationRequest
from .checkpoint import Checkpoint

class OutputRef:
    def __init__(self, step_id: str, path: str) -> None: ...
    @property
    def step_id(self) -> str: ...
    @property
    def path(self) -> str: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class RetryPolicy:
    def __init__(
        self,
        max_attempts: int = 1,
        retryable_errors: Optional[List[str]] = None,
        backoff_ms: int = 1000,
        max_delay_ms: int = 30000,
        jitter: bool = True,
    ) -> None: ...
    @property
    def max_attempts(self) -> int: ...
    @property
    def retryable_errors(self) -> List[str]: ...
    @property
    def backoff_ms(self) -> int: ...
    @property
    def max_delay_ms(self) -> int: ...
    @property
    def jitter(self) -> bool: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class FailurePolicy:
    StopPipeline: int
    Continue: int
    SkipDependents: int
    def to_dict(self) -> dict: ...
    def __repr__(self) -> str: ...

class PipelineStep:
    def __init__(
        self,
        name: str,
        request: OperationRequest,
        *,
        condition: Optional[str] = None,
        dependencies: Optional[List[str]] = None,
        timeout_ms: Optional[int] = None,
        parallel_group: Optional[str] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def request(self) -> OperationRequest: ...
    @property
    def condition(self) -> Optional[str]: ...
    @property
    def dependencies(self) -> List[str]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    @property
    def parallel_group(self) -> Optional[str]: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class StepResult:
    def __init__(
        self,
        step_name: str,
        status: ExecutionStatus,
        *,
        result: Optional[OperationResult] = None,
        duration_ms: int = 0,
        attempt: int = 1,
    ) -> None: ...
    @property
    def step_name(self) -> str: ...
    @property
    def status(self) -> ExecutionStatus: ...
    @property
    def result(self) -> Optional[OperationResult]: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def attempt(self) -> int: ...
    def is_success(self) -> bool: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PipelineResult:
    def __init__(
        self,
        name: str,
        status: ExecutionStatus,
        *,
        step_results: Optional[List[StepResult]] = None,
        total_duration_ms: int = 0,
        retried_steps: int = 0,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def status(self) -> ExecutionStatus: ...
    @property
    def step_results(self) -> List[StepResult]: ...
    @property
    def total_duration_ms(self) -> int: ...
    @property
    def retried_steps(self) -> int: ...
    def is_success(self) -> bool: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Pipeline:
    def __init__(
        self,
        name: str,
        *,
        stop_on_failure: bool = True,
        retry_policy: Optional[RetryPolicy] = None,
        failure_policy: Optional[FailurePolicy] = None,
        max_concurrency: int = 1,
    ) -> None: ...
    def add_step(
        self,
        name: str,
        request: OperationRequest,
        *,
        condition: Optional[str] = None,
        dependencies: Optional[List[str]] = None,
        timeout_ms: Optional[int] = None,
        parallel_group: Optional[str] = None,
    ) -> Pipeline: ...
    def set_stop_on_failure(self, stop: bool) -> None: ...
    def set_checkpoint_store(self, store: "CheckpointStore") -> None: ...
    def run(self, engine: "Engine") -> PipelineResult: ...
    def resume_from(
        self,
        engine: "Engine",
        checkpoint: Checkpoint,
    ) -> PipelineResult: ...
    def steps_count(self) -> int: ...
    def pipeline_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def steps(self) -> List[PipelineStep]: ...
    @property
    def stop_on_failure(self) -> bool: ...
    @property
    def retry_policy(self) -> Optional[RetryPolicy]: ...
    @property
    def failure_policy(self) -> FailurePolicy: ...
    @property
    def max_concurrency(self) -> int: ...
    def __repr__(self) -> str: ...

class AsyncPipeline:
    def __init__(
        self,
        name: str,
        *,
        stop_on_failure: bool = True,
        retry_policy: Optional[RetryPolicy] = None,
        failure_policy: Optional[FailurePolicy] = None,
        max_concurrency: int = 1,
    ) -> None: ...
    def add_step(
        self,
        name: str,
        request: OperationRequest,
        *,
        condition: Optional[str] = None,
        dependencies: Optional[List[str]] = None,
        timeout_ms: Optional[int] = None,
        parallel_group: Optional[str] = None,
    ) -> AsyncPipeline: ...
    def set_stop_on_failure(self, stop: bool) -> None: ...
    def set_checkpoint_store(self, store: "CheckpointStore") -> None: ...
    def run(self, engine: "AsyncEngine") -> "PyFuture": ...
    def resume_from(
        self,
        engine: "AsyncEngine",
        checkpoint: Checkpoint,
    ) -> "PyFuture": ...
    def steps_count(self) -> int: ...
    def pipeline_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def steps(self) -> List[PipelineStep]: ...
    @property
    def stop_on_failure(self) -> bool: ...
    @property
    def retry_policy(self) -> Optional[RetryPolicy]: ...
    @property
    def failure_policy(self) -> FailurePolicy: ...
    @property
    def max_concurrency(self) -> int: ...
    def __repr__(self) -> str: ...
