from typing import List
from .requests import OperationRequest

class PlanStep:
    def __init__(
        self,
        operation: str,
        request: OperationRequest,
        rationale: str,
        priority: int = 1,
        estimated_duration_ms: int = 5000,
    ) -> None: ...
    @property
    def operation(self) -> str: ...
    @property
    def request(self) -> OperationRequest: ...
    @property
    def rationale(self) -> str: ...
    @property
    def priority(self) -> int: ...
    @property
    def estimated_duration_ms(self) -> int: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ScanPlan:
    def __init__(
        self,
        target: str,
        *,
        steps: List[PlanStep] = ...,
        estimated_total_ms: int = 0,
        scope_notes: List[str] = ...,
    ) -> None: ...
    @property
    def target(self) -> str: ...
    @property
    def steps(self) -> List[PlanStep]: ...
    @property
    def estimated_total_ms(self) -> int: ...
    @property
    def scope_notes(self) -> List[str]: ...
    def steps_count(self) -> int: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
