class PreflightResultPy:
    @property
    def operation_id(self) -> str: ...
    @property
    def target(self) -> str | None: ...
    @property
    def outcome(self) -> str: ...
    @property
    def requires_confirmation(self) -> bool: ...
    @property
    def confirmation_classes(self) -> list[str]: ...
    @property
    def suggested_cli_flags(self) -> list[str]: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def decision(self) -> object: ...
    @property
    def scope_status(self) -> str | None: ...
    @property
    def risk_level(self) -> str | None: ...
    @property
    def surface(self) -> str | None: ...
    @property
    def profile(self) -> str | None: ...
    @property
    def manual_override_honored(self) -> bool: ...
    @property
    def scope_path(self) -> str | None: ...

def preflight_operation(operation_id: str, target: str | None = None) -> PreflightResultPy: ...
def preflight_with_descriptor(descriptor: object, surface: object | None = None, override: object | None = None) -> PreflightResultPy: ...
