from typing import Any, Dict, List, Optional, Tuple
from .network import ConnectionTimingPy

class DnsQueryConfigPy:
    @property
    def domain(self) -> str: ...
    @property
    def record_types(self) -> List[str]: ...
    @property
    def resolver(self) -> Optional[str]: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def tcp_fallback(self) -> bool: ...
    @property
    def max_retries(self) -> int: ...
    def __init__(self, domain: str, record_types: Optional[List[str]] = None, resolver: Optional[str] = None, timeout_ms: int = 5000, tcp_fallback: bool = True, max_retries: int = 2) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DnsRecordPy:
    @property
    def record_type(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def data(self) -> str: ...
    @property
    def ttl(self) -> int: ...
    @property
    def cls(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DnsQueryResultPy:
    @property
    def domain(self) -> str: ...
    @property
    def records(self) -> List[DnsRecordPy]: ...
    @property
    def response_code(self) -> str: ...
    @property
    def authoritative(self) -> bool: ...
    @property
    def truncated(self) -> bool: ...
    @property
    def resolver_used(self) -> str: ...
    @property
    def timing(self) -> ConnectionTimingPy: ...
    @property
    def raw_artifact(self) -> Optional[str]: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TlsProbeConfigPy:
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def sni(self) -> Optional[str]: ...
    @property
    def alpn(self) -> List[str]: ...
    @property
    def min_version(self) -> Optional[str]: ...
    @property
    def max_version(self) -> Optional[str]: ...
    @property
    def verify_certificate(self) -> bool: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def include_chain(self) -> bool: ...
    def __init__(self, host: str, port: int = 443, sni: Optional[str] = None, alpn: Optional[List[str]] = None, min_version: Optional[str] = None, max_version: Optional[str] = None, verify_certificate: bool = True, timeout_ms: int = 10000, include_chain: bool = True) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CertificateInfoPy:
    @property
    def subject(self) -> str: ...
    @property
    def issuer(self) -> str: ...
    @property
    def valid_from(self) -> str: ...
    @property
    def valid_until(self) -> str: ...
    @property
    def serial_number(self) -> str: ...
    @property
    def signature_algorithm(self) -> str: ...
    @property
    def public_key_algorithm(self) -> str: ...
    @property
    def key_size(self) -> Optional[int]: ...
    @property
    def is_expired(self) -> bool: ...
    @property
    def days_until_expiry(self) -> Optional[int]: ...
    @property
    def subject_alternative_names(self) -> List[str]: ...
    @property
    def chain(self) -> List[CertificateChainEntryPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CertificateChainEntryPy:
    @property
    def subject(self) -> str: ...
    @property
    def issuer(self) -> str: ...
    @property
    def valid_from(self) -> str: ...
    @property
    def valid_until(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TlsProbeResultPy:
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def has_tls(self) -> bool: ...
    @property
    def tls_version(self) -> Optional[str]: ...
    @property
    def cipher_suite(self) -> Optional[str]: ...
    @property
    def alpn_negotiated(self) -> Optional[str]: ...
    @property
    def certificate(self) -> Optional[CertificateInfoPy]: ...
    @property
    def hostname_verified(self) -> bool: ...
    @property
    def certificate_verified(self) -> bool: ...
    @property
    def supported_versions(self) -> List[str]: ...
    @property
    def supported_ciphers(self) -> List[str]: ...
    @property
    def issues(self) -> List[TlsIssuePy]: ...
    @property
    def timing(self) -> ConnectionTimingPy: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TlsIssuePy:
    @property
    def severity(self) -> str: ...
    @property
    def code(self) -> str: ...
    @property
    def description(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HttpProbeConfigPy:
    @property
    def url(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def headers(self) -> List[Tuple[str, str]]: ...
    @property
    def body(self) -> Optional[str]: ...
    @property
    def follow_redirects(self) -> bool: ...
    @property
    def max_redirects(self) -> int: ...
    @property
    def verify_tls(self) -> bool: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def user_agent(self) -> Optional[str]: ...
    def __init__(self, url: str, method: str = "GET", headers: Optional[List[Tuple[str, str]]] = None, body: Optional[str] = None, follow_redirects: bool = True, max_redirects: int = 10, verify_tls: bool = True, timeout_ms: int = 10000, user_agent: Optional[str] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HttpProbeResultPy:
    @property
    def url(self) -> str: ...
    @property
    def final_url(self) -> Optional[str]: ...
    @property
    def status_code(self) -> int: ...
    @property
    def reason(self) -> Optional[str]: ...
    @property
    def headers(self) -> List[Tuple[str, str]]: ...
    @property
    def body_bytes(self) -> bytes: ...
    @property
    def body_text(self) -> Optional[str]: ...
    @property
    def content_length(self) -> Optional[int]: ...
    @property
    def redirect_count(self) -> int: ...
    @property
    def timing(self) -> ConnectionTimingPy: ...
    @property
    def tls_metadata(self) -> Optional[TlsProbeResultPy]: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def dns_query(domain: str, record_types: Optional[List[str]] = None, resolver: Optional[str] = None, timeout_ms: int = 5000) -> DnsQueryResultPy: ...
def async_dns_query(domain: str, record_types: Optional[List[str]] = None, resolver: Optional[str] = None, timeout_ms: int = 5000) -> Any: ...
def tls_probe(host: str, port: int = 443, sni: Optional[str] = None, timeout_ms: int = 10000, verify_certificate: bool = True) -> TlsProbeResultPy: ...
def async_tls_probe(host: str, port: int = 443, sni: Optional[str] = None, timeout_ms: int = 10000, verify_certificate: bool = True) -> Any: ...
def http_probe(url: str, method: str = "GET", timeout_ms: int = 10000, follow_redirects: bool = True) -> HttpProbeResultPy: ...
def async_http_probe(url: str, method: str = "GET", timeout_ms: int = 10000, follow_redirects: bool = True) -> Any: ...

class UdpProbeConfigPy:
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def payload(self) -> bytes: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def max_response_size(self) -> int: ...
    @property
    def retries(self) -> int: ...
    def __init__(self, host: str, port: int, payload: Optional[bytes] = None, timeout_ms: int = 5000, max_response_size: int = 65535, retries: int = 2) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class UdpProbeResultPy:
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def reachable(self) -> bool: ...
    @property
    def response_bytes(self) -> bytes: ...
    @property
    def response_size(self) -> int: ...
    @property
    def truncated(self) -> bool: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def timing(self) -> ConnectionTimingPy: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def udp_probe(host: str, port: int, payload: Optional[bytes] = None, timeout_ms: int = 5000, max_response_size: int = 65535, retries: int = 2) -> UdpProbeResultPy: ...
def async_udp_probe(host: str, port: int, payload: Optional[bytes] = None, timeout_ms: int = 5000, max_response_size: int = 65535, retries: int = 2) -> Any: ...
