from typing import Any, Dict, List, Optional, Tuple

class ProxyTypePy:
    Socks4: "ProxyTypePy"
    Socks5: "ProxyTypePy"
    Http: "ProxyTypePy"
    Https: "ProxyTypePy"
    Tor: "ProxyTypePy"
    @property
    def value(self) -> str: ...
    @staticmethod
    def from_str(s: str) -> "ProxyTypePy": ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class RotationStrategyPy:
    RoundRobin: "RotationStrategyPy"
    Random: "RotationStrategyPy"
    Weighted: "RotationStrategyPy"
    LeastUsed: "RotationStrategyPy"
    LowestLatency: "RotationStrategyPy"
    @property
    def value(self) -> str: ...
    @staticmethod
    def from_str(s: str) -> "RotationStrategyPy": ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class ProxyConfigPy:
    def __init__(
        self,
        rotation_strategy: RotationStrategyPy = ...,
        health_check_enabled: bool = ...,
        health_check_interval_secs: int = ...,
        health_check_timeout_ms: int = ...,
        test_url: Optional[str] = ...,
        health_check_url: Optional[str] = ...,
        health_check_frequency_secs: int = ...,
        max_failures_before_disable: int = ...,
        chain_proxies: bool = ...,
        max_chain_length: int = ...,
    ) -> None: ...
    @property
    def rotation_strategy(self) -> RotationStrategyPy: ...
    @property
    def health_check_enabled(self) -> bool: ...
    @property
    def health_check_interval_secs(self) -> int: ...
    @property
    def health_check_timeout_ms(self) -> int: ...
    @property
    def max_failures_before_disable(self) -> int: ...
    @property
    def chain_proxies(self) -> bool: ...
    @property
    def max_chain_length(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ProxyEntryPy:
    def __init__(
        self,
        proxy_type: ProxyTypePy,
        address: str,
        port: int,
        name: Optional[str] = ...,
        username: Optional[str] = ...,
        password: Optional[str] = ...,
        weight: int = ...,
        priority: int = ...,
        timeout_ms: int = ...,
        enabled: bool = ...,
        tags: Optional[List[str]] = ...,
    ) -> None: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def proxy_type(self) -> ProxyTypePy: ...
    @property
    def address(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def username(self) -> Optional[str]: ...
    @property
    def weight(self) -> int: ...
    @property
    def priority(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def tags(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HealthCheckResultPy:
    @property
    def proxy_url(self) -> str: ...
    @property
    def is_healthy(self) -> bool: ...
    @property
    def latency_ms(self) -> Optional[int]: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ProxyHealthPy:
    @property
    def total(self) -> int: ...
    @property
    def healthy(self) -> int: ...
    @property
    def unhealthy(self) -> int: ...
    @property
    def healthy_percentage(self) -> float: ...
    @property
    def results(self) -> List[HealthCheckResultPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ProxyManagerPy:
    def add_proxy(self, entry: ProxyEntryPy) -> None: ...
    def add_proxies_from_file(self, path: str) -> int: ...
    def get_next_proxy(self) -> Optional[ProxyEntryPy]: ...
    def get_healthy_proxy(self) -> Optional[ProxyEntryPy]: ...
    def check_health(self) -> ProxyHealthPy: ...
    def pool_size(self) -> int: ...
    def __enter__(self) -> ProxyManagerPy: ...
    def __exit__(self, exc_type: Any = None, exc_value: Any = None, traceback: Any = None) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def create_proxy_manager(config: ProxyConfigPy) -> ProxyManagerPy: ...
def async_add_proxy(manager: ProxyManagerPy, entry: ProxyEntryPy) -> Any: ...
def async_proxy_health_check(manager: ProxyManagerPy) -> Any: ...

# --- Interception proxy types ---

class InterceptConfigPy:
    def __init__(
        self,
        listen_addr: str = ...,
        listen_port: int = ...,
        target_host: Optional[str] = ...,
        target_port: Optional[int] = ...,
        ssl_intercept: bool = ...,
        verbose: bool = ...,
        max_flows: int = ...,
        timeout_secs: int = ...,
        modify_request: bool = ...,
        modify_response: bool = ...,
    ) -> None: ...
    @property
    def listen_addr(self) -> str: ...
    @property
    def listen_port(self) -> int: ...
    @property
    def target_host(self) -> Optional[str]: ...
    @property
    def target_port(self) -> Optional[int]: ...
    @property
    def ssl_intercept(self) -> bool: ...
    @property
    def verbose(self) -> bool: ...
    @property
    def max_flows(self) -> int: ...
    @property
    def timeout_secs(self) -> int: ...
    @property
    def modify_request(self) -> bool: ...
    @property
    def modify_response(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CapturedExchangePy:
    @property
    def id(self) -> int: ...
    @property
    def method(self) -> str: ...
    @property
    def uri(self) -> str: ...
    @property
    def request_headers(self) -> List[Tuple[str, str]]: ...
    @property
    def request_body(self) -> Optional[str]: ...
    @property
    def response_status(self) -> Optional[int]: ...
    @property
    def response_headers(self) -> List[Tuple[str, str]]: ...
    @property
    def response_body(self) -> Optional[str]: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def latency_ms(self) -> Optional[int]: ...
    @property
    def request_modified(self) -> bool: ...
    @property
    def response_modified(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class InterceptSessionResultPy:
    @property
    def listen_addr(self) -> str: ...
    @property
    def listen_port(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def total_exchanges(self) -> int: ...
    @property
    def modified_requests(self) -> int: ...
    @property
    def modified_responses(self) -> int: ...
    @property
    def exchanges(self) -> List[CapturedExchangePy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# --- Release 3: Interception proxy lifecycle ---

class InterceptSessionStatePy:
    Created: "InterceptSessionStatePy"
    Listening: "InterceptSessionStatePy"
    Capturing: "InterceptSessionStatePy"
    Stopped: "InterceptSessionStatePy"
    Error: "InterceptSessionStatePy"
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class InterceptStatsPy:
    @property
    def connections_total(self) -> int: ...
    @property
    def exchanges_captured(self) -> int: ...
    @property
    def bytes_captured(self) -> int: ...
    @property
    def errors(self) -> int: ...
    @property
    def uptime_secs(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class InterceptFilterPy:
    def __init__(
        self,
        host_pattern: Optional[str] = ...,
        path_pattern: Optional[str] = ...,
        method_pattern: Optional[str] = ...,
        status_pattern: Optional[str] = ...,
    ) -> None: ...
    @property
    def host_pattern(self) -> Optional[str]: ...
    @property
    def path_pattern(self) -> Optional[str]: ...
    @property
    def method_pattern(self) -> Optional[str]: ...
    @property
    def status_pattern(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RequestModificationPy:
    def __init__(
        self,
        header_name: Optional[str] = ...,
        header_value: Optional[str] = ...,
        new_path: Optional[str] = ...,
        new_body: Optional[str] = ...,
    ) -> None: ...
    @property
    def header_name(self) -> Optional[str]: ...
    @property
    def header_value(self) -> Optional[str]: ...
    @property
    def new_path(self) -> Optional[str]: ...
    @property
    def new_body(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ResponseModificationPy:
    def __init__(
        self,
        header_name: Optional[str] = ...,
        header_value: Optional[str] = ...,
        new_body: Optional[str] = ...,
        new_status: Optional[int] = ...,
    ) -> None: ...
    @property
    def header_name(self) -> Optional[str]: ...
    @property
    def header_value(self) -> Optional[str]: ...
    @property
    def new_body(self) -> Optional[str]: ...
    @property
    def new_status(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class InterceptRulePy:
    def __init__(
        self,
        name: str,
        host_pattern: str,
        action: str,
        path_pattern: Optional[str] = ...,
        method_pattern: Optional[str] = ...,
        priority: int = ...,
        enabled: bool = ...,
        request_modifications: Optional[List[RequestModificationPy]] = ...,
        response_modifications: Optional[List[ResponseModificationPy]] = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def host_pattern(self) -> str: ...
    @property
    def path_pattern(self) -> Optional[str]: ...
    @property
    def method_pattern(self) -> Optional[str]: ...
    @property
    def action(self) -> str: ...
    @property
    def priority(self) -> int: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def request_modifications(self) -> List[RequestModificationPy]: ...
    @property
    def response_modifications(self) -> List[ResponseModificationPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CertificateAuthorityConfigPy:
    def __init__(
        self,
        ca_cert_path: Optional[str] = ...,
        ca_key_path: Optional[str] = ...,
        auto_generate: bool = ...,
        valid_days: int = ...,
    ) -> None: ...
    @property
    def ca_cert_path(self) -> Optional[str]: ...
    @property
    def ca_key_path(self) -> Optional[str]: ...
    @property
    def auto_generate(self) -> bool: ...
    @property
    def valid_days(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class IssuedCertificatePy:
    @property
    def hostname(self) -> str: ...
    @property
    def serial(self) -> str: ...
    @property
    def valid_from(self) -> str: ...
    @property
    def valid_until(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HarEntryPy:
    @property
    def method(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def status(self) -> int: ...
    @property
    def time_ms(self) -> float: ...
    @property
    def request_headers(self) -> List[Tuple[str, str]]: ...
    @property
    def response_headers(self) -> List[Tuple[str, str]]: ...
    @property
    def request_body(self) -> Optional[str]: ...
    @property
    def response_body(self) -> Optional[str]: ...
    @property
    def started_date_time(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HarDocumentPy:
    def __init__(
        self,
        entries: Optional[List[HarEntryPy]] = ...,
        creator_name: str = ...,
        creator_version: str = ...,
    ) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def creator_name(self) -> str: ...
    @property
    def creator_version(self) -> str: ...
    @property
    def entry_count(self) -> int: ...
    @property
    def entries(self) -> List[HarEntryPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def run_intercept_session(config: InterceptConfigPy) -> InterceptSessionResultPy: ...
def async_run_intercept_session(config: InterceptConfigPy) -> Any: ...

# Release 3 WS12: Mutation decision/error

class MutationDecisionPy:
    Applied: "MutationDecisionPy"
    Skipped: "MutationDecisionPy"
    TimedOut: "MutationDecisionPy"
    Error: "MutationDecisionPy"
    NoMatch: "MutationDecisionPy"
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class MutationErrorPy:
    @property
    def error_kind(self) -> str: ...
    @property
    def rule_name(self) -> Optional[str]: ...
    @property
    def message(self) -> str: ...
    @property
    def flow_index(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

# Release 3 WS13: Certificate Authority and Store

class CertificateAuthorityPy:
    @property
    def ca_fingerprint(self) -> str: ...
    @property
    def ca_subject(self) -> str: ...
    @property
    def valid_from(self) -> str: ...
    @property
    def valid_until(self) -> str: ...
    @property
    def issued_count(self) -> int: ...
    @property
    def key_type(self) -> str: ...
    @property
    def key_bits(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class CertificateStorePy:
    @property
    def total_issued(self) -> int: ...
    @property
    def total_expired(self) -> int: ...
    @property
    def entries(self) -> List[IssuedCertificatePy]: ...
    def find_by_hostname(self, hostname: str) -> Optional[IssuedCertificatePy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

# Release 3 WS14: Replay and comparison

class ReplayRequestPy:
    @property
    def exchange_id(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def headers(self) -> Dict[str, str]: ...
    @property
    def body(self) -> Optional[str]: ...
    @property
    def override_host(self) -> Optional[str]: ...
    @property
    def override_port(self) -> Optional[int]: ...
    @property
    def preserve_auth(self) -> bool: ...
    @property
    def timeout_secs(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ReplayResultPy:
    @property
    def exchange_id(self) -> str: ...
    @property
    def status_code(self) -> int: ...
    @property
    def response_headers(self) -> Dict[str, str]: ...
    @property
    def response_body(self) -> Optional[str]: ...
    @property
    def latency_ms(self) -> int: ...
    @property
    def success(self) -> bool: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def comparison(self) -> Optional[ResponseComparisonPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ResponseComparisonPy:
    @property
    def status_match(self) -> bool: ...
    @property
    def original_status(self) -> int: ...
    @property
    def replayed_status(self) -> int: ...
    @property
    def headers_differ(self) -> bool: ...
    @property
    def body_differ(self) -> bool: ...
    @property
    def body_diff_size(self) -> int: ...
    @property
    def timing_diff_ms(self) -> int: ...
    @property
    def volatile_headers(self) -> List[str]: ...
    @property
    def identical(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ComparisonRulePy:
    @property
    def name(self) -> str: ...
    @property
    def compare_status(self) -> bool: ...
    @property
    def compare_headers(self) -> bool: ...
    @property
    def compare_body(self) -> bool: ...
    @property
    def compare_timing(self) -> bool: ...
    @property
    def volatile_headers(self) -> List[str]: ...
    @property
    def body_diff_threshold(self) -> int: ...
    @property
    def timing_diff_threshold_ms(self) -> int: ...
    @property
    def ignore_header_order(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

InterceptSessionState = InterceptSessionStatePy
InterceptStats = InterceptStatsPy
InterceptFilter = InterceptFilterPy
InterceptRule = InterceptRulePy
CertificateAuthorityConfig = CertificateAuthorityConfigPy
IssuedCertificate = IssuedCertificatePy
HarEntry = HarEntryPy
HarDocument = HarDocumentPy
MutationDecision = MutationDecisionPy
MutationError = MutationErrorPy
CertificateAuthority = CertificateAuthorityPy
CertificateStore = CertificateStorePy
ReplayRequest = ReplayRequestPy
ResponseComparison = ResponseComparisonPy
ComparisonRule = ComparisonRulePy
