from typing import Any, Dict, List, Optional

class ProxyTypePy:
    SOCKS4: "ProxyTypePy"
    SOCKS5: "ProxyTypePy"
    HTTP: "ProxyTypePy"
    HTTPS: "ProxyTypePy"
    TOR: "ProxyTypePy"
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RotationStrategyPy:
    ROUND_ROBIN: "RotationStrategyPy"
    RANDOM: "RotationStrategyPy"
    WEIGHTED: "RotationStrategyPy"
    LEAST_USED: "RotationStrategyPy"
    LOWEST_LATENCY: "RotationStrategyPy"
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ProxyConfigPy:
    @property
    def rotation_strategy(self) -> RotationStrategyPy: ...
    @property
    def health_check_enabled(self) -> bool: ...
    @property
    def health_check_interval_secs(self) -> int: ...
    @property
    def health_check_timeout_ms(self) -> int: ...
    @property
    def max_failures_before_disable(self) -> int: ...
    @property
    def chain_proxies(self) -> bool: ...
    @property
    def max_chain_length(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ProxyEntryPy:
    @property
    def name(self) -> Optional[str]: ...
    @property
    def proxy_type(self) -> ProxyTypePy: ...
    @property
    def address(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def username(self) -> Optional[str]: ...
    @property
    def weight(self) -> int: ...
    @property
    def priority(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def tags(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HealthCheckResultPy:
    @property
    def proxy_url(self) -> str: ...
    @property
    def is_healthy(self) -> bool: ...
    @property
    def latency_ms(self) -> Optional[int]: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ProxyHealthPy:
    @property
    def total(self) -> int: ...
    @property
    def healthy(self) -> int: ...
    @property
    def unhealthy(self) -> int: ...
    @property
    def healthy_percentage(self) -> float: ...
    @property
    def results(self) -> List[HealthCheckResultPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ProxyManagerPy:
    @property
    def socket_path(self) -> Optional[str]: ...
    def add_proxy(self, entry: ProxyEntryPy) -> None: ...
    def add_proxies_from_file(self, path: str) -> int: ...
    def get_next_proxy(self) -> Optional[ProxyEntryPy]: ...
    def get_healthy_proxy(self) -> Optional[ProxyEntryPy]: ...
    def check_health(self) -> ProxyHealthPy: ...
    def pool_size(self) -> int: ...
    def __enter__(self) -> ProxyManagerPy: ...
    def __exit__(self, exc_type: Any = None, exc_value: Any = None, traceback: Any = None) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...

def create_proxy_manager(config: ProxyConfigPy) -> ProxyManagerPy: ...
def async_add_proxy(manager: ProxyManagerPy, entry: ProxyEntryPy) -> Any: ...
def async_proxy_health_check(manager: ProxyManagerPy) -> Any: ...

class InterceptConfigPy:
    @property
    def listen_address(self) -> str: ...
    @property
    def listen_port(self) -> int: ...
    @property
    def target_url(self) -> Optional[str]: ...
    @property
    def dry_run(self) -> bool: ...
    @property
    def capture_request_body(self) -> bool: ...
    @property
    def capture_response_body(self) -> bool: ...
    @property
    def max_body_bytes(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CapturedExchangePy:
    @property
    def request_method(self) -> str: ...
    @property
    def request_uri(self) -> str: ...
    @property
    def request_headers(self) -> Dict[str, str]: ...
    @property
    def request_body(self) -> Optional[str]: ...
    @property
    def response_status(self) -> Optional[int]: ...
    @property
    def response_headers(self) -> Dict[str, str]: ...
    @property
    def response_body(self) -> Optional[str]: ...
    @property
    def timestamp(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class InterceptSessionResultPy:
    @property
    def listen_address(self) -> str: ...
    @property
    def duration_secs(self) -> float: ...
    @property
    def exchanges(self) -> List[CapturedExchangePy]: ...
    @property
    def total_requests(self) -> int: ...
    @property
    def total_responses(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
