from typing import Any, Dict, List, Optional

class MxRecord:
    @property
    def preference(self) -> int: ...
    @property
    def exchange(self) -> str: ...

class SoaRecord:
    @property
    def mname(self) -> str: ...
    @property
    def rname(self) -> str: ...
    @property
    def serial(self) -> int: ...
    @property
    def refresh(self) -> int: ...
    @property
    def retry(self) -> int: ...
    @property
    def expire(self) -> int: ...
    @property
    def minimum(self) -> int: ...

class DnsRecordSet:
    @property
    def a(self) -> list[str]: ...
    @property
    def aaaa(self) -> list[str]: ...
    @property
    def cname(self) -> list[str]: ...
    @property
    def mx(self) -> list[MxRecord]: ...
    @property
    def txt(self) -> list[str]: ...
    @property
    def ns(self) -> list[str]: ...
    @property
    def soa(self) -> Optional[SoaRecord]: ...
    @property
    def caa(self) -> list[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class TlsCertificateInfo:
    @property
    def subject(self) -> str: ...
    @property
    def issuer(self) -> str: ...
    @property
    def not_before(self) -> str: ...
    @property
    def not_after(self) -> str: ...
    @property
    def serial_number(self) -> str: ...
    @property
    def signature_algorithm(self) -> str: ...
    @property
    def key_size(self) -> int: ...
    @property
    def is_ca(self) -> bool: ...
    @property
    def is_self_signed(self) -> bool: ...
    @property
    def subject_alternative_names(self) -> list[str]: ...

class SslIssue:
    @property
    def severity(self) -> str: ...
    @property
    def code(self) -> str: ...
    @property
    def description(self) -> str: ...

class TlsInspectionResult:
    @property
    def certificate(self) -> TlsCertificateInfo: ...
    @property
    def supported_versions(self) -> list[str]: ...
    @property
    def supported_cipher_suites(self) -> list[str]: ...
    @property
    def issues(self) -> list[SslIssue]: ...

class TechStack:
    @property
    def servers(self) -> list[str]: ...
    @property
    def frameworks(self) -> list[str]: ...
    @property
    def languages(self) -> list[str]: ...
    @property
    def databases(self) -> list[str]: ...
    @property
    def cdns(self) -> list[str]: ...
    @property
    def cms(self) -> list[str]: ...
    @property
    def javascript(self) -> list[str]: ...
    @property
    def other(self) -> list[str]: ...

class TechDetectionResult:
    @property
    def url(self) -> str: ...
    @property
    def status_code(self) -> int: ...
    @property
    def headers(self) -> Dict[str, str]: ...
    @property
    def tech_stack(self) -> TechStack: ...
