from typing import Any, Dict, List, Optional
from .finding_schema import VersionedFinding

class FindingRepository:
    def __init__(self) -> None: ...
    def add_finding(self, finding: VersionedFinding) -> None: ...
    def add_findings(self, findings: List[VersionedFinding]) -> int: ...
    def get_finding(self, finding_id: str) -> Optional[VersionedFinding]: ...
    def remove_finding(self, finding_id: str) -> bool: ...
    def count(self) -> int: ...
    def is_empty(self) -> bool: ...
    def clear(self) -> None: ...
    def list_ids(self) -> List[str]: ...
    def all_findings(self) -> List[VersionedFinding]: ...
    def by_severity(self, severity: str) -> List[VersionedFinding]: ...
    def by_confidence(self, confidence: str) -> List[VersionedFinding]: ...
    def by_finding_type(self, finding_type: str) -> List[VersionedFinding]: ...
    def by_target(self, target: str) -> List[VersionedFinding]: ...
    def by_cve(self, cve: str) -> List[VersionedFinding]: ...
    def by_cwe(self, cwe: str) -> List[VersionedFinding]: ...
    def by_tag(self, tag: str) -> List[VersionedFinding]: ...
    def by_tool(self, tool: str) -> List[VersionedFinding]: ...
    def by_date_range(self, start: str, end: str) -> List[VersionedFinding]: ...
    def filter(self, *, severity: Optional[str] = None, confidence: Optional[str] = None, finding_type: Optional[str] = None, target: Optional[str] = None, cve: Optional[str] = None, cwe: Optional[str] = None, tag: Optional[str] = None, tool: Optional[str] = None, min_severity: Optional[str] = None) -> List[VersionedFinding]: ...
    def deduplicate(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class Assessment:
    def __init__(self, id: str, name: str, target: str, *, created_at: Optional[str] = None, finding_count: Optional[int] = None, metadata: Optional[str] = None) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def created_at(self) -> str: ...
    @property
    def finding_count(self) -> int: ...
    @property
    def metadata(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class AssessmentRepository:
    def __init__(self) -> None: ...
    def save(self, assessment: Assessment) -> None: ...
    def get(self, assessment_id: str) -> Optional[Assessment]: ...
    def list(self) -> List[Assessment]: ...
    def remove(self, assessment_id: str) -> bool: ...
    def count(self) -> int: ...
