from typing import Any, Dict, List, Optional
from .finding_schema import VersionedFinding

class FindingReporter:
    def __init__(self, format: str, *, redaction_policy: Optional[str] = None, include_artifacts: bool = False) -> None: ...
    def generate(self, findings: List[VersionedFinding], title: Optional[str] = None) -> str: ...
    def generate_json(self, findings: List[VersionedFinding], title: Optional[str] = None) -> str: ...
    def generate_jsonl(self, findings: List[VersionedFinding]) -> str: ...
    def generate_markdown(self, findings: List[VersionedFinding], title: Optional[str] = None) -> str: ...
    def generate_csv(self, findings: List[VersionedFinding]) -> str: ...
    def generate_html(self, findings: List[VersionedFinding], title: Optional[str] = None) -> str: ...
    def generate_sarif(self, findings: List[VersionedFinding], title: Optional[str] = None) -> str: ...
    def write(self, findings: List[VersionedFinding], path: str, title: Optional[str] = None) -> int: ...
    @property
    def format_name(self) -> str: ...
    @property
    def redaction_policy_name(self) -> str: ...
    @property
    def includes_artifacts(self) -> bool: ...

class SeveritySummary:
    @property
    def critical(self) -> int: ...
    @property
    def high(self) -> int: ...
    @property
    def medium(self) -> int: ...
    @property
    def low(self) -> int: ...
    @property
    def info(self) -> int: ...
    @property
    def total(self) -> int: ...
    @property
    def risk_score(self) -> float: ...
    @staticmethod
    def from_findings(findings: List[VersionedFinding]) -> SeveritySummary: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ReportEnvelope:
    def __init__(self, title: str, findings: List[VersionedFinding], *, report_id: Optional[str] = None, tool_name: Optional[str] = None, tool_version: Optional[str] = None) -> None: ...
    @property
    def report_id(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def generated_at(self) -> str: ...
    @property
    def schema_version(self) -> str: ...
    @property
    def finding_count(self) -> int: ...
    @property
    def severity_summary(self) -> SeveritySummary: ...
    @property
    def findings(self) -> List[VersionedFinding]: ...
    @property
    def tool_name(self) -> str: ...
    @property
    def tool_version(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def generate_report(self, format: str) -> str: ...
