from typing import Any, Dict, List, Optional

class OperationRequest:
    @property
    def operation(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    @property
    def metadata(self) -> Dict[str, str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class PortScanRequest:
    @property
    def target(self) -> str: ...
    @property
    def ports(self) -> Optional[str]: ...
    @property
    def mode(self) -> Optional[str]: ...
    @property
    def timing(self) -> Optional[str]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class EndpointScanRequest:
    @property
    def target(self) -> str: ...
    @property
    def paths(self) -> Optional[List[str]]: ...
    @property
    def methods(self) -> Optional[List[str]]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class FingerprintRequest:
    @property
    def target(self) -> str: ...
    @property
    def ports(self) -> Optional[List[int]]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ReconDnsRequest:
    @property
    def target(self) -> str: ...
    @property
    def record_types(self) -> Optional[List[str]]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class TlsInspectRequest:
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class TechDetectRequest:
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class WafDetectRequest:
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class LoadTestRequest:
    @property
    def target(self) -> str: ...
    @property
    def requests(self) -> Optional[int]: ...
    @property
    def concurrency(self) -> Optional[int]: ...
    @property
    def method(self) -> Optional[str]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class WafValidateRequest:
    @property
    def target(self) -> str: ...
    @property
    def payloads(self) -> Optional[List[str]]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class FuzzRequest:
    @property
    def target(self) -> str: ...
    @property
    def payload_type(self) -> Optional[str]: ...
    @property
    def threads(self) -> Optional[int]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class RequestBuilder:
    def __init__(self, operation: str, target: str) -> None: ...
    def port(self, ports: str) -> RequestBuilder: ...
    def timing(self, t: str) -> RequestBuilder: ...
    def timeout(self, ms: int) -> RequestBuilder: ...
    def metadata_key(self, k: str, v: str) -> RequestBuilder: ...
    def mode(self, m: str) -> RequestBuilder: ...
    def build(self) -> OperationRequest: ...
