from typing import Any, Dict, List, Optional

class OperationRequest:
    @property
    def operation(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    @property
    def metadata(self) -> Dict[str, str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class PortScanRequest:
    @property
    def target(self) -> str: ...
    @property
    def ports(self) -> Optional[str]: ...
    @property
    def mode(self) -> Optional[str]: ...
    @property
    def timing(self) -> Optional[str]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class EndpointScanRequest:
    @property
    def target(self) -> str: ...
    @property
    def paths(self) -> Optional[List[str]]: ...
    @property
    def methods(self) -> Optional[List[str]]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class FingerprintRequest:
    @property
    def target(self) -> str: ...
    @property
    def ports(self) -> Optional[List[int]]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ReconDnsRequest:
    @property
    def target(self) -> str: ...
    @property
    def record_types(self) -> Optional[List[str]]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class TlsInspectRequest:
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class TechDetectRequest:
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class WafDetectRequest:
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class LoadTestRequest:
    @property
    def target(self) -> str: ...
    @property
    def requests(self) -> Optional[int]: ...
    @property
    def concurrency(self) -> Optional[int]: ...
    @property
    def method(self) -> Optional[str]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class WafValidateRequest:
    @property
    def target(self) -> str: ...
    @property
    def payloads(self) -> Optional[List[str]]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class FuzzRequest:
    @property
    def target(self) -> str: ...
    @property
    def payload_type(self) -> Optional[str]: ...
    @property
    def threads(self) -> Optional[int]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class GitSecretsScanRequest:
    @property
    def repo_path(self) -> str: ...
    @property
    def max_commits(self) -> Optional[int]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class SbomRequest:
    @property
    def project_path(self) -> str: ...
    @property
    def ecosystem(self) -> Optional[str]: ...
    @property
    def format(self) -> Optional[str]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ConsolidatedReconRequest:
    @property
    def target(self) -> str: ...
    @property
    def run_dns(self) -> Optional[bool]: ...
    @property
    def run_ssl(self) -> Optional[bool]: ...
    @property
    def run_tech_detect(self) -> Optional[bool]: ...
    @property
    def run_subdomain(self) -> Optional[bool]: ...
    @property
    def run_whois(self) -> Optional[bool]: ...
    @property
    def run_cors(self) -> Optional[bool]: ...
    @property
    def run_wayback(self) -> Optional[bool]: ...
    @property
    def run_js_analysis(self) -> Optional[bool]: ...
    @property
    def run_content(self) -> Optional[bool]: ...
    @property
    def run_email(self) -> Optional[bool]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class GraphqlTestRequest:
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class OauthTestRequest:
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class AuthTestRequest:
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class DbProbeRequest:
    @property
    def target(self) -> str: ...
    @property
    def port(self) -> Optional[int]: ...
    @property
    def database(self) -> Optional[str]: ...
    @property
    def username(self) -> Optional[str]: ...
    @property
    def password(self) -> Optional[str]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class NseRunRequest:
    @property
    def target(self) -> str: ...
    @property
    def scripts(self) -> Optional[List[str]]: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class DockerImageScanRequest:
    @property
    def image(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class KubernetesScanRequest:
    @property
    def target(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ApkAnalysisRequest:
    @property
    def apk_path(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class IpaAnalysisRequest:
    @property
    def ipa_path(self) -> str: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class RequestBuilder:
    def __init__(self, operation: str, target: str) -> None: ...
    def port(self, ports: str) -> RequestBuilder: ...
    def timing(self, t: str) -> RequestBuilder: ...
    def timeout(self, ms: int) -> RequestBuilder: ...
    def metadata_key(self, k: str, v: str) -> RequestBuilder: ...
    def mode(self, m: str) -> RequestBuilder: ...
    def build(self) -> OperationRequest: ...
