from typing import Any, Dict, List, Optional

from .finding import Severity

class SbomFormatPy:
    CYCLONEDX: "SbomFormatPy"
    SPDX: "SbomFormatPy"
    @staticmethod
    def from_str(s: str) -> "SbomFormatPy": ...
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class SbomComponentPy:
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def ecosystem(self) -> str: ...
    @property
    def purl(self) -> str: ...
    @property
    def licenses(self) -> List[str]: ...
    @property
    def is_direct(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SbomVulnerabilityPy:
    @property
    def component(self) -> str: ...
    @property
    def cve_id(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def description(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SbomReportPy:
    @property
    def format(self) -> SbomFormatPy: ...
    @property
    def project_name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def generated_at(self) -> str: ...
    @property
    def components(self) -> List[SbomComponentPy]: ...
    @property
    def vulnerabilities(self) -> List[SbomVulnerabilityPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def generate_sbom(
    project_path: str, format: str = "cyclonedx", ecosystem: str = "cargo"
) -> SbomReportPy: ...
def async_generate_sbom(
    project_path: str, format: str = "cyclonedx", ecosystem: str = "cargo"
) -> Any: ...
