from typing import List

class Scope:
    @staticmethod
    def allow_hosts(hosts: List[str]) -> Scope: ...
    @staticmethod
    def allow_cidrs(cidrs: List[str]) -> Scope: ...
    @staticmethod
    def deny_all() -> Scope: ...
    @staticmethod
    def from_file(path: str) -> Scope: ...
    def is_target_allowed(self, target: str) -> bool: ...
    def is_port_allowed(self, port: int) -> bool: ...
