from __future__ import annotations
import os
from typing import List, Union

class Scope:
    @staticmethod
    def allow_hosts(hosts: List[str]) -> Scope: ...
    @staticmethod
    def allow_cidrs(cidrs: List[str]) -> Scope: ...
    @staticmethod
    def deny_all() -> Scope: ...
    @staticmethod
    def from_file(path: Union[str, os.PathLike[str]]) -> Scope: ...
    def is_target_allowed(self, target: str) -> bool: ...
    def is_port_allowed(self, port: int) -> bool: ...
