from typing import Any, Dict, List, Optional

class SessionState:
    Created: "SessionState"
    Starting: "SessionState"
    Running: "SessionState"
    Pausing: "SessionState"
    Paused: "SessionState"
    Stopping: "SessionState"
    Stopped: "SessionState"
    Failed: "SessionState"
    Cancelled: "SessionState"
    @staticmethod
    def from_str(s: str) -> Optional["SessionState"]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionCloseMode:
    Graceful: "SessionCloseMode"
    Forced: "SessionCloseMode"
    Immediate: "SessionCloseMode"
    @staticmethod
    def from_str(s: str) -> Optional["SessionCloseMode"]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionIdentity:
    def __init__(
        self,
        session_id: str,
        session_type: str,
        created_at_ms: int,
        owner_id: Optional[str] = None,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def session_type(self) -> str: ...
    @property
    def created_at_ms(self) -> int: ...
    @property
    def owner_id(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionStats:
    def __init__(
        self,
        *,
        total_operations: int = 0,
        completed_operations: int = 0,
        failed_operations: int = 0,
        cancelled_operations: int = 0,
        elapsed_ms: int = 0,
        last_activity_ms: Optional[int] = None,
    ) -> None: ...
    @property
    def total_operations(self) -> int: ...
    @property
    def completed_operations(self) -> int: ...
    @property
    def failed_operations(self) -> int: ...
    @property
    def cancelled_operations(self) -> int: ...
    @property
    def elapsed_ms(self) -> int: ...
    @property
    def last_activity_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionEvent:
    def __init__(
        self,
        sequence: int,
        timestamp_ms: int,
        event_type: str,
        message: Optional[str] = None,
    ) -> None: ...
    @property
    def sequence(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def event_type(self) -> str: ...
    @property
    def message(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionEventStream:
    def __init__(
        self,
        session_id: str,
        events: Optional[List[SessionEvent]] = None,
        sequence: int = 0,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def events(self) -> List[SessionEvent]: ...
    @property
    def sequence(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionCapabilities:
    def __init__(
        self,
        *,
        supports_cancellation: bool = False,
        supports_timeout: bool = False,
        supports_artifacts: bool = False,
        supports_streaming: bool = False,
        max_concurrent_operations: int = 1,
    ) -> None: ...
    @property
    def supports_cancellation(self) -> bool: ...
    @property
    def supports_timeout(self) -> bool: ...
    @property
    def supports_artifacts(self) -> bool: ...
    @property
    def supports_streaming(self) -> bool: ...
    @property
    def max_concurrent_operations(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def create_session_event(
    sequence: int,
    timestamp_ms: int,
    event_type: str,
    message: Optional[str] = None,
) -> SessionEvent: ...
