from typing import Any, Dict, List, Optional

class SessionState:
    Initializing: "SessionState"
    Active: "SessionState"
    Paused: "SessionState"
    Closing: "SessionState"
    Closed: "SessionState"
    Error: "SessionState"
    @property
    def value(self) -> str: ...
    def from_str(s: str) -> SessionState: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionIdentity:
    def __init__(
        self,
        session_id: str,
        surface: str,
        *,
        client_label: Optional[str] = None,
        parent_session_id: Optional[str] = None,
    ) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def surface(self) -> str: ...
    @property
    def client_label(self) -> Optional[str]: ...
    @property
    def parent_session_id(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionStats:
    def __init__(
        self,
        *,
        tasks_submitted: int = 0,
        tasks_completed: int = 0,
        tasks_failed: int = 0,
        tasks_cancelled: int = 0,
        uptime_ms: int = 0,
        last_activity_ms: Optional[int] = None,
    ) -> None: ...
    @property
    def tasks_submitted(self) -> int: ...
    @property
    def tasks_completed(self) -> int: ...
    @property
    def tasks_failed(self) -> int: ...
    @property
    def tasks_cancelled(self) -> int: ...
    @property
    def uptime_ms(self) -> int: ...
    @property
    def last_activity_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionCloseMode:
    Graceful: "SessionCloseMode"
    Immediate: "SessionCloseMode"
    Timeout: "SessionCloseMode"
    @property
    def value(self) -> str: ...
    def from_str(s: str) -> SessionCloseMode: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionEvent:
    def __init__(
        self,
        event_type: str,
        payload: Any,
        *,
        timestamp_ms: Optional[int] = None,
        session_id: Optional[str] = None,
        sequence: Optional[int] = None,
    ) -> None: ...
    @property
    def event_type(self) -> str: ...
    @property
    def payload(self) -> Any: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def session_id(self) -> Optional[str]: ...
    @property
    def sequence(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionEventStream:
    def __init__(self, session_id: str) -> None: ...
    @property
    def session_id(self) -> str: ...
    def next(self) -> Optional[SessionEvent]: ...
    def recv(self) -> Any: ...
    def close(self) -> None: ...
    def __enter__(self) -> SessionEventStream: ...
    def __exit__(self, *args: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SessionCapabilities:
    def __init__(
        self,
        *,
        supports_cancel: bool = True,
        supports_policy_approve: bool = False,
        supports_subscribe: bool = True,
        supports_persist: bool = False,
        max_concurrent_tasks: int = 1,
        surfaces: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def supports_cancel(self) -> bool: ...
    @property
    def supports_policy_approve(self) -> bool: ...
    @property
    def supports_subscribe(self) -> bool: ...
    @property
    def supports_persist(self) -> bool: ...
    @property
    def max_concurrent_tasks(self) -> int: ...
    @property
    def surfaces(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
