from typing import Any, Dict, List, Optional

from .finding_schema import VersionedFinding
from .repository import Assessment

class SqliteFindingRepository:
    def __init__(self, db_path: str) -> None: ...
    @property
    def db_path(self) -> str: ...
    def add_finding(self, finding: VersionedFinding) -> None: ...
    def add_findings(self, findings: List[VersionedFinding]) -> int: ...
    def get_finding(self, finding_id: str) -> Optional[VersionedFinding]: ...
    def remove_finding(self, finding_id: str) -> bool: ...
    def count(self) -> int: ...
    def is_empty(self) -> bool: ...
    def clear(self) -> None: ...
    def list_ids(self) -> List[str]: ...
    def all_findings(self) -> List[VersionedFinding]: ...
    def by_severity(self, severity: str) -> List[VersionedFinding]: ...
    def by_confidence(self, confidence: str) -> List[VersionedFinding]: ...
    def by_finding_type(self, finding_type: str) -> List[VersionedFinding]: ...
    def by_target(self, target: str) -> List[VersionedFinding]: ...
    def by_cve(self, cve: str) -> List[VersionedFinding]: ...
    def by_cwe(self, cwe: str) -> List[VersionedFinding]: ...
    def by_tag(self, tag: str) -> List[VersionedFinding]: ...
    def by_tool(self, tool: str) -> List[VersionedFinding]: ...
    def by_date_range(self, start: str, end: str) -> List[VersionedFinding]: ...
    def filter(
        self,
        *,
        severity: Optional[str] = None,
        confidence: Optional[str] = None,
        finding_type: Optional[str] = None,
        target: Optional[str] = None,
        cve: Optional[str] = None,
        cwe: Optional[str] = None,
        tag: Optional[str] = None,
        tool: Optional[str] = None,
        min_severity: Optional[str] = None,
    ) -> List[VersionedFinding]: ...
    def deduplicate(self) -> int: ...
    def export_json(self, path: str) -> int: ...
    def import_json(self, path: str) -> int: ...
    def backup(self, dest_path: str) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> SqliteFindingRepository: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SqliteAssessmentRepository:
    def __init__(self, db_path: str) -> None: ...
    @property
    def db_path(self) -> str: ...
    def save(self, assessment: Assessment) -> None: ...
    def get(self, assessment_id: str) -> Optional[Assessment]: ...
    def list(self) -> List[Assessment]: ...
    def remove(self, assessment_id: str) -> bool: ...
    def count(self) -> int: ...
    def clear(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> SqliteAssessmentRepository: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SqliteMigration:
    def __init__(self, db_path: str) -> None: ...
    @property
    def db_path(self) -> str: ...
    def current_version(self) -> int: ...
    def target_version(self) -> int: ...
    def pending_migrations(self) -> List[Dict[str, Any]]: ...
    def migrate(self) -> "MigrationResult": ...
    def rollback(self, steps: int = 1) -> "MigrationResult": ...
    def migration_history(self) -> List[Dict[str, Any]]: ...
    def __enter__(self) -> SqliteMigration: ...
    def __exit__(self, *args: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MigrationResult:
    def __init__(
        self,
        *,
        success: bool = False,
        source_version: int = 0,
        target_version: int = 0,
        items_migrated: int = 0,
        warnings: Optional[List[str]] = None,
        errors: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def success(self) -> bool: ...
    @property
    def source_version(self) -> int: ...
    @property
    def target_version(self) -> int: ...
    @property
    def items_migrated(self) -> int: ...
    @property
    def warnings(self) -> List[str]: ...
    @property
    def errors(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
