from typing import Any, Dict, List, Optional

class ExecutionStatus:
    Pending: ExecutionStatus
    Running: ExecutionStatus
    Completed: ExecutionStatus
    Failed: ExecutionStatus
    Cancelled: ExecutionStatus
    Timeout: ExecutionStatus
    def name(self) -> str: ...

class ExecutionStats:
    @property
    def duration_ms(self) -> int: ...
    @property
    def items_processed(self) -> int: ...
    @property
    def items_failed(self) -> int: ...
    @property
    def bytes_transferred(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class Artifact:
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def mime_type(self) -> Optional[str]: ...
    @property
    def data(self) -> Optional[str]: ...
    @property
    def path(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class OperationError:
    schema_version: str
    kind: str
    code: str
    message: str
    operation_id: Optional[str]
    retryable: bool
    denial_class: Optional[str]
    source: Optional[str]
    details: Dict[str, str]
    causes: List[str]
    def __init__(self, kind: str, code: str, message: str, *, operation_id: Optional[str] = ..., retryable: bool = ..., denial_class: Optional[str] = ..., source: Optional[str] = ..., details: Optional[Dict[str, str]] = ..., causes: Optional[List[str]] = ...) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class OperationResult:
    @property
    def status(self) -> ExecutionStatus: ...
    @property
    def stats(self) -> Optional[ExecutionStats]: ...
    @property
    def artifacts(self) -> List[Artifact]: ...
    @property
    def error(self) -> Optional[OperationError]: ...
    @property
    def error_message(self) -> Optional[str]: ...
    @property
    def metadata(self) -> Dict[str, str]: ...
    def is_success(self) -> bool: ...
    def is_failure(self) -> bool: ...
    def artifact_count(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
