from typing import Any, Dict, List, Optional

class ExecutionStatus:
    Pending: ExecutionStatus
    Running: ExecutionStatus
    Completed: ExecutionStatus
    Failed: ExecutionStatus
    Cancelled: ExecutionStatus
    Timeout: ExecutionStatus
    def name(self) -> str: ...

class ExecutionStats:
    @property
    def duration_ms(self) -> int: ...
    @property
    def items_processed(self) -> int: ...
    @property
    def items_failed(self) -> int: ...
    @property
    def bytes_transferred(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class Artifact:
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def mime_type(self) -> Optional[str]: ...
    @property
    def data(self) -> Optional[str]: ...
    @property
    def path(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class OperationResult:
    @property
    def status(self) -> ExecutionStatus: ...
    @property
    def stats(self) -> Optional[ExecutionStats]: ...
    @property
    def artifacts(self) -> List[Artifact]: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def metadata(self) -> Dict[str, str]: ...
    def is_success(self) -> bool: ...
    def is_failure(self) -> bool: ...
    def artifact_count(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
