from typing import Any, Dict, List, Optional

class StreamingReportConfig:
    def __init__(
        self,
        format: str = "jsonl",
        *,
        output_path: Optional[str] = None,
        buffer_size: int = 100,
        include_artifacts: bool = False,
        include_evidence: bool = False,
        redact_secrets: bool = True,
        timestamp_format: Optional[str] = None,
    ) -> None: ...
    @property
    def format(self) -> str: ...
    @property
    def output_path(self) -> Optional[str]: ...
    @property
    def buffer_size(self) -> int: ...
    @property
    def include_artifacts(self) -> bool: ...
    @property
    def include_evidence(self) -> bool: ...
    @property
    def redact_secrets(self) -> bool: ...
    @property
    def timestamp_format(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ReportSummary:
    def __init__(
        self,
        format: str = "jsonl",
        *,
        total_findings: int = 0,
        findings_by_severity: Optional[List[Dict[str, Any]]] = None,
        output_path: Optional[str] = None,
        output_size_bytes: int = 0,
        duration_ms: int = 0,
        content_hash: Optional[str] = None,
    ) -> None: ...
    @property
    def format(self) -> str: ...
    @property
    def total_findings(self) -> int: ...
    @property
    def findings_by_severity(self) -> List[Dict[str, Any]]: ...
    @property
    def output_path(self) -> Optional[str]: ...
    @property
    def output_size_bytes(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def content_hash(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class StreamingReporter:
    def __init__(self, config: StreamingReportConfig) -> None: ...
    @property
    def config(self) -> StreamingReportConfig: ...
    def start(self) -> None: ...
    def write_finding(self, finding_json: str) -> None: ...
    def write_findings_batch(self, findings_json: str) -> None: ...
    def get_buffered_count(self) -> int: ...
    def flush(self) -> None: ...
    def finish(self) -> ReportSummary: ...
    def get_output_path(self) -> Optional[str]: ...
    def __enter__(self) -> StreamingReporter: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FindingDiffResult:
    def __init__(
        self,
        finding_id: str,
        diff_status: str,
        *,
        baseline_finding_id: Optional[str] = None,
        changes: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def finding_id(self) -> str: ...
    @property
    def diff_status(self) -> str: ...
    @property
    def baseline_finding_id(self) -> Optional[str]: ...
    @property
    def changes(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class DiffReportSummary:
    def __init__(
        self,
        *,
        total_findings: int = 0,
        new_findings: int = 0,
        resolved_findings: int = 0,
        changed_findings: int = 0,
        unchanged_findings: int = 0,
        duration_ms: int = 0,
        output_path: Optional[str] = None,
    ) -> None: ...
    @property
    def total_findings(self) -> int: ...
    @property
    def new_findings(self) -> int: ...
    @property
    def resolved_findings(self) -> int: ...
    @property
    def changed_findings(self) -> int: ...
    @property
    def unchanged_findings(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def output_path(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class StreamingDiffReporter:
    def __init__(
        self,
        config: StreamingReportConfig,
        *,
        baseline_json: Optional[str] = None,
    ) -> None: ...
    def start(self) -> None: ...
    def write_finding(self, finding_json: str) -> Optional[FindingDiffResult]: ...
    def finish(self) -> DiffReportSummary: ...
    def __enter__(self) -> StreamingDiffReporter: ...
    def __exit__(self, *args: Any) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...

class ReportManifest:
    def __init__(
        self,
        report_id: str,
        format: str,
        created_at_ms: int,
        finding_count: int,
        content_hash: str,
        *,
        schema_version: Optional[str] = None,
        tool_version: Optional[str] = None,
        artifact_ids: Optional[List[str]] = None,
    ) -> None: ...
    @property
    def report_id(self) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def schema_version(self) -> str: ...
    @property
    def tool_version(self) -> str: ...
    @property
    def created_at_ms(self) -> int: ...
    @property
    def finding_count(self) -> int: ...
    @property
    def artifact_ids(self) -> List[str]: ...
    @property
    def content_hash(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
