from typing import Any, Dict, List, Optional

class StressTypePy:
    SYN: "StressTypePy"
    UDP: "StressTypePy"
    HTTP: "StressTypePy"
    TCP: "StressTypePy"
    ICMP: "StressTypePy"
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class StressConfigPy:
    @property
    def target(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def stress_type(self) -> StressTypePy: ...
    @property
    def rate_pps(self) -> int: ...
    @property
    def duration_secs(self) -> int: ...
    @property
    def concurrency(self) -> int: ...
    @property
    def spoof_source(self) -> bool: ...
    @property
    def spoof_range(self) -> Optional[str]: ...
    @property
    def random_source_port(self) -> bool: ...
    @property
    def payload_size(self) -> int: ...
    @property
    def use_proxies(self) -> bool: ...
    @property
    def proxy_pool(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class StressStatsPy:
    @property
    def duration_ms(self) -> int: ...
    @property
    def packets_sent(self) -> int: ...
    @property
    def bytes_sent(self) -> int: ...
    @property
    def errors(self) -> int: ...
    @property
    def avg_rate_pps(self) -> int: ...
    @property
    def avg_bandwidth_mbps(self) -> float: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class StressConfigSummaryPy:
    @property
    def rate_pps(self) -> int: ...
    @property
    def duration_secs(self) -> int: ...
    @property
    def spoof_source(self) -> bool: ...
    @property
    def used_proxies(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class StressResultPy:
    @property
    def target(self) -> str: ...
    @property
    def stress_type(self) -> StressTypePy: ...
    @property
    def stats(self) -> StressStatsPy: ...
    @property
    def config_used(self) -> StressConfigSummaryPy: ...
    @property
    def warnings(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def stress_test(
    target: str,
    port: int = 80,
    stress_type: str = "http",
    rate_pps: int = 1000,
    duration_secs: int = 60,
    concurrency: int = 10,
    spoof_source: bool = False,
    spoof_range: Optional[str] = None,
    random_source_port: bool = True,
    payload_size: int = 64,
    use_proxies: bool = False,
    proxy_pool: Optional[str] = None,
) -> StressResultPy: ...
def async_stress_test(
    target: str,
    port: int = 80,
    stress_type: str = "http",
    rate_pps: int = 1000,
    duration_secs: int = 60,
    concurrency: int = 10,
    spoof_source: bool = False,
    spoof_range: Optional[str] = None,
    random_source_port: bool = True,
    payload_size: int = 64,
    use_proxies: bool = False,
    proxy_pool: Optional[str] = None,
) -> Any: ...
