from typing import Any, Callable, Dict, List, Optional

from .finding_schema import VersionedFinding

class StreamingReportConfig:
    def __init__(
        self,
        *,
        format: str = "jsonl",
        buffer_size: int = 100,
        flush_interval_ms: int = 5000,
        include_metadata: bool = True,
        redact_sensitive: bool = False,
        output_path: Optional[str] = None,
        append_mode: bool = False,
        on_flush: Optional[Callable[["ReportSummary"], None]] = None,
    ) -> None: ...
    @property
    def format(self) -> str: ...
    @property
    def buffer_size(self) -> int: ...
    @property
    def flush_interval_ms(self) -> int: ...
    @property
    def include_metadata(self) -> bool: ...
    @property
    def redact_sensitive(self) -> bool: ...
    @property
    def output_path(self) -> Optional[str]: ...
    @property
    def append_mode(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class StreamingReporter:
    def __init__(self, config: StreamingReportConfig) -> None: ...
    @property
    def config(self) -> StreamingReportConfig: ...
    @property
    def finding_count(self) -> int: ...
    @property
    def is_closed(self) -> bool: ...
    def emit(self, finding: VersionedFinding) -> None: ...
    def emit_many(self, findings: List[VersionedFinding]) -> int: ...
    def flush(self) -> "ReportSummary": ...
    def close(self) -> "ReportSummary": ...
    def summary(self) -> "ReportSummary": ...
    def __enter__(self) -> StreamingReporter: ...
    def __exit__(self, *args: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ReportSummary:
    def __init__(
        self,
        *,
        total_findings: int = 0,
        critical_count: int = 0,
        high_count: int = 0,
        medium_count: int = 0,
        low_count: int = 0,
        info_count: int = 0,
        flush_count: int = 0,
        bytes_written: int = 0,
        format: str = "jsonl",
        output_path: Optional[str] = None,
    ) -> None: ...
    @property
    def total_findings(self) -> int: ...
    @property
    def critical_count(self) -> int: ...
    @property
    def high_count(self) -> int: ...
    @property
    def medium_count(self) -> int: ...
    @property
    def low_count(self) -> int: ...
    @property
    def info_count(self) -> int: ...
    @property
    def flush_count(self) -> int: ...
    @property
    def bytes_written(self) -> int: ...
    @property
    def format(self) -> str: ...
    @property
    def output_path(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class StreamingDiffReporter:
    def __init__(
        self,
        *,
        current: StreamingReporter,
        baseline_path: Optional[str] = None,
        include_new: bool = True,
        include_resolved: bool = True,
        include_unchanged: bool = False,
    ) -> None: ...
    @property
    def current(self) -> StreamingReporter: ...
    @property
    def baseline_path(self) -> Optional[str]: ...
    @property
    def include_new(self) -> bool: ...
    @property
    def include_resolved(self) -> bool: ...
    @property
    def include_unchanged(self) -> bool: ...
    def emit(self, finding: VersionedFinding) -> None: ...
    def diff(self) -> "DiffReportSummary": ...
    def close(self) -> "DiffReportSummary": ...
    def __enter__(self) -> StreamingDiffReporter: ...
    def __exit__(self, *args: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FindingDiffResult:
    def __init__(
        self,
        finding_id: str,
        diff_status: str,
        *,
        finding: Optional[VersionedFinding] = None,
        baseline_severity: Optional[str] = None,
        current_severity: Optional[str] = None,
        severity_changed: bool = False,
    ) -> None: ...
    @property
    def finding_id(self) -> str: ...
    @property
    def diff_status(self) -> str: ...
    @property
    def finding(self) -> Optional[VersionedFinding]: ...
    @property
    def baseline_severity(self) -> Optional[str]: ...
    @property
    def current_severity(self) -> Optional[str]: ...
    @property
    def severity_changed(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DiffReportSummary:
    def __init__(
        self,
        *,
        new_findings: int = 0,
        resolved_findings: int = 0,
        unchanged_findings: int = 0,
        severity_changes: int = 0,
        total_current: int = 0,
        total_baseline: int = 0,
        diffs: Optional[List[FindingDiffResult]] = None,
    ) -> None: ...
    @property
    def new_findings(self) -> int: ...
    @property
    def resolved_findings(self) -> int: ...
    @property
    def unchanged_findings(self) -> int: ...
    @property
    def severity_changes(self) -> int: ...
    @property
    def total_current(self) -> int: ...
    @property
    def total_baseline(self) -> int: ...
    @property
    def diffs(self) -> List[FindingDiffResult]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ReportManifest:
    def __init__(
        self,
        *,
        report_id: str = "",
        title: str = "",
        format: str = "jsonl",
        generated_at: Optional[str] = None,
        finding_count: int = 0,
        content_hash: Optional[str] = None,
        file_path: Optional[str] = None,
        file_size_bytes: int = 0,
        schema_version: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None: ...
    @property
    def report_id(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def generated_at(self) -> Optional[str]: ...
    @property
    def finding_count(self) -> int: ...
    @property
    def content_hash(self) -> Optional[str]: ...
    @property
    def file_path(self) -> Optional[str]: ...
    @property
    def file_size_bytes(self) -> int: ...
    @property
    def schema_version(self) -> Optional[str]: ...
    @property
    def metadata(self) -> Dict[str, Any]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
