from typing import Any, Dict, List, Optional

class ToolDescriptor:
    @property
    def tool_id(self) -> str: ...
    @property
    def operation_id(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def risk(self) -> str: ...
    @property
    def feature_required(self) -> Optional[str]: ...
    @property
    def maturity(self) -> str: ...
    @property
    def confirmation_required(self) -> bool: ...
    @property
    def confirmation_message(self) -> Optional[str]: ...
    @property
    def target_policy(self) -> str: ...
    @property
    def input_schema(self) -> Optional[str]: ...
    @property
    def output_schema(self) -> Optional[str]: ...
    @property
    def supports_streaming(self) -> bool: ...
    @property
    def supports_cancellation(self) -> bool: ...
    @property
    def supports_timeout(self) -> bool: ...
    @property
    def local_available(self) -> bool: ...
    @property
    def daemon_available(self) -> bool: ...
    @property
    def intended_uses(self) -> List[str]: ...
    @property
    def supported_surfaces(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ToolRegistry:
    @staticmethod
    def list() -> List[ToolDescriptor]: ...
    @staticmethod
    def get(tool_id: str) -> Optional[ToolDescriptor]: ...
    @staticmethod
    def schema(tool_id: str) -> Optional[str]: ...
    @staticmethod
    def validate(tool_id: str, payload: Dict[str, Any]) -> ValidationReport: ...
    @staticmethod
    def count() -> int: ...
    @staticmethod
    def operations_for_feature(feature: str) -> List[ToolDescriptor]: ...
    @staticmethod
    def operations_for_category(category: str) -> List[ToolDescriptor]: ...
    def __repr__(self) -> str: ...

class OperationToolView:
    @property
    def descriptor(self) -> ToolDescriptor: ...
    @property
    def request_type_name(self) -> str: ...
    @property
    def result_type_name(self) -> str: ...
    @property
    def example_request(self) -> Optional[str]: ...
    @property
    def example_result(self) -> Optional[str]: ...
    def invoke_description(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ValidationReport:
    @property
    def valid(self) -> bool: ...
    @property
    def errors(self) -> List[str]: ...
    @property
    def warnings(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

class SchemaGenerator:
    @staticmethod
    def generate_input_schema(tool_id: str) -> Optional[str]: ...
    @staticmethod
    def generate_output_schema(tool_id: str) -> Optional[str]: ...
    @staticmethod
    def all_schemas() -> Dict[str, Dict[str, Any]]: ...
    def __repr__(self) -> str: ...

class OpenApiAdapter:
    @staticmethod
    def tool_to_openapi(tool_id: str) -> Optional[Dict[str, Any]]: ...
    @staticmethod
    def full_openapi_spec() -> Dict[str, Any]: ...
    def __repr__(self) -> str: ...

def operation_as_tool(operation_id: str) -> Optional[OperationToolView]: ...
