from typing import Any, Dict, List, Optional, Union

class TargetType:
    @staticmethod
    def url() -> TargetType: ...
    @staticmethod
    def domain() -> TargetType: ...
    @staticmethod
    def ip() -> TargetType: ...
    @staticmethod
    def cidr() -> TargetType: ...
    @staticmethod
    def file() -> TargetType: ...
    @staticmethod
    def from_str(s: str) -> TargetType: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> str: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class AuthType:
    @staticmethod
    def none() -> AuthType: ...
    @staticmethod
    def basic() -> AuthType: ...
    @staticmethod
    def bearer() -> AuthType: ...
    @staticmethod
    def api_key() -> AuthType: ...
    @staticmethod
    def oauth2() -> AuthType: ...
    @staticmethod
    def from_str(s: str) -> AuthType: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> str: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class ResponseType:
    @staticmethod
    def success() -> ResponseType: ...
    @staticmethod
    def partial_success() -> ResponseType: ...
    @staticmethod
    def failed() -> ResponseType: ...
    @staticmethod
    def timeout() -> ResponseType: ...
    @staticmethod
    def scope_violation() -> ResponseType: ...
    @staticmethod
    def cancelled() -> ResponseType: ...
    @staticmethod
    def from_str(s: str) -> ResponseType: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> str: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class ToolFindingType:
    @staticmethod
    def vulnerability() -> ToolFindingType: ...
    @staticmethod
    def information() -> ToolFindingType: ...
    @staticmethod
    def weakness() -> ToolFindingType: ...
    @staticmethod
    def configuration() -> ToolFindingType: ...
    @staticmethod
    def misconfiguration() -> ToolFindingType: ...
    @staticmethod
    def sensitive_data() -> ToolFindingType: ...
    @staticmethod
    def banner() -> ToolFindingType: ...
    @staticmethod
    def technology() -> ToolFindingType: ...
    @staticmethod
    def service() -> ToolFindingType: ...
    @staticmethod
    def endpoint() -> ToolFindingType: ...
    @staticmethod
    def subdomain() -> ToolFindingType: ...
    @staticmethod
    def open_port() -> ToolFindingType: ...
    @staticmethod
    def from_str(s: str) -> ToolFindingType: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> str: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class ToolSeverity:
    @staticmethod
    def critical() -> ToolSeverity: ...
    @staticmethod
    def high() -> ToolSeverity: ...
    @staticmethod
    def medium() -> ToolSeverity: ...
    @staticmethod
    def low() -> ToolSeverity: ...
    @staticmethod
    def info() -> ToolSeverity: ...
    @staticmethod
    def none() -> ToolSeverity: ...
    @staticmethod
    def from_str(s: str) -> ToolSeverity: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> str: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class ToolErrorType:
    @staticmethod
    def validation() -> ToolErrorType: ...
    @staticmethod
    def authentication() -> ToolErrorType: ...
    @staticmethod
    def authorization() -> ToolErrorType: ...
    @staticmethod
    def rate_limit() -> ToolErrorType: ...
    @staticmethod
    def network() -> ToolErrorType: ...
    @staticmethod
    def timeout() -> ToolErrorType: ...
    @staticmethod
    def scope_violation() -> ToolErrorType: ...
    @staticmethod
    def not_found() -> ToolErrorType: ...
    @staticmethod
    def configuration() -> ToolErrorType: ...
    @staticmethod
    def internal() -> ToolErrorType: ...
    @staticmethod
    def tool_not_found() -> ToolErrorType: ...
    @staticmethod
    def from_str(s: str) -> ToolErrorType: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> str: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class PortState:
    @staticmethod
    def open() -> PortState: ...
    @staticmethod
    def closed() -> PortState: ...
    @staticmethod
    def filtered() -> PortState: ...
    @staticmethod
    def from_str(s: str) -> PortState: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> str: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class StreamEventType:
    @staticmethod
    def progress() -> StreamEventType: ...
    @staticmethod
    def finding() -> StreamEventType: ...
    @staticmethod
    def result() -> StreamEventType: ...
    @staticmethod
    def error() -> StreamEventType: ...
    @staticmethod
    def from_str(s: str) -> StreamEventType: ...
    @property
    def value(self) -> str: ...
    def to_dict(self) -> str: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class ScopeTool:
    @staticmethod
    def new(
        allowed_patterns: Optional[List[str]] = ...,
        excluded_patterns: Optional[List[str]] = ...,
        allowed_ips: Optional[List[str]] = ...,
        allow_subdomains: bool = ...,
    ) -> ScopeTool: ...
    @staticmethod
    def allow_all() -> ScopeTool: ...
    @staticmethod
    def deny_all() -> ScopeTool: ...
    @property
    def allowed_patterns(self) -> List[str]: ...
    @property
    def excluded_patterns(self) -> List[str]: ...
    @property
    def allowed_ips(self) -> List[str]: ...
    @property
    def allow_subdomains(self) -> bool: ...
    def is_allowed(self, target: str) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ToolTarget:
    @staticmethod
    def url(value: str) -> ToolTarget: ...
    @staticmethod
    def domain(value: str) -> ToolTarget: ...
    @staticmethod
    def ip(value: str) -> ToolTarget: ...
    @staticmethod
    def cidr(value: str) -> ToolTarget: ...
    @staticmethod
    def file(value: str) -> ToolTarget: ...
    @staticmethod
    def with_scope(target: ToolTarget, scope: ScopeTool) -> ToolTarget: ...
    @property
    def target_type(self) -> TargetType: ...
    @property
    def value(self) -> str: ...
    @property
    def scope(self) -> Optional[ScopeTool]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RequestOptions:
    @staticmethod
    def new(
        timeout_ms: Optional[int] = ...,
        concurrency: Optional[int] = ...,
        rate_limit: Optional[float] = ...,
        proxy: Optional[str] = ...,
        stealth: bool = ...,
        follow_redirects: bool = ...,
        verify_ssl: bool = ...,
    ) -> RequestOptions: ...
    @property
    def timeout_ms(self) -> Optional[int]: ...
    @property
    def concurrency(self) -> Optional[int]: ...
    @property
    def rate_limit(self) -> Optional[float]: ...
    @property
    def proxy(self) -> Optional[str]: ...
    @property
    def stealth(self) -> bool: ...
    @property
    def follow_redirects(self) -> bool: ...
    @property
    def verify_ssl(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class AuthConfig:
    @staticmethod
    def basic(username: str, password: str) -> AuthConfig: ...
    @staticmethod
    def bearer(token: str) -> AuthConfig: ...
    @staticmethod
    def api_key(key: str, header: str) -> AuthConfig: ...
    @property
    def auth_type(self) -> AuthType: ...
    @property
    def credentials(self) -> Dict[str, str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ToolRequest:
    @staticmethod
    def new(
        tool: str,
        target: ToolTarget,
        params: Optional[Dict[str, Any]] = ...,
        options: Optional[RequestOptions] = ...,
    ) -> ToolRequest: ...
    @property
    def id(self) -> str: ...
    @property
    def tool(self) -> str: ...
    @property
    def target(self) -> ToolTarget: ...
    @property
    def params(self) -> Any: ...
    @property
    def options(self) -> RequestOptions: ...
    @property
    def has_cancellation(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ResponseMetadata:
    def __init__(
        self,
        started_at: str,
        completed_at: str,
        duration_ms: int,
        targets_scanned: int,
        findings_count: int,
    ) -> None: ...
    @staticmethod
    def now() -> ResponseMetadata: ...
    @property
    def started_at(self) -> str: ...
    @property
    def completed_at(self) -> str: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def targets_scanned(self) -> int: ...
    @property
    def findings_count(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ToolFinding:
    def __init__(
        self,
        id: str,
        finding_type: ToolFindingType,
        severity: ToolSeverity,
        title: str,
        description: str,
        location: str,
        evidence: Optional[str] = ...,
        cve_ids: Optional[List[str]] = ...,
        remediation: Optional[str] = ...,
    ) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def finding_type(self) -> ToolFindingType: ...
    @property
    def severity(self) -> ToolSeverity: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def location(self) -> str: ...
    @property
    def evidence(self) -> Optional[str]: ...
    @property
    def cve_ids(self) -> List[str]: ...
    @property
    def remediation(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ToolError:
    def __init__(
        self,
        code: str,
        message: str,
        error_type: Optional[ToolErrorType] = ...,
        recoverable: bool = ...,
        retry_after_ms: Optional[int] = ...,
    ) -> None: ...
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def error_type(self) -> ToolErrorType: ...
    @property
    def recoverable(self) -> bool: ...
    @property
    def retry_after_ms(self) -> Optional[int]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ToolResponse:
    @property
    def request_id(self) -> str: ...
    @property
    def tool_id(self) -> str: ...
    @property
    def status(self) -> ResponseType: ...
    @property
    def results(self) -> Any: ...
    @property
    def metadata(self) -> ResponseMetadata: ...
    @property
    def errors(self) -> List[ToolError]: ...
    @property
    def findings(self) -> List[ToolFinding]: ...
    def is_success(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ProgressUpdate:
    def __init__(
        self,
        request_id: str,
        stage: str,
        progress: float,
        message: str,
        items_found: int,
    ) -> None: ...
    @property
    def request_id(self) -> str: ...
    @property
    def stage(self) -> str: ...
    @property
    def progress(self) -> float: ...
    @property
    def message(self) -> str: ...
    @property
    def items_found(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class StreamEvent:
    @staticmethod
    def progress_event(
        request_id: str, stage: str, progress: float, message: str, items_found: int
    ) -> StreamEvent: ...
    @staticmethod
    def finding_event(finding: ToolFinding) -> StreamEvent: ...
    @staticmethod
    def result_event(response: ToolResponse) -> StreamEvent: ...
    @staticmethod
    def error() -> StreamEvent: ...
    @property
    def event_type(self) -> StreamEventType: ...
    @property
    def request_id(self) -> Optional[str]: ...
    @property
    def progress(self) -> Optional[ProgressUpdate]: ...
    @property
    def finding(self) -> Optional[ToolFinding]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PortData:
    def __init__(
        self,
        port: int,
        protocol: str,
        state: PortState,
        service: Optional[str] = ...,
        version: Optional[str] = ...,
        banner: Optional[str] = ...,
    ) -> None: ...
    @property
    def port(self) -> int: ...
    @property
    def protocol(self) -> str: ...
    @property
    def state(self) -> PortState: ...
    @property
    def service(self) -> Optional[str]: ...
    @property
    def version(self) -> Optional[str]: ...
    @property
    def banner(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class EndpointData:
    def __init__(
        self,
        url: str,
        status_code: Optional[int] = ...,
        content_length: Optional[int] = ...,
        content_type: Optional[str] = ...,
    ) -> None: ...
    @property
    def url(self) -> str: ...
    @property
    def status_code(self) -> Optional[int]: ...
    @property
    def content_length(self) -> Optional[int]: ...
    @property
    def content_type(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TechnologyData:
    def __init__(
        self,
        name: str,
        category: str,
        version: Optional[str] = ...,
        confidence: float = ...,
        website: Optional[str] = ...,
        cpe: Optional[str] = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> Optional[str]: ...
    @property
    def category(self) -> str: ...
    @property
    def confidence(self) -> float: ...
    @property
    def website(self) -> Optional[str]: ...
    @property
    def cpe(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RateLimitConfig:
    @staticmethod
    def standard() -> RateLimitConfig: ...
    @staticmethod
    def relaxed() -> RateLimitConfig: ...
    @staticmethod
    def strict() -> RateLimitConfig: ...
    def __init__(
        self,
        requests_per_minute: int = ...,
        concurrent_scans: int = ...,
        burst_size: int = ...,
        global_rate_limit: Optional[int] = ...,
        enable_ip_based_limiting: bool = ...,
    ) -> None: ...
    @property
    def requests_per_minute(self) -> int: ...
    @property
    def concurrent_scans(self) -> int: ...
    @property
    def burst_size(self) -> int: ...
    @property
    def global_rate_limit(self) -> Optional[int]: ...
    @property
    def enable_ip_based_limiting(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class RateLimitStatus:
    def __init__(
        self,
        tokens_available: float,
        requests_this_minute: int,
        requests_per_minute: int,
        concurrent_available: int,
        concurrent_limit: int,
        concurrent_in_use: int,
    ) -> None: ...
    @property
    def tokens_available(self) -> float: ...
    @property
    def requests_this_minute(self) -> int: ...
    @property
    def requests_per_minute(self) -> int: ...
    @property
    def concurrent_available(self) -> int: ...
    @property
    def concurrent_limit(self) -> int: ...
    @property
    def concurrent_in_use(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ExecutionEntry:
    @property
    def request_id(self) -> str: ...
    @property
    def tool_id(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def target_type(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def started_at(self) -> str: ...
    @property
    def completed_at(self) -> str: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def findings_count(self) -> int: ...
    @property
    def errors_count(self) -> int: ...
    @property
    def summary(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
