from typing import Any, Dict, List, Optional
from .network import ConnectionTimingPy, ConnectionMetadataPy, SocketEndpointPy

class TcpConfigPy:
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def connect_timeout_ms(self) -> int: ...
    @property
    def read_timeout_ms(self) -> int: ...
    @property
    def write_timeout_ms(self) -> int: ...
    @property
    def idle_timeout_ms(self) -> int: ...
    @property
    def nodelay(self) -> bool: ...
    def __init__(self, host: str, port: int, connect_timeout_ms: int = 5000, read_timeout_ms: int = 30000, write_timeout_ms: int = 30000, idle_timeout_ms: int = 60000, nodelay: bool = True) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TcpSessionPy:
    @property
    def is_closed(self) -> bool: ...
    @property
    def config(self) -> TcpConfigPy: ...
    @property
    def transcript(self) -> Any: ...
    @property
    def bytes_sent(self) -> int: ...
    @property
    def bytes_received(self) -> int: ...
    def connect(self) -> TcpConnectResultPy: ...
    def read(self, max_bytes: int = 4096) -> TcpReadResultPy: ...
    def read_exact(self, n: int) -> TcpReadResultPy: ...
    def read_until(self, delimiter: int = 10, max_len: int = 65536) -> TcpReadResultPy: ...
    def write(self, data: bytes) -> TcpWriteResultPy: ...
    def write_all(self, data: bytes) -> TcpWriteResultPy: ...
    def close(self) -> None: ...
    def __enter__(self) -> TcpSessionPy: ...
    def __exit__(self, *args: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TcpConnectResultPy:
    @property
    def local_endpoint(self) -> SocketEndpointPy: ...
    @property
    def remote_endpoint(self) -> SocketEndpointPy: ...
    @property
    def timing(self) -> ConnectionTimingPy: ...
    @property
    def metadata(self) -> ConnectionMetadataPy: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TcpReadResultPy:
    @property
    def data(self) -> bytes: ...
    @property
    def bytes_read(self) -> int: ...
    @property
    def eof(self) -> bool: ...
    @property
    def duration_ms(self) -> float: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TcpWriteResultPy:
    @property
    def bytes_written(self) -> int: ...
    @property
    def duration_ms(self) -> float: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class UdpConfigPy:
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def max_datagram_size(self) -> int: ...
    @property
    def bind_address(self) -> Optional[str]: ...
    def __init__(self, host: str, port: int, timeout_ms: int = 5000, max_datagram_size: int = 65535, bind_address: Optional[str] = None) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class UdpSocketPy:
    @property
    def is_closed(self) -> bool: ...
    @property
    def bytes_sent(self) -> int: ...
    @property
    def bytes_received(self) -> int: ...
    @property
    def transcript(self) -> Any: ...
    def connect(self) -> None: ...
    def send(self, data: bytes) -> UdpSendResultPy: ...
    def send_to(self, data: bytes, addr: str) -> UdpSendResultPy: ...
    def recv(self) -> UdpRecvResultPy: ...
    def recv_from(self) -> UdpRecvFromResultPy: ...
    def close(self) -> None: ...
    def __enter__(self) -> UdpSocketPy: ...
    def __exit__(self, *args: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class UdpSendResultPy:
    @property
    def bytes_sent(self) -> int: ...
    @property
    def duration_ms(self) -> float: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class UdpRecvResultPy:
    @property
    def data(self) -> bytes: ...
    @property
    def bytes_received(self) -> int: ...
    @property
    def truncated(self) -> bool: ...
    @property
    def duration_ms(self) -> float: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class UdpRecvFromResultPy:
    @property
    def data(self) -> bytes: ...
    @property
    def bytes_received(self) -> int: ...
    @property
    def source_address(self) -> str: ...
    @property
    def source_port(self) -> int: ...
    @property
    def truncated(self) -> bool: ...
    @property
    def duration_ms(self) -> float: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BannerProbeResultPy:
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def banner_bytes(self) -> bytes: ...
    @property
    def banner_text(self) -> Optional[str]: ...
    @property
    def encoding(self) -> Optional[str]: ...
    @property
    def timeout(self) -> bool: ...
    @property
    def connection_error(self) -> Optional[str]: ...
    @property
    def timing(self) -> ConnectionTimingPy: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def tcp_connect_probe(host: str, port: int, timeout_ms: int = 5000) -> TcpConnectResultPy: ...
def async_tcp_connect_probe(host: str, port: int, timeout_ms: int = 5000) -> Any: ...
def banner_probe(host: str, port: int, timeout_ms: int = 5000, max_banner_bytes: int = 4096) -> BannerProbeResultPy: ...
def async_banner_probe(host: str, port: int, timeout_ms: int = 5000, max_banner_bytes: int = 4096) -> Any: ...
