from typing import Any, Dict, List, Optional

class WafDetectionResult:
    @property
    def url(self) -> str: ...
    @property
    def detected(self) -> bool: ...
    @property
    def vendor(self) -> Optional[str]: ...
    @property
    def waf_name(self) -> Optional[str]: ...
    @property
    def confidence(self) -> int: ...
    @property
    def server_header(self) -> Optional[str]: ...
    @property
    def status_code(self) -> int: ...
    @property
    def request_error(self) -> Optional[str]: ...
    @property
    def matched_headers(self) -> list[str]: ...
    @property
    def matched_cookies(self) -> list[str]: ...
    @property
    def matched_patterns(self) -> list[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
