"""WAF validation and HTTP fuzzing type stubs."""

from typing import Any, Dict, List, Optional

class BypassResultPy:
    @property
    def technique(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def description(self) -> str: ...
    @property
    def payload(self) -> Optional[str]: ...
    @property
    def status_code(self) -> int: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

BypassResult = BypassResultPy

class WafScanResultPy:
    @property
    def target(self) -> str: ...
    @property
    def waf_detected(self) -> bool: ...
    @property
    def waf_name(self) -> Optional[str]: ...
    @property
    def confidence(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def bypasses_tested(self) -> int: ...
    @property
    def bypasses_successful(self) -> int: ...
    @property
    def bypass_results(self) -> List[BypassResultPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

WafScanResult = WafScanResultPy

class PayloadPy:
    @property
    def payload_type(self) -> str: ...
    @property
    def payload(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def tags(self) -> List[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def __repr__(self) -> str: ...

Payload = PayloadPy

class FuzzResultPy:
    @property
    def payload(self) -> str: ...
    @property
    def payload_type(self) -> str: ...
    @property
    def status_code(self) -> int: ...
    @property
    def response_time_ms(self) -> int: ...
    @property
    def is_vulnerable(self) -> bool: ...
    @property
    def is_waf_blocked(self) -> bool: ...
    @property
    def leaks_found(self) -> List[str]: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

FuzzResult = FuzzResultPy

class FuzzSessionPy:
    @property
    def target_url(self) -> str: ...
    @property
    def payload_type(self) -> str: ...
    @property
    def total_payloads(self) -> int: ...
    @property
    def successful_requests(self) -> int: ...
    @property
    def failed_requests(self) -> int: ...
    @property
    def potential_leaks(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    @property
    def results(self) -> List[FuzzResultPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

FuzzSession = FuzzSessionPy

class FuzzConfig:
    def __init__(
        self,
        url: str,
        payload_type: str = "all",
        method: str = "GET",
        param: Optional[str] = None,
        concurrency: int = 10,
        timeout: int = 30,
    ) -> None: ...
    @property
    def url(self) -> str: ...
    @property
    def payload_type(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def param(self) -> Optional[str]: ...
    @property
    def concurrency(self) -> int: ...
    @property
    def timeout(self) -> int: ...
