from typing import Any, Dict, List, Optional, Tuple

from .finding import Severity

class ConnectionTestResultPy:
    @property
    def url(self) -> str: ...
    @property
    def connected(self) -> bool: ...
    @property
    def response_headers(self) -> List[Tuple[str, str]]: ...
    @property
    def subprotocols(self) -> List[str]: ...
    @property
    def extensions(self) -> List[str]: ...
    @property
    def latency_ms(self) -> Optional[float]: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class InjectionTestResultPy:
    @property
    def payload(self) -> str: ...
    @property
    def sent(self) -> bool: ...
    @property
    def received_response(self) -> bool: ...
    @property
    def response_content(self) -> Optional[str]: ...
    @property
    def vulnerability_detected(self) -> bool: ...
    @property
    def details(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class OriginTestResultPy:
    @property
    def origin(self) -> str: ...
    @property
    def accepted(self) -> bool: ...
    @property
    def status_code(self) -> Optional[int]: ...
    @property
    def details(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FuzzTestResultPy:
    @property
    def test_name(self) -> str: ...
    @property
    def payload_size(self) -> int: ...
    @property
    def sent(self) -> bool: ...
    @property
    def connection_dropped(self) -> bool: ...
    @property
    def server_response(self) -> Optional[str]: ...
    @property
    def vulnerability_detected(self) -> bool: ...
    @property
    def details(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketFindingPy:
    @property
    def category(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def recommendation(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketReportPy:
    @property
    def target(self) -> str: ...
    @property
    def connection_test(self) -> Optional[ConnectionTestResultPy]: ...
    @property
    def injection_tests(self) -> List[InjectionTestResultPy]: ...
    @property
    def origin_tests(self) -> List[OriginTestResultPy]: ...
    @property
    def fuzz_tests(self) -> List[FuzzTestResultPy]: ...
    @property
    def findings(self) -> List[WebSocketFindingPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketTestConfigPy:
    @property
    def url(self) -> str: ...
    @property
    def timeout_secs(self) -> int: ...
    @property
    def injection_payloads(self) -> List[str]: ...
    @property
    def test_connection(self) -> bool: ...
    @property
    def test_origins(self) -> bool: ...
    @property
    def test_injection(self) -> bool: ...
    @property
    def test_dos(self) -> bool: ...
    @property
    def test_message_fuzz(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def websocket_probe(url: str, timeout_secs: int = 10) -> WebSocketReportPy: ...
def async_websocket_probe(url: str, timeout_secs: int = 10) -> Any: ...
def websocket_fuzz(url: str, timeout_secs: int = 10) -> WebSocketReportPy: ...
def async_websocket_fuzz(url: str, timeout_secs: int = 10) -> Any: ...

class WebSocketSessionConfigPy:
    @property
    def url(self) -> str: ...
    @property
    def headers(self) -> List[Tuple[str, str]]: ...
    @property
    def cookies(self) -> List[Tuple[str, str]]: ...
    @property
    def origin(self) -> Optional[str]: ...
    @property
    def subprotocols(self) -> List[str]: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def max_message_size(self) -> int: ...
    @property
    def ping_interval_ms(self) -> Optional[int]: ...
    @property
    def close_timeout_ms(self) -> int: ...
    @property
    def verify_tls(self) -> bool: ...
    def __init__(self, url: str, *, headers: Optional[List[Tuple[str, str]]] = None, cookies: Optional[List[Tuple[str, str]]] = None, origin: Optional[str] = None, subprotocols: Optional[List[str]] = None, timeout_ms: int = 10000, max_message_size: int = 1048576, ping_interval_ms: Optional[int] = 30000, close_timeout_ms: int = 5000, verify_tls: bool = True) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketMessagePy:
    @property
    def data(self) -> bytes: ...
    @property
    def is_text(self) -> bool: ...
    @property
    def is_binary(self) -> bool: ...
    @property
    def text_content(self) -> Optional[str]: ...
    @property
    def size(self) -> int: ...
    def to_text(self) -> Optional[str]: ...
    def to_bytes(self) -> bytes: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketFramePy:
    @property
    def opcode(self) -> int: ...
    @property
    def opcode_name(self) -> str: ...
    @property
    def payload(self) -> bytes: ...
    @property
    def fin(self) -> bool: ...
    @property
    def masked(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketCloseInfoPy:
    @property
    def code(self) -> int: ...
    @property
    def reason(self) -> str: ...
    @property
    def was_clean(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketHandshakePy:
    @property
    def url(self) -> str: ...
    @property
    def status_code(self) -> int: ...
    @property
    def headers(self) -> List[Tuple[str, str]]: ...
    @property
    def selected_subprotocol(self) -> Optional[str]: ...
    @property
    def selected_extensions(self) -> List[str]: ...
    @property
    def duration_ms(self) -> float: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketSessionPy:
    @property
    def is_closed(self) -> bool: ...
    @property
    def url(self) -> str: ...
    def __init__(self, config: WebSocketSessionConfigPy) -> None: ...
    def connect(self) -> WebSocketHandshakePy: ...
    def send_text(self, text: str) -> None: ...
    def send_binary(self, data: bytes) -> None: ...
    def recv(self) -> WebSocketMessagePy: ...
    def ping(self, data: Optional[bytes] = None) -> None: ...
    def close(self, code: Optional[int] = None, reason: Optional[str] = None) -> WebSocketCloseInfoPy: ...
    def __enter__(self) -> WebSocketSessionPy: ...
    def __exit__(self, *args: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class AsyncWebSocketSessionPy:
    @property
    def is_closed(self) -> bool: ...
    @property
    def url(self) -> str: ...
    def __init__(self, config: WebSocketSessionConfigPy) -> None: ...
    def async_connect(self) -> Any: ...
    def async_send_text(self, text: str) -> Any: ...
    def async_send_binary(self, data: bytes) -> Any: ...
    def async_recv(self) -> Any: ...
    def async_ping(self, data: Optional[bytes] = None) -> Any: ...
    def async_close(self, code: Optional[int] = None, reason: Optional[str] = None) -> Any: ...
    def __aenter__(self) -> AsyncWebSocketSessionPy: ...
    def __aexit__(self, *args: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketAssessmentConfigPy:
    @property
    def url(self) -> str: ...
    @property
    def timeout_ms(self) -> int: ...
    @property
    def test_connection(self) -> bool: ...
    @property
    def test_origin_validation(self) -> bool: ...
    @property
    def test_authentication(self) -> bool: ...
    @property
    def test_subprotocol(self) -> bool: ...
    @property
    def test_message_access(self) -> bool: ...
    @property
    def test_close_behavior(self) -> bool: ...
    def __init__(self, url: str, *, timeout_ms: int = 30000, test_connection: bool = True, test_origin_validation: bool = True, test_authentication: bool = True, test_subprotocol: bool = True, test_message_access: bool = True, test_close_behavior: bool = True) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketAssessmentResultPy:
    @property
    def target(self) -> str: ...
    @property
    def handshake(self) -> Optional[WebSocketHandshakePy]: ...
    @property
    def origin_test(self) -> Optional[OriginTestResultPy]: ...
    @property
    def auth_test(self) -> Optional[ConnectionTestResultPy]: ...
    @property
    def subprotocol_test(self) -> Optional[ConnectionTestResultPy]: ...
    @property
    def message_test(self) -> Optional[ConnectionTestResultPy]: ...
    @property
    def close_test(self) -> Optional[WebSocketCloseInfoPy]: ...
    @property
    def findings(self) -> List[WebSocketFindingPy]: ...
    @property
    def finding_count(self) -> int: ...
    @property
    def timing(self) -> Any: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def websocket_assess(url: str, timeout_ms: int = 30000) -> WebSocketAssessmentResultPy: ...
def async_websocket_assess(url: str, timeout_ms: int = 30000) -> Any: ...
