from typing import Any, Dict, List, Optional, Tuple

from .finding import Severity

class ConnectionTestResultPy:
    @property
    def url(self) -> str: ...
    @property
    def connected(self) -> bool: ...
    @property
    def response_headers(self) -> List[Tuple[str, str]]: ...
    @property
    def subprotocols(self) -> List[str]: ...
    @property
    def extensions(self) -> List[str]: ...
    @property
    def latency_ms(self) -> Optional[float]: ...
    @property
    def error(self) -> Optional[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class InjectionTestResultPy:
    @property
    def payload(self) -> str: ...
    @property
    def sent(self) -> bool: ...
    @property
    def received_response(self) -> bool: ...
    @property
    def response_content(self) -> Optional[str]: ...
    @property
    def vulnerability_detected(self) -> bool: ...
    @property
    def details(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class OriginTestResultPy:
    @property
    def origin(self) -> str: ...
    @property
    def accepted(self) -> bool: ...
    @property
    def status_code(self) -> Optional[int]: ...
    @property
    def details(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FuzzTestResultPy:
    @property
    def test_name(self) -> str: ...
    @property
    def payload_size(self) -> int: ...
    @property
    def sent(self) -> bool: ...
    @property
    def connection_dropped(self) -> bool: ...
    @property
    def server_response(self) -> Optional[str]: ...
    @property
    def vulnerability_detected(self) -> bool: ...
    @property
    def details(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketFindingPy:
    @property
    def category(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def recommendation(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketReportPy:
    @property
    def target(self) -> str: ...
    @property
    def connection_test(self) -> Optional[ConnectionTestResultPy]: ...
    @property
    def injection_tests(self) -> List[InjectionTestResultPy]: ...
    @property
    def origin_tests(self) -> List[OriginTestResultPy]: ...
    @property
    def fuzz_tests(self) -> List[FuzzTestResultPy]: ...
    @property
    def findings(self) -> List[WebSocketFindingPy]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class WebSocketTestConfigPy:
    @property
    def url(self) -> str: ...
    @property
    def timeout_secs(self) -> int: ...
    @property
    def injection_payloads(self) -> List[str]: ...
    @property
    def test_connection(self) -> bool: ...
    @property
    def test_origins(self) -> bool: ...
    @property
    def test_injection(self) -> bool: ...
    @property
    def test_dos(self) -> bool: ...
    @property
    def test_message_fuzz(self) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

def websocket_probe(url: str, timeout_secs: int = 10) -> WebSocketReportPy: ...
def async_websocket_probe(url: str, timeout_secs: int = 10) -> Any: ...
def websocket_fuzz(url: str, timeout_secs: int = 10) -> WebSocketReportPy: ...
def async_websocket_fuzz(url: str, timeout_secs: int = 10) -> Any: ...
