# Feature-gated: wireless scanning
from typing import Any

class SecurityTypePy:
    pass

class WirelessNetworkPy:
    @property
    def ssid(self) -> str: ...
    @property
    def bssid(self) -> str: ...
    @property
    def security_type(self) -> SecurityTypePy: ...
    @property
    def signal_strength(self) -> int: ...

class WirelessVulnerabilityPy:
    @property
    def description(self) -> str: ...
    @property
    def severity(self) -> str: ...

class WirelessScanResultPy:
    @property
    def networks(self) -> list[WirelessNetworkPy]: ...
    @property
    def vulnerabilities(self) -> list[WirelessVulnerabilityPy]: ...

class WirelessScanConfigPy:
    pass

def wireless_scan(config: WirelessScanConfigPy) -> WirelessScanResultPy: ...
async def async_wireless_scan(config: WirelessScanConfigPy) -> WirelessScanResultPy: ...
def wireless_analyze_networks(networks: list[WirelessNetworkPy]) -> list[Any]: ...
