//! Regression tests: navigation must not mutate tab state while a task runs.
//!
//! The `is_running()` guard convention (see `AGENTS.override.md`) requires every
//! input/navigation handler to bail out before touching focus or field state
//! while a task is active.
//!
//! Why this is a real user-visible defect, not merely an internal invariant: a
//! focus handler that runs mid-scan can move focus off the input area, but
//! `handle_char` / `handle_backspace` still refuse to edit because `is_running`
//! is true. The operator is left with a focus ring that no longer marks a field
//! they can type into, mid-scan, with no way to tell why their keys stopped
//! landing. `handle_escape` / `Ctrl+C` still stop the task, so the scan has to
//! be cancelled before the form is usable again.
//!
//! `TabInput::is_input_focused()` is the precise observable: it is what the
//! focus ring renders and what the key handler consults before editing, so a
//! `true -> false` flip mid-run *is* the user-visible bug. The tests drive every
//! tab through the same `App`-level entry points a real keystroke uses
//! (`ensure_input_focus` on tab entry, `as_tab_input` for keys), so they keep
//! working if a tab is later refactored onto a different macro.

use crate::tabs::{AppState, Tab};

/// Reaching a tab through `as_tab_input` needs a `&mut App`, so the current tab
/// is copied out first to keep the two borrows non-overlapping.
fn is_input_focused(app: &mut crate::App) -> bool {
    let mut tab = app.current_tab;
    tab.as_tab_input(app).is_input_focused()
}

fn set_state(app: &mut crate::App, state: AppState) {
    let mut tab = app.current_tab;
    tab.as_tab_state_mut(app).set_state(state);
}

/// Simulate entering a tab: reset it, then run the tab-entry hook that
/// establishes the "focus ring points at a field" invariant.
fn enter_tab(app: &mut crate::App, tab: &Tab) {
    app.current_tab = *tab;
    app.reset_current_tab();
    let mut current = app.current_tab;
    current.as_tab_input(app).ensure_input_focus();
}

/// Put a tab into the running state, the way a dispatch would.
///
/// `TabState` exposes no state setter in production — a tab reaches `Running`
/// only through a dispatch, which the App-level path gates on enforcement and
/// target validation. The invariant under test is specifically "what happens to
/// navigation *after* a task is running", so the precondition is injected via
/// the test-only `set_state` hook (generated by `tab_state_boilerplate!`) and
/// the App-level task marker is set too, keeping `App::is_running()` honest.
fn force_running(app: &mut crate::App) {
    app.task_state.tab = Some(app.current_tab);
    set_state(app, AppState::Running);
}

/// Tabs that can never be running, because they own no task lifecycle: they
/// report `AppState::Idle` unconditionally and have no `set_state` hook. There
/// is no "mid-run" state to protect, so they are excluded.
fn can_run(tab: &Tab) -> bool {
    !matches!(*tab, Tab::Dashboard | Tab::History | Tab::Settings)
}

#[test]
fn navigation_never_focuses_an_input_while_a_task_is_running() {
    let mut app = crate::app::create_test_app();

    for tab in Tab::all() {
        if !can_run(tab) {
            continue;
        }
        enter_tab(&mut app, tab);
        force_running(&mut app);

        assert!(
            is_input_focused(&mut app),
            "{tab:?}: precondition: the focus ring starts on an input field"
        );

        // Every navigation key a keystroke can deliver, in one pass.
        {
            let mut current = app.current_tab;
            let input = current.as_tab_input(&mut app);
            input.handle_focus_prev();
            input.handle_focus_next();
            input.handle_down();
            input.handle_up();
            input.handle_top();
            input.handle_bottom();
        }

        assert!(
            is_input_focused(&mut app),
            "{tab:?}: navigation moved focus off the input mid-run. The focus \
             ring no longer marks a usable field, but handle_char still refuses \
             to edit because the task is running, so every keystroke is \
             silently discarded until the task is cancelled — dead input."
        );
    }
}

#[test]
fn navigation_is_not_disabled_while_idle() {
    // Guards the fix from over-correcting into "focus never moves at all".
    let mut app = crate::app::create_test_app();

    let mut moved = 0usize;
    for tab in Tab::all() {
        enter_tab(&mut app, tab);
        if !is_input_focused(&mut app) {
            // Tabs that open on a selector/options area rather than the inputs.
            continue;
        }

        {
            let mut current = app.current_tab;
            current.as_tab_input(&mut app).handle_focus_next();
        }

        if !is_input_focused(&mut app) {
            moved += 1;
        }
    }

    assert!(
        moved > 0,
        "focus_next never moved focus off the inputs on any tab while idle — the \
         is_running() guard looks like it was applied unconditionally"
    );
}
