#!/usr/bin/env python3
"""F2: Semantic Python compatibility checker.

Compares the installed eggsec package against a generated baseline to detect
breaking, deprecating, widening, and compatible changes.

Requirements:
    - eggsec installed (maturin develop)
    - compatibility_baseline.json generated by generate_python_compatibility_baseline.py

Usage:
    python scripts/check_python_compatibility.py [--allowlist FILE]
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import json
import sys
from pathlib import Path
from typing import Any


_BASELINE_PATH = Path(__file__).resolve().parent.parent / "crates" / "eggsec-python" / "tests" / "compatibility_baseline.json"
_ALLOWLIST_PATH = Path(__file__).resolve().parent.parent / "crates" / "eggsec-python" / "tests" / "compatibility_allowlist.json"
_REPORT_PATH = Path(__file__).resolve().parent.parent / "target" / "compatibility-report.json"

_SENTINEL = object()


# ---------------------------------------------------------------------------
# Change classification
# ---------------------------------------------------------------------------

class Change:
    """A detected compatibility change."""

    __slots__ = ("symbol", "kind", "description", "stability", "details")

    def __init__(self, symbol: str, kind: str, description: str,
                 stability: str = "stable", details: dict | None = None):
        self.symbol = symbol
        self.kind = kind
        self.description = description
        self.stability = stability
        self.details = details or {}

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            "symbol": self.symbol,
            "change_type": self.kind,
            "description": self.description,
            "stability": self.stability,
        }
        if self.details:
            d["details"] = self.details
        return d

    def __repr__(self) -> str:
        return f"Change({self.kind}, {self.symbol}: {self.description})"


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------

def load_baseline(path: Path) -> dict[str, Any]:
    """Load the baseline JSON."""
    if not path.exists():
        print(f"Baseline not found at {path}", file=sys.stderr)
        print("Run: python scripts/generate_python_compatibility_baseline.py", file=sys.stderr)
        sys.exit(1)
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_allowlist(path: Path) -> dict[str, list[str]]:
    """Load the allowlist of known intentional breaking changes."""
    if not path.exists():
        return {}
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, dict) else {}


def _safe_import(name: str) -> Any:
    """Import name from eggsec, return _SENTINEL on failure."""
    try:
        mod = importlib.import_module("eggsec")
        return getattr(mod, name, _SENTINEL)
    except Exception:
        return _SENTINEL


def _resolve_submodule(name: str) -> Any:
    """Try to import a submodule-qualified name."""
    parts = name.rsplit(".", 1)
    if len(parts) == 2:
        try:
            mod = importlib.import_module(parts[0])
            return getattr(mod, parts[1], _SENTINEL)
        except ImportError:
            pass
    return _SENTINEL


# ---------------------------------------------------------------------------
# Change detection
# ---------------------------------------------------------------------------

def detect_removed_symbols(
    baseline_symbols: dict[str, Any],
    current_surface: set[str],
) -> list[Change]:
    """Detect symbols present in baseline but absent in current package."""
    changes: list[Change] = []
    for name, info in baseline_symbols.items():
        if name in current_surface:
            continue
        stability = info.get("stability", "stable")
        kind = info.get("kind", "unknown")
        changes.append(Change(
            symbol=name,
            kind="definitely_breaking" if stability == "stable" else "provisional_change",
            description=f"Symbol '{name}' ({kind}) removed from package",
            stability=stability,
        ))
    return changes


def detect_added_symbols(
    baseline_symbols: dict[str, Any],
    current_surface: set[str],
) -> list[Change]:
    """Detect symbols present in current but absent in baseline."""
    changes: list[Change] = []
    for name in sorted(current_surface):
        if name in baseline_symbols:
            continue
        changes.append(Change(
            symbol=name,
            kind="compatible_addition",
            description=f"New public symbol '{name}' added to package",
            stability="stable",
        ))
    return changes


def detect_deprecation_changes(
    baseline_symbols: dict[str, Any],
    current_surface: set[str],
) -> list[Change]:
    """Detect newly deprecated symbols."""
    changes: list[Change] = []
    for name in current_surface:
        if name not in baseline_symbols:
            continue
        baseline_dep = baseline_symbols[name].get("deprecated", False)
        if baseline_dep:
            continue  # Already deprecated in baseline
        obj = _safe_import(name)
        if obj is _SENTINEL:
            continue
        # Check for deprecation markers
        is_dep = False
        try:
            mod = importlib.import_module("eggsec")
            aliases = getattr(mod, "_DEPRECATED_ALIASES", {})
            if name in aliases:
                is_dep = True
        except Exception:
            pass
        # Check for DeprecationWarning on access
        if not is_dep:
            try:
                import warnings
                with warnings.catch_warnings(record=True) as w:
                    warnings.simplefilter("always")
                    _ = getattr(importlib.import_module("eggsec"), name, None)
                    for warning in w:
                        if issubclass(warning.category, DeprecationWarning):
                            is_dep = True
                            break
            except Exception:
                pass
        if is_dep:
            baseline_stability = baseline_symbols[name].get("stability", "stable")
            changes.append(Change(
                symbol=name,
                kind="deprecation",
                description=f"Symbol '{name}' is now deprecated",
                stability=baseline_stability,
            ))
    return changes


def detect_signature_changes(
    baseline_symbols: dict[str, Any],
    current_surface: set[str],
) -> list[Change]:
    """Detect function signature changes (parameters, defaults, return types)."""
    changes: list[Change] = []

    for name in current_surface:
        if name not in baseline_symbols:
            continue
        baseline_info = baseline_symbols[name]
        if baseline_info.get("kind") != "function":
            continue
        if baseline_info.get("stability") not in ("stable", "provisional"):
            continue

        obj = _safe_import(name)
        if obj is _SENTINEL or not callable(obj):
            continue

        # Compare parameters from baseline
        baseline_params = baseline_info.get("parameters", [])
        if not isinstance(baseline_params, list):
            continue

        try:
            sig = inspect.signature(obj)
            current_params = []
            for pname, param in sig.parameters.items():
                p: dict[str, Any] = {
                    "name": pname,
                    "required": param.default is inspect.Parameter.empty,
                    "kind": {
                        inspect.Parameter.POSITIONAL_ONLY: "posonly",
                        inspect.Parameter.POSITIONAL_OR_KEYWORD: "positional",
                        inspect.Parameter.KEYWORD_ONLY: "keyword",
                    }.get(param.kind, "positional"),
                }
                if param.default is not inspect.Parameter.empty:
                    p["default"] = repr(param.default)
                current_params.append(p)
        except (ValueError, TypeError):
            continue

        # Build lookup maps
        baseline_by_name = {p["name"]: p for p in baseline_params if isinstance(p, dict)}
        current_by_name = {p["name"]: p for p in current_params}

        baseline_names = set(baseline_by_name.keys())
        current_names = set(current_by_name.keys())

        # Removed parameters
        for removed in baseline_names - current_names:
            old_param = baseline_by_name[removed]
            stability = baseline_info.get("stability", "stable")
            if old_param.get("required", True):
                changes.append(Change(
                    symbol=name,
                    kind="definitely_breaking" if stability == "stable" else "potentially_breaking",
                    description=f"Required parameter '{removed}' removed from '{name}'",
                    stability=stability,
                    details={"removed_param": removed},
                ))
            else:
                changes.append(Change(
                    symbol=name,
                    kind="compatible_widening" if stability == "stable" else "provisional_change",
                    description=f"Optional parameter '{removed}' removed from '{name}' (was optional)",
                    stability=stability,
                    details={"removed_param": removed},
                ))

        # Added parameters
        for added in current_names - baseline_names:
            new_param = current_by_name[added]
            stability = baseline_info.get("stability", "stable")
            if new_param.get("required", True):
                changes.append(Change(
                    symbol=name,
                    kind="definitely_breaking" if stability == "stable" else "potentially_breaking",
                    description=f"New required parameter '{added}' added to '{name}'",
                    stability=stability,
                    details={"added_param": added},
                ))
            else:
                changes.append(Change(
                    symbol=name,
                    kind="compatible_widening",
                    description=f"New optional parameter '{added}' added to '{name}'",
                    stability=stability,
                    details={"added_param": added},
                ))

        # Changed defaults
        for pname in baseline_names & current_names:
            old = baseline_by_name[pname]
            new = current_by_name[pname]
            if old.get("required") != new.get("required"):
                stability = baseline_info.get("stability", "stable")
                if old.get("required") and not new.get("required"):
                    changes.append(Change(
                        symbol=name,
                        kind="compatible_widening",
                        description=f"Parameter '{pname}' in '{name}' changed from required to optional",
                        stability=stability,
                    ))
                else:
                    changes.append(Change(
                        symbol=name,
                        kind="definitely_breaking" if stability == "stable" else "potentially_breaking",
                        description=f"Parameter '{pname}' in '{name}' changed from optional to required",
                        stability=stability,
                    ))
            elif not old.get("required") and not new.get("required"):
                old_default = old.get("default")
                new_default = new.get("default")
                if old_default != new_default:
                    stability = baseline_info.get("stability", "stable")
                    changes.append(Change(
                        symbol=name,
                        kind="provisional_change",
                        description=f"Default value for '{pname}' in '{name}' changed: {old_default} -> {new_default}",
                        stability=stability,
                        details={"old_default": old_default, "new_default": new_default},
                    ))

    return changes


def detect_enum_changes(
    baseline_symbols: dict[str, Any],
    current_surface: set[str],
) -> list[Change]:
    """Detect enum value removals, additions, or renames."""
    changes: list[Change] = []

    for name in current_surface:
        if name not in baseline_symbols:
            continue
        baseline_info = baseline_symbols[name]
        if baseline_info.get("kind") != "enum":
            continue
        if baseline_info.get("stability") not in ("stable", "provisional"):
            continue

        baseline_values = set(baseline_info.get("enum_values", {}).keys())
        obj = _safe_import(name)
        if obj is _SENTINEL:
            continue

        current_values = set()
        if hasattr(obj, "__members__"):
            current_values = set(obj.__members__.keys())
        elif hasattr(obj, "__dict__"):
            current_values = {k for k in obj.__dict__ if not k.startswith("_")}

        removed = baseline_values - current_values
        added = current_values - baseline_values
        stability = baseline_info.get("stability", "stable")

        for val in sorted(removed):
            changes.append(Change(
                symbol=f"{name}.{val}",
                kind="definitely_breaking" if stability == "stable" else "potentially_breaking",
                description=f"Enum value '{val}' removed from '{name}'",
                stability=stability,
                details={"removed_value": val, "enum": name},
            ))

        for val in sorted(added):
            changes.append(Change(
                symbol=f"{name}.{val}",
                kind="compatible_widening",
                description=f"New enum value '{val}' added to '{name}'",
                stability=stability,
                details={"added_value": val, "enum": name},
            ))

    return changes


def detect_class_change_type(
    baseline_symbols: dict[str, Any],
    current_surface: set[str],
) -> list[Change]:
    """Detect kind changes (e.g. function -> class, constant -> function)."""
    changes: list[Change] = []

    for name in current_surface:
        if name not in baseline_symbols:
            continue
        baseline_kind = baseline_symbols[name].get("kind", "unknown")
        obj = _safe_import(name)
        if obj is _SENTINEL:
            continue
        # Determine current kind
        if inspect.isclass(obj):
            current_kind = "class"
            if hasattr(obj, "__members__"):
                current_kind = "enum"
        elif callable(obj):
            current_kind = "function"
        else:
            current_kind = "constant"

        if baseline_kind != current_kind and baseline_kind != "unknown" and current_kind != "unknown":
            # Allow enum/class interchangeability
            if {baseline_kind, current_kind} <= {"class", "enum"}:
                continue
            stability = baseline_symbols[name].get("stability", "stable")
            changes.append(Change(
                symbol=name,
                kind="definitely_breaking" if stability == "stable" else "potentially_breaking",
                description=f"Symbol kind changed: {baseline_kind} -> {current_kind}",
                stability=stability,
                details={"old_kind": baseline_kind, "new_kind": current_kind},
            ))

    return changes


def detect_version_changes(
    baseline: dict[str, Any],
) -> list[Change]:
    """Detect version/protocol/ABI constant changes."""
    changes: list[Change] = []
    baseline_versions = baseline.get("version_constants", {})

    try:
        import eggsec
        current_versions = {
            "schema_version": getattr(eggsec, "SCHEMA_VERSION", getattr(eggsec, "__schema_version__", "")),
            "protocol_version": getattr(eggsec, "PROTOCOL_VERSION", getattr(eggsec, "__protocol_version__", "")),
            "abi_version": getattr(eggsec, "ABI_VERSION", getattr(eggsec, "__abi_version__", "")),
        }
    except Exception:
        return changes

    for key in ("schema_version", "protocol_version", "abi_version"):
        old_val = baseline_versions.get(key, "")
        new_val = current_versions.get(key, "")
        if old_val and new_val and old_val != new_val:
            # Parse version tuples for comparison
            try:
                old_parts = tuple(int(x) for x in str(old_val).split("."))
                new_parts = tuple(int(x) for x in str(new_val).split("."))
                is_major_break = (len(new_parts) > 0 and len(old_parts) > 0
                                  and new_parts[0] > old_parts[0])
            except (ValueError, TypeError):
                is_major_break = False

            changes.append(Change(
                symbol=key,
                kind="definitely_breaking" if is_major_break else "compatible_widening",
                description=f"{key} changed: {old_val} -> {new_val}",
                stability="stable",
                details={"old": str(old_val), "new": str(new_val)},
            ))

    return changes


def detect_exception_changes(
    baseline: dict[str, Any],
) -> list[Change]:
    """Detect exception hierarchy changes."""
    changes: list[Change] = []
    baseline_exc = baseline.get("exception_hierarchy", {})
    if not baseline_exc:
        return changes

    try:
        import eggsec
        for exc_name in baseline_exc:
            exc_cls = getattr(eggsec, exc_name, None)
            if exc_cls is None:
                try:
                    from eggsec import errors
                    exc_cls = getattr(errors, exc_name, None)
                except Exception:
                    pass
            if exc_cls is None:
                changes.append(Change(
                    symbol=exc_name,
                    kind="definitely_breaking",
                    description=f"Exception class '{exc_name}' removed from hierarchy",
                    stability="stable",
                ))
    except ImportError:
        pass

    return changes


def detect_feature_profile_drift(
    baseline: dict[str, Any],
) -> list[Change]:
    """Detect feature-profile export drift."""
    changes: list[Change] = []
    baseline_profile = baseline.get("wheel_profile_inventory", {})
    if not baseline_profile:
        return changes

    try:
        from eggsec import wheel_profile, features
        current_profile = wheel_profile()
        current_features = sorted(features())

        if baseline_profile.get("profile") != current_profile:
            changes.append(Change(
                symbol="wheel_profile",
                kind="compatible_widening",
                description=f"Wheel profile changed: {baseline_profile.get('profile')} -> {current_profile}",
                stability="stable",
            ))

        baseline_features = sorted(baseline_profile.get("compiled_features", []))
        removed_features = set(baseline_features) - set(current_features)
        for feat in sorted(removed_features):
            changes.append(Change(
                symbol=f"feature:{feat}",
                kind="potentially_breaking",
                description=f"Compiled feature '{feat}' no longer available",
                stability="stable",
            ))

        added_features = set(current_features) - set(baseline_features)
        for feat in sorted(added_features):
            changes.append(Change(
                symbol=f"feature:{feat}",
                kind="compatible_addition",
                description=f"New compiled feature '{feat}' available",
                stability="stable",
            ))
    except Exception:
        pass

    return changes


def detect_operation_id_changes(
    baseline: dict[str, Any],
) -> list[Change]:
    """Detect operation registry changes."""
    changes: list[Change] = []
    baseline_ops = baseline.get("operation_registry", {})
    if not baseline_ops:
        return changes

    try:
        from eggsec import OperationRegistry
        all_ops = OperationRegistry.all_operations()
        current_op_ids = {getattr(op, "operation_id", "") for op in all_ops if getattr(op, "operation_id", "")}

        for op_id in baseline_ops:
            if op_id not in current_op_ids:
                changes.append(Change(
                    symbol=f"operation:{op_id}",
                    kind="definitely_breaking",
                    description=f"Operation '{op_id}' removed from registry",
                    stability="stable",
                ))

        for op_id in current_op_ids:
            if op_id and op_id not in baseline_ops:
                changes.append(Change(
                    symbol=f"operation:{op_id}",
                    kind="compatible_addition",
                    description=f"New operation '{op_id}' added to registry",
                    stability="stable",
                ))
    except Exception:
        pass

    return changes


# ---------------------------------------------------------------------------
# Allowlist filtering
# ---------------------------------------------------------------------------

def filter_allowlist(
    changes: list[Change],
    allowlist: dict[str, list[str]],
) -> tuple[list[Change], list[Change]]:
    """Filter changes through the allowlist. Returns (filtered, allowed)."""
    filtered: list[Change] = []
    allowed: list[Change] = []

    breaking_types = {"definitely_breaking", "potentially_breaking"}
    for change in changes:
        if change.kind not in breaking_types:
            filtered.append(change)
            continue
        # Check allowlist
        allowed_symbols = allowlist.get(change.kind, [])
        allowed_symbols += allowlist.get("all", [])
        if change.symbol in allowed_symbols or "*" in allowed_symbols:
            allowed.append(change)
        else:
            filtered.append(change)

    return filtered, allowed


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def generate_report(
    baseline: dict[str, Any],
    changes: list[Change],
    allowed: list[Change],
) -> dict[str, Any]:
    """Generate the compatibility report."""
    by_type: dict[str, list[dict]] = {}
    for change in changes:
        by_type.setdefault(change.kind, []).append(change.to_dict())
    for change in allowed:
        by_type.setdefault(f"{change.kind}_allowed", []).append(change.to_dict())

    definitely = [c for c in changes if c.kind == "definitely_breaking"]
    potentially = [c for c in changes if c.kind == "potentially_breaking"]

    return {
        "baseline_schema_version": baseline.get("schema_version", "unknown"),
        "summary": {
            "total_changes": len(changes) + len(allowed),
            "definitely_breaking": len([c for c in changes if c.kind == "definitely_breaking"]),
            "potentially_breaking": len([c for c in changes if c.kind == "potentially_breaking"]),
            "deprecations": len([c for c in changes if c.kind == "deprecation"]),
            "compatible_additions": len([c for c in changes if c.kind == "compatible_addition"]),
            "compatible_widening": len([c for c in changes if c.kind == "compatible_widening"]),
            "provisional_changes": len([c for c in changes if c.kind == "provisional_change"]),
            "allowlisted": len(allowed),
        },
        "has_blocking_changes": len(definitely) > 0,
        "changes_by_type": by_type,
        "definitely_breaking": [c.to_dict() for c in definitely],
        "potentially_breaking": [c.to_dict() for c in potentially],
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description="Check Python API compatibility")
    parser.add_argument(
        "--baseline", type=Path, default=_BASELINE_PATH,
        help="Path to compatibility_baseline.json",
    )
    parser.add_argument(
        "--allowlist", type=Path, default=_ALLOWLIST_PATH,
        help="Path to compatibility_allowlist.json",
    )
    parser.add_argument(
        "--output", type=Path, default=_REPORT_PATH,
        help="Path for compatibility report output",
    )
    args = parser.parse_args()

    # Load baseline
    baseline = load_baseline(args.baseline)
    baseline_symbols = baseline.get("symbols", {})
    allowlist = load_allowlist(args.allowlist)

    # Build current surface
    print("Introspecting current package state...")
    current_surface: set[str] = set()
    try:
        import eggsec
        surface = eggsec.api_surface()
        current_surface = set(surface.keys())
    except Exception as e:
        print(f"Warning: api_surface() failed: {e}", file=sys.stderr)

    # Also add submodule symbols
    for submod_name in ("eggsec.net", "eggsec.sessions", "eggsec.storage",
                        "eggsec.reporting", "eggsec.daemon", "eggsec.experimental"):
        try:
            submod = importlib.import_module(submod_name)
            for attr_name in dir(submod):
                if not attr_name.startswith("_"):
                    current_surface.add(f"{submod_name}.{attr_name}")
        except ImportError:
            pass

    print(f"Baseline: {len(baseline_symbols)} symbols, Current: {len(current_surface)} symbols")

    # Detect changes
    print("Detecting changes...")
    all_changes: list[Change] = []
    all_changes.extend(detect_removed_symbols(baseline_symbols, current_surface))
    all_changes.extend(detect_added_symbols(baseline_symbols, current_surface))
    all_changes.extend(detect_deprecation_changes(baseline_symbols, current_surface))
    all_changes.extend(detect_signature_changes(baseline_symbols, current_surface))
    all_changes.extend(detect_enum_changes(baseline_symbols, current_surface))
    all_changes.extend(detect_class_change_type(baseline_symbols, current_surface))
    all_changes.extend(detect_version_changes(baseline))
    all_changes.extend(detect_exception_changes(baseline))
    all_changes.extend(detect_feature_profile_drift(baseline))
    all_changes.extend(detect_operation_id_changes(baseline))

    # Apply allowlist
    filtered, allowed = filter_allowlist(all_changes, allowlist)

    # Generate report
    report = generate_report(baseline, filtered, allowed)

    # Write report
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, default=str)

    # Print summary
    summary = report["summary"]
    print(f"\n{'=' * 60}")
    print("COMPATIBILITY REPORT")
    print(f"{'=' * 60}")
    print(f"  Definitely breaking:  {summary['definitely_breaking']}")
    print(f"  Potentially breaking: {summary['potentially_breaking']}")
    print(f"  Deprecations:         {summary['deprecations']}")
    print(f"  Compatible additions: {summary['compatible_additions']}")
    print(f"  Compatible widening:  {summary['compatible_widening']}")
    print(f"  Provisional changes:  {summary['provisional_changes']}")
    print(f"  Allowlisted:          {summary['allowlisted']}")
    print(f"{'=' * 60}")

    if summary["definitely_breaking"] > 0:
        print("\nDEFINITELY BREAKING CHANGES:")
        for change in report["definitely_breaking"]:
            print(f"  [{change['stability']}] {change['symbol']}: {change['description']}")

    if summary["potentially_breaking"] > 0:
        print("\nPOTENTIALLY BREAKING CHANGES:")
        for change in report["potentially_breaking"]:
            print(f"  [{change['stability']}] {change['symbol']}: {change['description']}")

    if report["has_blocking_changes"]:
        print(f"\nFAILED: {summary['definitely_breaking']} definitely-breaking change(s) detected")
        print(f"Report written to: {args.output}")
        return 1

    print(f"\nPASSED: No unallowlisted breaking changes detected")
    print(f"Report written to: {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
