#!/usr/bin/env python3
"""Package .toml theme files into a binary archive and emit a Rust source file.

The archive format is little-endian:
  magic:   b"SLPTHEME\\0"  (9 bytes)
  version: u16 (currently 1)
  file_count: u32
  repeat file_count times:
    path_len: u16
    path_utf8: [u8; path_len]   (relative path, must be .toml)
    content_len: u64
    content: [u8; content_len]

The archive is LZMA-compressed and base64-encoded for embedding in Rust source.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import io
import lzma
import os
import struct
import sys
from pathlib import Path

ARCHIVE_MAGIC = b"SLPTHEME\0"
ARCHIVE_VERSION = 1
REQUIRED_THEME = "Cyber Red.toml"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Package .toml theme files into a binary archive and emit Rust source.",
    )
    parser.add_argument(
        "--themes-dir",
        type=Path,
        default=Path("themes"),
        help="Directory containing .toml theme files (default: themes)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("crates/slapper-tui/src/theme/packaged.rs"),
        help="Output Rust source file (default: crates/slapper-tui/src/theme/packaged.rs)",
    )
    return parser.parse_args()


def collect_themes(themes_dir: Path) -> list[tuple[str, bytes]]:
    """Collect all .toml files from themes_dir, returning (relative_path, content) pairs.

    Skips macOS resource fork files (._ prefix).
    """
    if not themes_dir.is_dir():
        sys.exit(f"Error: themes directory not found: {themes_dir}")

    files: list[tuple[str, bytes]] = []
    for entry in sorted(themes_dir.iterdir()):
        if not entry.is_file():
            continue
        name = entry.name
        # Skip macOS resource fork / extended attribute files
        if name.startswith("._"):
            continue
        if not name.endswith(".toml"):
            continue
        rel = name  # relative to themes_dir
        content = entry.read_bytes()
        files.append((rel, content))

    return files


def validate_themes(files: list[tuple[str, bytes]], themes_dir: Path) -> None:
    """Validate collected theme files for correctness."""
    if not files:
        sys.exit(
            f"Error: no .toml files found in {themes_dir}. "
            "Ensure the directory contains at least one theme file."
        )

    # Check for required theme (case-insensitive search for "Cyber Red")
    names = [f[0] for f in files]
    has_cyber_red = any(n.lower() == "cyber red.toml" for n in names)
    if not has_cyber_red:
        sys.exit(
            f"Error: required theme '{REQUIRED_THEME}' not found in {themes_dir}. "
            f"Available themes: {', '.join(names)}"
        )

    # Check for duplicates (after case normalization)
    seen: dict[str, str] = {}
    for rel, _ in files:
        key = rel.lower()
        if key in seen:
            sys.exit(
                f"Error: duplicate theme paths (case-insensitive): "
                f"'{seen[key]}' and '{rel}'"
            )
        seen[key] = rel


def build_archive(files: list[tuple[str, bytes]]) -> bytes:
    """Build the binary archive from theme files.

    Args:
        files: List of (relative_path, content) pairs, already sorted.

    Returns:
        The raw (uncompressed) archive bytes.
    """
    buf = io.BytesIO()

    # Magic
    buf.write(ARCHIVE_MAGIC)

    # Version (u16 LE)
    buf.write(struct.pack("<H", ARCHIVE_VERSION))

    # File count (u32 LE)
    buf.write(struct.pack("<I", len(files)))

    for rel_path, content in files:
        path_bytes = rel_path.encode("utf-8")

        # Path length (u16 LE)
        if len(path_bytes) > 65535:
            sys.exit(
                f"Error: path too long ({len(path_bytes)} bytes): {rel_path}"
            )
        buf.write(struct.pack("<H", len(path_bytes)))

        # Path UTF-8 bytes
        buf.write(path_bytes)

        # Content length (u64 LE)
        buf.write(struct.pack("<Q", len(content)))

        # Content bytes
        buf.write(content)

    return buf.getvalue()


def sanitize_path_for_rust(path: str) -> str:
    """Escape a path string for use in a Rust string literal."""
    return path.replace("\\", "\\\\").replace('"', '\\"')


def emit_rust(files: list[tuple[str, bytes]], archive_bytes: bytes) -> str:
    """Generate the Rust source file content."""
    compressed = lzma.compress(archive_bytes)
    b64 = base64.b64encode(compressed).decode("ascii")
    sha256 = hashlib.sha256(archive_bytes).hexdigest()

    filenames = sorted(f[0] for f in files)

    lines: list[str] = []
    lines.append("// @generated by scripts/package_themes.py; do not edit by hand.")
    lines.append("")
    lines.append(f"pub const PACKAGED_THEMES_VERSION: u16 = {ARCHIVE_VERSION};")
    lines.append(
        f"pub const PACKAGED_THEMES_FILE_COUNT: usize = {len(files)};"
    )
    lines.append(f'pub const PACKAGED_THEMES_ARCHIVE_SHA256: &str = "{sha256}";')
    lines.append("")
    # Wrap long base64 string at ~80 chars per line for readability
    lines.append("pub const PACKAGED_THEMES_LZMA_BASE64: &str =")
    _emit_long_string(lines, b64)
    lines.append(";")
    lines.append("")
    lines.append("pub const PACKAGED_THEME_FILES: &[&str] = &[")
    for name in filenames:
        lines.append(f'    "{sanitize_path_for_rust(name)}",')
    lines.append("];")
    lines.append("")

    return "\n".join(lines)


def _emit_long_string(lines: list[str], s: str) -> None:
    """Emit a long string literal split across multiple lines."""
    CHUNK = 80
    if len(s) <= CHUNK:
        lines.append(f'    "{s}"')
        return
    lines.append('    "')
    for i in range(0, len(s), CHUNK):
        lines.append(s[i : i + CHUNK])
    lines.append('    "')


def main() -> None:
    args = parse_args()

    themes_dir = args.themes_dir.resolve()
    out_path = args.out.resolve()

    # Collect and validate
    files = collect_themes(themes_dir)
    validate_themes(files, themes_dir)

    # Build deterministic archive (files already sorted by collect_themes)
    archive_bytes = build_archive(files)

    # Emit Rust source
    rust_source = emit_rust(files, archive_bytes)

    # Ensure output directory exists
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Write output
    out_path.write_text(rust_source)
    print(f"Wrote {out_path} ({len(files)} themes, {len(rust_source)} bytes)")


if __name__ == "__main__":
    main()
