//! Configuration management module
//!
//! This module handles loading, parsing, and managing Slapper configuration.
//! Configuration can be loaded from TOML files, environment variables, or
//! created programmatically.
//!
//! ## Key Components
//!
//! - [`SlapperConfig`] - Main configuration struct containing all settings
//! - [`Scope`] - Target scope rules for authorized scanning
//! - [`ScanConfig`] - Port scanning, endpoint discovery, and fuzzing settings
//! - [`HttpConfig`] - HTTP client configuration (timeouts, proxies, auth)
//!
//! ## Usage
//!
//! ### Loading Configuration
//!
//! ```rust,no_run
//! use slapper::config::{load_config, SlapperConfig};
//!
//! // Load from default location (~/.config/slapper/config.toml)
//! let config = load_config(None)?;
//! println!("Default concurrency: {}", config.scan.default_concurrency);
//!
//! // Load from specific path
//! let config = load_config(Some("/path/to/config.toml"))?;
//! # Ok::<(), anyhow::Error>(())
//! ```
//!
//! ### Environment Variables
//!
//! Configuration can be overridden with environment variables prefixed with `SLAPPER_`:
//! - `SLAPPER_HTTP_TIMEOUT` - HTTP timeout in seconds
//! - `SLAPPER_SCAN_CONCURRENCY` - Default concurrency
//! - `SLAPPER_LOG_LEVEL` - Logging level (trace, debug, info, warn, error)
//!
//! ## Configuration File
//!
//! The default configuration file is located at:
//! - Linux/macOS: `~/.config/slapper/config.toml`
//! - Windows: `%APPDATA%\slapper\config.toml`

mod api;
mod http;
mod loader;
mod scan;
mod scope;
mod settings;

pub use api::{ApiConfig, ApiKeyConfig, IpApiConfig, MaxMindConfig, NvdConfig, WaybackConfig};
pub use http::{HttpConfig, Verbosity};
pub use loader::{config_dir, load_config, load_scope};
pub use scan::{
    FuzzProfile, NotificationConfig, OutputConfig, ScanConfig, ScanProfile, WebhookConfig,
    WebhookEvent,
};
pub use scope::{Scope, ScopeError, ScopeRule, TargetScope};
pub use settings::{
    AiConfig, AllowedWorker, CacheConfig, ConfigError, PathsConfig, ProxyConfigEntry, ReconConfig,
    RemoteConfig, ScheduledScan, SlapperConfig,
};

pub const ENV_PREFIX: &str = "SLAPPER_";

pub fn get_default_config() -> String {
    r#"# Slapper Configuration File
# Generated by slapper

[http]
timeout = 30
user_agent = "Slapper/0.1.0"
follow_redirects = true
max_redirects = 5

[http.proxy]
# Uncomment to use a proxy
# http = "http://127.0.0.1:8080"
# https = "http://127.0.0.1:8080"

[scan]
default_concurrency = 10
default_timeout = 30

[scan.ports]
default_range = "1-1024"
default_concurrency = 100

[scan.endpoints]
default_concurrency = 20
default_wordlist = "wordlists/directories.txt"

[scan.fuzz]
default_concurrency = 10
default_payload_type = "all"

[recon]
default_concurrency = 10
# NVD API key for CVE lookups (optional)
# nvd_api_key = "your-api-key"

[output]
default_format = "pretty"
# Uncomment to save reports
# report_dir = "./reports"

[logging]
level = "info"
format = "pretty"

[rate_limit]
enabled = false
requests_per_second = 100
"#
    .to_string()
}
