#![allow(dead_code)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::vec_init_then_push)]
#![allow(clippy::new_without_default)]
#![allow(clippy::derivable_impls)]
#![allow(clippy::collapsible_if)]
#![allow(clippy::collapsible_else_if)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::manual_range_contains)]
#![allow(clippy::single_char_add_str)]
#![allow(clippy::should_implement_trait)]
#![allow(clippy::get_first)]
#![allow(clippy::manual_find)]
#![allow(clippy::manual_ok_err)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::unnecessary_to_owned)]
#![allow(clippy::let_and_return)]
#![allow(clippy::map_flatten)]
#![allow(clippy::len_zero)]
#![allow(clippy::unused_enumerate_index)]
#![allow(clippy::needless_borrow)]
#![allow(clippy::single_match)]
#![allow(clippy::manual_strip)]
#![allow(clippy::manual_clamp)]
#![allow(clippy::double_ended_iterator_last)]
#![allow(clippy::useless_format)]
#![allow(clippy::unnecessary_map_or)]
#![allow(clippy::manual_range_patterns)]
#![allow(clippy::redundant_locals)]
#![allow(clippy::op_ref)]
#![allow(clippy::manual_is_multiple_of)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::iter_next_loop)]
#![allow(clippy::for_kv_map)]
#![allow(clippy::if_same_then_else)]
#![allow(clippy::io_other_error)]
#![allow(clippy::useless_vec)]
#![allow(clippy::single_component_path_imports)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::wrong_self_convention)]

mod cli;
mod config;
mod constants;
mod error;
mod fuzzer;
mod loadtest;
mod logging;
mod notify;
mod output;
mod pipeline;
mod proxy;
mod recon;
mod scanner;
mod tui;
mod utils;
mod waf;

#[cfg(feature = "python-plugins")]
mod plugin;

#[cfg(any(feature = "packet-inspection", feature = "stress-testing"))]
mod packet;

#[cfg(feature = "stress-testing")]
mod stress;

mod distributed;

#[cfg(any(feature = "rest-api", feature = "grpc-api", feature = "mcp-server", feature = "tool-api"))]
mod tool;

#[cfg(feature = "nse")]
mod nse;

use anyhow::Result;
use clap::{CommandFactory, Parser};
use clap_complete::Shell;

use crate::cli::{Cli, Commands};
use crate::config::{load_config, load_scope};
use crate::logging::{init_logging, LogLevel, LogFormat};
use crate::utils::check_scope_from_url;

fn get_default_config() -> String {
    r#"# Slapper Configuration File
# Generated by slapper

[http]
timeout = 30
user_agent = "Slapper/0.1.0"
follow_redirects = true
max_redirects = 5

[http.proxy]
# Uncomment to use a proxy
# http = "http://127.0.0.1:8080"
# https = "http://127.0.0.1:8080"

[scan]
default_concurrency = 10
default_timeout = 30

[scan.ports]
default_range = "1-1024"
default_concurrency = 100

[scan.endpoints]
default_concurrency = 20
default_wordlist = "wordlists/directories.txt"

[scan.fuzz]
default_concurrency = 10
default_payload_type = "all"

[recon]
default_concurrency = 10
# NVD API key for CVE lookups (optional)
# nvd_api_key = "your-api-key"

[output]
default_format = "pretty"
# Uncomment to save reports
# report_dir = "./reports"

[logging]
level = "info"
format = "pretty"

[rate_limit]
enabled = false
requests_per_second = 100
"#
    .to_string()
}

fn generate_shell_completion(shell: Shell) -> Result<()> {
    let mut cmd = Cli::command();
    clap_complete::generate(shell, &mut cmd, "slapper", &mut std::io::stdout());
    Ok(())
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();
    
    if cli.generate_config {
        println!("{}", get_default_config());
        return Ok(());
    }
    
    if let Some(shell) = cli.generate_shell_completion {
        generate_shell_completion(shell)?;
        return Ok(());
    }
    
    init_logging(
        LogLevel::Info,
        if cli.json { LogFormat::Json } else { LogFormat::Pretty },
        cli.json,
    );
    
    let config = load_config(cli.config.as_deref())?;
    let scope = load_scope(cli.scope.as_deref())?;
    
    match cli.command {
        None => {
            if atty::is(atty::Stream::Stdout) {
                tui::run(cli.config.clone())?;
            } else {
                println!("No command specified and not running in interactive terminal.");
                println!("Available commands:");
                println!("  slapper load <url>          - Run HTTP load test");
                println!("  slapper scan-ports <host>   - Scan ports");
                println!("  slapper scan-endpoints <url> - Discover endpoints");
                println!("  slapper fuzz <url>          - Fuzz target");
                println!("  slapper recon <target>      - Reconnaissance");
                println!("  slapper --help             - Show all commands");
                println!("\nTo launch TUI, run from an interactive terminal.");
            }
        }
        Some(Commands::Load(args)) => {
            check_scope_from_url(&scope, &args.url)?;
            loadtest::run_cli(args, &config).await?;
        }
        Some(Commands::ScanPorts(args)) => {
            crate::utils::check_scope(&scope, &args.host)?;
            scanner::ports::run_cli(args, &config).await?;
        }
        Some(Commands::ScanEndpoints(args)) => {
            check_scope_from_url(&scope, &args.url)?;
            scanner::endpoints::run_cli(args, &config).await?;
        }
        Some(Commands::Fingerprint(args)) => {
            crate::utils::check_scope(&scope, &args.host)?;
            scanner::fingerprint::run_cli(args, &config).await?;
        }
        #[cfg(feature = "nse")]
        Some(Commands::Nse(args)) => {
            crate::utils::check_scope(&scope, &args.target)?;
            nse::run_cli(args, &config).await?;
        }
        Some(Commands::Fuzz(args)) => {
            check_scope_from_url(&scope, &args.url)?;
            fuzzer::run_cli(args, &config).await?;
        }
        Some(Commands::WafStress(args)) => {
            check_scope_from_url(&scope, &args.url)?;
            fuzzer::run_waf_stress(args, &config).await?;
        }
        Some(Commands::Waf(args)) => {
            check_scope_from_url(&scope, &args.url)?;
            waf::run_cli(args, &config).await?;
        }
        Some(Commands::Scan(args)) => {
            crate::utils::check_scope(&scope, &args.target)?;
            pipeline::run_cli(args, &config).await?;
        }
        Some(Commands::Resume(args)) => {
            pipeline::resume_cli(args).await?;
        }
        Some(Commands::Recon(args)) => {
            check_scope_from_url(&scope, &args.target)?;
            recon::run_cli(args, &config).await?;
        }
        Some(Commands::Graphql(args)) => {
            check_scope_from_url(&scope, &args.url)?;
            fuzzer::run_cli(cli::FuzzArgs {
                url: args.url,
                payload_type: "graphql".to_string(),
                mode: cli::FuzzMode::Sequential,
                mutate: false,
                mutation_count: 3,
                grammar_fuzz: false,
                grammar_type: None,
                adaptive_rate: false,
                session: false,
                diffing: false,
                capture_baseline: false,
                enhanced_redos: false,
                waf_fingerprint: false,
                chaining: false,
                chain_file: None,
                method: "POST".to_string(),
                param: None,
                concurrency: args.concurrency,
                timeout: args.timeout,
                json: args.json,
                output: args.output,
                verbose: args.verbose,
                format: None,
                target: None,
                jwt_token: None,
                oauth_issuer: None,
                oauth_client_id: None,
                oauth_client_secret: None,
                idor_base_id: None,
                idor_user_ids: None,
                ssti_param: None,
                graphql_introspection: true,
                graphql_depth_bypass: true,
                graphql_alias_overload: true,
                oauth_redirect: true,
                oauth_scope: true,
                oauth_state: true,
                oauth_grant: true,
                common: args.common,
            }, &config).await?;
        }
        Some(Commands::OAuth(args)) => {
            check_scope_from_url(&scope, &args.url)?;
            fuzzer::run_cli(cli::FuzzArgs {
                url: args.url,
                payload_type: "oauth".to_string(),
                mode: cli::FuzzMode::Sequential,
                mutate: false,
                mutation_count: 3,
                grammar_fuzz: false,
                grammar_type: None,
                adaptive_rate: false,
                session: false,
                diffing: false,
                capture_baseline: false,
                enhanced_redos: false,
                waf_fingerprint: false,
                chaining: false,
                chain_file: None,
                method: "GET".to_string(),
                param: None,
                concurrency: args.concurrency,
                timeout: args.timeout,
                json: args.json,
                output: args.output,
                verbose: args.verbose,
                format: None,
                target: None,
                jwt_token: None,
                oauth_issuer: None,
                oauth_client_id: None,
                oauth_client_secret: None,
                idor_base_id: None,
                idor_user_ids: None,
                ssti_param: None,
                graphql_introspection: true,
                graphql_depth_bypass: true,
                graphql_alias_overload: true,
                oauth_redirect: true,
                oauth_scope: true,
                oauth_state: true,
                oauth_grant: true,
                common: args.common,
            }, &config).await?;
        }
        #[cfg(feature = "packet-inspection")]
        Some(Commands::Packet(args)) => {
            use crate::cli::PacketSubcommand;
            use crate::packet::cli as packet_cli;

            match args.command {
                PacketSubcommand::Capture(cap_args) => {
                    packet_cli::handle_packet_capture(cap_args, cli.json).await?;
                }
                PacketSubcommand::Send(send_args) => {
                    packet_cli::handle_packet_send(send_args, cli.json).await?;
                }
                PacketSubcommand::Dump(dump_args) => {
                    packet_cli::handle_packet_dump(dump_args, cli.json)?;
                }
                PacketSubcommand::Traceroute(trace_args) => {
                    packet_cli::handle_packet_traceroute(trace_args, cli.json).await?;
                }
                PacketSubcommand::Interfaces => {
                    packet_cli::handle_packet_interfaces()?;
                }
            }
        }
        #[cfg(not(feature = "packet-inspection"))]
        Some(Commands::Packet(_)) => {
            anyhow::bail!("Packet inspection requires 'packet-inspection' feature. Build with: cargo build --features packet-inspection");
        }
        #[cfg(feature = "stress-testing")]
        Some(Commands::Icmp(args)) => {
            use crate::scanner::icmp_probe;
            use std::time::Duration;
            
            crate::utils::check_scope(&scope, &args.target)?;
            
            let timeout = Duration::from_secs(args.timeout);
            let interval = Duration::from_secs_f64(args.interval);
            
            let (results, stats) = icmp_probe::ping_host(
                &args.target,
                args.count,
                timeout,
                interval,
            ).await?;
            
            if cli.json {
                println!("{{");
                println!("  \"target\": \"{}\",", args.target);
                println!("  \"stats\": {{");
                println!("    \"sent\": {},", stats.sent);
                println!("    \"received\": {},", stats.received);
                println!("    \"lost\": {},", stats.lost);
                if let Some(rtt) = stats.min_rtt { println!("    \"min_rtt_ms\": {},", rtt.as_secs_f64() * 1000.0); }
                if let Some(rtt) = stats.max_rtt { println!("    \"max_rtt_ms\": {},", rtt.as_secs_f64() * 1000.0); }
                if let Some(rtt) = stats.avg_rtt { println!("    \"avg_rtt_ms\": {}", rtt.as_secs_f64() * 1000.0); }
                println!("  }},");
                println!("  \"results\": [");
                for (i, r) in results.iter().enumerate() {{
                    println!("    {{");
                    println!("      \"seq\": {},", r.sequence);
                    println!("      \"rtt_ms\": {},", r.rtt.as_secs_f64() * 1000.0);
                    println!("      \"ttl\": {}", r.ttl);
                    println!("    }}{}", if i < results.len() - 1 {","} else {""});
                }}
                println!("  ]");
                println!("}}");
            } else {
                println!("PING {}: {} data bytes", args.target, 56);
                for r in &results {
                    println!("{} bytes from {}: icmp_seq={} ttl={} time={:.3} ms", 
                        r.payload_size, r.target, r.sequence, r.ttl, r.rtt.as_secs_f64() * 1000.0);
                }
                println!("\n--- {} ping statistics ---", args.target);
                println!("{} packets transmitted, {} packets received, {}% packet loss",
                    stats.sent, stats.received, 
                    if stats.sent > 0 { (stats.lost as f64 / stats.sent as f64 * 100.0) as u32 } else { 0 });
                if let Some(rtt) = stats.min_rtt {
                    println!("round-trip min/avg/max = {:.3}/{:.3}/{:.3} ms",
                        rtt.as_secs_f64() * 1000.0,
                        stats.avg_rtt.unwrap_or_default().as_secs_f64() * 1000.0,
                        stats.max_rtt.unwrap_or_default().as_secs_f64() * 1000.0);
                }
            }
        }
        #[cfg(feature = "stress-testing")]
        Some(Commands::Traceroute(args)) => {
            use crate::packet::traceroute::{Traceroute, TracerouteConfig};
            use std::time::Duration;
            
            crate::utils::check_scope(&scope, &args.target)?;
            
            let config = TracerouteConfig {
                target: args.target.clone(),
                max_hops: args.max_hops,
                timeout: Duration::from_secs(args.timeout),
                max_retries: 3,
                first_ttl: 1,
                port: 33434,
                use_icmp: args.icmp,
                packet_size: 32,
                parallel_probes: args.parallel,
                resolve_names: !args.no_resolve,
            };
            
            let traceroute = Traceroute::new(config);
            let result = traceroute.run().await?;
            
            if cli.json {
                println!("{}", serde_json::to_string_pretty(&result)?);
            } else {
                println!("traceroute to {} ({}), {} hops max\n", 
                    result.target, result.resolved_address, result.total_hops);
                for hop in &result.hops {
                    let addr = hop.address.clone().unwrap_or_else(|| "*".to_string());
                    let rtt_str = hop.rtt_ms.map(|ms| format!("{:.3} ms", ms)).unwrap_or_else(|| "*".to_string());
                    println!(" {:2}  {:<20} {}", hop.hop, addr, rtt_str);
                }
                if !result.success {
                    println!("\nTrace incomplete (destination not reached).");
                }
            }
        }
        #[cfg(feature = "python-plugins")]
        Some(Commands::Plugin(args)) => {
            use crate::cli::PluginCommand;
            use crate::plugin::{PluginManager, PluginLanguage};
            
            let mut manager = PluginManager::new();
            manager.discover_plugins();
            
            match args.command {
                PluginCommand::List(list_args) => {
                    let plugins = manager.list_plugins();
                    if plugins.is_empty() {
                        println!("No plugins found.");
                        println!("Add Python plugins to: ~/.config/slapper/plugins/ or ./plugins/");
                    } else {
                        println!("Available plugins:\n");
                        for info in &plugins {
                            println!("  {} (v{})", info.name, info.version);
                            if list_args.verbose {
                                println!("    Author: {}", info.author);
                                println!("    Language: {:?}", info.language);
                                if !info.description.is_empty() {
                                    println!("    {}", info.description);
                                }
                                if !info.tags.is_empty() {
                                    println!("    Tags: {:?}", info.tags.join(", "));
                                }
                            }
                        }
                    }
                }
                PluginCommand::Run(run_args) => {
                    let plugins = manager.list_plugins();
                    let plugin_info = plugins.iter().find(|p| p.name == run_args.name);
                    
                    if let Some(info) = plugin_info {
                        if info.language != PluginLanguage::Python {
                            anyhow::bail!("Only Python plugins are currently supported for execution");
                        }
                        
                        println!("Running plugin '{}' against target '{}'", run_args.name, run_args.target);
                        
                        let mut python_mgr = crate::plugin::PythonPluginManager::new();
                        
                        for dir in &manager.plugin_dirs {
                            if dir.exists() {
                                if let Err(e) = python_mgr.load_plugins(dir) {
                                    tracing::warn!("Failed to load plugins from {:?}: {}", dir, e);
                                }
                            }
                        }
                        
                        let results = python_mgr.run_check(&run_args.name, &run_args.target)?;
                        
                        if results.is_empty() {
                            println!("No findings from plugin.");
                        } else {
                            println!("\nPlugin Results:");
                            for finding in &results {
                                println!("  - {:?}", finding);
                            }
                            
                            if let Some(output_file) = run_args.output {
                                std::fs::write(&output_file, serde_json::to_string_pretty(&results)?)?;
                                println!("\nResults written to: {}", output_file);
                            }
                        }
                    } else {
                        anyhow::bail!("Plugin '{}' not found. Use 'slapper plugin list' to see available plugins.", run_args.name);
                    }
                }
            }
        }
        Some(Commands::Report(args)) => {
            use crate::cli::ReportFormat;
            use crate::output::convert;
            
            match args.command {
                crate::cli::ReportCommand::Convert(convert_args) => {
                    let report = convert::load_scan_report(&convert_args.input)
                        .map_err(|e| anyhow::anyhow!(e))?;
                    
                    let output = match convert_args.format {
                        ReportFormat::Json => serde_json::to_string_pretty(&report)?,
                        ReportFormat::Csv => convert::convert_to_csv(&report),
                        ReportFormat::Junit => convert::convert_to_junit(&report),
                        ReportFormat::Sarif => convert::convert_to_sarif(&report),
                        ReportFormat::Html => convert::convert_to_html(&report),
                        ReportFormat::Markdown => convert::convert_to_markdown(&report),
                    };
                    
                    if let Some(output_file) = convert_args.output {
                        std::fs::write(&output_file, &output)?;
                        println!("Report written to: {}", output_file);
                    } else {
                        println!("{}", output);
                    }
                }
                crate::cli::ReportCommand::Trend(trend_args) => {
                    let before = convert::load_scan_report(&trend_args.before)
                        .map_err(|e| anyhow::anyhow!(e))?;
                    let after = convert::load_scan_report(&trend_args.after)
                        .map_err(|e| anyhow::anyhow!(e))?;
                    
                    let before_counts: std::collections::HashMap<String, usize> = before.findings.iter()
                        .fold(std::collections::HashMap::new(), |mut acc, f| {
                            *acc.entry(f.severity.clone()).or_insert(0) += 1;
                            acc
                        });
                    let after_counts: std::collections::HashMap<String, usize> = after.findings.iter()
                        .fold(std::collections::HashMap::new(), |mut acc, f| {
                            *acc.entry(f.severity.clone()).or_insert(0) += 1;
                            acc
                        });
                    
                    let mut output = String::new();
                    output.push_str("# Security Scan Trend Analysis\n\n");
                    output.push_str(&format!("## Target: {} → {}\n\n", before.target, after.target));
                    output.push_str("| Severity | Before | After | Change |\n");
                    output.push_str("|----------|--------|-------|--------|\n");
                    
                    for sev in &["critical", "high", "medium", "low", "info"] {
                        let before_count = before_counts.get(*sev).unwrap_or(&0);
                        let after_count = after_counts.get(*sev).unwrap_or(&0);
                        let change = *after_count as i32 - *before_count as i32;
                        let change_str = if change > 0 {
                            format!("+{}", change)
                        } else {
                            change.to_string()
                        };
                        output.push_str(&format!("| {} | {} | {} | {} |\n", sev, before_count, after_count, change_str));
                    }
                    
                    if let Some(output_file) = trend_args.output {
                        std::fs::write(&output_file, &output)?;
                        println!("Trend analysis written to: {}", output_file);
                    } else {
                        println!("{}", output);
                    }
                }
                crate::cli::ReportCommand::Schedule(schedule_args) => {
                    use crate::config::ScheduledScan;
                    
                    match schedule_args.command {
                        crate::cli::ScheduleCommand::List => {
                            let config = load_config(cli.config.as_deref())?;
                            if config.schedule.is_empty() {
                                println!("No scheduled scans configured.");
                                println!("\nTo add a schedule, use:");
                                println!("  slapper report schedule add <cron_expr> <target>");
                                println!("\nExample:");
                                println!("  slapper report schedule add '0 */6 * * *' https://example.com");
                            } else {
                                println!("Scheduled Scans:\n");
                                for (i, sched) in config.schedule.iter().enumerate() {
                                    println!("  [{}] {} -> {}", 
                                        i + 1, 
                                        sched.schedule, 
                                        sched.target
                                    );
                                    println!("       Type: {}, Output: {:?}", sched.scan_type, sched.output);
                                    println!();
                                }
                                println!("To generate crontab entries, run:");
                                println!("  slapper report schedule cron");
                            }
                        }
                        crate::cli::ScheduleCommand::Add(add_args) => {
                            let config_path = cli.config.as_deref().unwrap_or("slapper.toml");
                            let mut config = load_config(cli.config.as_deref())?;
                            
                            let new_sched = ScheduledScan {
                                schedule: add_args.schedule.clone(),
                                target: add_args.target.clone(),
                                scan_type: add_args.scan_type.clone(),
                                output: add_args.output.clone(),
                                enabled: true,
                            };
                            
                            config.schedule.push(new_sched);
                            
                            let toml_content = toml::to_string_pretty(&config)
                                .map_err(|e| anyhow::anyhow!("Failed to serialize config: {}", e))?;
                            
                            std::fs::write(config_path, toml_content)?;
                            
                            println!("Schedule added successfully!");
                            println!("  {} -> {}", add_args.schedule, add_args.target);
                            println!("\nTo generate crontab entry, run:");
                            println!("  slapper report schedule cron");
                        }
                        crate::cli::ScheduleCommand::Remove(remove_args) => {
                            let config_path = cli.config.as_deref().unwrap_or("slapper.toml");
                            let mut config = load_config(cli.config.as_deref())?;
                            
                            if let Ok(idx) = remove_args.id.parse::<usize>() {
                                if idx == 0 || idx > config.schedule.len() {
                                    anyhow::bail!("Invalid schedule ID: {}. Use 'slapper report schedule list' to see valid IDs", idx);
                                }
                                let removed = config.schedule.remove(idx - 1);
                                let toml_content = toml::to_string_pretty(&config)
                                    .map_err(|e| anyhow::anyhow!("Failed to serialize config: {}", e))?;
                                std::fs::write(config_path, toml_content)?;
                                println!("Removed schedule: {} -> {}", removed.schedule, removed.target);
                            } else {
                                anyhow::bail!("Invalid schedule ID: {}", remove_args.id);
                            }
                        }
                        crate::cli::ScheduleCommand::Cron(cron_args) => {
                            let config = load_config(cli.config.as_deref())?;
                            
                            if config.schedule.is_empty() {
                                println!("No scheduled scans configured.");
                                println!("Add schedules with: slapper report schedule add <cron_expr> <target>");
                            } else {
                                let schedules_to_cron: Vec<_> = if let Some(id) = &cron_args.id {
                                    let idx = id.parse::<usize>().ok()
                                        .filter(|&i| i > 0 && i <= config.schedule.len())
                                        .map(|i| i - 1);
                                    match idx {
                                        Some(i) => vec![config.schedule[i].clone()],
                                        None => {
                                            println!("Invalid schedule ID: {}. Use 'slapper report schedule list' to see valid IDs", id);
                                            println!("Generating crontab for all schedules:\n");
                                            config.schedule.clone()
                                        }
                                    }
                                } else {
                                    config.schedule.clone()
                                };
                                
                                for sched in schedules_to_cron {
                                    let output_part = match &sched.output {
                                        Some(path) => format!(" -o {}", path),
                                        None => String::new(),
                                    };
                                    println!("{} slapper scan {} --profile {}{}", sched.schedule, sched.target, sched.scan_type, output_part);
                                }
                            }
                        }
                    }
                }
            }
        }
        #[cfg(feature = "stress-testing")]
        Some(Commands::Stress(args)) => {
            use crate::stress::{StressConfig, StressType, StressTest};
            
            crate::utils::check_scope(&scope, &args.target)?;
            
            let stress_type = match args.stress_type {
                cli::StressTypeArg::Syn => StressType::Syn,
                cli::StressTypeArg::Udp => StressType::Udp,
                cli::StressTypeArg::Http => StressType::Http,
                cli::StressTypeArg::Tcp => StressType::Tcp,
                cli::StressTypeArg::Icmp => StressType::Icmp,
            };
            
            let (host, port) = if args.target.contains(':') {
                let parts: Vec<&str> = args.target.splitn(2, ':').collect();
                let p: u16 = parts[1].parse()?;
                (parts[0].to_string(), p)
            } else {
                (args.target.clone(), 80)
            };
            
            let config = StressConfig {
                target: host,
                port,
                stress_type,
                rate_pps: args.rate,
                duration_secs: args.duration,
                concurrency: args.concurrency,
                spoof_source: args.spoof,
                spoof_range: args.spoof_range.clone(),
                random_source_port: args.random_port,
                payload_size: args.payload_size.unwrap_or(64),
                use_proxies: args.use_proxies,
                proxy_pool: args.proxy_file,
            };
            
            let stress_test = StressTest::new(config)?;
            let stats = stress_test.run().await?;
            
            if cli.json {
                println!("{}", serde_json::to_string_pretty(&stats)?);
            } else {
                println!("\nStress Test Complete:");
                println!("  Packets sent: {}", stats.packets_sent);
                println!("  Bytes sent: {}", stats.bytes_sent);
                println!("  Duration: {} ms", stats.duration_ms);
                if stats.errors > 0 {
                    println!("  Errors: {}", stats.errors);
                }
            }
        }
        #[cfg(feature = "stress-testing")]
        Some(Commands::Proxy(args)) => {
            use crate::proxy::{ProxyEntry, ProxyType, HealthChecker, HealthCheckConfig};
            use crate::config::ProxyConfigEntry;
            use std::str::FromStr;
            
            match args.command {
                cli::ProxyCommand::Add(add_args) => {
                    let proxies = ProxyEntry::load_from_file(&add_args.file)?;
                    let count = proxies.len();
                    
                    let mut config = load_config(cli.config.as_deref())?;
                    let new_entries: Vec<ProxyConfigEntry> = proxies.iter().map(|p| {
                        ProxyConfigEntry {
                            proxy_type: p.proxy_type.to_string(),
                            address: p.address.clone(),
                            port: p.port,
                            username: p.username.clone(),
                            password: p.password.clone(),
                            weight: p.weight,
                            priority: p.priority,
                            enabled: p.enabled,
                        }
                    }).collect();
                    
                    config.proxies.extend(new_entries);
                    
                    let config_path = cli.config.as_deref().unwrap_or("slapper.toml");
                    let toml_content = toml::to_string_pretty(&config)
                        .map_err(|e| anyhow::anyhow!("Failed to serialize config: {}", e))?;
                    std::fs::write(config_path, toml_content)?;
                    
                    println!("Loaded {} proxies from {} and saved to config", count, add_args.file);
                    for proxy in proxies.iter().take(5) {
                        println!("  - {}", proxy.to_url());
                    }
                    if count > 5 {
                        println!("  ... and {} more", count - 5);
                    }
                }
                cli::ProxyCommand::List(list_args) => {
                    let config = load_config(cli.config.as_deref())?;
                    
                    if config.proxies.is_empty() {
                        println!("No proxies loaded.");
                        println!("Run 'slapper proxy add --file proxies.txt' first.");
                        println!("\nProxy file format (one per line):");
                        println!("  http://127.0.0.1:8080");
                        println!("  socks5://user:pass@proxy:1080");
                        println!("  http://proxy:8080 # with optional comment");
                    } else {
                        println!("Proxy Pool ({} proxies):\n", config.proxies.len());
                        for (i, proxy) in config.proxies.iter().enumerate() {
                            println!("  [{}] {}://{}:{} - {}", 
                                i + 1, 
                                proxy.proxy_type, 
                                proxy.address, 
                                proxy.port,
                                if proxy.enabled { "enabled" } else { "disabled" });
                            if list_args.verbose {
                                println!("      type: {}, priority: {}, weight: {}", 
                                    proxy.proxy_type, proxy.priority, proxy.weight);
                            }
                        }
                    }
                }
                cli::ProxyCommand::HealthCheck(health_args) => {
                    use crate::proxy::{ProxyEntry, ProxyType, HealthChecker, HealthCheckConfig};
                    
                    let config = load_config(cli.config.as_deref())?;
                    
                    if config.proxies.is_empty() {
                        println!("No proxies loaded.");
                        println!("Run 'slapper proxy add --file proxies.txt' first.");
                        anyhow::bail!("No proxies to check");
                    }
                    
                    let proxy_entries: Vec<ProxyEntry> = config.proxies.iter().map(|p| {
                        ProxyEntry {
                            name: None,
                            proxy_type: ProxyType::from_str(&p.proxy_type).unwrap_or(ProxyType::Http),
                            address: p.address.clone(),
                            port: p.port,
                            username: p.username.clone(),
                            password: p.password.clone(),
                            weight: p.weight,
                            priority: p.priority,
                            timeout_ms: 10000,
                            enabled: p.enabled,
                            tags: Vec::new(),
                        }
                    }).collect();
                    
                    let health_config = HealthCheckConfig {
                        enabled: true,
                        interval_secs: 60,
                        timeout_ms: (health_args.timeout * 1000) as u64,
                        test_url: health_args.test_url,
                        max_failures: 3,
                    };
                    
                    let checker = HealthChecker::new(health_config)?;
                    let results = checker.check_all(&proxy_entries).await?;
                    
                    println!("Proxy Health Check Results:");
                    println!("  Total: {} | Healthy: {} | Unhealthy: {}\n", 
                        results.total, results.healthy, results.unhealthy);
                    
                    for result in &results.results {
                        let status = if result.is_healthy { "✓" } else { "✗" };
                        let latency = result.latency_ms.map(|ms| format!("{}ms", ms)).unwrap_or_else(|| "N/A".to_string());
                        let error = result.error.as_deref().unwrap_or("OK");
                        println!("  [{}] {} - {} ({})", status, result.proxy_url, latency, error);
                    }
                }
                cli::ProxyCommand::Test(test_args) => {
                    use crate::proxy::{ProxyEntry, ProxyType, HealthChecker, HealthCheckConfig};
                    
                    let proxy_url = &test_args.proxy;
                    let proxy_type = if proxy_url.starts_with("socks5://") || proxy_url.starts_with("socks://") {
                        ProxyType::Socks5
                    } else if proxy_url.starts_with("socks4://") {
                        ProxyType::Socks4
                    } else if proxy_url.starts_with("https://") {
                        ProxyType::Https
                    } else {
                        ProxyType::Http
                    };
                    
                    let (address, port, username, password) = parse_proxy_url(proxy_url)?;
                    
                    let proxy_entry = ProxyEntry {
                        name: None,
                        proxy_type,
                        address,
                        port,
                        username,
                        password,
                        weight: 1,
                        priority: 0,
                        timeout_ms: 10000,
                        enabled: true,
                        tags: Vec::new(),
                    };
                    
                    let test_url = test_args.test_url.clone();
                    
                    let health_config = HealthCheckConfig {
                        enabled: true,
                        interval_secs: 60,
                        timeout_ms: 10000,
                        test_url: test_url.clone(),
                        max_failures: 3,
                    };
                    
                    let checker = HealthChecker::new(health_config)?;
                    
                    let result = checker.check(&proxy_entry).await;
                    
                    println!("Testing proxy: {}", test_args.proxy);
                    println!("Target URL: {}", test_url);
                    
                    if result.is_healthy {
                        println!("\n[✓] Proxy is healthy (latency: {}ms)", 
                            result.latency_ms.unwrap_or(0));
                    } else {
                        println!("\n[✗] Proxy failed: {}", result.error.unwrap_or_else(|| "Unknown error".to_string()));
                    }
                }
            }
        }
        Some(Commands::Cluster(args)) => {
            use crate::distributed::{RemoteListener, RemoteClient};
            use crate::cli::ClusterCommand;
            
            match args.command {
                ClusterCommand::Worker(worker_args) => {
                    let psk = match worker_args.psk.clone() {
                        Some(p) => p,
                        None => {
                            if let Some(config_psk) = config.remote.psk.clone() {
                                config_psk
                            } else {
                                anyhow::bail!("PSK is required for worker mode. Use --psk <key> or set [remote.psk] in config");
                            }
                        }
                    };
                    
                    println!("Starting worker node...");
                    println!("  Coordinator: {}", worker_args.coordinator);
                    println!("  Workers: {}", worker_args.workers);
                    
                    let worker_id = worker_args.worker_id.unwrap_or_else(|| {
                        use std::time::{SystemTime, UNIX_EPOCH};
                        format!("worker-{}", SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_millis())
                    });
                    
                    let target = worker_args.coordinator.clone();
                    let port = if let Some(p) = target.rsplit(':').next() {
                        p.parse().unwrap_or(9000)
                    } else {
                        9000
                    };
                    let host = target.rsplit(':').next().unwrap_or(&target);
                    
                    let client = RemoteClient::new(psk.clone());
                    
                    println!("Worker '{}' connecting to coordinator at {}:{}", worker_id, host, port);
                    
                    let result = client.execute(
                        host,
                        port,
                        vec!["slapper".to_string(), "--version".to_string()],
                        Some(30)
                    ).await;
                    
                    match result {
                        Ok(_r) => {
                            println!("Connected to coordinator successfully!");
                            println!("Worker '{}' ready. Press Ctrl+C to stop.", worker_id);
                            println!("\nWorker functionality: Use 'slapper remote exec' to execute commands on this worker.");
                        }
                        Err(e) => {
                            anyhow::bail!("Failed to connect to coordinator: {}. Make sure the coordinator is running with 'slapper cluster coordinator --psk <key>'", e);
                        }
                    }
                }
                ClusterCommand::Coordinator(coordinator_args) => {
                    let bind_addr = coordinator_args.bind.unwrap_or_else(|| "0.0.0.0".to_string());
                    
                    let psk = coordinator_args.psk.clone().or_else(|| {
                        config.remote.psk.clone()
                    }).unwrap_or_else(|| {
                        let key = crate::distributed::generate_psk();
                        println!("No PSK provided. Generated key (add to config for persistence):");
                        println!("  {}", key);
                        key
                    });
                    
                    println!("Starting distributed coordinator...");
                    println!("  Bind: {}:{}", bind_addr, coordinator_args.port);
                    
                    let listener = RemoteListener::new(psk);
                    
                    println!("Coordinator started on {}:{}", bind_addr, coordinator_args.port);
                    println!("Workers can connect using: slapper cluster worker --coordinator {}:{} --psk <key>", bind_addr, coordinator_args.port);
                    
                    tokio::select! {
                        result = listener.start(coordinator_args.port) => {
                            if let Err(e) = result {
                                anyhow::bail!("Coordinator error: {}", e);
                            }
                        }
                        _ = tokio::signal::ctrl_c() => {
                            println!("\nShutting down coordinator...");
                            listener.shutdown();
                        }
                    }
                }
                ClusterCommand::Status(status_args) => {
                    if let Some(addr) = status_args.coordinator {
                        println!("Fetching cluster status from {}...", addr);
                        
                        let psk = config.remote.psk.clone().ok_or_else(||
                            anyhow::anyhow!("No PSK configured. Set [remote.psk] in config or provide --psk")
                        )?;
                        
                        let port = if let Some(p) = addr.rsplit(':').next() {
                            p.parse().unwrap_or(9000)
                        } else {
                            9000
                        };
                        let host = addr.rsplit(':').next().unwrap_or(&addr);
                        
                        let client = RemoteClient::new(psk);
                        
                        match client.execute(host, port, vec!["slapper".to_string(), "cluster".to_string(), "status".to_string()], Some(10)).await {
                        Ok(r) => {
                                println!("{}", r.output);
                            }
                            Err(e) => {
                                println!("Failed to connect: {}", e);
                            }
                        }
                    } else {
                        println!("Cluster Status:");
                        println!("  No coordinator address provided.");
                        println!("  Start a coordinator with: slapper cluster coordinator --psk <key>");
                        println!("  Then check status with: slapper cluster status --coordinator <address>");
                    }
                }
            }
        }
        Some(Commands::Notify(args)) => {
            
            
            match args.command {
                cli::NotifyCommand::Test(test_args) => {
                    use crate::notify::{WebhookNotifier, WebhookConfig, NotificationPayload, WebhookEvent, FindingSummary, ScanStats};
                    use chrono::Utc;
                    
                    let _config = load_config(cli.config.as_deref())?;
                    
                    let test_payload = NotificationPayload {
                        event: WebhookEvent::ScanComplete,
                        timestamp: Utc::now(),
                        scan_id: "test-scan-id".to_string(),
                        target: "test.example.com".to_string(),
                        message: "This is a test notification from Slapper".to_string(),
                        findings: Some(vec![FindingSummary {
                            severity: "info".to_string(),
                            finding_type: "test".to_string(),
                            description: "Test finding".to_string(),
                            location: "/test".to_string(),
                        }]),
                        stats: Some(ScanStats {
                            duration_ms: 100,
                            requests_total: 10,
                            requests_success: 9,
                            requests_failed: 1,
                            findings_total: 1,
                        }),
                    };
                    
                    let has_slack = test_args.slack.is_some();
                    let has_discord = test_args.discord.is_some();
                    let has_teams = test_args.teams.is_some();
                    let has_webhook = test_args.webhook.is_some();
                    
                    if let Some(slack_url) = &test_args.slack {
                        println!("Sending test to Slack: {}", slack_url);
                        if let Ok(notifier) = WebhookNotifier::new(vec![]) {
                            match notifier.notify_slack(slack_url, &test_payload).await {
                                Ok(_) => println!("  ✓ Test notification sent successfully!"),
                                Err(e) => println!("  ✗ Failed: {}", e),
                            }
                        } else {
                            println!("  ✗ Failed to create notifier");
                        }
                    }
                    if let Some(discord_url) = &test_args.discord {
                        println!("Sending test to Discord: {}", discord_url);
                        if let Ok(notifier) = WebhookNotifier::new(vec![]) {
                            match notifier.notify_discord(discord_url, &test_payload).await {
                                Ok(_) => println!("  ✓ Test notification sent successfully!"),
                                Err(e) => println!("  ✗ Failed: {}", e),
                            }
                        } else {
                            println!("  ✗ Failed to create notifier");
                        }
                    }
                    if let Some(teams_url) = &test_args.teams {
                        println!("Sending test to Teams: {}", teams_url);
                        if let Ok(notifier) = WebhookNotifier::new(vec![]) {
                            match notifier.notify_teams(teams_url, &test_payload).await {
                                Ok(_) => println!("  ✓ Test notification sent successfully!"),
                                Err(e) => println!("  ✗ Failed: {}", e),
                            }
                        } else {
                            println!("  ✗ Failed to create notifier");
                        }
                    }
                    if let Some(webhook_url) = &test_args.webhook {
                        println!("Sending test to custom webhook: {}", webhook_url);
                        let webhook_config = vec![WebhookConfig {
                            name: "test".to_string(),
                            url: webhook_url.clone(),
                            secret: test_args.secret.clone(),
                            headers: std::collections::HashMap::new(),
                            events: vec![WebhookEvent::ScanComplete],
                        }];
                        if let Ok(notifier) = WebhookNotifier::new(webhook_config) {
                            match notifier.notify(&test_payload).await.first() {
                                Some(Ok(_)) => println!("  ✓ Test notification sent successfully!"),
                                Some(Err(e)) => println!("  ✗ Failed: {}", e),
                                None => println!("  No webhooks configured"),
                            }
                        }
                    }
                    
                    if !has_slack && !has_discord && !has_teams && !has_webhook {
                        println!("No webhook URL provided.");
                        println!("Usage:");
                        println!("  slapper notify test --slack <url>");
                        println!("  slapper notify test --discord <url>");
                        println!("  slapper notify test --teams <url>");
                        println!("  slapper notify test --webhook <url> [--secret <secret>]");
                    }
                }
                cli::NotifyCommand::Send(send_args) => {
                    use crate::notify::{WebhookNotifier, WebhookConfig, NotificationPayload, WebhookEvent};
                    use chrono::Utc;
                    
                    let _config = load_config(cli.config.as_deref())?;
                    
                    let severity = send_args.severity.clone().unwrap_or_else(|| "info".to_string());
                    let target = send_args.target.clone().unwrap_or_else(|| "N/A".to_string());
                    
                    let payload = NotificationPayload {
                        event: if severity == "critical" || severity == "high" { 
                            WebhookEvent::FindingDetected 
                        } else { 
                            WebhookEvent::ScanComplete 
                        },
                        timestamp: Utc::now(),
                        scan_id: format!("manual-{}", chrono::Utc::now().timestamp()),
                        target: target.clone(),
                        message: send_args.message.clone(),
                        findings: None,
                        stats: None,
                    };
                    
                    let has_slack = send_args.slack.is_some();
                    let has_discord = send_args.discord.is_some();
                    let has_teams = send_args.teams.is_some();
                    let has_webhook = send_args.webhook.is_some();
                    
                    if let Some(slack_url) = &send_args.slack {
                        println!("Sending to Slack: {}", slack_url);
                        if let Ok(notifier) = WebhookNotifier::new(vec![]) {
                            match notifier.notify_slack(slack_url, &payload).await {
                                Ok(_) => println!("  ✓ Notification sent successfully!"),
                                Err(e) => println!("  ✗ Failed: {}", e),
                            }
                        } else {
                            println!("  ✗ Failed to create notifier");
                        }
                    }
                    if let Some(discord_url) = &send_args.discord {
                        println!("Sending to Discord: {}", discord_url);
                        if let Ok(notifier) = WebhookNotifier::new(vec![]) {
                            match notifier.notify_discord(discord_url, &payload).await {
                                Ok(_) => println!("  ✓ Notification sent successfully!"),
                                Err(e) => println!("  ✗ Failed: {}", e),
                            }
                        } else {
                            println!("  ✗ Failed to create notifier");
                        }
                    }
                    if let Some(teams_url) = &send_args.teams {
                        println!("Sending to Teams: {}", teams_url);
                        if let Ok(notifier) = WebhookNotifier::new(vec![]) {
                            match notifier.notify_teams(teams_url, &payload).await {
                                Ok(_) => println!("  ✓ Notification sent successfully!"),
                                Err(e) => println!("  ✗ Failed: {}", e),
                            }
                        } else {
                            println!("  ✗ Failed to create notifier");
                        }
                    }
                    if let Some(webhook_url) = &send_args.webhook {
                        println!("Sending to: {}", webhook_url);
                        let webhook_config = vec![WebhookConfig {
                            name: "manual".to_string(),
                            url: webhook_url.clone(),
                            secret: None,
                            headers: std::collections::HashMap::new(),
                            events: vec![WebhookEvent::ScanComplete],
                        }];
                        if let Ok(notifier) = WebhookNotifier::new(webhook_config) {
                            match notifier.notify(&payload).await.first() {
                                Some(Ok(_)) => println!("  ✓ Notification sent successfully!"),
                                Some(Err(e)) => println!("  ✗ Failed: {}", e),
                                None => println!("  No webhooks configured"),
                            }
                        }
                    }
                    
                    if !has_slack && !has_discord && !has_teams && !has_webhook {
                        println!("\nNo webhook URL provided.");
                        println!("Configure webhooks in config file or use:");
                        println!("  slapper notify send --slack <url> --message 'your message'");
                    }
                }
            }
        }
        Some(Commands::Remote(args)) => {
            use crate::distributed::generate_psk;
            
            match args.command {
                cli::RemoteCommand::GenerateKey => {
                    let key = generate_psk();
                    println!("{}", key);
                    println!("\nAdd to your config file:");
                    println!("[remote]");
                    println!("psk = \"{}\"", key);
                }
                cli::RemoteCommand::Cert(_cert_args) => {
                    println!("TLS Certificate Generation");
                    println!("=========================");
                    println!();
                    println!("To create a TLS certificate for distributed communication,");
                    println!("use OpenSSL to generate a PKCS12 file:");
                    println!();
                    println!("  # Generate private key and certificate");
                    println!("  openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj '/CN=localhost'");
                    println!();
                    println!("  # Convert to PKCS12 format (required by native-tls)");
                    println!("  openssl pkcs12 -export -out cert.p12 -inkey key.pem -in cert.pem");
                    println!();
                    println!("Usage:");
                    println!("  slapper remote start --tls-cert cert.p12");
                    println!();
                    println!("Note: The password used in the openssl command must be provided");
                    println!("      when starting the remote listener.");
                }
                cli::RemoteCommand::Start(start_args) => {
                    use crate::distributed::{RemoteListener, TlsConfig};
                    
                    let config = load_config(cli.config.as_deref())?;
                    
                    let psk = start_args.auth.clone()
                        .or_else(|| config.remote.psk.clone())
                        .unwrap_or_else(|| {
                            println!("No PSK provided. Using generated key (add to config for persistence):");
                            let key = generate_psk();
                            println!("  {}", key);
                            key
                        });
                    
                    let listener = if let Some(tls_cert) = &start_args.tls_cert {
                        let password = start_args.tls_password.clone()
                            .unwrap_or_else(|| "password".to_string());
                        let tls_config = TlsConfig {
                            pkcs12_path: tls_cert.clone().into(),
                            password,
                        };
                        RemoteListener::with_tls(psk, tls_config)
                    } else {
                        RemoteListener::new(psk)
                    };
                    
                    if listener.is_tls() {
                        println!("TLS enabled");
                    }
                    
                    tokio::select! {
                        result = listener.start(start_args.port) => {
                            if let Err(e) = result {
                                anyhow::bail!("Remote listener error: {}", e);
                            }
                        }
                        _ = tokio::signal::ctrl_c() => {
                            println!("\nShutting down...");
                            listener.shutdown();
                        }
                    }
                }
                cli::RemoteCommand::Stop => {
                    println!("Remote listener stop signal sent.");
                    println!("(Note: This requires a running listener to respond to stop signal)");
                }
            }
        }
        Some(Commands::Exec(args)) => {
            use crate::distributed::{RemoteClient, RemoteResult};
            
            let config = load_config(cli.config.as_deref())?;
            
            let psk = args.auth.clone()
                .or_else(|| config.remote.psk.clone())
                .ok_or_else(|| anyhow::anyhow!("No PSK provided. Use --auth or set [remote.psk] in config"))?;
            
            let client = if let Some(_tls_cert) = &args.tls_cert {
                let domain = args.tls_domain.as_deref().unwrap_or("localhost");
                RemoteClient::with_tls(psk, domain).map_err(|e| anyhow::anyhow!("Failed to initialize TLS: {}", e))?
            } else {
                RemoteClient::new(psk)
            };
            
            if client.is_tls() {
                println!("TLS enabled");
            }
            
            let targets: Vec<String> = if let Some(targets_file) = &args.targets {
                std::fs::read_to_string(targets_file)?
                    .lines()
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty() && !s.starts_with('#'))
                    .collect()
            } else if let Some(target) = &args.target {
                vec![target.clone()]
            } else {
                anyhow::bail!("Either --target or --targets must be specified");
            };
            
            let mut results: Vec<RemoteResult> = Vec::new();
            
            for target in &targets {
                let (host, port) = if target.contains(':') {
                    let parts: Vec<&str> = target.splitn(2, ':').collect();
                    let p: u16 = parts[1].parse()?;
                    (parts[0].to_string(), p)
                } else {
                    (target.clone(), config.remote.default_port)
                };
                
                println!("Executing on {}:{}...", host, port);
                
                match client.execute(&host, port, args.command.clone(), Some(args.timeout)).await {
                    Ok(result) => {
                        results.push(result);
                    }
                    Err(e) => {
                        results.push(RemoteResult::new(
                            target.clone(),
                            false,
                            String::new(),
                            Some(e.to_string()),
                            0,
                        ));
                    }
                }
            }
            
            if cli.json {
                println!("{}", serde_json::to_string_pretty(&results)?);
            } else {
                println!("\n=== Results ===");
                let mut success_count = 0;
                let mut fail_count = 0;
                
                for result in &results {
                    if result.success {
                        success_count += 1;
                        println!("\n[✓] {}", result.hostname);
                    } else {
                        fail_count += 1;
                        println!("\n[✗] {}", result.hostname);
                    }
                    if let Some(error) = &result.error {
                        println!("  Error: {}", error);
                    }
                    if !result.output.is_empty() && result.output.len() < 500 {
                        println!("  Output: {}", result.output.chars().take(200).collect::<String>());
                        if result.output.len() > 200 {
                            println!("  ... (truncated, use --json for full output)");
                        }
                    }
                    println!("  Duration: {}ms", result.duration_ms);
                }
                
                println!("\n=== Summary ===");
                println!("Total: {} | Success: {} | Failed: {}", results.len(), success_count, fail_count);
            }
        }
        #[cfg(feature = "rest-api")]
        Some(Commands::Serve(args)) => {
            use crate::tool::{create_default_registry, protocol::rest::create_router};
            use axum::serve;
            use std::net::SocketAddr;
            use tokio::net::TcpListener;

            let registry = create_default_registry();
            let app = create_router(registry, args.api_key.clone());
            
            let addr: SocketAddr = format!("{}:{}", args.bind, args.port)
                .parse()
                .map_err(|e| anyhow::anyhow!("Invalid address: {}", e))?;
            
            let listener = TcpListener::bind(addr).await?;
            
            println!("Starting REST API server on http://{}", addr);
            println!("API available at http://{}/api/v1/tools", addr);
            println!("Health check at http://{}/health", addr);
            if args.api_key.is_some() {
                println!("API key authentication enabled");
            }
            
            serve(listener, app).await?;
        }
        #[cfg(feature = "mcp-server")]
        Some(Commands::McpServe(args)) => {
            use crate::tool::{create_default_registry, protocol::mcp::create_mcp_router, protocol::mcp::run_stdio};
            use std::net::SocketAddr;
            use tokio::net::TcpListener;

            if args.stdio {
                let registry = create_default_registry();
                run_stdio(registry, args.api_key.clone()).await;
            } else {
                let registry = create_default_registry();
                let app = create_mcp_router(registry, args.api_key.clone()).await;
                
                let addr: SocketAddr = format!("{}:{}", args.bind, args.port)
                    .parse()
                    .map_err(|e| anyhow::anyhow!("Invalid address: {}", e))?;
                
                let listener = TcpListener::bind(addr).await?;
                
                println!("Starting MCP server on http://{}", addr);
                println!("MCP endpoint at http://{}/mcp", addr);
                if args.api_key.is_some() {
                    println!("API key authentication enabled");
                }
                
                axum::serve(listener, app).await?;
            }
        }
    }

    Ok(())
}

fn extract_target_from_url(url: &str) -> Option<String> {
    url::Url::parse(url)
        .ok()
        .and_then(|u| u.host_str().map(|s| s.to_string()))
}

fn parse_proxy_url(proxy_url: &str) -> anyhow::Result<(String, u16, Option<String>, Option<String>)> {
    let url = url::Url::parse(proxy_url)
        .map_err(|e| anyhow::anyhow!("Invalid proxy URL: {}", e))?;
    
    let host = url.host_str()
        .ok_or_else(|| anyhow::anyhow!("Proxy URL missing host"))?
        .to_string();
    
    let port = url.port()
        .ok_or_else(|| anyhow::anyhow!("Proxy URL missing port"))?;
    
    let (username, password) = if let Some(pwd) = url.password() {
        let user = url.username();
        (Some(user.to_string()), Some(pwd.to_string()))
    } else if !url.username().is_empty() {
        (Some(url.username().to_string()), None)
    } else {
        (None, None)
    };
    
    Ok((host, port, username, password))
}
