use super::palette::{Theme, ThemeColors, ThemeMode};

pub fn dark_theme() -> Theme {
    Theme {
        mode: ThemeMode::Dark,
        name: "dark".to_string(),
        colors: ThemeColors {
            primary: ratatui::style::Color::Cyan,
            secondary: ratatui::style::Color::Blue,
            accent: ratatui::style::Color::Yellow,
            background: ratatui::style::Color::Black,
            foreground: ratatui::style::Color::White,
            surface: ratatui::style::Color::DarkGray,
            border: ratatui::style::Color::DarkGray,
            border_focused: ratatui::style::Color::Yellow,
            text: ratatui::style::Color::White,
            text_dim: ratatui::style::Color::DarkGray,
            text_bright: ratatui::style::Color::White,
            success: ratatui::style::Color::Green,
            warning: ratatui::style::Color::Yellow,
            error: ratatui::style::Color::Red,
            info: ratatui::style::Color::Cyan,
            selected: ratatui::style::Color::Yellow,
            selected_text: ratatui::style::Color::Black,
            highlight: ratatui::style::Color::Magenta,
            mode_normal: ratatui::style::Color::Green,
            mode_insert: ratatui::style::Color::Yellow,
            tab_active: ratatui::style::Color::Cyan,
            tab_inactive: ratatui::style::Color::DarkGray,
            status_running: ratatui::style::Color::Green,
            status_idle: ratatui::style::Color::DarkGray,
            status_error: ratatui::style::Color::Red,
            focus_normal: ratatui::style::Color::Indexed(220),
            focus_input: ratatui::style::Color::Indexed(51),
            focus_results: ratatui::style::Color::Indexed(82),
        },
    }
}

pub fn light_theme() -> Theme {
    Theme {
        mode: ThemeMode::Light,
        name: "light".to_string(),
        colors: ThemeColors {
            primary: ratatui::style::Color::Blue,
            secondary: ratatui::style::Color::Cyan,
            accent: ratatui::style::Color::Magenta,
            background: ratatui::style::Color::White,
            foreground: ratatui::style::Color::Black,
            surface: ratatui::style::Color::LightGreen,
            border: ratatui::style::Color::LightBlue,
            border_focused: ratatui::style::Color::Blue,
            text: ratatui::style::Color::Black,
            text_dim: ratatui::style::Color::Gray,
            text_bright: ratatui::style::Color::Black,
            success: ratatui::style::Color::Green,
            warning: ratatui::style::Color::Yellow,
            error: ratatui::style::Color::Red,
            info: ratatui::style::Color::Blue,
            selected: ratatui::style::Color::Blue,
            selected_text: ratatui::style::Color::White,
            highlight: ratatui::style::Color::Magenta,
            mode_normal: ratatui::style::Color::Green,
            mode_insert: ratatui::style::Color::Red,
            tab_active: ratatui::style::Color::Blue,
            tab_inactive: ratatui::style::Color::LightBlue,
            status_running: ratatui::style::Color::Green,
            status_idle: ratatui::style::Color::DarkGray,
            status_error: ratatui::style::Color::Red,
            focus_normal: ratatui::style::Color::Indexed(21),
            focus_input: ratatui::style::Color::Indexed(196),
            focus_results: ratatui::style::Color::Indexed(28),
        },
    }
}

pub fn cyber_red_theme() -> Theme {
    Theme {
        mode: ThemeMode::Dark,
        name: "cyber-red".to_string(),
        colors: ThemeColors {
            primary: ratatui::style::Color::Red,
            secondary: ratatui::style::Color::Magenta,
            accent: ratatui::style::Color::Cyan,
            background: ratatui::style::Color::Black,
            foreground: ratatui::style::Color::White,
            surface: ratatui::style::Color::DarkGray,
            border: ratatui::style::Color::DarkGray,
            border_focused: ratatui::style::Color::Red,
            text: ratatui::style::Color::White,
            text_dim: ratatui::style::Color::DarkGray,
            text_bright: ratatui::style::Color::White,
            success: ratatui::style::Color::Green,
            warning: ratatui::style::Color::Yellow,
            error: ratatui::style::Color::Red,
            info: ratatui::style::Color::Cyan,
            selected: ratatui::style::Color::Red,
            selected_text: ratatui::style::Color::Black,
            highlight: ratatui::style::Color::Magenta,
            mode_normal: ratatui::style::Color::Green,
            mode_insert: ratatui::style::Color::Yellow,
            tab_active: ratatui::style::Color::Red,
            tab_inactive: ratatui::style::Color::DarkGray,
            status_running: ratatui::style::Color::Green,
            status_idle: ratatui::style::Color::DarkGray,
            status_error: ratatui::style::Color::Red,
            focus_normal: ratatui::style::Color::Indexed(196),
            focus_input: ratatui::style::Color::Indexed(51),
            focus_results: ratatui::style::Color::Indexed(82),
        },
    }
}
